### ISSUE TITLE
underscore methods on Collection return and array of Models (not a Collection)

### ISSUE THREAD

**Issue by RandomEtc** [jashkenas/backbone#120]
I tried to do:

```
var things = new Backbone.Collection([
    { name: "thing 1", active: false },
    ...,
    { name: "thing n", active: true }
]);
var activeThingNames = things.filter(function(t) { 
    return t.get('active')
}).pluck('name');
```

But `pluck` didn't work after `filter`, because `pluck` is a method on `Collection` but `filter` returns an `array` of `Model`s. It's not a big deal (I can just use `map` to get the names) but I'm new to Backbone and wondering if I'm missing something?

**Comment by alexsasharegan** [comment]
I'm way late to this party, but I just came across a need for this myself. I extended the Backbone.Collection with my own base collection and added a wrap function like so:

```js
const ExtendedCollection = Backbone.Collection.extend( {
	wrap( method, ...args ) {
		return new this.constructor( this[ method ]( ...args ) );
	},
} );
```

Usage looks like so:

```js
collection.wrap('map', f => f.set('test', true) )
```

Cheers to any other Backbone users out there. Maybe not the cleanest syntax, but it does the job with minimal hackery.
