### ISSUE TITLE
Add the ability to disable navigate same url short circuit

### ISSUE THREAD

**Issue by markdaws** [jashkenas/backbone#1214]
In the navigate method of the Router object, there is the following line:

if (this.fragment == frag) return;

So if the target URL is the same as the current URL, the navigate method does nothing. In my app I want to be able to execute the routing code even if the url is the same.

I'm thinking that an extra field could be passed to the options object of the navigate method:

force: [true|false]

by default this is set to false, but if set to true the navigate method would still run even if the current url is the same as the target url.  Has this been discussed before?  I am willing to do a pull request with the change if it would be accepted to the project.

Thanks
Mark.

**Comment by spenoir** [comment]
>Think of Backbone's changing the URL in the browser as dropping a bookmark that folks can go back to later -- not as a thing that you need to do to change your application's state.

So are you saying that the browser (and url) isn't the best state machine a web developer can use? I would totally disagree with that and say that it is the only state machine a web developer should use.
