### ISSUE TITLE
incorrect value for event.currentTarget in delegateEvents' callback

### ISSUE THREAD

**Issue by tifroz** [jashkenas/backbone#127]
The delegateEvents' callback in my view gets called with an event passed as a parameter, but the currentTarget attribute is incorrect. The pseudo code should do a better job describing the problem:

```
<html>
    <div id=div1>
        <div id=div2>
            <div id=div3>
                Click me!
            </div>
        </div>
    </div>
</html>
<script>
var View = Backbone.View.extend({
    events: {
        "click #div2": "clicked"
    }
    clicked: function(event) {
        // This should say "div2" when the element is clicked,
        // instead it says "div1"!
        alert(event.currentTarget.id)
    }
});
var view = new View({el: document.getElementById("div1")})
</script>
```

**Comment by cloakedninjas** [comment]
Apologies for the 7 year response - perhaps this will be of some help to others...

If you are using Exoskeleton, you will need to use `event.delegateTarget` as `currentTarget` will reference the view. It is explained here, http://paulmillr.com/exoskeleton/ but if like me you weren't aware it might easily be missed.
