### ISSUE TITLE
Multiple backbones inside Node makes instanceof fail

### ISSUE THREAD

**Issue by balupton** [jashkenas/backbone#1288]
This just consumed the last 4 hours of my life... and boy was it the most crazy difficult thing to debug.

If we have two modules:
- Module A provides custom backbone.js models
- Module B provides custom backbone.js collections

Then we have our app which:
- Requires Module A
- Requires Module B
- Creates a model instance using a custom model from Module A
- Creates a collection instance using a custom collection from Module B
- Adds the model instance to the collection instance

Then the sky falls down and burns all the horrible plagues at once. Why? I know the answer, but I'll give you a gold star if you can guess it.

Here's the answer: because our lovely `model instanceof Model` inside `Backbone.Model.prototype._prepareModel` fails, as the models are using one backbone.js and the collections are using another!!!! Despite them being the same backbone.js version.

ARGH! That line needs to be better, perhaps check for the presence of a `this.isBackboneModel` variable defined by the `Backbone.Model.prototype`.

ARGHHHH. For now, it seems the only solution is to pass the Modules the Backbone.js module that we want them to use, rather than having them use their own local copies. Which is a real PIA. Which imho, the flag idea is a much better one.

Thoughts?

**Comment by ilmeskio** [comment]
For anybody that is using webpack. I had a problem related to the instanceof fail using with-backbone. I could only solve by forcing Backbone globally in the webpack config.

```
    resolve: {
      alias: {
        backbone: path.resolve(
          path.join(__dirname, "node_modules", "backbone")
        ),
        Backbone: path.resolve(
          path.join(__dirname, "node_modules", "backbone")
        ),
...
      },
    }
```
