### ISSUE TITLE
Collection.where() fails on string/numeric integer comparison

### ISSUE THREAD

**Issue by kochb** [jashkenas/backbone#1350]
There's some awkward behavior in backbone's Collection.where() method.  Unlike Collection.get(), the where() operation operates on an identity comparison.  This is particularly problematic when dealing with integer ids - if you do a get operation, things will work fine either way, but if you do a where() operation it fails and you get stuck wondering what went wrong.

The most glaring example of this problem would be a router which grabs an ID out of the URL.  The id is therefore a string instead of a proper integer, and unless you take care to parseInt each route, it will cause failures down the line when it meets well formed integers in the model data.

Should Collection.where() have its behavior loosened to accept string/number comparison?  Sanitizing all that data gets a bit onerous, considering all the possible ways this can accidentally be triggered.

**Comment by yehudahkay** [comment]
When I create a collection from a GET the ids are all strings. When I create a new model in the collection the id is a number. Therefore I can no longer do where on this collection based on id.
