### ISSUE TITLE
Unable to bind an event to a view, where the event is using the ("parent > child") selector

### ISSUE THREAD

**Issue by jayd3e** [jashkenas/backbone#1354]
So I love Backbone.js, but I'm a little shocked that there currently isn't a way to bind a View method to an event that happens on one of View.el's immediate children.  Let me explain:

```
// How we usually define events in a view
View = Backbone.View({

    el: $(".elements.main"),

    events: {
        "click .element": "do_something"
    },

   do_something: function() {}

});
```

This works fine until you encounter a situation where you only want the immediate children of ".elements.main" to have the click event.  A good example of this is when you have a tree of data, like so:

```
.elements.main
    --.element
        --.elements
            --.element
            --.element
                --.elements
                    -.element
            --.element
    --.element
```

See how every ".element" could potentially have an ".elements" child that holds more elements?  So using the View declaration from above, by binding the click event to ".element", we would be binding that click event to every ".element" tag in the entire tree.  And when each .element is represented by an actual element in the DOM this can cause a number of problems, because you will undoubtedly have methods that use the current view's DOM object(View.el), and it's possible that a trigger of an event could change the wrong object.  So the next logical step is to declare something like this:

```
// How we usually define events in a view
View = Backbone.View({

    el: $(".elements.main"),

    events: {
        "click > .element": "do_something"
    },

   do_something: function() {}

});
```

Notice the greater than sign.  I used the jQuery ("parent > child") selector in order to try to only pinpoint the immediate children.  But it doesn't work..... Why?  JQuery's delegate function(used by View.delegateEvents() to call the bound methods with the correct context) does not play nicely with the ("parent > child") selector.  There were a lot of really terrible work-arounds that broke things for me like calling e.stopImmediatePropagation().  My eventual solution was putting this in the initialize method of my view:

```
method = _.bind(this.do_something, this);
this.$el.children(".element").delegate('.add_reply', 'click', method);
```

Anyway, this seems like a pretty basic feature to ask for, is there anyway this can get fixed?  I'm not experienced enough I feel to attempt to tackle it, but I was just mainly wondering if this issue has been looked at before?  Also are there any other potential fixes?

**Comment by bgolubovic** [comment]
I am having the same issue.

`'click #main-nav li': 'onClickNavigation'`

`nClickNavigation: function(ev){
			this.$('#main-nav > .active').removeClass('active');
		},`

So #main-nav li applies to all elemnts li under #main-nav.

And I want click event only on first level child.
I need this: #main-nav > li

Thank you.
