### ISSUE TITLE
Destroying all models from a collection

### ISSUE THREAD

**Issue by luniki** [jashkenas/backbone#139]
Not so obviously 'collection.invoke("destroy")' does not work. How would one empty a collection?

**Comment by jwogan5** [comment]
@martindrapeau 

I have been searching for a long time but I came across this and was wondering if you could send me your deleteAll method for a backbone collection.   Here is my issue.  I hit an api to get a list of items and I store them in a collection.  I then want to completely remove all items in the collection and refresh them with a nw list.  I can do that locally but when I call fetch on the collection all the items come back again as they are not removed from the server.  I can also do the whole removing one item at a time from the server but that can take 15 seconds to finish if I have about 200 items.  Preferably I want to both call refresh locally and one call to remove all items on the server to speed up the removal process.  Any help would be appreciated.
