### ISSUE TITLE
Combine hash routing with pushstate

### ISSUE THREAD

**Issue by Koc** [jashkenas/backbone#1547]
Sometimes we need support both types of routing in one application. This is not possible yet

**Comment by afinnell** [comment]
Doesn't pushState require backend support to know when to return the same page for every request which has "pushState" associated with it? While the page to page transitions can happen client side requiring no backend requests, the moment a user hits refresh with a url of /myapp/view/123/items the backend won't know what to do with that unless it's specifically configured to handle it. To me it would make sense to use pushState for hard view switches and hash for intraview state. In other words, like non single page websites work. There's no reason the fallback mode for pushState when using HTML4 couldn't encode the fake pushState into the hash. Meaning there wouldn't be conflixts and all of it would work for all browsers.
