### ISSUE TITLE
Collection create doesn't trigger error if {wait: true}

### ISSUE THREAD

**Issue by rinatio** [jashkenas/backbone#1845]
Hello guys, thank you for this awesome library!

Have a question: when i do `collection.create({name: 'Name'}, {wait: true})`, if server returns a 400 response error won't be triggered on collection level. I understand that it happens because you attach `_onModelEvent` on success. Is it by design? Is there some workaround except passing error option in create?

Thanks

**Comment by mmrko** [comment]
@caeost I ran into the same issue. I resorted to the following workaround for my use case:

```js
var collection  = new Backbone.Collection();
var model = collection.create(data, { wait: true });

if (model.validationError) {
  // ...
}
```
