### ISSUE TITLE
HTTP Status code 204 no content

### ISSUE THREAD

**Issue by Pindar** [jashkenas/backbone#2017]
I recognized that currently backbone.js tries to update the model also in case of no content (http status code 204). So the validation and all update functions will be called but without data it finally returns an error.

Is this behavior desired or should backbone recognize the special status code?

**Comment by ryanmt** [comment]
`.fetch({success: testSuccess})`

and 

    testSuccess: function(collection, response) {
      console.log(response) // => null 
    }

This happens when the response is 204.  This seems like something is really wrong.  Should I open a ticket?

**Comment by Pindar** [comment]
I don't get the problem:
> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by ryanmt** [comment]
When you get the response from a 400 error code in the error callback, it is an object with a `status` key.  I expected the same.
