### ISSUE TITLE
Potential security thing for hashes

### ISSUE THREAD

**Issue by nwertzberger** [jashkenas/backbone#2071]
in the code for routes, a raw string is passed to _updateHash on line 1242, which can cause security issues according to certain automated scanners. Here's a potential solution that I am using, which quiets down these scanners:

```
// Update the hash location, either replacing the current entry, or adding
// a new one to the browser history.
_updateHash: function(location, fragment, replace) {
  if (replace) {
    var href = location.href.replace(/(javascript:|#).*$/, '');
    location.replace(href + '#' + fragment);
  } else {
    // Some browsers require that `hash` contains a leading #.
    location.hash = '#' + encodeURIComponent(fragment);
  }
}
```

**Comment by simoncb** [comment]
@deanapeterson we are also using hp fortify and the same issues with backbone are being flagged.  We are in a similar situation where critical issues in fortify need to be addressed in order to be compliant.  
I was wondering what you ended up doing in order to pass the fortify scans?

**Comment by nwertzberger** [comment]
The initial suggestion is what I have used to pass security scans when this came up. We have since moved to AngularJS.

**Comment by deanapeterson** [comment]
Since we never used the backbone router we took the entire router module
out of the source.

We have since moved to angular.

**Comment by joevennix** [comment]
This check doesn't actually seem useful, since it lacks the case-insensitive regex modifier. `JaVaScRiPt:` URLs work just as well as `javascript:`.

**Comment by larytet** [comment]
Check this link out 
`http://www.hs.sienerga.com/#https%3A//suelybarbosa.com.br/nnz/ZS?Pepper=them&gang%3Dssatterfield@wencorgroup.com`
