### ISSUE TITLE
No AMD support?

### ISSUE THREAD

**Issue by AjaxSolutions** [jashkenas/backbone#2115]
I hope this is not due to some theoretical considerations because in practice the lack of AMD support creates an inconvenience for developers.

I know you can use an AMD compliant fork or a shim config in RequireJS, but sill ii would be prerable if AMD support was available in Backbone.

I hope you can add this feature in release 1.0.

See this article for more info:

http://bardevblog.wordpress.com/2013/01/05/re-learning-backbone-js-require-js-and-amd/

**Comment by maratbn** [comment]
Caveats of AMD support regarding use of stock Backbone in modular CMS plugins -- https://github.com/jashkenas/backbone/issues/3151
