### ISSUE TITLE
HTTP PATCH method not supported in IE8

### ISSUE THREAD

**Issue by ThePromoter** [jashkenas/backbone#2152]
After reading the update notes I was really excited to implement the new patch functionality.  I got it working perfectly, and then switched over to IE8 just to be sure it worked.  Turns out IE8 does not recognize "PATCH" as a valid HTTP method, below is a list of supported methods:

The object permits only the following HTTP methods: "GET", "POST", "HEAD", "PUT", "DELETE", "MOVE", "PROPFIND", "PROPPATCH", "MKCOL", "COPY", "LOCK", "UNLOCK", "OPTIONS".

Is there a possible workaround to this?

EDIT: After doing a little more research, turns out this is certainly on jQuery's end.  The ActiveXObject for XMLHTTP requests does support PATCH, but the native XMLHttpRequest in IE8 does not.  jQuery ends up using the native version, since it's available to the browser.  This is all in IE9, but using IE8 compatibility mode, I wonder if this issue would persist if the user was using native IE8.  I'll try to test a little more and respond, but for now I'll try to submit a bug report to the jQuery team, since the problem is on their end.

**Comment by devotis** [comment]
It may also occur in IE9 if your html has given IE reasons to believe it should operate in a lower version. To prevent this, do include IE=edge in the html header.

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome" /> 

This forces IE9 to run in IE9 mode. Resource: http://stackoverflow.com/questions/5374099/how-do-i-force-internet-explorer-to-render-in-standards-mode-and-not-in-quirks
