### ISSUE TITLE
Model - Add ._savedAttributes property and revert() function to rollback model to last-synced version

### ISSUE THREAD

**Issue by jackwanders** [jashkenas/backbone#2208]
I recently found myself with this problem: A user could make a variety of changes to models in a collection, and then choose to either save those changes or 'cancel', trashing all changes made.

As `.previousAttributes` represents the state of a model at the time of the last `change` event, I would propose a similar `.savedAttributes` which represents the state of the model at the time of the last `sync` event. In addition, there would be a `.revert()` function that would allow a model to rollback to a state that matches what is persisted (localStorage, database, etc) without the need for a `.fetch()` call.

I feel this could be done with code similar to what follows (I haven't attempted this solution, I've only coded my own solutions on a per-model basis).

``` javascript
// Add _savedAttributes property and revert function to Backbone.Model
var Model = Backbone.Model = function(attributes, options) {
  ...
  this._savedAttributes = this._previousAttributes = _.clone(this.attributes);
  ...
  _.extend(Model.prototype, Events, {
    ...
    revert: function() {
        this.attributes = this._savedAttributes;
    },
    ...
  });
}

// Clone .attributes to ._savedAttributes on sync success
Backbone.sync = function(method, model, options) {
  ...
  options.success = function(resp, status, xhr) {
    if (success) {
      model._savedAttributes = _.clone(model.attributes);
      success(resp, status, xhr);
    }
    model.trigger('sync', model, resp, options);
  };
  ...
}


```

**Comment by morunas** [comment]
Just giving my two cents... this pattern is I believe easier to achieve by passing a full clone (like a sandbox model) to whatever view presents mechnisms to make changes to it. I often use this pattern with promises, where cancellation rejects the returned promise effectively cancelling any changes without having to do revert ops, and resolving the returned promise will then apply partial or full overwrite of the model.
