### ISSUE TITLE
A View's default options are not merged into the options passed to the initialize method.

### ISSUE THREAD

**Issue by jrreed** [jashkenas/backbone#2222]
When you define a View with default options:

```
var MyView = Backbone.View.extend({
  tagName: "div",
  className: "my-view",

  options: {
    foo: "foo"
  },

  initialize: function(options) {
    alert("this.options.foo = " + this.options.foo);
    alert("this.options.bar = " + this.options.bar);

    alert("options.foo = " + options.foo);
    alert("options.bar = " + options.bar);
  }
});
```

These options get extended by any options passed to the constructor:

```
myView = new MyView({bar: "bar"});
```

The result of the extension gets set as `this.options`. I had expected that the result of the extension would also get passed into the initialize function. Instead, the options passed to the initialize method are the same options passed to the constructor (i.e. they don't include the defaults).

The above example alerts `options.foo` as `undefined` even though `this.options.foo` has the value `"foo"` properly set from the default options.

Is this expected behavior? I was under the impression that the `options` argument and `this.options` were equivalent objects. If this is expected behavior, perhaps the docs could be updated to clarify that the options passed in are strictly the options passed to the constructor.

**Comment by gunjankothari** [comment]
I found a solution for the problem, 
I am not sure will it work for you or not but it worked for me.
scope.MyView = {
        attributes: {
            'data-foo': 'foo',
        }
    }

    var obj = new Backbone.View.extend($.extend(true,{},scope.MyView,{
        attributes: {
            'data-bar': 'bar',
        }
    }));
