### ISSUE TITLE
Model.save 202 status code = error?

### ISSUE THREAD

**Issue by switzer** [jashkenas/backbone#2248]
Hi - I have an API which returns a status code of 202 when creating a new user that still needs information before it is usable (e.g. email verification).  When I save my model in Backbone, it comes up in the error handler (rather than in "success").

Shouldn't all 2xx level status codes come up as success?

Thanks for your input.

**Comment by alex-dow** [comment]
searching for jquery 202 error, this thread comes up in the top ten results.

as such I will just add a comment here that jQuery adheres to HTTP protocol in a very strict way. As such, a 202 response that contains an empty body will cause jQuery to consider the request in error (it wants to parse something but nothing is there). I've been trying to find the justification for this behavior from jQuery itself but haven't been able to do so. Either have your API return a body with the 202 or have the API return a 204.
