### ISSUE TITLE
added array in the add event callback for collection

### ISSUE THREAD

**Issue by wanderer** [jashkenas/backbone#2265]
When adding multiple items to a collection it would be helpful have the array of models that were added in the `add` callback. Maybe in options? The following is how it might work

``` javascript
someRandomCollection.on("add",callback);

function  callback(model, collect, options) {
        //last model added do something
       if(model === _.last(options.added)){
           dosomething()
       }
}
```

**Comment by fastest963** [comment]
Not to revive a dying thread.. but I just opened #3492 which relates to this. The problem with using `debounce` is that all the events might not have been added at the end during your debounce time. We're doing real-time syncing of collections between tabs and we'd have to do a debounce while also keeping track of all the indexes which can get difficult. The changes I proposed are very small and hopefully resolve this issue and the many others raised on this topic.
