### ISSUE TITLE
Detect full page load vs navigation/route event

### ISSUE THREAD

**Issue by pete-the-pete** [jashkenas/backbone#2275]
I wanted the ability to determine if the code is being run on a full page load vs a route event.   My use case is so I can load a full page of content that would normally be loaded by fetching the model and updating the view.

I still want the route to fire so I can pre-fetch some other content, so passing silent:true to the history.start function won't work.  I came up with a solution that modifies the Backbone.history object's navigate method to set a flag. I also added a function to return the variable.  Before doing a pull request I wanted to see if there was an alternative.

var first_load = true;
Backbone.history.isFirstLoad = function() {
    return first_load;
}

var origNavigate = Backbone.history.navigate;
Backbone.history.navigate = function(fragment, options) {
    first_load = false;
    origNavigate.call(this, fragment, options);
}

Later to use it I have something like this:

pRouter.on('route:showProjects', function() {
    Projects = new projectsList({ el: $("#content")});
    if(!Backbone.history.isFirstLoad()) {
        //attach the reset event if this is a navigate call, so the view will be rendered
        Projects.attachReset();
    }
    //get the data anyway
    Projects.fetch();
});

**Comment by cherouvim** [comment]
here is a little nice pattern for avoiding the variable on history.

    this.listenToOnce(Backbone.history, 'route', function() {
        this.listenTo(Backbone.history, 'route', function() {
            // stuff that needs to happen on all routes apart from the inital page load one
        });
    });
