### ISSUE TITLE
add event fired multiple times on collection

### ISSUE THREAD

**Issue by thomheymann** [jashkenas/backbone#2287]
when listening to a collection's add event, the callback is triggered not once per `collection.add([model1, model2, model3])` but once for every model added individually.

in my use case I want to add a bunch of models to a collection and then re-render my view once all models have been added. Backbone simply proxies through model events though so if you add 50 models to a collection, the add event is called 50 times and thus the whole view is rendered 50 times. This is unexpected behaviour since the collection method only takes arrays of models:

``` javascript
collection.add([model1, model2, model3])
```

rather than passing them in individual:

``` javascript
collection.add(model1);
collection.add(model1);
collection.add(model2);
```

I expect the same to be reflected in the event callback since I'm not listening to the model but the collection as a whole. 

Is there currently a clean way of adapting a collection to support this behaviour or is this something that could be added into the core? I know this is expected behaviour at the moment so I'm not raising it as a bug but I'm not sure how useful it currently is.

**Comment by vfiodor** [comment]
[dash_debug.txt](https://github.com/jashkenas/backbone/files/1352742/dash_debug.txt)

The quality changed many times in this log (i think 2 full cycles from highest to lowest)
