### ISSUE TITLE
Complex model fields are returned by reference by `toJSON`

### ISSUE THREAD

**Issue by jedrichards** [jashkenas/backbone#2315]
If your model contains some complex data in some of its fields (say some nested simple objects) then the object returned by `toJSON` will refer to these by reference. So if you mess around with the values in your `toJSON` object then you are inadvertently silently poisoning your model data directly.

Here's an example:

``` javascript
// Init model with data object
var model = new Backbone.Model({
    simpleValue: "foo",
    objectValue: {
        subObject: {
            nestedValue: "bar"
        }
    }
});

// Create a toJSON representation
var modelJSON = model.toJSON();

// Change some values in your toJSON object
modelJSON.simpleValue = "baz";
modelJSON.objectValue.subObject.nestedValue = "baz";

console.log(model.get("simpleValue")); // returns "foo", as expected
console.log(model.get("objectValue").subObject.nestedValue); // returns "baz", lolwut?
```

So it seems like `toJSON` is returning references to complex objects in the model, not clones. Is that desired behaviour? It just took me ages to track down this issue. I was doing some post-processing and calculations on some to `toJSON` results before sending back to the server expecting it to be free of repercussions ...

**Comment by tjgupta** [comment]
I just banged my head against this for quite a while too. It seems counter-intuitive that a method named toJSON() would output a shallow serialization of your model, but with complex attributes as pointers to the model.

Also, once I figured out why modifying data in my serialized toJSON object was affecting data in my model, I went to the documentation to understand if there was a deep copy option for model.toJSON(). It seems you can pass "options" in, but they are then not used. Perhaps this could be configurable? Or if not, then the documentation should be updated.
https://github.com/jashkenas/backbone/blob/master/backbone.js#L397

I'm happy to submit a PR to either update the docs, or add a "deep" option, depending on what direction you all prefer.
