### ISSUE TITLE
Collection#set isn’t maintaining the input order

### ISSUE THREAD

**Issue by molily** [jashkenas/backbone#2443]
[Chaplin](https://github.com/chaplinjs/chaplin) has had `Collection#update` right from the beginning, later [we removed it](https://github.com/chaplinjs/chaplin/pull/329/files) when Backbone provided it out of the box. Now I realized that Backbone’s version doesn’t maintain the order when updating:

```
collection = new Backbone.Collection([{id:0}, {id:2}, {id:4}]);
collection.set([{id:0}, {id:1}, {id:2}, {id:3}, {id:4}])
collection.pluck('id')
Actual: [0, 2, 4, 1, 3]
Expected: [0, 1, 2, 3, 4]
```

That is, the new models aren’t inserted at the right position. Is this behavior on purpose?

Collection#set is generally more useful than Collection#reset. It doesn’t throw away all models and creates them from scratch. With `add`, `remove` and `change` events, it’s easier to build list views that is optimized for performance. We have been using it for Chaplin’s optimized [CollectionView](https://github.com/chaplinjs/chaplin/blob/master/src/chaplin/views/collection_view.coffee).

If I fetch a list as a JSON array from the server, I expect the collection to reflect the input order. If the server returns `[{"id":0}, {"id":1}, {"id":2}, {"id":3}, {"id":4}]`, the collection order should be the same. I know that I can `.fetch({ reset: true })` to maintain the order, but then I’m losing all the benefits of Collection#set’s smart updating.

**Comment by ledancs** [comment]
Hello guys! Thanks for all the effort you put into Backbone. I know this is an old issue but I came across the use case in which the server returns a sorted collection and when Backbone parses that, the order is lost. I found this discussion in StackOverflow that explains that in a JSON response, the order is maintained when using an array: [Sorted elements in JSON](http://stackoverflow.com/questions/7214293/is-the-order-of-elements-in-a-json-list-maintained)
Is there a particular option I need to pass to my Backbone collection to explicitly respect the order from the JSON response coming from the server?
Thanks a ton!
