### ISSUE TITLE
saving model and collection options

### ISSUE THREAD

**Issue by jstrimpel** [jashkenas/backbone#2458]
Is there a reason why model and collection do not save off a copy of the options hash to the instance like a view? I see key properties getting plucked in the source and added to the instance, but then the options argument is not assigned to <instance>.options.

**Comment by cletusw** [comment]
I built a codemod that adds options handling to each `Backbone.View`'s `initialize` method.

https://gist.github.com/cletusw/da515f4b91a13db6ac293f796b884d49
