### ISSUE TITLE
When hash has a single quote, Firefox always sees current fragment and new fragment as different

### ISSUE THREAD

**Issue by ravirajani** [jashkenas/backbone#2523]
When the hash contains a single quote character, Firefox (version 20.0 on Ubuntu) will encode it as **%27** in the string **window.location.href**.  This variable provides the value of **current** when the function **checkUrl()** is run.  However the value of **this.fragment**  to which it is compared is got from whatever is passed to **Backbone.router.navigate()**.  If we encode the hash that is passed to this function with **encodeURIComponent()** (or even **encodeURI()**), even Firefox will not encode the single quote to **%27**.  So the variables **this.fragment** and **current** will always be different. 

Solution: Backbone should decode the URI components before comparing them because

``` javascript
decodeURIComponent("%27") = "'";
encodeURIComponent("'") = "'"; 
```

I propose:

```
1439c1439,1441
<       if (current === this.fragment && this.iframe) {

---
>       var decodedCurrent = decodeURIComponent(current);
>       var decodedFragment = decodeURIComponent(this.fragment);
>       if (decodedCurrent === decodedFragment && this.iframe) {
1442c1444
<       if (current === this.fragment) return false;

---
>       if (decodedCurrent === decodedFragment) return false;
```

**Comment by jaafarexcz** [comment]
@braddunbar
