### ISSUE TITLE
CORS sync sends OPTIONS request instead of POST

### ISSUE THREAD

**Issue by ghost** [jashkenas/backbone#2542]
I'm trying to use the model.save() with a rest service on another subdomain. I got the following request headers which are far from my expectations:

```
OPTIONS /user HTTP/1.1
Host: not.public
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:20.0) Gecko/20100101 Firefox/20.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://not.public
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

How to fix this?

Ofc. my REST server responds 404 not found for an OPTIONS call...

To avoid unwanted questions: the server is ok, it handles REST calls and CORS calls well, tested with $.ajax and a REST interface tester application too.

**Comment by pashtika** [comment]
Can someone please help on this issue? http://stackoverflow.com/questions/32725249/cors-filter-issue-for-authentrypoint

**Comment by amanos1022** [comment]
In case anyone else is having this problem I had to add "x-http-method-override" to my list of Access-Control-Allow-Methods which is used when you set Backbone.emulateHTTP = true
