### ISSUE TITLE
while in Model.set method

### ISSUE THREAD

**Issue by qiangtou** [jashkenas/backbone#2577]
http://backbonejs.org/docs/backbone.html#section-48

```
Changes can be recursively nested within "change" events.
```

i don't know how it be recursively nested
Can you give me an example of it .
looking forward your help.

**Comment by braddunbar** [comment]
Hi @jasonslyvia! You're right, I didn't exactly explain the while loop. Consider this example:

```js
new Backbone.Model()
.on('all', function(event){ console.log(event); })
.on('change', function(){ this.set('b', 1); })
.set('a', 0);
```

During the `change` event, we've made a second change. This means we need to fire *another* `change` event to notify listeners. Otherwise, any listeners fired previously will be in an inconsistent state. Does that clear it up?

**Comment by jasonslyvia** [comment]
Oh I see, trick is the `all` event that makes things inconsistent! Thank you for your brilliant explanation! Do you mind me copying your answer to the SO question?

**Comment by braddunbar** [comment]
> Oh I see, trick is the all event that makes things inconsistent!

Nah, the example is the same without the `all` event handler. The crux of the matter is that changes can be made *during* the `change` event. When that happens, another `change` event needs to be triggered. Maybe this is a better example:

```js
new Backbone.Model()
.on('change', function(){
  console.log(this.get('x'));
  var x = this.get('x');
  if (x < 2) this.set('x', x + 1);
})
.set('x', 1);
```

Try it with an `if` statement and a `while` statement!

**Comment by jasonslyvia** [comment]
Yeah, it seems like I'm rushed to conclusions. Thank your for your patience and expertise.
