### ISSUE TITLE
Router: Better Catch-All (/.*/) Route

### ISSUE THREAD

**Issue by machineghost** [jashkenas/backbone#2721]
The inclusion of a "*notFound" route was a real improvement for Backbone ... but it's not quite perfect.  One major issue is that it has to be the last route defined, which isn't always so simple (eg. if you have multiple routers or routes being manually registered in Required files).  This is enough of a problem in fact that someone went and made a whole plug-in just to deal with it (https://github.com/STRML/backbone.routeNotFound).  Hopefully if you look at that plug-in's source you'll agree that it shouldn't need to exist.

So rather than making the 404 (or "page not found") route something implicit that people have to struggle to get in to the right position, could you please consider adding an explicit `Backbone.History.pageNotFound` (or something similar) method?

In other words, inside of `Backbone.History.loadUrl` instead of its current return line:

```
return matched;
```

if it did:

```
return matched || this.pageNotFound();
```

that would be really great, and super easy.  It'd be a little dirty though, because what's supposed to get returned there is a matching route, not the output of a route, so maybe a slightly cleaner way of doing it would be to have a `Backbone.History.registerPageNotFound` method and then do:

```
return matched || this.getRegisteredPageNotFoundRoute();
```

Or I could see at least a couple other variations; the important thing is just that it would be really awesome if I could say "Backbone do this when there's no route defined" instead of "Backbone, do this if there's no route defined ... but god help me if I say that before all my routes are registered" ;-)

**Comment by arbaaz** [comment]
I am facing the same issue. I am using [subroutes](https://github.com/ModelN/backbone.subroute). I have more than 5 subrouters. what's the solution?
