### ISSUE TITLE
collection.fetch( { add: true } ) still removes original models

### ISSUE THREAD

**Issue by atipasvanund** [jashkenas/backbone#2782]
I am trying all options of { add: true, reset: false, update: true, remove: false } together or in various combinations.

In all cases, fetch will remove all original models from collections and replace with new ones.

I am trying to append new models to existing models in collection.

The following is my simple code.

collection.fetch({
        data: { offset: 25 },
        add: true,
        reset: false,
        update: true,
        remove: false,
        success: function(){

**Comment by Rinkuk1993** [comment]
This fiddle has been updated with working one. Check enclosing syntax
http://jsfiddle.net/awesomeRk/fu3g913k/1/
