### ISSUE TITLE
Deep-Model missing

### ISSUE THREAD

**Issue by ghost** [jashkenas/backbone#2826]
By using backbone-deep-model Backbone's plugin we can do the following very well,
Improved support for models with nested attributes,
Allows you to get and set nested attributes with path syntax, e.g. user.type,
Triggers change events for changes on nested attributes.

I think; this must be build-in in backbone core library itself rather then using any third party library.

Hope this get updated in upcoming Backbone versions.

**Comment by hegdeashwin** [comment]
:+1:  @braddunbar
