### ISSUE TITLE
Save with patch method won't call toJSON (and therefore no custom method for creating json)

### ISSUE THREAD

**Issue by kt0** [jashkenas/backbone#2831]
Consider this :

``` javascript
Model.prototype.toJSON = function(options){
     return {upd: Backbone.Model.prototype.toJSON.apply(this,arguments)};
}

model.save({attr1: 'awd'}); // <-- This work fine

model.save({attr1: 'awd'},{patch: true}); // <-- this will ignore my toJSON method and make server error
```

What I can do :

override `Backbone.sync` method and `toJSON` method : 

``` javascript
Backbone.sync = function(method, model, options) {
....
// params.data = JSON.stringify(options.attrs || model.toJSON(options));
params.data = JSON.stringify(model.toJSON(options));
....
}

Backbone.Model.prototype.toJSON = function(options){
     if(options.attrs){
         return options.attrs;
     }
     return _.clone(this.attributes);
}
```

I cant see problem with that but maybe it make problems with other parts of backbone.

I'm using Backbone v1.0.

Overrided `Model.prototype.toJSON` method in this issue is just an example.

Please ignore typo problems with my example (if any).

**Comment by kevinisaac** [comment]
Same problem here. I think there should be some control over sending data via PATCH method. For example, if the server accepts data namespaced in a `data` object, I need to be able to do use the namespace while sending the data to the server and at the same time, I need to original non-namespaced data to store in the local model.
