### ISSUE TITLE
Model ``invalid`` event is triggered before model is initialized.

### ISSUE THREAD

**Issue by jgerigmeyer** [jashkenas/backbone#2839]
I'm not sure this is actually a bug, but I found a change in behavior from v1.0.0 to v1.1.0 that I think should be noted in the changelog.

When creating a new model (either via `new my_model()` or by calling `add()` or `create()` on a collection) with `{validate: true}`, the `invalid` event (assuming validation fails) is triggered on the new model _before_ the model's `initialize` fn is executed. For instantiating a new model, this is not a change from v1.0.0. But this does change the behavior of collection `create()` and `add()` methods, which used to validate again _after_ initializing the new model. For instance, in my code I'm attaching an event handler to the model as follows:

``` js
var model = Backbone.Model.extend({
    initialize: function () {
        this.on('invalid', function (model, error) {
            console.log(error);
        });
    }
});
```

Because the `invalid` event is triggered before this `initialize` code runs, however, doing `my_collection.add(my_invalid_data, {validate: true});` no longer triggers the `console.log(error)` code.

Here is the relevant diff from v1.0.0 to v.1.1.0 (see https://github.com/jashkenas/backbone/compare/1.0.0...1.1.0#diff-0d56d0d310de7ff18b3cef9c2f8f75dcL909):

``` js
       var model = new this.model(attrs, options);
-      if (!model._validate(attrs, options)) {
-        this.trigger('invalid', this, attrs, options);
-        return false;
-      }
-      return model;
+      if (!model.validationError) return model;
+      this.trigger('invalid', this, model.validationError, options);
+      return false;
```

In v1.0.0, the `invalid` event was being triggered again by the `model._validate` fn on line 909, after the model was created on line 908. In v1.1.0, the event is only triggered once upon model creation on what is now line 913. This change causes any `invalid` event handlers attached in the model `initialize` fn to not fire. At the very least, I think this change should be noted in the public changelog.

I can think of two ways to "fix" my code to work with v1.1.0, but I would appreciate any feedback on which is recommended:

1) Attach `invalid` event handlers using the model's `constructor` fn instead of `initialize`:

``` js
var model = Backbone.Model.extend({
    constructor: function () {
        this.on('invalid', function (model, error) {
            console.log(error);
        });
        // call the original Backbone.Model constructor
        Backbone.Model.apply(this, arguments);
    }
});
```

2) Attach `invalid` event handlers to the _collection_ instead of the model, again using the `initialize` fn:

``` js
var collection = Backbone.Collection.extend({
    initialize: function () {
        this.on('invalid', function (model, error) {
            console.log(error);
        });
    }
});
```

Since models can exist without collections, it seems to me like option (1) is preferred if wanting to validate a model (with handlers listening to the `invalid` event) when it is created, though it's not ideal to have to remember to call the original Backbone.Model constructor when overriding the `constructor` fn.

**Comment by xgbuils** [comment]
It is also possible to subscribe to the event `invalid` before the `set` & `validate` functions using [`parse`](https://github.com/jashkenas/backbone/blob/master/backbone.js#L371-375):
``` javascript
var model = Backbone.Model.extend({
    parse: function (attrs) {
        this.on('invalid', function (model, error) {
            console.log(error);
        });
        return attrs;
    }
});
```

But I think that resolve this irregularity is better.
