### ISSUE TITLE
Where to ask things about Backbone?

### ISSUE THREAD

**Issue by meleyal** [jashkenas/backbone#287]
Is it OK to ask here, or is there an official place to ask?

**Comment by eblink** [comment]
I am new to github and i do not know where to ask ma doubts. I am asking it here. please help me out to solve this issue. Thanks in advance.
I am trying to control a mouse with the help of image processing and using a dsp processor TMS320DM6437(DAVINCI BOARD). I do not know how to interrconnect an opencv code with this board.

**Comment by omp8059** [comment]
In android 4.4.2, logger driver (drivers/staging/android/logger.c) was used to read and write android logs to /dev/log/(main or system). In android lollipop, Logger driver logger.c is removed. Then how does logcat reads android logs? where is reading and writing of android logs handled at kernel?
