### ISSUE TITLE
Model with id "undefined" returned by collection.get(obj)

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/backbone#2922]
@caseywebdev The `Collection::get` method defined by 01d9f0f9b1e85cb21a2940902bc8ba4280c8bca9 has this odd behavior when the collection contains a model with the id `"undefined"`: `collection.get(obj)` will return that model whenever `obj.id` is `undefined`. An odd edge case, I know, but believe it or not I ran into this in a production application... among other things, it means that

```
new Backbone.Collection([{id: 'undefined'}, {id: 'foo'}, {id: 'bar'}])
```

will create a collection with length `1`.

What was wrong with the [Backbone 1.0.0 definition](https://github.com/jashkenas/backbone/blob/1.0.0/backbone.js#L786) of `get`, which explicitly checked for this case?

```
return this._byId[obj.id != null ? obj.id : obj.cid || obj];
```

Related to #2847.

**Comment by samarthsikotara** [comment]
Has anyone solved that problem? id "undefined": collection.get(obj)
