### ISSUE TITLE
Backbone Collection create does not work with an existing model and wait set to true

### ISSUE THREAD

**Issue by lfac-pt** [jashkenas/backbone#3028]
Please checkout this jsfiddle http://jsfiddle.net/GSs8H/1/

An error `Uncaught Error: A "url" property or function must be specified` is thrown because `_prepareModel` no longer sets the the model's `collection` which is problematic because `add` is only called after the server response.

This problem was introduced between 1.1 and 1.1.1.

I can try to make a PR with a fix, if this is indeed a bug.

**Comment by slavajacobson** [comment]
This is still a problem. How come this issue keeps on getting closed?

**Comment by jridgewell** [comment]
@slavajacobson: Can you provide a test case?

**Comment by FaKeller** [comment]
I just came across this issue as well and can confirm that it occurred in my case using Backbone 1.1.2, which is the version used in the fiddle opening the issue. 

After updating Backbone to 1.2.1 the issue did not occur anymore and everything worked as expected. You can see for yourself in the modified fiddle: http://jsfiddle.net/1jtk8nuo/
