### ISSUE TITLE
In IE <= 8, redefined "document.domain" will block;

### ISSUE THREAD

**Issue by luozhihua** [jashkenas/backbone#3068]
We have some project using ```iframe``` for load webapps, and redefined ```document.domain ```, all right in other browser, but under IE 7/8 backbone doesn't work any more.

I very averse to use iframe, but that is requirement from customer, you knew that: customer is god.

**Comment by akre54** [comment]
@jdalton this one too?

**Comment by jdalton** [comment]
Oh man `document.domain` is a pain. It's a trap! (I'll try to carve some time to look at this).

**Comment by jdalton** [comment]
This isn't a Backbone issue. If you scan stackoverflow you'll find lots of issues around setting `document.domain` in older IE.

**Comment by akre54** [comment]
Thanks @jdalton.

**Comment by jdalton** [comment]
Thinking on this a bit more. @luozhihua could the issue be with the iframe that Backbone [creates](https://github.com/jashkenas/backbone/blob/ebed63ad90b3a48df32c6754a6cee23a19010463/backbone.js#L1581). Try manually changing [that](https://github.com/jashkenas/backbone/blob/ebed63ad90b3a48df32c6754a6cee23a19010463/backbone.js#L1581) to `'javascript:(document.domain="'+document.domain+'",void 0)'`.
