### ISSUE TITLE
Link to documentation tool for backbonejs.org?

### ISSUE THREAD

**Issue by machineghost** [jashkenas/backbone#3072]
The documentation style used at www.backbonejs.com (and www.underscorejs.com) is really great; it definitely seems like a step up from what JSDoc produces.  However, I couldn't find any information on what tool is used to generate it.

Would it be possible to include a link to the tool, possibly in fine print at the bottom of the page, so that others could benefit from it?  Or perhaps somewhere in the wiki?  Or, failing that, could you possibly include a link to the tool in this ticket?

**Comment by emiglobetrotting** [comment]
Backbone + Lodash is wow...
