### ISSUE TITLE
Any reason to ignore the minified files in bower.json?

### ISSUE THREAD

**Issue by damianignacio** [jashkenas/backbone#3097]
According to the bower.json spec, recommends to not include the minified version in the "main" attribute.  But I'm wondering if there is any reason to ignore it.

**Comment by franz-josef-kaiser** [comment]
We are currently in the situation where we build a click dummy first (plain HTML) and then build a WordPress theme from it. The clickdummy has it's asset pipelines, but WordPress ships with its own versions of _Backbone_ and _Underscore_. For that reason we can't add _Backbone_ and _Underscore_ (and _jQuery_ ) to our asset pipelines. It still would be nice to not have to maintain separate pipelines for those libraries and instead have `.min.js` files shipped _along_ the unminified files. Any chance that this behavior changes?
