### ISSUE TITLE
Router parsing of fragment hash causes information to be lost or misinterpreted

### ISSUE THREAD

**Issue by enunez** [jashkenas/backbone#3104]
The general code setup:

Backbone.Router.extend({
    routes: {
        '*query': 'onQueryRoute'
    },
    initialize: function() {
        Backbone.history.start();
    },
    onQueryRoute: function(query) {
        // "query" is impossible to reliably parse as a query string
        // due to full-string url-decode on line 1306 of backbone.js
        // inside of _extractParameters().
    }
});

Here's the scenario. Imagine I have a single query parameter with an arbitrary value that happens to contain "1&bar=2".
So I construct my fragment string like so:

var value = encodeURIComponent("1&bar=2");
router.navigate("foo=" + value);

When I refresh the page and my onQueryRoute event handler gets called, I will receive this string: "foo=1&bar=2", which is obviously impossible to parse now because it can be interpreted as two
query parameters when it should actually only be one. This is happening because on line 1306 inside of _extractParamters(), you are url-decoding the _whole_ fragment hash without splitting it first.

In my particular use-case, the query parameters are not fixed; there can be an arbitrary number of them so I can't easily set a route regex that automatically parses the individual values. The structure of my URL is like this: key1[0]=value1&key2[0]=value2&key1[1]=...&foo=bar&baz=blah

The execute() preprocessor method is useless here because it gets called _after_ _extractParameters() has mangled the hash string by url-decoding it whole without splitting it first by default. My current workaround is to override the method with this:
        _extractParameters: function(route, fragment) {
            return Backbone.Router.prototype._extractParameters
                   .call(this, route, encodeURIComponent(fragment));
        }

I basically url-encode it again before passing it back to the original implementation so that when I get it in my callback, I get the original version that I can proceed to parse normally. This is not very efficient and I'd like to see this fixed properly in the source.

Thoughts?

**Comment by DavidUnzue** [comment]
This is not working for me with Backbone 1.3.3.

I'm using `Backbone.history.navigate("?q=" + encodeURIComponent(searchQuery))` to change the URL when submitting a search form. 
In my case, `searchQuery` could be something like "max müller", so I encode it with `encodeURIComponent` into "max+m%C3%BCller". But within Backbones navigate function, my searchQuery is beeing decoded back to "max müller" and returned like that.
So at the end the URL gets changed into "myroot.com/?q=max müller", which is not a valid URL. Instead it should be like this: "myroot.com/?q=max+m%C3%BCller".

Am I missing something? This should be the standard behavior or not? Is there a way to achieve it beside modifying Backbones core?
