### ISSUE TITLE
Single Model in multiple collections?

### ISSUE THREAD

**Issue by azaslavsky** [jashkenas/backbone#3113]
Example detailing the issue:
http://stackoverflow.com/questions/22838095/can-a-single-backbone-model-instance-be-in-two-collections-at-once

While it's clear from that answer that models can be placed in multiple without any problems, but I've noticed that at least one plugin relies on detecting that a model is part of a particular extension by querying the model.collection property. Since this property only allow one collection, this often throws errors.  Would it be possible, or advisable, to make this property into an array of all the collections of which the model is a member?

**Comment by sam-at-github** [comment]
What is the use case for 1 model in >1 collection??
