### ISSUE TITLE
Collection#set cannot handle deduplicating models if the idAttribute is nested

### ISSUE THREAD

**Issue by loe** [jashkenas/backbone#3145]
Maybe this should call idAttribute if it is a function?

My use case is objects nested under a key for the model type, basically what rails does by default.
I have this little patch which helps wrap/unwrap in most places: https://gist.github.com/trydionel/719080

My model for the collection is:
```javascript
  model: function(attrs, options) {
    if (attrs && attrs['folder']) {
      return new Doppio.Models.Folder(attrs, options);
    } else {
      return new Doppio.Models.File(attrs, options);
    }
  }
```

I can change it to a more advanced function:
```javascript
  model: Backbone.Model.extend({
    constructor: function(attrs, options) {
      if (attrs && attrs['folder']) {
        return new Doppio.Models.Folder(attrs, options);
      } else {
        return new Doppio.Models.File(attrs, options);
      }
    },

    idAttribute: 'id'
  })
```

But I am still limited here because Backbone is going to use string notation on the attributes object (https://github.com/jashkenas/backbone/blob/master/backbone.js#L705):
```javascript
id = attrs[this.model.prototype.idAttribute || 'id'];
```

In my case the object looks like:
```javascript
{file: 
  {
    id: '4'
  }
}
```

There is no way using that notation to get to the id, `attrs['file.id']` or something doesn't work.

Perhaps it should be a function that receives attrs?

**Comment by jashkenas** [comment]
Fixed by https://github.com/jashkenas/backbone/pull/3133
