### ISSUE TITLE
How to debounce view events?

### ISSUE THREAD

**Issue by meleyal** [jashkenas/backbone#315]
How would you debounce this keyup listener so the subdomain check only happens after a delay?

This kind of works, but the `_checkSubdomain` function is still called for each keyup event, the calls just get delayed:

```
events: {
  'keyup #subdomain' : 'checkSubdomain'
},

checkSubdomain: function(e){
  this.debounced = _.debounce(_.bind(this._checkSubdomain, this, e), 2000);
  this.debounced();
},

_checkSubdomain: function(e){
  // called once for each keyup event :(     
  console.log(e.target.value);
}
```

**Comment by mohandere** [comment]
Either you can write also,

    events: {
       'keyup #subdomain': _.debounce(function(){
          this. getSubdomain();
       }, 500),
    },

**Comment by elgubenis** [comment]
you should always create the debounced version of a function in the initialize method (if not earlier) when the 'delay' is not dynamic.

**Comment by valecarlos** [comment]
it's been a while now, but this issue has not been closed, is @jsoncorwin 's approach the best yet?
