### ISSUE TITLE
Binary Search for Sorted Collections

### ISSUE THREAD

**Issue by joshbambrick** [jashkenas/backbone#3169]
I am considering writing a small binary search function method for sorted collections. I would also modify the current `where` and `findWhere` methods in order to take advantage of this feature whenever possible (user search has only one field, which is the same as the comparator). This would offer a very significant reduction for searching already sorted collection to O(lg n). Furthermore, this speedup could be achieved by users without having to modify their code at all.

It may also be worth considering modifying the `Collection.set` method to offer O(n) insertion into sorted collections, as opposed to O(n lg n) currently achieved by re-sorting the entire collection. The main downside to this idea is that it may be slower if inserting many Models, not just one, because the collection is only re-sorted once in that case - so I think I will put this off in the meantime.

If I were to submit a pull request, would this be considered a desirable feature?

**Comment by jashkenas** [comment]
Let's move this conversation over into the ticket(s).
