### ISSUE TITLE
Backbone.history / Router.navigate {replace:true} not working (related to issue #3182)

### ISSUE THREAD

**Issue by egpierro** [jashkenas/backbone#3183]
Following the same setup on issue #3182, we noticed that the {replace:true} flag is not working as expected; the Backbone documentation states that using this flag will prevent a navigate request to insert a history record in the browser. In our case, we see `module1/dummy` when we hit the browser's back button, after successfully navigating to `module1/home`.

Flow:

```
/ --> module1/home --> back button --> module1/dummy
```

Desired Flow:

```
/ --> module1/home --> back button --> /
```

One colleague suggested adding {replace:true} to the master router that is doing the handoff to the modular router as well, which worked well, but we're not sure why is it that we need to add this flag in two places, since the `module1/dummy` navigate command is being executed after the fact.

Obviously, having a permanent fix to #3182 will null this issue, but it the workaround is unavoidable, we need to find a solution to this unnecessary history addition.

**Comment by pajtai** [comment]
I believe the docs are not quite right. replace:true just calls window.history.replaceState, and this method REPLACES the current state with the one called.... so if you don't want a "page" in your history then you would use replace:true when navigating way from the page, not when navigating to it.

**Comment by soroushhakami** [comment]
I can confirm the behaviour @pajtai mentions. Could be clarified in the docs.
