### ISSUE TITLE
Poor "add" performance on sorted collections

### ISSUE THREAD

**Issue by dts** [jashkenas/backbone#3242]
I am having significant performance problems when adding items separately to a sorted collection.  This appears to be because a whole-list sort happens every time an item is added.  In my case, I cannot roll all of the additions into a single addition operation (which would trigger only one sort).

Performance could be improved by using binary search to find the insertion point (unfortunately not with underscore's sortedIndex, as this does not take a comparator), and inserting the record at the appropriate location instantly.

**Comment by sayyedhanif** [comment]
Is there any utility/lib to improve performance(or optimize code) on backbone code while running on mobile

**Comment by jashkenas** [comment]
Yes. If you're adding items one at a time, keeping the list sorted is going to be fundamentally slower.

> In my case, I cannot roll all of the additions into a single addition operation (which would trigger only one sort).

I'd suggest finding a way ;) That's the correct way to deal with this issue. (And one of the reasons why `reset` exists.)

**Comment by dts** [comment]
@jashkenas: It is possible, as @kidplug suggests, to add a new event by modifying or monkey-patching Backbone to support it, but this does not seem like a fantastic solution either, as it also involves modifying Backbone internals.  I have not seen a way to do this without bungling up the innards of backbone, which is why I raised this issue.  Further, there doesn't seem to be a compelling reason preventing the correct-location insertion of the item (mergesort, basically), except that the sortedIndex method doesn't accept comparators.

**Comment by sayyedhanif** [comment]
Thanks for ur suggestions...
