### ISSUE TITLE
fix the  unrecognizable characters bug for safari

### ISSUE THREAD

**Issue by KgTong** [jashkenas/backbone#3267]
It will cause unrecognizable characters in safari when call 

       location.hash = '#' + fragment; //line 1634 in backbone.js

especially when the page's data is get by router according to the url, it leads the page's data show abnormally.

call the function of `encodeURI` can be better

        location.hash = encodeURI('#' + fragment);

**Comment by kadishmal** [comment]
Perhaps due to this bug two routes tests fail in Safari under Mac.

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

![screen shot 2015-01-19 at 6 55 04 pm](https://cloud.githubusercontent.com/assets/978004/5798637/b8cf922a-a00c-11e4-8eca-24f55ec0d6d3.png)

**Comment by braddunbar** [comment]
Hi @kadishmal! The test suite is passing for me locally, are you using the master branch?

**Comment by kadishmal** [comment]
Yes, I forked just yesterday and ran the test on the master branch.

**Comment by braddunbar** [comment]
Huh…seems to be working correctly in Safari for me. :confused: Any other details that might help me reproduce your issue?

**Comment by kadishmal** [comment]
Ok, do you have a guide about how to run the tests? Maybe I'm doing something wrong. Such things are better to be described in the README for everybody to try. This would also make sure every contributor can easily run tests and make sure their changes pass the tests.

The reason I ran the tests is because I plan to send some PR.

**Comment by braddunbar** [comment]
The tests are static so you just load `/test/index.html` in a browser. :+1:

**Comment by kadishmal** [comment]
Checked out the latest code and now the tests are green.
