### ISSUE TITLE
Validation: validate only currently set attributes

### ISSUE THREAD

**Issue by jeron-diovis** [jashkenas/backbone#3268]
Why need to always pass [all model attributes](https://github.com/jashkenas/backbone/blob/master/backbone.js#L585) to `validate` method? Due to this inside `validate` we never know what exactly need to be validated. And so, for example, if I create a new model with two required attributes, empty by default, and then trying to set one of them with `{ validate: true }` - I will have an error, because **both** of them will be validated, and second one will be invalid.

Such approach is logical for `save` method - as entire model should be valid to be saved. But definitely not for `set`.

So why not to remove [this line](https://github.com/jashkenas/backbone/blob/master/backbone.js#L585) and, for example, add something like `attrs = _.extend({}, attributes, attrs)` before [this one](https://github.com/jashkenas/backbone/blob/master/backbone.js#L479)?

**Comment by platinumazure** [comment]
Couldn't you just implement your `validate()` function to ignore undefined attributes but complain about nulls and empty strings? (To take care of the "on save" scenario, simply pass in an option like `{ saving: true }` and check for that in your `validate()`.)

**Comment by jmeas** [comment]
This makes sense to me.

**Comment by jashkenas** [comment]
Validation is supposed to be holistic for the resource. Fields don't exist in isolation.

But if, for your app, they should — then by all means write your `validate` function to handle partial attributes being passed in.
