### ISSUE TITLE
Allow listenTo callback to be a method name? (string)

### ISSUE THREAD

**Issue by FellowMD** [jashkenas/backbone#3333]
Since "The **callback** will always be called with **object** as context", perhaps we could optionally give the string name of a method on **object**? This would more closely mirror the functionality of the events hash.
It does open the doors for an error when that method doesn't exist on **object**, but people can already pass undefined so it's an issue that really already exists.

**Comment by akre54** [comment]
Moving discussion to #3397 and #3396
