### ISSUE TITLE
ios-webkit-debug-proxy installation error "aclocal: file '/usr/local/share/aclocal/pkg.m4' does not exist"

### ISSUE THREAD

**Issue by infotoudaya** [jashkenas/backbone#3335]
When i tried to install  ios-webkit-debug-proxy, its throwing teh below error. 
I have update the brew. 

Could you please guide me to resolve it.. 
Error : aclocal: error: aclocal: file '/usr/local/share/aclocal/pkg.m4' does not exist

---

Ebiz-Tests-MacBook-Pro:~ ebiztest$ brew update
Updated Homebrew from f41464c1 to e494a840.
==> Updated Formulae
awscli gnupg2
opam qwt
varnish
chromedriver libssh
pianobar solr
vte3
daemon mksh
python3 sound-touch
wireshark
geoserver mongodb
## qt5 unixodbc

Ebiz-Tests-MacBook-Pro:~ ebiztest$ brew install ios-webkit-debug-proxy
==> Downloading https://github.com/google/ios-webkit-debug-proxy/archive/1.4.tar
Already downloaded: /Library/Caches/Homebrew/ios-webkit-debug-proxy-1.4.tar.gz
==> ./autogen.sh

./autogen.sh

aclocal
aclocal: error: aclocal: file '/usr/local/share/aclocal/pkg.m4' does not exist

**Comment by paqman** [comment]
I had the same problem and found the answer [right here](http://stackoverflow.com/questions/25151658/xcode-build-failure-aclocal-share-files-missing)

I needed to run `brew doctor` then `brew prune`
