### ISSUE TITLE
Collection.create throws "missing URL" exception when given a Model and `wait: true`

### ISSUE THREAD

**Issue by colllin** [jashkenas/backbone#3344]
...but succeeds if you don't pass `wait: true`.  Specifically this happens when passing a Model to `Collection.create`:
http://jsfiddle.net/colllin/nufbo3sx/

Is this expected?  I was surprised by it.  I want it to use the collection's URL... hence using `Collection.create` instead of `Model.save`.

**Comment by ambicoder** [comment]
I am facing the same problem....in the docs it is mentioned that collection.create can accept also an unsaved model object.

**Comment by akre54** [comment]
This looks like it should've been fixed in f5dba8edf4f9cf773d3564b3a6671a3b04d631aa. @ambicoder @colllin can you guys test out master and see if that fixes your problem? I'll add a test.

**Comment by akre54** [comment]
Related: #3028
