### ISSUE TITLE
Custom comparators?

### ISSUE THREAD

**Issue by cbroome** [jashkenas/backbone#3345]
Backbone 'set' relies on the underscore isEqual method to determine whether attributes have changed, however this becomes an issue when an attribute contains another model or collection.  I'd really like for there to be a way to specify a custom comparator on an attribute that could be consulted instead of _.isEqual if present. Overriding 'set' gets to be a pain.

**Comment by MidnightWonderer** [comment]
@cbroome Why you need to revert isEqual back after you override it?
In megawac's solution you can put as many condition check as you like to make sure there is no conflict not just instanceof check.

**Comment by cbroome** [comment]
@MidnightWonderer Let's say I trust underscore's isEqual to be safer than anything my fellow coders or myself would cook up. We use isEqual in other portions of the app, and the idea of running through complex conditional logic every time is not appealing. It strikes me as bad practice. 

But to bring this back to my original point: I really think it would be beneficial for objects to define their own equality checks.

**Comment by akre54** [comment]
@cbroome let's test this out in a PR. Want to whip one up?

**Comment by cbroome** [comment]
sorry, PR? I'm unfamiliar with the acronym.

**Comment by akre54** [comment]
"PR" == "pull request" on Github.

**Comment by cbroome** [comment]
Ahhh, duh. Yeah, I'll give it a go in the next couple days.

**Comment by akre54** [comment]
Thanks :)

**Comment by cbroome** [comment]
Pull Request: https://github.com/jashkenas/backbone/pull/3515
