### ISSUE TITLE
Implementation of isNew() and save() breaks saving new models with an assigned id

### ISSUE THREAD

**Issue by jcano** [jashkenas/backbone#3364]
Either using the default id (`_id`) or using `idAttribute` to define the id field, when calling `model.save()` on a Backbone model it fails to create a new object on the backend if the id field has already been set.

At the end of `save()` the function calls `isNew()` to determine the method to use for the sync method. `isNew()` just checks if the id field has been set and sets the sync method accordingly. As the id field has been set, `isNew()` determines that the action is update, calling to PUT instead of POST on the backend and failing to save the model in the backend as it doesn't exist.

In previous versions, one downloaded in March at least, it was possible to save models using `idAttribute` with a preassigned id.

**Comment by sthomas1618** [comment]
Encountered this issue when upgrading from 1.1.0 to 1.1.2 today. Found some code like this:

```
var Model = Backbone.Model.extend({
    urlRoot: '/collection'
});
var model = new Model();
model.save({ id: 42 }, { wait: true });
```

Before, you would get a POST to /collection. Now you get a PUT to /collection/undefined.
Totally abhorrent practice and I will be changing my API so I can get rid of it. But, I do feel the inconsistency between model.isNew() and model.url() is surprising and odd.

**Comment by jashkenas** [comment]
Really? That sounds like a bug if that's actually happening. It should be a PUT to `/collection/42`

**Comment by sthomas1618** [comment]
I have a PR ready, but I'm not sure if its the correct way to go about it. 
I fixed it falling back to idAttribute in url(): 
```
return base.replace(/([^\/])$/, '$1/') + encodeURIComponent(this.id || this.attributes[this.idAttribute]);
```
It appears the change was introduced in 11cc0e863f

**Comment by jashkenas** [comment]
If you're not sure, then feel to simply open a PR with a failing test case (but not the patch), and ping @caseywebdev about it.

**Comment by caseywebdev** [comment]
Yup a failing test would be great.
