### ISSUE TITLE
Backbone.history.navigate( '/' ) strips slash

### ISSUE THREAD

**Issue by ellatrix** [jashkenas/backbone#3391]
If my root is set to `/path/to/root/`, `Backbone.history.navigate( '/' )` should not navigate to `/path/to/root`.

See #2656 and especially 151bd73d26ab92de3c224ded656e535a06d7e85b.

**Comment by jashkenas** [comment]
Is there a PR to address this?

**Comment by jridgewell** [comment]
@jashkenas: https://github.com/jashkenas/backbone/pull/3443 would solve it, but is a [breaking change](https://github.com/jashkenas/backbone/pull/3443#issuecomment-69660640).

**Comment by rdquintas** [comment]
Hi, was wondering if I could help here.
Is this still an open issue ?

**Comment by qodesmith** [comment]
I'm trying to get a solution to this as well. I would like my routes to look like:
`domain.com/#/route1` as opposed to `domain.com/#route1` and I cant figure out how.

**Comment by kdickerson** [comment]
(Bringing issue back from the dead)

This does result in a technical wart if you're marrying Backbone to a server-side framework that requires trailing slashes.  Right now with my Django code everything works, however Backbone modifies the URL to lose the trailing slash; the result is a request to Django which sends a redirect to include the trailing slash.  So a completely unproductive round trip happens every time.

It does feel inconsistent to only strip a trailing slash when we match the "root" and not at any other time.

I have a code change that keeps or strips the trailing slash based on whether the root was set with one or not.  Would a PR on that be welcome?  It's 2 lines of code and then tests.

**Comment by jashkenas** [comment]
> Would a PR on that be welcome? It's 2 lines of code and then tests.

Happy to take a look, if you want to open the PR...

**Comment by kdickerson** [comment]
Great, I have to push it through a corporate-review process before I can submit it, so that will take a little while; but it is happening.

**Comment by kdickerson** [comment]
Hey, @jashkenas, I'd really appreciate it if you could take a look at the PR for this.  Thanks.
