### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by agrberg** [jashkenas/backbone#3403]
I was wondering if there is a release schedule or plans for the next release of Backbone. The reason I'm asking is the current release (`1.1.2` as of this writing) has a bug with Models with custom `idAttribute` s. There is a fix for it on master where you can specify `modelId` on a collection but without a new release, dependency tools like Bower won't get it unless you point it to master which isn't what you want to be doing.

**Comment by agrberg** [comment]
Any update on the release schedule of Backbone?

**Comment by jashkenas** [comment]
Ah yes, this slipped on by. It would be good to cut a release as soon as possible, but I'm afraid I don't have any particular plan for you.
