### ISSUE TITLE
Collections wiped after 304 responses / Models parsed

### ISSUE THREAD

**Issue by jmeas** [jashkenas/backbone#3412]
**Type**: Bug

**Description**: Backbone wipes Collections when 304 responses are returned from the server by calling `set` and/or `reset` on the Collection. Models are parsed, which may be harmless in certain situations, but not all.

**Expected behavior**: Backbone does not empty the collection, and Backbone shouldn't call parse on the model, but still triggers the `sync` event in both situations.

====

**Wat is this 304 response?**

Servers can be configured to return a 304, or "Not modified," response. This response means that the version of the resource that the server has is the same one that you have on the client. This behavior is distinct from client-side caching (which typically means not making an AJAX request at all) and server-side caching (which typically means not hitting the database; sometimes even the application interfacing with the database). Rather, it is more like a handshake between the client and server. For the feature to work according to the specification, both the server and client must be configured appropriately.

The server must store one of two things for each resource: the time that it was last modified, or an ETag. An ETag is a unique identity for a resource at a given URL. Note again that these are completely independent from arbitrary caching times configured on the server. These modified dates and ETags must reference *specific* versions of resources.

When a request is made by a client, the API will always return the full resource unless one of two headers is passed in: the `If-Last-Modified` header or the `If-None-Matched` header. These headers correspond to the computed last modified timestamp and the ETag value on the server, respectively. The server can use these values to determine whether or not the client has an outdated version of the resource or not.

If the server determines that the resource has not changed, it returns the 304 response.

So, who cares, right? Well, the final piece of the 304 response is that it contains an empty body, which is where the problems with Backbone stem from. In this situation the client is supposed to keep the current version of the resource that it has. For more on why this whole process is convenient, [this blog post](http://blogs.telerik.com/fiddler/posts/12-11-05/understanding-http-304-responses) may do a better job at explaining the details.

===

**So where does Backbone go wrong?**

Backbone goes wrong because it **always** sets the data on a successful callback. Even 304 responses, which return no data. Because of this, collections get wiped due to the behavior of `set`, and Models get `parse` called on them, which is not only inefficient but could reasonably throw errors if you aren't checking for empty responses. Within `parse`, there isn't enough information to determine whether it was a 304 or an actually empty response, so that method should never be relied upon to make the distinction.

===

**Are there any hooks to prevent this?**

No, but you can make it work. Backbone [wraps the success callback](https://github.com/jashkenas/backbone/blob/master/backbone.js#L459-L464) you pass in with its own success callback, which is what erases your data. The only way to get around this is to wrap *Backbone's* wrapped method by overriding `Backbone.$.ajax`, as in [this example](https://github.com/jmeas/gistbook/blob/master/client.src/core/services/resource-cache.js#L16-L32).

The way that it works is that it updates the empty response with the value that you have cached. It then sets that as the response, so that by the time Backbone's code accesses it, it doesn't even realize that the response was actually empty.

This is fine from the standpoint of functionality, but it still causes unnecessary code to be executed, such as `set` and `parse`. Ideally nothing happens other than Backbone saying 'ok ur good' and firing the success callbacks.

===

**Can we see an example?**

In the following example, we use jQuery's `ifModified` option to configure jQuery to automatically manage our caching for us. This means that jQuery will automatically send the appropriate `If-` headers along with every request. In other words, it handles the client's side of things for us.

We also use Github's API, which [is configured](https://developer.github.com/v3/#conditional-requests) to manage the server's role in this feature.

We can see that Backbone wipes the collection after the second fetch, wherein the server informs us that our resource is up-to-date.

```js
// Configure jQuery
Backbone.$.ajaxSetup({ ifModified: true });

// Define and instantiate a collection
var Gists = Backbone.Collection.extend({ url: 'https://api.github.com/users/jmeas/gists' });
var gists = new Gists();

// Fetch it twice and log the length after each fetch
gists.fetch().then(function() {
  // This logs 28
  console.log('First fetch:', gists.length);
  gists.fetch().then(function() {
    // This logs 0
    console.log('Second fetch:', gists.length);
  });
});
```

By switching things up a bit, we can create a Model that has parse called (unnecessarily). In this situation, there is no problem; the data remains. But if your parse function isn't checking for 304 responses (I don't think that it should), then you might calculate some incorrect data.

```js
// Configure jQuery
Backbone.$.ajaxSetup({ ifModified: true });

// Define and instantiate our model w. parse
var Model = Backbone.Model.extend({
  url: 'https://api.github.com/gists/026b3b6b90b498d8bb09',
  parse: function(data) {
    console.log('parse has been called');
    return data;
  }
});
var model = new Model();

// Fetch it twice and log the attributes after each fetch
model.fetch().then(function() {
  console.log('First fetch:', model.attributes);
  model.fetch().then(function() {
    console.log('Second fetch:', model.attributes);
  });
});
```

===

**How can we fix this?**

One idea is to revert d04b0f793b95ea which reverted ea24e0a2 which was PRed in #3410

In that PR, @braddunbar gives a counter-example where he shows Backbone appearing to be functioning correctly. The issue with that example is twofold:

1. The server is not following any specification. It should only return a 304 if the resource hasn't changed based on the `If-X` headers, not arbitrary caching times. The correct response in that situation is a 200 response + the data, as if the caching layer didn't exist.
2. Even so, had the server returned a correct 304 response, it should have been empty. It's not unreasonable to conceive of situations where this could cause a `parse` method to error out or otherwise calculate an incorrect value.

**Other concerns with that PR**

That PR requires a specific convention with using models, which is that once a model is created it cannot be destroyed.

The reason for this is that the PR does not provide any new hooks to fetch data from a cache. Rather, it assumes that the current version of the model still has the data from the last fetch. Because jQuery fetches by URI, if I get rid of my Model instance, or otherwise make a new one, I will be unable to get new data for that model unless I reference the original model (or some external cache).

This is fine for my apps, as this is how I use Backbone, but maybe there are folks out there who are destroying and instantiating models that all point to the same URI.

**Comment by jashkenas** [comment]
> That doesn't solve the issue for second instantiation. And what I meant by { ifModified: false} when fetching for the first time is:
> 
> var gists = new Gists();
> gists.fetch();
> 
> var gists2 = new Gists();
> gists2.fetch(); // 304, gists2 is empty.
> Passing { ifModified: false } for gists2 (its first fetch) would grab the new data needed for a second instance. A caching layer would solve this for you, since the empty response body would be replaced by the original request's.
