### ISSUE TITLE
Collection.set iteration i+1 tests variable 'model' of iteration i

### ISSUE THREAD

**Issue by eloubout** [jashkenas/backbone#3413]
Hello and thanks for your work.

see Version 1.1.2
see Collection.set
see loop "for (i = 0, l = models.length; i < l; i++)"

- iteration i; 
line 686: suppose 'attrs' is not an instance of 'Model' => variable 'model' is not set.
...
line 706, 713: variable 'model' is set.

- iteration i+1
line 686: suppose 'attrs' is not an instance of 'Model' => variable 'model' is not changed.
...
line 697: test "attrs = attrs === model ? model.attributes : attrs;"
=> 'attrs' of iteration i+1 is test against 'model' of iteration i.

**Comment by arshabh** [comment]
+1 @jridgewell
