### ISSUE TITLE
Left scrollbar is not working in Safari 8 on OS X Yosemite

### ISSUE THREAD

**Issue by rtorr** [jashkenas/backbone#3416]
When debugging the issue for https://github.com/AmpersandJS/ampersandjs.com/issues/119, I also checked backbonejs.org to see if other sites were having the same issue.

**Comment by akre54** [comment]
After looking into this issue a bit it truly is an unfortunate Safari bug. All the code-based workarounds seem to add unnecessarily ugly code or break the basic functionality of the docs page.
