### ISSUE TITLE
Collection Issue

### ISSUE THREAD

**Issue by meshakeeb** [jashkenas/backbone#3429]
I have a Backbone App with 3 model which have nested collections:

**Models Structure:**

``` javascript
Layout extends Backbone.Model
-> sections: new Sections extends Backbone.Collection

Section extends Backbone.Model
-> rows: new Rows extends Backbone.Collection
```

Now if I have two section model in layout and I go and add row model to one of the Section.rows collection, it is adding it to both sections.

BTW, I am adding it from a view on an event.

**Thanks in Advance.**

**Comment by spyropress** [comment]
Hi @akre54 ,

I have mention in my comment " as JavaScript pass the value by reference" which is same you mention "Any references to objects stored on a prototype are shared amongst all of its instances"..

So, if I have a default attributes property in Backbone and I init two objects both have same reference, which is happening in the **Example 1**

So I think in the Model Constructor we should clone the defaults and then add it to the attributes.

Thanks

**Comment by akre54** [comment]
If you want to clone the defaults in initialize that's up to you. In general it's a bad idea to store objects on the prototype, and Backbone isn't going to help you with that.

**Comment by megawac** [comment]
Sure there's similar precedent in other languages (such as everyones favourite gotcha: [mutable default parameters in python](http://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument)), but I'd argue that this is in scope for BB to handle. For instance, competition such as Mootools will shallow clone objects on the Models prototype

@spyropress you can make defaults a function and you won't run into this issue

```js
defaults() {
    return {
       data: []   
     };
}
```
