### ISSUE TITLE
There's any chance to "unattach" the view layer of Backbone?

### ISSUE THREAD

**Issue by chiefGui** [jashkenas/backbone#3438]
Hey guys!

Backbone is a very lightweight library which enables us to have a solid foundation to create our web apps, period. For a long time I'm not using its View layer and although it is lightweight as well, I want to know if there's any chance to remove it from Backbone core.

### Why?
Two years ago I started to use Backbone. Since then, the way I think about modularization have changed. This is because it is very decoupled and due to its extension possibilities, facilities to create plug-ins on its top comes out — it is really easy to get into.

Hence, just a few times I used its built-in View layer to design something — it is barely unnecessary for me and I think it is the weakest point on Backbone. However, it is there: making the library slightly heavier. In other words, in every project I make using Backbone — almost all —, the Views' layer it's there, dead, waiting an opportunity to be excluded; totally unusable, with dust on its surface.

Then I thought: there is some plan to make it as a "plug-in"? I was discussing this with a few guys on React's IRC. But see: something really easy to attach, but independent.

_DISCLAIMER: This is a question followed by an opinion — it isn't by far the absolute truth. Maybe there's something related that I don't know._

**Comment by jashkenas** [comment]
The best way not to use the View "layer", is not to make any views ;)

Otherwise, feel free to delete `Backbone.View` from your copy of Backbone.

**Comment by tgriesser** [comment]
Or checkout @HenrikJoreteg's excellent [AmpersandJS](http://ampersandjs.com/), a modular fork of Backbone which was created to solve [this exact issue](http://blog.andyet.com/2014/06/25/introducing-ampersand-js).

**Comment by chiefGui** [comment]
@jashkenas I'm using React from top to bottom. I'm not using the Backbone's built-in view layer. But it's okay, thanks for clarifying.

@tgriesser I already heard about it a long time ago. Seeing it again now, sounds _exactly_ what I want. I will give it a shot. Thank you! :+1:
