### ISSUE TITLE
Change event bound to model.fetch doesn't work.

### ISSUE THREAD

**Issue by whitefire** [jashkenas/backbone#3439]
I tried the following binding in a model today: <code>this.on('change:q', this.fetch);</code>
Long story short, the model is sent to jQuery.ajax as option. jQuery then tries to make sense of the url() method and appends the function-body to the url.

This seems really counterintuitive to me.

**Comment by jridgewell** [comment]
You have an arguments mismatch. The change event calls the callback with `model, value, options`, while `#fetch` expects `options` as its first param, so it's treating `model` as `options`.

You'll need to guard `#fetch`:

```javascript
this.on('change:q', function() {
    this.fetch();
});

**Comment by whitefire** [comment]
I found out after some prodding. It's been a while since I last used Backbone. The logical connection between "property on model changed" and sync with server seemed so natural to me that I expected it to work "out of the box". 

Do you agree? To me it seems logical that backbone-methods and events on the same objects are connectable. Perhaps I'm using the model in an unconventional way. I intend for the model to hold the state of a search-form.

I am somewhat surprised that I haven't stumbled upon this problem earlier.

**Comment by braddunbar** [comment]
Hi @whitefire, thanks for bringing this up!

At this stage in the game the API for `#fetch` is unlikely to change very much. I'd recommend that you just be a bit more explicit.

```js
this.on('change:x', function() { this.fetch(); }, this);
```

It's not much more typing and it's much less error prone.

**Comment by whitefire** [comment]
Agreed! Thank you for your time! :)
