### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by designermonkey** [jashkenas/backbone#3445]
Hi. Firstly, I love Backbone (I'm very new to it, but enjoying it so far), but I'm finding the documentation very difficult to understand, without having to resort to searching online for tutorials. I know it's quite free as a framework, to not lock people in too much, but figuring the little bits out is hard.

As an example, Looking at the `Model.validate` explanation:

>By default validate is called before `save`, but can also be called before `set` if `{validate:true}` is passed.

Where am I supposed to pass the option? My case is that I'm trying to extend `Model`, and want all my attributes to be validated on `set`. I am obviously passing `validate` as a function, so where am I supposed to pass `{validate:true}` if it's being defined as a function?

In general, even though I love this stuff, I feel that the documentation could really benefit from lists of available options for each function (like `Model`) and method (like `set`), that way, a noob could easily ascertain what they can do by default.

However, thanks for a great tool.

**Comment by designermonkey** [comment]
I've figured out the `set` example, but still, the point about options lists would still be helpful.

**Comment by akre54** [comment]
Thanks for the bug report (and sorry for the late reply, just saw this now.) How's this? #3498
