### ISSUE TITLE
listenToOnce space-separated events only attaching callback once

### ISSUE THREAD

**Issue by thejameskyle** [jashkenas/backbone#3448]
http://jsbin.com/wuriku/1/edit?js,console

```js
events.once('foo bar', callback);
events.trigger('foo');
events.trigger('foo');
events.trigger('bar');
events.trigger('bar');

console.log(count === 2); // >> true
```

```js
events.listenToOnce(target, 'foo bar', callback);
target.trigger('foo');
target.trigger('foo');
target.trigger('bar');
target.trigger('bar');

console.log(count === 2); // >> false
```

Removing the (seemingly overkill) `_.once` would fix this.

**Comment by braddunbar** [comment]
Hi @thejameskyle! Thanks for pointing this out!

You're right that the function should be evaluated once for each space-separated event, but I don't think removing the `_.once` is the right approach. I'll pull a fix shortly.

**Comment by thejameskyle** [comment]
> but I don't think removing the `_.once` is the right approach

Why's that?

**Comment by jridgewell** [comment]
> Why's that?

It's needed for https://github.com/akre54/backbone/pull/23#discussion_r19637176
