### ISSUE TITLE
Memory leak in stopListening?

### ISSUE THREAD

**Issue by albinohrn** [jashkenas/backbone#3453]
Hi,

this issue is some what related to ticket #3226 but it's not the same. If you think they are feel free to close and reference that.

After the fix of #3226 there's still a leak. But this doesn't just apply to the listenToOnce. Take a look at the following [example](http://requirebin.com/?gist=8a50edb1123e063fe875). (The example runs Backbone v1.1.2 but the master works the same way).

The problem is that if the `model` I'm listening to has a listener as well. Then the `view.listeningTo` will not be cleaned up correctly. 

It is because of this [line](https://github.com/jashkenas/backbone/blob/master/backbone.js#L213):

```javascript
    if (remove || _.isEmpty(obj._events)) delete this._listeningTo[id];
```
`obj._events` isn't empty and therefore the `view` will keep its reference to the `model`. Is this correct? In our project this causes problems since the object that is listened to will always have its own listeners and where using `listenToOnce` so the references to the old objects will be kept "forever". But we might have to rethink our solution to workaround this issue?

/Albin

**Comment by smelnikov** [comment]
A pull request #3049 is already open to address this issue. Although there seems to be no desire to merge it at this time.
