### ISSUE TITLE
Confusing docs for View.el

### ISSUE THREAD

**Issue by mgummelt** [jashkenas/backbone#3454]
The docs for View.el say:

> this.el is created from the view's tagName, className, id and attributes properties, if specified. If not, el is an empty div.

Which is contradicted by the example:

```javascript
var BodyView = Backbone.View.extend({
  el: 'body'
});
```

since here, `el` is assigned a string, which seems to make it equivalent to `tagName`.  It's unclear why you would use `el` in this case instead of `tagName`

**Comment by akre54** [comment]
In this case `el` is a selector, not a tagName. This is definitely unclear, I'll fix.

**Comment by mgummelt** [comment]
Thanks!
