### ISSUE TITLE
Suggestion for Backbone.Model.clone

### ISSUE THREAD

**Issue by banjolina-jolie** [jashkenas/backbone#3457]
So currently,
```JavaScript
Backbone.Model.clone = function() {
    return new this.constructor(this.attributes);
}
```
But an issue could arise if any attribute value is of type "object" because the newly cloned model's attribute refers to the same object as the original model.  I propose something like:

```JavaScript
Backbone.Model.clone = function() {
    // create new attributes hash with new object references
    var attrsCopy = {};
    _.each(this.attributes, function(val, key) {
        attrsCopy[key] = _.clone(val);
        return new this.constructor(attrsCopy);
    });
}
```

**Comment by Florian-R** [comment]
See last comment on #155 and a few others. Backbone attributes are shallow by design, but you can easily change this in a base Model.

**Comment by akre54** [comment]
Yep, thanks @Florian-R. It's generally considered a bad idea to store anything other than primitives in your `attributes` hash. What you're proposing would be better handled by a deep structured clone, and your base Model is a perfect place to do this.

**Comment by banjolina-jolie** [comment]
@akre54 @Florian-R Thanks for the feedback guys!
