### ISSUE TITLE
Trigger with object

### ISSUE THREAD

**Issue by jridgewell** [jashkenas/backbone#3460]
Currently, calling `#trigger` with an object will prepend the prop's value to the arguments that get triggered. Is this the desired functionality? I can't find any tests for this behavior.

```javascript
obj.on('event', function() { console.log(arguments); });

obj.trigger({ event: 'first arg' }, 1, 2, 3);
// Logs ['first arg', 1, 2, 3]
```

**Comment by braddunbar** [comment]
Hey @jridgewell! Thanks for pointing it out. I think the docs do cover this, though it's a bit removed from `trigger`.

> All Backbone event methods also support an event map syntax, as an alternative to positional arguments:

It doesn't seem to make much sense for `trigger` though. :confused:

**Comment by jridgewell** [comment]
> It doesn't seem to make much sense for trigger though

I agree. But, my issue wasn't with the object syntax, but that the value is prepended to the arguments.

I'm working on refactoring `eventsApi` (and `listenApi` post https://github.com/jashkenas/backbone/pull/3455), and this is one of the gotchas I noticed. There are two others, but I'll open separate Issues for those.

**Comment by akre54** [comment]
Do we actually need this? I'm not sure there's ever a situation where we'd want to trigger using an object, right?

I think the reason it works is more a result of using `eventsApi` under the hood, no reason to make this official codified behavior.

**Comment by jridgewell** [comment]
> I think the docs do cover this, though it's a bit removed from trigger.

Actually, the [`#trigger` docs](http://backbonejs.org/#Events-trigger) only list single or space-separated events as supported.

> I think the reason it works is more a result of using eventsApi under the hood, no reason to make this official codified behavior.

With the old `eventsApi`, it was indeed just an implementation detail. With my new reducing `eventsApi`, it's something I've had to [hack in](https://github.com/jashkenas/backbone/blob/master/backbone.js#L294-L296).

I'd love to see this behavior removed, and #3465 reverted.

**Comment by jashkenas** [comment]
Feel free to remove and revert it in your reduced API.

**Comment by jridgewell** [comment]
Closed with https://github.com/jashkenas/backbone/pull/3499.
