### ISSUE TITLE
Router confusion

### ISSUE THREAD

**Issue by designermonkey** [jashkenas/backbone#3464]
I have just spent hours trying to debug my first Backbone app, as none of the URLs are being handled by the router.

I set up the router like so

```js
var AppRouter = Backbone.Router.extend({
    routes: {
        '': 'index',
        'contact': 'contact',
        'newsletter': 'newsletter',
        'jobs': 'jobs'
    },

    index: function () {
        console.log('matches index');
    },

    contact: function () {
        console.log('matches contact');
    },

    newsletter: function () {
        console.log('matches newsletter');
    },

    jobs: function () {
        console.log('matches jobs');
    }
});
```

and ran the app like so

```js
var App = {}

App.Router = new AppRouter();

App.Router.on('route', function (route, params) {
    console.log(route, params);
});

$(function () {
    'use strict';

    Backbone.history.start({
        pushState: true,
        root: '/'
    });
});
```

When I click a link in my webpage, the browser refreshes the request. What? But isn't the router and History API supposed to jump in and catch all links and use the App to route them?

Nowhere in the documentation does it allude to the fact that I have to manually hijack all links in my page and run them through the router. Nowhere.

From the way the docs are worded, I was expecting to not have to, as I've set the `root`, and told it to use `pushState`.

Very confusing. Should this not be explained somewhere?

**Comment by thejameskyle** [comment]
FYI, @jmeas created https://github.com/jmeas/backbone.intercept for this and hijacking form submissions.

**Comment by designermonkey** [comment]
That's a good utility to know about, thanks.

**Comment by jmeas** [comment]
> But isn't the router and History API supposed to jump in and catch all links and use the App to route them?

@designermonkey, I felt the same way when I was first learning Backbone. Over time, though, I've come to think that this is actually a concern for a View. One of the role of views is to link the DOM with the rest of your app, right? So it would be weird if the Router, or History, reached over and changed the behavior of DOM elements.

I'm also not a big fan of ambient management of these things, which is the only way that a Router/History could do this task. I'd much rather configure it per-link. I might sound like a hypocrite given how Backbone.Intercept works, but that lib is only intended to be a temporary solution until I have time to sit down and work on a more substantial overhaul to bb routing.

I agree with you that the docs should mention this more explicitly. If there were a guide on "How to Route," then this information would naturally fit in there. Backbone doesn't really have guides, though; this sort of information is sort of baked in with the API (Marionette's docs are the same way :frowning:) Perhaps a note could be added to the section on the Router's `navigate` method?

**Comment by designermonkey** [comment]
I get your point about Backbone, it's the reason I like it compared to Angular; It doesn't assume anything.

Yeah, as I'm learning, it is actually making sense for the Router to not do this, I just think it's very confusing at first.

**Comment by jmeas** [comment]
> I just think it's very confusing at first.

Yeah, I can totally relate.

You should whip up a PR that adds a note to the docs. I'm sure it would be considered for merge! And it would *definitely* help future developers.

**Comment by jridgewell** [comment]
> You should whip up a PR that adds a note to the docs.

:+1:

**Comment by designermonkey** [comment]
Maaaaaaybe... :smile:

**Comment by jmeas** [comment]
If you don't think that you'll have the time, just let me know and I'll make one up.

**Comment by akre54** [comment]
As you can see from the length of jmeas' plugin, there's a ton of different ways to handle this, and each app has different requirements. (Sometimes it's nice to be able to cancel a route, or only route when within a specific context, for instance). A doc note would be great.
