### ISSUE TITLE
During event execution, stopListening call on another object does not prevent handler from executing

### ISSUE THREAD

**Issue by juodaspaulius** [jashkenas/backbone#3466]
If there are two related objects listening to the same event, it appears that during event execution one object can not call stopListening on another object and prevent the handler callback during the same execution. Looks like the events get cached somewhere in the trigger and stopListening does not change that.

Let me illustrate with an example:

    var parent = new Backbone.Model();
    var child = new Backbone.Model();
    var vent = new Backbone.Model();
    
    parent.listenTo(vent, "alert", function(){
        alert("parent");
        child.stopListening();
    });
    
    child.listenTo(vent, "alert", function(){
        alert("child");
    });
    
    vent.trigger("alert");

My expectation is that if parent handler is called first, the child alert should not come up. However both alerts are issued.

http://jsfiddle.net/8y4b1ruv/1/

Backbone.js 1.1.2

**Comment by jridgewell** [comment]
We're actually discussing the cause of that behavior in https://github.com/jashkenas/backbone/pull/3463.
