### ISSUE TITLE
Model#save parse option

### ISSUE THREAD

**Issue by jmeas** [jashkenas/backbone#3470]
Reading [the src](https://github.com/jashkenas/backbone/blob/master/backbone.js#L565) suggests that passing `parse:false` when saving a model would prevent a parse, but it doesn't seem to matter what you pass for the option – [it always gets parsed](https://github.com/jashkenas/backbone/blob/master/backbone.js#L524). Am I missing something obvious here? :open_mouth:

**Comment by danstanhope** [comment]
I noticed that too. Didn't want to call parse, so I passed parse: false expecting that the parse method wouldn't be called. But it was…I'm missing something, too :)

**Comment by braddunbar** [comment]
Just out of curiosity, when would you need to prevent parsing a response from the server?

**Comment by mr47** [comment]
I think too it dont need it, we get changes from server -> call parse, that simple dont make it complicated.

**Comment by jmeas** [comment]
> Just out of curiosity, when would you need to prevent parsing a response from the server?

I have since refactored that code, so I, too, don't need this anymore.

The situation was pretty durn specific, though. I think (roughly) these three conditions were happening:

1. The API and client represented the data differently. More specifically, the API followed the JSON API spec, so the attributes of the resource were returned under a nested attribute.
2. I *always* created a particular resource on the client (without nesting), and would then pass it into the `parse` method that did not assume nesting
3. Later, I saved it, and the call to `parse` would break the parse method due to the nested attribute.

In this particular instance, what the server returned didn't need to be used on the client, so I just needed to ignore the response – not parse it. Like I said...very specific situation.

Anway, I still think it's important that the code be fixed up to be more clear that this isn't an option. For many methods in Backbone, the source acts as the documentation for what options a given method accepts. I'll prob. whip up a PR to update this method if I don't forget.

**Comment by mr47** [comment]
@jmeas why you dont used durty checking in ```parse``` ?

like so:

```javascript
...
parse:function(response){
   return _.isUndefined(response.nested.data)?response:response.nested.data;
  // or many other ways to format or check or fix your data _.clone - > format -> etc
}
...
```
Thanks.

**Comment by jmeas** [comment]
Yup @mr47, I did something like that before posting the issue :stuck_out_tongue: I was just surprised that my original idea didn't work after reading the sauce
