### ISSUE TITLE
Inconsistency in the attribute name of model when the response from a server returns some key in object in snake case

### ISSUE THREAD

**Issue by SauloSilva** [jashkenas/backbone#3471]
By using the backbone to get data from several APIs, I noticed on almost every attributes which has compound words comes in the snake_case, being thus the attribute of model is created in snake case as well.
I think that the ideal it is to have an normalizing for such attributes, can be something optional and which defaults to turned off.

Now we have something similar to this, eg.

```js
// bad

this.model.attributes //=> { foo_bar: 'whatever' }
```

To me it would be ideal in camel case, eg.

```js
// good

this.model.attributes //=> { fooBar: 'whatever' }
```

I wanna know the opnion of you?
If everyone agrees and if there is nothing in progress about that, I'm willing to contribute a pull request.

Thanks

**Comment by jashkenas** [comment]
Nope. See previous tickets.
