### ISSUE TITLE
model.parse() called incorrectly in certain cases of collection.set()

### ISSUE THREAD

**Issue by ralfthewise** [jashkenas/backbone#3472]
It seems that if you call collection.set() with an array of mixed models and attributes, and options `{parse: true}`, Backbone will call parse on the model's attributes.  Perhaps that is the desired behavior, but I definitely didn't expect it.  A quick example:

```
var TestModel = Backbone.Model.extend({
    parse: function(r, options) {
        if (r.other_value != null) {
            r.translated_value = r.other_value + ' MB';
            delete r.other_value;
        } else {
            r.translated_value = 'Not set';
        }
        return r;
    }
});

var m = new TestModel({other_value: 64}, {parse: true});
var c = new Backbone.Collection([m]);
c.set([m, {other_value: 128}], {parse: true});
if (m.get('translated_value') !== '64 MB') {
    alert('what!!');
}
```

I created a jsfiddle of it as well: http://jsfiddle.net/qL49q5vb/2/

**Comment by mr47** [comment]
@ralfthewise first of all you fogget create a collection proto with model attr, second [Backbone Debug for Chome](https://chrome.google.com/webstore/detail/backbone-debugger/bhljhndlimiafopmmhjlgfpnnchjjbhd) it must have for all who develop backbone application.

And here is more normal way to use Model.parse [jsfiddle](http://jsfiddle.net/edmrnort/1/)
(With your example you always get a first model attr translated_value)

Open the debuger and you will see 2 models in collection with 64 and 128 mb. 

Thanks.
