### ISSUE TITLE
Unable to remove view & related events

### ISSUE THREAD

**Issue by tejastank** [jashkenas/backbone#3479]
window.web.form_view = new FormView({ el: $("#form"),  });
window.web.form_view.remove()

or other any of tried code not working to remove.

How can we do this ?

**Comment by akre54** [comment]
Hi @tejastank, try the mailing list or the IRC channel for questions like this. Github issues are for maintaing the framework only.

**Comment by tejastank** [comment]
I prefer to post bug/issue in github, instead of IRC, I do not prefer IRC.

Is someone can help or fix let me know
