### ISSUE TITLE
[BUG] Memory leak, unable to remove object

### ISSUE THREAD

**Issue by tejastank** [jashkenas/backbone#3481]
window.web.form_view = new FormView({ el: $("#form"), });
window.web.form_view.remove()

window.web.form_view = new FormView({ el: $("#form"), });

It keeps all events of first instance & never remove it from memory.

Big memory leakage issue. Do not advice to move on IRC, instead fix it, let us know what exact todo, I will write code to manage this issue.

**Comment by hacfi** [comment]
@tejastank I think this is expected behaviour:
https://github.com/jashkenas/backbone/blob/master/backbone.js#L1160-1166
The `remove` method of the view just removes the view element/DOM node from the DOM and stops listening to the events.

**Comment by tejastank** [comment]
I had tried same things.

Even many different way, also with delete, but old events & memory object exists even we do .remove or other methods.

**Comment by akre54** [comment]
Try the mailing list or the IRC channel for questions. Github issues are for maintaining the framework only.
