### ISSUE TITLE
Acceptable values for `models` arg of collection.remove()

### ISSUE THREAD

**Issue by jmm** [jashkenas/backbone#3494]
The current documentation implies that only model objects are acceptable, but under the hood it uses `collection.get()`, which will take a model object, `id`, or `cid`. Is it supposed to be restricted to just model objects or can it be documented as accepting the same values as `get()`?

**Comment by jashkenas** [comment]
Yes, you're right — we should document this as accepting model references or model ids.

**Comment by jmm** [comment]
If you want I'll submit a PR next week. (My plan would be to say that `models` [or its elements if it's an array] can consist of any of the acceptable values for the `id` arg of `collection.get()`.

**Comment by platinumazure** [comment]
In theory it can contain a combination of each of those, right?

**Comment by jmm** [comment]
> In theory it can contain a combination of each of those, right?

You mean?:

```js
some_collection.remove([
  // A model `id`
  '123',
  // A model `cid`
  'c123',
  // A model object
  some_model
])
```

It currently does that in practice (uses `collection.get()` under the hood). That's my expectation of what it's supposed to do in theory, and how I described it in my [pull request](https://github.com/jashkenas/backbone/pull/3495).

**Comment by platinumazure** [comment]
@jmm Yeah, you got it. And yeah, that's what I was expecting too, just wanted to make sure.
