### ISSUE TITLE
Document Collection push() / unshift() args / return values / events

### ISSUE THREAD

**Issue by jmm** [jashkenas/backbone#3496]
1. `Backbone.Collection` `push()` and `unshift()` are documented as only accepting a single model, but under the hood they each pass their `model` arg to `add()`, which accepts a model or array as its `models` arg. Are they intended to be restricted to accepting a single model, or can they be documented as accepting an array (that is, accepting the same values that can be passed to `add()` as `models`)?
2. There's no return value documented for those same methods, but they both return the return value from `add()`.
3. Edit: it's undocumented that these trigger an `add` event.

**Comment by akre54** [comment]
I'd say this is just an implementation detail.

Their documented public behavior is to add just a single model, but this way you don't need to use some ugly hack like `col.push.apply(col, [model1, model2])` when all you really want is `col.add([model1, model2])`. I don't think there's a need to document this, however. 

> There's no return value documented for those same methods, but they both return the return value from `add()`.

Which in turn returns the value from `set`, which [returns the added model or models](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L755). Not sure this needs to be documented either. If you care about the return value, stick with a method that has a documented return value. At this point I doubt we'll be making sweeping changes to the collection methods so you should be fine regardless.

**Comment by jmm** [comment]
> but this way you don't need to use some ugly hack like col.push.apply(col, [model1, model2]) when all you really want is col.add([model1, model2])

Huh? What way -- you mean with them calling `add()` under the hood? What exactly would `col.push.apply(col, [model1, model2])` accomplish? `push()` doesn't accept `N` model arguments either, so that would just be passing `model1` as `model` and `model2` as `options`.

I'm actually not clear on what the difference in behavior (if any) is between `push()` and the default `add()` (with no options) -- it's not documented, so I'll need to dig around in the code to find out. But if there is a significant difference that means I need `push()` instead of `add()` for multiple models it does indeed mean that I'll have to do something like this instead:

```js
[model1, model2].forEach(function (model) {
  collection.push(model);
});
```

> Which in turn returns the value from `set`, which returns the added model or models.

Right.

> Not sure this needs to be documented either.

The return values of these methods are also an implementation detail?

> If you care about the return value, stick with a method that has a documented return value.

Again, if there's no significant difference between `push()` and `add()`, no problem. But if there is, then why not document these methods. I assume there must be some important difference between `push()` and `add()` or else one would just be listed as an alias of the other.

> At this point I doubt we'll be making sweeping changes to the collection methods so you should be fine regardless.

You just told me you consider it an implementation detail. If you're not willing to document it, I'm certainly not willing to rely on it in my code.

**Comment by jashkenas** [comment]
We should document this.

**Comment by akre54** [comment]
Collection's `push`, `pop`, `unshift`, etc. methods are meant to mimic the ones found on Array. Their names are the same but their exact API might be slightly different. 

With all of these questions, why not try it out for yourself? The source is well commented, and it should be easy to follow the logic as you're moving through the methods. Just hook up a debugger and head down the rabbit hole. 

> I'm actually not clear on what the difference in behavior (if any) is between push() and the default add() (with no options)

The main difference is the `{at: this.length}` option at the end. It essentially tells `add` to ignore the default sorting behavior (say you have a comparator) and push all models to the end. We could document this, sure. 

>  If you're not willing to document it, I'm certainly not willing to rely on it in my code.

Then don't. You should use the `add` method then, or ignore the return values from these methods. Realize that by now Backbone isn't going to change drastically in this area.

**Comment by jmm** [comment]
@akre54 

> Collection's `push`, `pop`, `unshift`, etc. methods are meant to mimic the ones found on Array. Their names are the same but their exact API might be slightly different.

I know that. As you say, these are analagous, not necessarily identical. So if the Array methods only accepted a single item there's no reason Backbone's methods couldn't accept multiple. But Array's `push()` and `unshift()` accept one or more elements, so the Backbone methods would actually be more analagous by also doing that.

> With all of these questions, why not try it out for yourself? The source is well commented, and it should be easy to follow the logic as you're moving through the methods. Just hook up a debugger and head down the rabbit hole.

I have. I already said that's what I'd have to do to figure out the differences between `push()` and `add()`. If you think of that as a substitute for good documentation then we fundamentally disagree.

Based on your suggestion of `col.push.apply(col, [model1, model2])` you seem to think that these collection methods have the same signature as the Array methods when in fact that suggestion makes no sense. What would arguably make sense is for the ability to do `col.push([model, model2], options)` to be part of the API.

> We could document this, sure.

:thumbsup:

> Then don't. You should use the add method then, or ignore the return values from these methods. Realize that by now Backbone isn't going to change drastically in this area.

I won't, until it's documented. You say it's an implementation detail, but ah, what the hell, rely on it anyway. (No thanks.) @jashkenas says this should be documented. I'll see how it turns out.

**Comment by jmm** [comment]
Not to mention that it's undocumented that these methods trigger an `add` event.

**Comment by akre54** [comment]
Wanna whip up a docs pull and we'll take it from there?

**Comment by jmm** [comment]
Sure, if we're essentially on the same page:
* They accept the same `models` argument as `add()`.
* They return the same value as `add()`
* They trigger an `add` event.

As discussed, the other difference between `push()` and `add()` (with respect to `options.at`) should also be documented, but I haven't had the chance to wrap my head around that yet.
