### ISSUE TITLE
`collection.reset()` unexpected parameter passed

### ISSUE THREAD

**Issue by albertorestifo** [jashkenas/backbone#3502]
I'm experiencing this very, very strange bug:

I have a object returned from a HTTP request with a structure like this (just an example):
```json
{
  "a": [1, 2, 3, 4],
  "b": true
}
```

When from the collection, I run:
```js
this.reset(results.a)
```

The model associated with the collection also gets initialised with the value of `b`

**Comment by akre54** [comment]
Can you create a small JSFiddle demonstrating the problem? `reset` just [calls `add` under the hood](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L769) so I'm not clear how this would be happening.

**Comment by albertorestifo** [comment]
@akre54 Sorry, isolating the collection resolves the issue. Should have tried before opening the issue.

Something elsewhere in my code is interfering.
