### ISSUE TITLE
Document `extend()` `properties` args as optional

### ISSUE THREAD

**Issue by jmm** [jashkenas/backbone#3503]
For all of the `extend()` method documentation (e.g. on Model, View, Collection) can the `properties` argument please be documented as optional, since it actually is. If I just want to setup the prototype chain and access the prototype, like:

```js
var Klass = Backbone.Model.extend();
Klass.prototype.whatever = whatever;
// ...
```

There's no point in having to do `Backbone.Model.extend({})` just because these params aren't documented as optional.

**Comment by jashkenas** [comment]
Meh. You could do it that way — but what's the point?
