### ISSUE TITLE
Collection.set() will fails if model is not present with add:false and remove:false

### ISSUE THREAD

**Issue by filipmares** [jashkenas/backbone#3509]
Trying to set a model in a collection IFF it exists already. Current 1.1.2 version fails in set():715 where it expects to have a model in the collection.

Call I'm using:
```
collection.set(model, {
  add: false,
  remove: false,
  merge: true
}
```

I think it's fair to have this working since the parameters are pretty descriptive. Thoughts?

**Comment by jridgewell** [comment]
`#set` takes an array of models, not a single one.

```javascript
collection.set([model], {
  add: false,
  remove: false,
  merge: true
});
```

**Comment by filipmares** [comment]
sorry i made a mistake in the snippet. i am passing in an array in my code

**Comment by akre54** [comment]
@jridgewell No [it can totally take a single model](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L671-L672). 

That aside. This should work already, correct?

```js
var collection = new Backbone.Collection;
var model1 = new Backbone.Model({id: 1, title: "The Great Gastby"}),
    model2 = new Backbone.Model({id: 1, title: "A Tale of Two Cities"});
collection.add(model1);
console.log(collection.get(1) === model1); // true
console.log(collection.get(1) === model2); // false
console.log(collection.get(1).get('title')); // "The Great Gastsby"
collection.set(model2, {add: false, remove: false, merge: true});
console.log(collection.get(1) === model1); // true
console.log(collection.get(1) === model2); // false
console.log(collection.get(1).get('title')); // "A Tale of Two Cities"
```

**Comment by akre54** [comment]
@filipmares what are you asking for here?

**Comment by filipmares** [comment]
I'm noticing that my 1.1.2 backbone.js (bower) is different then the github 1.1.2.

https://github.com/jashkenas/backbone/blob/master/backbone.js#L806
```
// Do not add multiple models with the same `id`.
model = existing || model;
if (!model) continue;
id = this.modelId(model.attributes);
if (order && (model.isNew() || !modelMap[id])) {
  order.push(model);
  // Check to see if this is actually a new model at this index.
  orderChanged = orderChanged || !this.models[i] || model.cid !== this.models[i].cid;
}
modelMap[id] = true;
```

vs

```
// Do not add multiple models with the same `id`.
model = existing || model;
if (order && (model.isNew() || !modelMap[model.id])) order.push(model);
modelMap[model.id] = true;
```

**Comment by jridgewell** [comment]
Sorry about that.

Both singular and array of models is working perfectly for me.

> I'm noticing that my 1.1.2 backbone.js (bower) is different then the github 1.1.2.

You linked to master (which has a bunch of unreleased commits). Here's [v1.1.2](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L664-L756).

Are you able to make a jsfiddle with the error?

**Comment by filipmares** [comment]
@jridgewell let me put one up.

**Comment by filipmares** [comment]
@jridgewell http://jsfiddle.net/ssj6y98a/

Open the console and note the error.

**Comment by akre54** [comment]
Well you can't merge nothing with something... You need to set `add: true` in the options.

**Comment by jridgewell** [comment]
Ah, I see now.

This has already been fixed on master. http://jsfiddle.net/ssj6y98a/1/

**Comment by filipmares** [comment]
@jridgewell Yea. It looks like it. Any idea when we'll see a release? Thnx.

**Comment by jridgewell** [comment]
[Soon](https://github.com/jashkenas/backbone/pull/3285), hopefully.
