### ISSUE TITLE
Add an extra trigger that would complement the current 'request' event

### ISSUE THREAD

**Issue by KyleNeedham** [jashkenas/backbone#3514]
Currently a very generic `request` event is triggered on the model, which doesn't allow for easy binding to specific HTTP request types.

We could possibly add another trigger here that would work similarly to the current change events.

`model.trigger('request:' + params.type.toLowerCase(), model, xhr, options);`

Adding this change would allow for explicit event binding. The newly available events would be as follows: 

```
request:post
request:put
request:patch
request:delete
request:get
```

**Comment by tsjoberg** [comment]
@KyleNeedham check out https://github.com/jashkenas/backbone/pull/2742 - this is has been discussed before recently and I believe this type of event will not be added but is recommended that you do your own implementation such as in that example

**Comment by KyleNeedham** [comment]
@tsjoberg That was a fair amount of time ago, i would be interested in the opinion on it now. For such a simple change it a

**Comment by jashkenas** [comment]
No — your client-side application shouldn't be overly concerned with what type of HTTP request is being sent into the server. It's not relevant information.

What's relevant on the client-side is what's being `add`ed or `remove`d, or `change`d, and so on, and so forth.
