### ISSUE TITLE
collection.create should update the model with it's ID after it's returned from the server

### ISSUE THREAD

**Issue by ajsharp** [jashkenas/backbone#3517]
I find this to be slightly unexpected behavior. My expectation is that using Collection.create to create a new model would add the model to the collection immediately, persist the model to the server, and then update the model with properties from the server on the "sync" event. However, the current behavior does nothing when the model is returned from the server, thus, the collection is left with an incomplete model instance.

**Comment by jashkenas** [comment]
Huh? Got a failing test case?

**Comment by ajsharp** [comment]
Yea. I should make clear that this behavior applies to all properties, not just ID.

This code won't run in the backbone test suite, but this is the basic idea:

```javascript
coll = new MyCollection.new
coll.create({key: 'value'})
// wait enough time for model to persist, or call this in the success handler
coll.models[0].id == null // => true
```

The behavior I expect is that by using `Backbone.Collection#create` to create a model instance, it will set properties on the model once it's returned from the server.

FWIW, locally I've patched the create method to do this, like so:

```javascript
create: function(model, options) {
      options = options ? _.clone(options) : {};
      if (!(model = this._prepareModel(model, options))) return false;

      if (!options.wait) {
        this.add(model, options);

        // PATCH
        model.on('sync', function(newMod, attrs) {
          model.set(attrs);
        });


      }
      var collection = this;
      var success = options.success;
      options.success = function(model, resp) {
        if (options.wait) collection.add(model, options);
        if (success) success(model, resp, options);
      };
      model.save(null, options);
      return model;
    }
```

**Comment by jashkenas** [comment]
It certainly should be setting the properties on the model. That's why we need a failing test case...

**Comment by ajsharp** [comment]
@jashkenas I couldn't figure out how to run the tests locally, but here's my best attempt: https://github.com/ajsharp/backbone/commit/436c6354fed3560899644e90e2d4cf0ee40b3672.

**Comment by mr47** [comment]
@ajsharp hi, i still cant undererstan what goes wrong ?
If you want to use ```Backbone.Collection``` with RESTful solution 

```javascript

var Book = Backbone.Model.extend({
   parse: function(data){
       return data; // in this case your model will be mixed with server response after sync was call
   }
});
var Books = Backbone.Collection.extend({
    url : "/books",
    model : Book
});

// Lets get all books

var Library = new Books();
Library.fetch();
var added = Library.create({
    book: "David Sulc",
    year : 2014
},{
   wait: true,
   success: function(model, resp, options){
       // now you can deal with added model 
   }
}); 
```
We send a POST request to ```http://example.com/books```
Response from server need to be someting like that:  
```JSON
{
    "id": "322",
    "book": "David Sulc",
    "year" : 2014
}
```
OR (more complicated solution)
```JSON
{
    "meta": {
        "code": "200",
        "message" : "success adding a book"
    },
    "response": {
        "id": "322",
        "book": "David Sulc",
        "year" : 2014
    }
}
```
So your collection will get an item with id.

@jashkenas i think dont need a failling test case. All is fine.

@ajsharp Maybe i don't understand your question but i think you just started to studying backbone.
Please read about [Mode.parse](http://backbonejs.org/#Model-parse), also we can change and id attribute to add to model [Model.idAttribute](http://backbonejs.org/#Model-idAttribute) too many options.

Thanks.

**Comment by ajsharp** [comment]
@mr47 Ahhhh the problem was I was over-riding `Model.parse` and not returning the original response :disappointed: After fixing that everything works as expected. Sorry about that guys!

**Comment by jashkenas** [comment]
Oh my...
