### ISSUE TITLE
fat arrow go back to original scope

### ISSUE THREAD

**Issue by elgubenis** [jashkenas/backbone#3518]
hey,

i would like to know if there is a way to go back to the original scope (single arrow) inside of a function which uses the fat arrow, the @@ i want to be the @ as if i would have chosen a single arrow.

````
        view.$el.find('[reference-source="' + @name + '"]').select2
          data: @data
        .on 'change', =>
          obj = @temp[$(@@).val()]
          @vent.trigger('references:change:' + @name, obj)
````

i need the this of the on change but i also need the this of the parent functions scope

**Comment by jashkenas** [comment]
There isn't. A function should only have one `this`.

The jQuery `this` is available as `event.currentTarget` within your handler.

**Comment by elgubenis** [comment]
thanks
