### ISSUE TITLE
Iterate object's array attributes passed in View template

### ISSUE THREAD

**Issue by kvslee** [jashkenas/backbone#3519]
Someone may help my problem . I try to present an object's array attributes (in this example, location_code). I could successfully present the model's parent (like model.record_num & model.title) and child attributes (model.recmetadata.creation_date_gmt). But I could not present the object's array attribute (location_code under biblocation property). 

I process the template with underscore, while using jade template to output a html through index.jade (Express).

 I have two questions:
1) Is it possible to display an object's array attributes passed in underscore template in Jade? Please teach me a right syntax. it is confusing in mixing both template systems. If it is not recommended or wrong to mix both templates, please direct me to a right way.

2) I use  {model: this.model.toJSON()} when passing a model in View template. How is it different than using this.model.attributes? I want to confirm if this is an appropriate way to pass all the model's properties, which can be iterated.

And I will also appreciate any fresh feedback to accomplish my task. 

*** 
My View
var Bib = Backbone.View.extend({
	tagName: 'li',
	className: 'bib',
	render: function() {
		var template = $('#bibtemplate').html();
		var compiled = _.template(template);
 		// var html = compiled(this.model.attributes);
		var html = compiled({model: this.model.toJSON()});
		this.$el.html(html);
		return this;
	}
});

*** 
JSON Object passed  in template
{
id: "7917533",
record_num: 1122525,
title: "A historical guide to the U.S. government",
biblocation: [
{
bib_record_id: "7917533",
location_code: "cllrf"
},
{
bib_record_id: "7917500",
location_code: "llrft"
}
],
recmetadata: {
id: "7917533",
creation_date_gmt: "1998-09-15T20:16:32.000Z",
}
}

*** 
Iterating the object in Jade file
script(id='bibtemplate', type='text/x-underscore')
    <a href="#" class="record_num"> <%= model.record_num %></a> - <%= model.title %> - <%= model.recmetadata.creation_date_gmt %>
    each i in <%= model %>
      each j in i.biblocation
        j.location_code

**Comment by altyn** [comment]
`tbody
                            each a, i in data
                                tr(name='#{a._id}')
                                    td #{i+1}
                                    td #{a.title}
                                    td
                                        each n, j in a.author
                                            li #{n.name}
                                    td #{a.release}`

this code great works for me)))))))))))
