### ISSUE TITLE
Inelegant fail if empty 200 response from PUT or POST

### ISSUE THREAD

**Issue by paulguz** [jashkenas/backbone#3520]
I was returning an empty response from my API to a successful POST or PUT after model.save().  In my console, I was getting "Uncaught SyntaxError: Unexpected end of input".  If I change it to return something (anything), the error goes away.

I understand the correct form of an empty response is an empty JSON object (i.e. {}), as opposed to absolutely nothing as I was doing (although I don't think an empty response should be invalid - why must I return something when I mean to return nothing?)

However, I suggest Backbone should treat an empty response in the same way as {}, or throw a meaningful error.

**Comment by paulguz** [comment]
I searched but didn't find a similar issue.  Which is it a duplicate of?  I'd like to read the discussion around it.

**Comment by jashkenas** [comment]
https://github.com/jashkenas/backbone/issues/2696

https://github.com/jashkenas/backbone/issues/3339

https://github.com/jashkenas/backbone/issues/3027

https://github.com/jashkenas/backbone/issues/2241

https://github.com/jashkenas/backbone/issues/2218

**Comment by paulguz** [comment]
So what you're saying is that the "Unexpected end of input" error in my console emanates from jQuery?

**Comment by jashkenas** [comment]
Yes. An application/json request needs a valid JSON response.
