### ISSUE TITLE
add event triggered prior to response

### ISSUE THREAD

**Issue by ambicoder** [jashkenas/backbone#3531]
My problem has to with collection.create...I have passed wait:true and a success callback to get the response from the server.
The thing that annoys me is the fact that an add event is triggered before the response from the server.
There is a case in my code where depending on the server response I do not want an add event to be triggered.
What can I do?

**Comment by mr47** [comment]
@ambicoder can you please provide some demo/tests?

Without it: 
```javascript
//collection creation, init.
....
collection.create({its_new_model:true},{
     wait:true,
     success: function(data){
         // data avaible
     }
}); // your new model (async);
....
// some other logic
```
i dont know what situation in your code, but you can just wrap this function with ```$.Deferred``` promise so you can detect when server get response.

I see another solution you can use ```Marionette.CollectionView``` so you can controll when model was added and rendered details you can read [here](http://marionettejs.com/docs/v2.4.1/marionette.collectionview.html).

Thanks.

**Comment by ambicoder** [comment]
First of all here is some code:
  if (this.model.isNew()) 
            {this.collection.create(test.model, {wait:true,success: function(model,response) {
                  if(response=="....")
                  { ....;}
                 
As I said first the add event is triggered and then the success callback fires....
One thins I do not understand in your code is this:
...{its_new_model:true}
I suppose it is a conditional for testing if a model is true...

I found a solution by doing the following:
model.save and then collection.add...

Either way.any comment is welcomed.
The other things you mention about $.Deferred and marionette...I will look at them at some time...for now I will stick with my solution.
