### ISSUE TITLE
1.0 -> 1.1: Adding a duplicate model with an overridden id is incorrectly added to a Backbone.Collection

### ISSUE THREAD

**Issue by mikeblum** [jashkenas/backbone#3533]
The core issue is that we no longer call new Model to construct an id or override other attributes before checking if the model is already in the collection. Thus if there is not an explicit id attribute on the model, a duplicate is added and the override in initialize is ignored.

Consider the following test:
```javascript
    var MockModel = Backbone.Model.extend({
		initialize: function(options){
                        //make a custom id
			this.id = options.firstName + '_' + options.lastName;
		}
	});

	var MockCollection = Backbone.Collection.extend({
		model: MockModel
	});

    describe('Backbone 1.1 breaking changes', function() {

        it('no-ops adding a model that already exists', function() {
           	var mockCollection = new MockCollection([
           		{
           			'firstName': 'test',
           			'lastName': 'user'
           		}
           	]);

           	expect(mockCollection.size()).toEqual(1);

           	mockCollection.add({
       			'firstName': 'test',
       			'lastName': 'user'
       		});

           	expect(mockCollection.size()).toEqual(1);
       });
});
```

Looking at the source code from 1.0 for adding a duplicate model we have the following at line ~160:

```javascript
 if (!(model = this._prepareModel(models[i], options))) continue;

        // If a duplicate is found, prevent it from being added and
        // optionally merge it into the existing model.
        if (existing = this.get(model)) {
```

The latest 1.1.2 release has the following:

```javascript
// Turn bare objects into model references, and prevent invalid models
      // from being added.
      for (i = 0, l = models.length; i < l; i++) {
        attrs = models[i] || {};
        if (attrs instanceof Model) {
          id = model = attrs;
        } else {
          id = attrs[targetModel.prototype.idAttribute || 'id'];
        }

        // If a duplicate is found, prevent it from being added and
        // optionally merge it into the existing model.
        if (existing = this.get(id)) {
```

**Comment by mr47** [comment]
@mikeblum hi, i think you fogget about ```Model.parse``` and power of this function, you can simply extend a incoming data add some fields. Or if you want someting more that ```Backbone``` can provide you can use ```Backbone.Epoxy``` (features: 2 way-bind, computeds, [readmore](http://epoxyjs.org))

**Comment by jridgewell** [comment]
On edge master, we've [introduced](https://github.com/jashkenas/backbone/pull/3133) [`Collection#modelId`](https://github.com/jashkenas/backbone/blob/master/backbone.js#L1031-L1034) to handle this very situation.

**Comment by mikeblum** [comment]
is https://github.com/jashkenas/backbone/blob/master/backbone.js#L1031-L1034 just like idAttribute?

**Comment by jridgewell** [comment]
By default, yes. However, `#modelId` is meant to be overridden to support cases like yours.

```javascript
var MockCollection = Backbone.Collection.extend({
    model: MockModel
    modelId: function(attrs) {
        // attrs.id isn't really necessary...
        return attrs.id || (attrs.firstName + ' ' + attrs.lastName);
    }
});
```

**Comment by akre54** [comment]
It does seem a little weird that `modelId` duplicates the id setting logic without actually setting the `id` property on the model itself (see #3529). @caseywebdev any thoughts?

**Comment by mikeblum** [comment]
I guess that's the confusing part that an attribute that affects a model has to be set on the collection.

**Comment by caseywebdev** [comment]
The collection is the only piece that can know how to uniquely identify the models it holds, which is why it uses it's own `modelId` method to make distinctions. At the model level, you cannot know what other models you may be grouped up with.

On a related note, I think `model.id` is an unnecessary and confusing property that should be removed altogether, but that's not likely to happen...

**Comment by akre54** [comment]
It seems to me the purpose of `model.id` is twofold: 1) identify the model to the server when persisting (also used in `isNew` to determine the persistence method), 2) identify the model uniquely within the collection. `Collection#modelId`, on the other hand, takes care of 2 but doesn't deal with 1 at all.

I think it really depends on your use case. `Collection#modelId` is great for pollymorphic collections, but it introduces extra complexity to those apps (I'd wager a large percentage) that don't need it.
