### ISSUE TITLE
Special characters in routing string, FF

### ISSUE THREAD

**Issue by YuriyApostol** [jashkenas/backbone#3535]
I use square brackets in routing string and it does not work in FF (v.35, Ubuntu).
This work: router.route(encodeURI('special characters'), ...), but only in FF.

**Comment by braddunbar** [comment]
Hi @YuriyApostol! Thanks for reporting this. Would you mind posting a working sample for me to look at?

**Comment by YuriyApostol** [comment]
http://jsfiddle.net/u7Ljntjy/
Routes #c[a] and #c[b] are not working.

It is FF bug, that fixed in v.36.
https://bugzilla.mozilla.org/show_bug.cgi?id=1133707
https://bugzilla.mozilla.org/show_bug.cgi?id=1121826
