### ISSUE TITLE
scrolling effect

### ISSUE THREAD

**Issue by ambicoder** [jashkenas/backbone#3536]
I want to achieve this scrolling effect(found in many single page apps)....http://alvarotrigo.com/fullPage/
I am just presenting this plugin as an example.
Is it possible that with backbone alone(without a plugin) I can achieve the above effect?
My logic for example is that I am going ti have(for example) "2 pages"(I am putting is it quotation marks to indicate that actually  is one HTML page), and each page is associated with a backbone view...the second page/view will be made visible to the user upon clicking a link or scrolling.

I hope you understand what I mean.

**Comment by akre54** [comment]
Try StackOverflow, the mailing list, the IRC channel, or the gitter room for questions. Github issues are for maintaing the framework only.

**Comment by ambicoder** [comment]
Ok...thanks for clarifying.

**Comment by akre54** [comment]
Yep. https://gitter.im/jashkenas/backbone
