### ISSUE TITLE
Telling whether or not an event has been bound

### ISSUE THREAD

**Issue by EvanCarroll** [jashkenas/backbone#3540]
It'd be great if there was an accessor to Backbone.Events such that we could tell if an event was bound. Just publicly expose a bit of functionality so we can rely on an API and not internal `._events`.

Inspired by real life, and [this question on StackOverflow](http://stackoverflow.com/a/29090779/124486)

**Comment by akre54** [comment]
It'd seem to me that if you don't know when your events are getting bound that's a pretty big code smell. You should really be binding your events only once (in initialize) or if you absolutely need to bind in your render (really not recommended), use a `once`. The rest of the solutions from that thread are good too.

**Comment by EvanCarroll** [comment]
The very nature of adding an event with `.on` makes knowing when an event has been added, very useful. I can't say you're making much sense here at all. Is there any reason why this functionality shouldn't be exposed?
