### ISSUE TITLE
Backbone Localstorage link broken in TODO app

### ISSUE THREAD

**Issue by Amit-Thawait** [jashkenas/backbone#3545]
The link referenced for `BACKBONE.LOCALSTORAGE.JS` in the Backbone TODO app is broken.

![backbone-todo](https://cloud.githubusercontent.com/assets/1220255/6777167/e22200ea-d16c-11e4-9be5-f6d188cd83ea.png)
 
![backbone-localstorage](https://cloud.githubusercontent.com/assets/1220255/6777200/43ac8466-d16d-11e4-9b0c-b62aa219c02f.png)

**Comment by Amit-Thawait** [comment]
I think the correct link is http://backbonejs.org/docs/backbone-localstorage.html

If someone can confirm this then, I can update it.

**Comment by akre54** [comment]
Ah. That is indeed weird. The difference between the two is `localStorage` vs `localstorage`. Good catch, let me look into it.
