### ISSUE TITLE
Unpredictable ordering after a model is added to a collection

### ISSUE THREAD

**Issue by peter-fu** [jashkenas/backbone#3552]
With a "sort" comparator function always returning 0, the order of the models in the collection becomes unpredictable after the 11th model is added. Expected result is that the order of the models should be the same as the order they are added.

_The bug was found with Backbone 1.1.0. The jsfiddle examples are based on Backbone 1.1.2 and Underscore 1.6.0._

Bug example jsfiddle
http://jsfiddle.net/ptbmaqv6/4/

It behaves correctly using a "sortBy" comparator function (see the jsfiddle below).
http://jsfiddle.net/8rLak1Lo/2/

**Comment by akre54** [comment]
When you define a comparator function with an argument count other than 1, Backbone [proxies to `Array.prototype.sort` under the hood](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L843). 

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort):

> If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAscript standard does not guarantee this behaviour, and thus not all browsers (e.g. Mozilla versions dating back to at least 2003) respect this.

Furthermore, `Array.prototype.sort` is *unstable*. By returning 0, you've told the JS engine that these objects have the same value, so what order they're returned to you should be irrelevant.

```js
> ['a','b','c','d','e','f','g','h','i','j','k','l','m'].sort(function() { return 0; })
[ 'g', 'a', 'c', 'd', 'e', 'f', 'b', 'h', 'i', 'j', 'k', 'l', 'm' ]
```

Lastly (and only tangentially related), keep in mind that numbers are converted to strings before being sorted lexographically. (`'11' < '3'`is true). 

```js
> [80, 9, 34, 23, 5, 1].sort()
[ 1, 23, 34, 5, 80, 9 ]
```

**Comment by akre54** [comment]
As a side note, you were onto something with 10 length arrays being magical. In v8 (chrome, node) at least, Insertion Sort (which is stable) is [used for arrays with up to 10 elements](https://github.com/v8/v8-git-mirror/blob/4.3.66/src/array.js#L899-L903), while Quick Sort (unstable) is used for arrays up to 1000 elements.

**Comment by peter-fu** [comment]
Thanks for revealing the magics.

Since `Array.prototype.sort` is not required to be stable, possible to add an option to specify another sort function instead? I can create a new issue instead if so.

**Comment by peter-fu** [comment]
I've posted a topic in [google group](https://groups.google.com/forum/#!forum/backbonejs), where we can continue the discussion.

I'll post the link here after it's approved.

Thanks again for the deep insight.

**Comment by akre54** [comment]
Thanks, much appreciated for using the mailing list. I'll follow up there.

**Comment by peter-fu** [comment]
Great.

The link to the topic is https://groups.google.com/d/msg/backbonejs/2R1GQEsjs8s/J-KSSMVTPzYJ.
