### ISSUE TITLE
stopListening should only unbind its own listeners from the other object

### ISSUE THREAD

**Issue by brian-mann** [jashkenas/backbone#3555]
Currently `listenTo` does not track the event name nor callback in the `_listeningTo` hash.  It only tracks the **other** object.

I would expect the behavior of `stopListening` to only remove the event names + associated callbacks that one object has listened to on another.  But that's not what happens, all callbacks are removed from all objects.

Example:

```coffeescript
## Host Model
host = new Backbone.Model

## Remote Model 1
## this object listens to the host model
remote1 = new Backbone.Model
remote1.listenTo host, "setup", someCallback

## Remove Model 2
## this object also listens to the host model
remote2 = new Backbone.Model
remote2.listenTo host, "setup", aDifferentCallback
```

What we've done so far is have 2 remote models listening to the same host model.  They're listening for the same event, but have 2 different callbacks.

Now let's see what happens when `remote1` stops listening to the host model.

```coffeescript
remote1.stopListening(host)
```

Or more specifically, even to the event namespace.

```coffeescript
remote1.stopListening(host, "setup")
```

The same thing happens...

**All listeners** are removed from `host`.  Including the listeners from `remote2` which match the event namespace, or in the case where its omitted, it will remove all listeners.

Now of course you could manually track all of the events and callbacks, and do this
```coffeescript
remote1.stopListening(host, "setup", someCallback)
```

But the defeats the purpose of `listenTo` and `stopListening` to begin with.  These methods automatically track event relationships BETWEEN separate object.  It only makes sense that internally they additionally track the event namespace and the callbacks.  Therefore when `stopListening` occurs, they should only remove **their** associated event listeners from other objects.  

As it stands, they remove **everything** which matches the host object, and/or the event name.  This obliterates listeners from other objects.

In my example above, I would expect the listeners for `remote1` to be removed, but the listeners for `remote2` to remain intact.

If I wanted to remove **all** listeners from the `host` model, I would simply write: 

```
host.off()
```

**Comment by jridgewell** [comment]
I'm not seeing this behavior on either master or v1.1.2. Can you provide a jsfiddle?

**Comment by brian-mann** [comment]
Okay ....

nevermind.

`off` takes a 3rd argument, `context`, which does in fact only unbind the objects own listeners.

I see now the `off` method of my object had been overridden, and did not take that argument into account, thus display the behavior I was seeing.
