### ISSUE TITLE
Router.execute doesn't return anything

### ISSUE THREAD

**Issue by emersonyu** [jashkenas/backbone#3557]
If the route callback returns false, a route event is not supposed to be fired. i.e.
`if (router.execute(callback, args, name) !== false) {//trigger 'route' event...}`

However, execute() doesn't actually return the callback functions return value:
`if (callback) callback.apply(this, args);`

Shouldn't this be:
`if (callback) return callback.apply(this, args);`

Is this by design, or am I missing something?

**Comment by akre54** [comment]
Nope, this is in place so folks can override `execute` in their apps to act as a `beforeAction`-like method (see #3016). We don't want the route handler's return value to affect the transition.

**Comment by emersonyu** [comment]
Thanks, makes sense. Didn't read the comments closely enough :)
