### ISSUE TITLE
Release new version 

### ISSUE THREAD

**Issue by paulmillr** [jashkenas/backbone#3558]
Backbone with commonjs-supported jQuery would be great in npm

**Comment by elgubenis** [comment]
+1

**Comment by megawac** [comment]
The issue with this is its not clear what version of jquery the user will want to use. Anyway, it wouldn't be hard (and it would be easy for any user to maintain) a package to do this

package.json
```js
{
   dependencies: {
         jquery: ">= 1",
         backbone: "^1.1.0"
   }
}
```

index.js
```js
module.exports = require('backbone');
module.exports.$ = require('jquery');
```

Feel free to publish the package and share it here

**Comment by akre54** [comment]
I think Paul is referring to #3542. For a problem with your `module.exports.$` solution see #3156.

**Comment by paulmillr** [comment]
@akre54 my npm package depends on backbone. They are loaded in bulk by build tool. So, doing `$ = require('jquery')` in my code doesn't help. 

The change from master would help though.
