### ISSUE TITLE
backbonejs.org sidebar scrolling issues

### ISSUE THREAD

**Issue by mib32** [jashkenas/backbone#3572]
I have issues with Safari 8 regarding finger-scrolling left sidebar on the backbonejs.org website. It just won't work most of the times. It makes it really kinda hard to read docs. I haven't found a solution right now. All i can say is that http://api.rubyonrails.org works fine on safari, but it uses frameset with two iframes. Anybody else having that?

**Comment by jridgewell** [comment]
[We're aware](https://github.com/jashkenas/backbone/issues/3416), but we're not going to [fix it](https://github.com/jashkenas/backbone/issues/3416#issuecomment-74766410).
