### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by Samaritan89** [jashkenas/backbone#3578]
onobject.on(event, callback, [context])别名: bind 
在 object 上绑定一个callback回调函数。 只要event触发，该回调函数就会调用。如果你的一个页面含有大量的不同**时间**，我们约定使用冒号来为事件添加 命名空间 俗成地使用冒号来命名

时间应该是事件

**Comment by mondaychen** [comment]
I didn't know backbone has a Chinese document. Where's it?

**Comment by akre54** [comment]
If this is a question or a bug, mind translating it into English? I'm afraid my Chinese isn't great.

**Comment by Samaritan89** [comment]
So so sorry, my mistake, I did't mean your project, someone translate backbone in Chinese, but write this github

Thank you for your great project, BTW

FYI

http://www.css88.com/doc/backbone/

**Comment by appleboy** [comment]
@Samaritan89 You can closed this issue by yourself.
