### ISSUE TITLE
Add support for silent model destroy

### ISSUE THREAD

**Issue by seth2810** [jashkenas/backbone#3591]
Sometimes it is necessary to model the ability to recover, while if it is in the collection, then when you call destroy it should stay in it. Now when deleting the model is always called:

var destroy = function() {
    model.trigger('destroy', model, model.collection, options);
};

because of what the model will always be removed from the collection. My suggestion is that, when transmitted to the options parameter silent:true don't made event call.

What you say?

**Comment by braddunbar** [comment]
Hi @seth2810! I've seen a huge amount a bugs due to silencing events so I don't think we should go down this route. Also, if you need to model in a collection you probably shouldn't destroy it but use a separate technique.
