### ISSUE TITLE
method get: return value by default

### ISSUE THREAD

**Issue by vdakalov** [jashkenas/backbone#3595]
if we have a method to get the value of the object can be added to it a couple of useful arguments?
e.g.
```
user.get("age"); // undefined
user.get("age", _.isNumber); // undefined
user.get("age", _.isNumber, "N/A"); // "N/A"
```
if user age is not a Number, then return "N/A". Thus, if the age of the user will be overwritten on the null or undefined, the interface will look good.

Besides, you can define your function checks the data type
```
_.mixin({
  isMoment: function(source){ return moment.isMoment(source); }
});
```

**Comment by jmeas** [comment]
You can extend `Backbone.Model` and write your own [`get` method](https://github.com/jashkenas/backbone/blob/master/backbone.js#L410-L413).

I don't think this should go in the core lib tho'.

**Comment by jridgewell** [comment]
> You can extend Backbone.Model and write your own get method.

Exactly. This is too special purpose for a simple `#get` method.
