### ISSUE TITLE
Annotated source version number is misleading

### ISSUE THREAD

**Issue by olizilla** [jashkenas/backbone#3597]
The published annotated source gives the impression that it is the annotated source of version 1.1.2

![screenshot 2015-05-05 16 12 27](https://cloud.githubusercontent.com/assets/58871/7475778/9150c5a6-f341-11e4-8eaa-af94fedb28ce.png)
http://backbonejs.org/docs/backbone.html

which is misleading, as it's really whatever the state of master was at last `redoc`. I lost a bunch of time thinking I'd gone mad as a consequence. That hasn't been ruled out.

Would you consider:
1. bumping the version number to `1.1.3-rc` in `backbone.js` on master, so that the generated docs are less surprising.
2. ...or generating the docs from the `1.1.2` tag, so the contents match the the release.
3. ...or publishing both stable & master docs, labelled as such.

I'm happy to make a PR, but wanted to see which route is preferred.

**Comment by jashkenas** [comment]
The annotated source on the website should be the version for 1.1.2. 

We shouldn't be republishing the docs until there's a version bump. Is this not the case?

**Comment by osuushi** [comment]
I just ran into this as well.

Case in point: search the annotated source for "modelId"; 7 occurrences in the source code.

Now do the same search in the 1.1.2 release; 0 occurrences.

**Comment by olizilla** [comment]
Aye, there was a `redoc`-ing on the gh-pages branch a few months ago: https://github.com/jashkenas/backbone/commit/ffbd58d03ece688e33ad6e3ee31855b5f10f0e4a
