### ISSUE TITLE
Event handlers executed after stopListening is called

### ISSUE THREAD

**Issue by bendulum** [jashkenas/backbone#3599]
The issue i ran into might be more of an _unhandled case_ than an actual bug. Consider the following setup:

* There are 3 views, A, B & C
* Both B & C listen to the same event triggered by A
* In _some_ cases B destroys (remove / stop listening) C when the event is triggered
* The event handler in C is still executed even if C was already destroyed by B

[Here is a jsfiddle](https://jsfiddle.net/jtk19x4n/2/)

I'm aware that it might not be ideal architecturally to have B destroy C, and rather have C destroy itself, but in my use case that is unavoidable.
Also, I can not guarantee in which order B and C are bound to A in my use case.

The point is that the expected behaviour of `stopListening` is that after calling it, event handlers will not be executed anymore.

I am assuming backbone does some internal caching of the callback functions, and once the event fires, does not check anymore if the callbacks have been unbound in the interim...

Is this a bug, intended behavior or how am I supposed to handle this case?

**Comment by jridgewell** [comment]
> I am assuming backbone does some internal caching of the callback functions, and once the event fires, does not check anymore if the callbacks have been unbound in the interim...

Exactly correct. Once the event has been triggered, any listeners already bound _will_ be called. We did have a bit of a discussion about mutable events in #3476, but it involved a large amount of code to support.
