### ISSUE TITLE
Advice: add a function in Router to give users a chance to populate callbacks for routes

### ISSUE THREAD

**Issue by freegink** [jashkenas/backbone#3601]
## Suggested change in Router
Add a new function 'callback' or whatever name you like in Router that users can override to populate callbacks according to the name that users specified in "routes". This change won't affect any existing projects that are using Backbone.
```
 route: function(route, name, callback) {
      if (!_.isRegExp(route)) route = this._routeToRegExp(route);
      if (_.isFunction(name)) {
        callback = name;
        name = '';
      }
      if (!callback) callback = this.callback(name);   /* changed from "this[name]" */
     ...
      return this;
    },

/* 
Users can override this function to populate callback functions according to the name. 
*/
callback: function(name) {
    return this[name];
}
```

### Modules
```
var modules = {
    Index : {
        home: function() {
        }
    },
    Account: {
        login: function() {
        }
    }
};
```

### Router module
```
var Router = Backbone.Router.extend({
    routes: {
        '': 'Index.home',
        'login': 'Account.login',
    },
    callback: function(name) {
        return function(args) {
            var names = name.split('.');      
            modules[names[0]][names[1]](args);
        };
    }
});
```

**Comment by braddunbar** [comment]
Hi @freegink! This already exists, and is called `execute`. Hope it works for you!

```js
var Router = Backbone.Router.extend({
    routes: {
        '': 'Index.home',
        'login': 'Account.login',
    },
    execute: function(callback, args, name) {
      // …
    }
})
```

**Comment by freegink** [comment]
No, it's different. "execute" happens after "route" function has found the callback from the inherited router. So I have to either add route manually using "route" function, or add callback functions in the inherited router. My suggestion was to give users a chance to dynamically populate the callback function according to the name specified in "routes". That is, I don't have to put callback functions in the inherited router.

So look at the example I provided:
```
routes: {
        '': 'Index.home',
        'login': 'Account.login',
    },
```
In this example, because "Account.login" isn't a function of the inherited router, so if I override "execute", the "callback" parameter would be null.


```
route: function(route, name, callback) {
      if (!_.isRegExp(route)) route = this._routeToRegExp(route);
      if (_.isFunction(name)) {
        callback = name;
        name = '';
      }
      /***** what I'm talking about is this place ******/
      if (!callback) callback = this[name];  /**** right here *****/
      var router = this;
      Backbone.history.route(route, function(fragment) {
        var args = router._extractParameters(route, fragment);
        /*** this is where "execute" happens ***/
        if (router.execute(callback, args, name) !== false) {
          router.trigger.apply(router, ['route:' + name].concat(args));
          router.trigger('route', name, args);
          Backbone.history.trigger('route', router, name, args);
        }
      });
      return this;
    },
```

**Comment by braddunbar** [comment]
> In this example, because "Account.login" isn't a function of the inherited router, so if I override "execute", the "callback" parameter would be null.

Right, but the `name` argument is not. You can still use it there to look up a function.

**Comment by freegink** [comment]
Right. I didn't notice "execute" has gotten the "name" parameter. Because I was looking at the backbone documentation. Thanks. That'll work.

> execute router.execute(callback, args)

**Comment by braddunbar** [comment]
Ah! Didn't realize that. I'll look into getting it fixed later on.

**Comment by akre54** [comment]
The `name` change is only on master, it hasn't yet been added to a release. Our documentation on the website only reflects the current released version.

We [should really](https://github.com/jashkenas/backbone/pull/3285) release a version bump soon....

**Comment by jridgewell** [comment]
> This already exists, and is called execute.

I've taken to using the `route` event to implement this on older Backbone.

```javascript
var Router = Backbone.Router.extend({
    routes: {
        '': 'Index.home',
        'login': 'Account.login',
    },
    initialize: function() {
        this.on('route', this.callback);
    }
    callback: function(name, args) {
        var names = name.split('.');      
        modules[names[0]][names[1]](args);
    }
});
```

> We should really release a version bump soon....

I think https://github.com/jashkenas/backbone/pull/3577 is the last change that should be in 1.2.

**Comment by freegink** [comment]
Cool. saw the new release. Hooray!
