### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by evanvosberg** [jashkenas/backbone#3607]
Dropping the `package.json` https://github.com/jashkenas/backbone/commit/c42b38dc3083c514a94229f8e903222c7aec7cf9  stops backbone working with webpack out of the box.

**Comment by akre54** [comment]
Curious. Are you [using webpack with the `ResolverPlugin`](http://webpack.github.io/docs/usage-with-bower.html)?

**Comment by evanvosberg** [comment]
Don't use this one `DirectoryDescriptionFilePlugin`, will have a try. However from my perspective there there is no reason to drop the other package description files.

**Comment by akre54** [comment]
You're right that it probably isn't a huge deal to keep `package.json` around in a bower package, but it certainly shouldn't be necessary.

Besides, Webpack's enhanced-resolve is unmaintained and unsupported. Give ResolverPlugin a try and we can reopen if you're still experiencing troubles.
