### ISSUE TITLE
modelId getter doesn't work with polymorphic Model getter

### ISSUE THREAD

**Issue by antpaw** [jashkenas/backbone#3608]
I think i found a bug inside the 1.2.0 version. My Collection contains different Models, so i've used a getter to solve this.

``````
new Collection(
   model: function(attrs){
      if (attrs.foo) {
          return new FooModel(attrs);
      }
      else {
         return new BarModel(attrs);
      }
   }
)
``````

after upgrading i had some trobles with my app because the collection couldnt find already exsiting models inside of it `collection.get(1) # => undefined`. So I've digged into the source and found this "bug".
`this.model` isn't always a Model it can be function sometimes. 

``````
    modelId: function (attrs) {
      return attrs[this.model.prototype.idAttribute || 'id'];
    },
``````

So I think everybody who is using a function in `this.model` and has a custom idAttribute defined, backbone won't find already existing models.

``````
  modelId: function (attrs, options) {
    return this.model(attrs, options).id;
  },
``````
This is the overridden function i'm using inside my collection now, and it works for me.
So maybe the `modelId` function needs something like this:
``````
  if (_.isFunction(this.model)) { 
    return this.model(attrs, options).id;
  } 
  else {
    return attrs[this.model.prototype.idAttribute || 'id'];
  }
``````

**Comment by akre54** [comment]
If `this.model` is a plain function, its `prototype.idAttribute` will be undefined and that line will fall back to `'id'`, catching the common case. If your models have a more advanced idAttribute you have to override `modelId` too (though I wouldn't recommend creating a new model instance just to get its id property).

**Comment by antpaw** [comment]
Thanks, I see, the only reason I've submitted it because I after updating from 1.1.2 to 1.2.0 my code didn't work properly and I think I'm not the only one who will run into this issue especially because there is no mentioning about this in the documentation, just in the changelog without any warnings.

**Comment by akre54** [comment]
You're right, we should totally document that. Let me put something together.

**Comment by akre54** [comment]
@antpaw #3609
