### ISSUE TITLE
Regression: collection.invoke not calling expected methods

### ISSUE THREAD

**Issue by mvujovic** [jashkenas/backbone#3610]
In my app, I noticed collection.invoke stopped forwarding arguments to individual method calls when I upgraded from Backbone 1.1.2 to 1.2.0.

I created a reduced example, and I'm not seeing `sampleMethod` log anything at all using 1.2.0. This example works properly with 1.1.2:

(Save as HTML to run)
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"></script>

<!-- This test fails with 1.2.0: -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.0/backbone.js"/>

<!-- This test passes with 1.1.2: -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone.js"></script> -->

<script>
    var SampleModel = Backbone.Model.extend({
        sampleMethod: function (arg) {
            console.log(arg);
        }
    });

    var SampleCollection = Backbone.Collection.extend({
        model: SampleModel
    });

    var sampleCollection = new SampleCollection();
    sampleCollection.add(new SampleModel());
    sampleCollection.invoke("sampleMethod", "sampleArg");
</script>
<p>If the test succeeds, you should see "sampleArg" printed in the console.</p>
```

**Comment by jridgewell** [comment]
Thanks for spotting this. #3612 should fix it for you.

**Comment by mvujovic** [comment]
Thanks for the fix!

**Comment by jashkenas** [comment]
So, this fix merits a 1.2.1 ... 

Anything else outstanding that deserves to make it in?

**Comment by jridgewell** [comment]
@jashkenas https://github.com/jashkenas/backbone/pull/3594 should be considered

**Comment by jridgewell** [comment]
@jashkenas Actually, here's a milestone: https://github.com/jashkenas/backbone/milestones/v1.2.1. In particular, #3603 should be considered for v1.2.1 as well.
