### ISSUE TITLE
Default (complex) attributes are by reference for multiple instances of a model.

### ISSUE THREAD

**Issue by slikrik98** [jashkenas/backbone#3619]
If you have an object specified as a 'default' attribute in your model, all instances of this model will share a reference to that object. Is there a reason we don't do a deep clone on the defaults object when creating a new Model instance?

As it is currently, if you make changes to a deep attribute of that object, you will be updating all model instances. Is this by design?

**Comment by jridgewell** [comment]
That's a common gotcha in _all_ JavasScript, not just Backbone. You're better off using a function that returns your defaults instead.

```js
var Model = Backbone.Model.extend({
  defaults: function() {
    return {
      deep: { object: true }
    };
  }
});

**Comment by slikrik98** [comment]
Does Backbone discourage the use of objects for model attributes?

**Comment by Florian-R** [comment]
Yap, see #3457
