### ISSUE TITLE
API of 'on' function does have not backward compatible changes

### ISSUE THREAD

**Issue by fedulovivan** [jashkenas/backbone#3621]
Previously this way of defining events as map and passing context worked fine:
```javascript
someview.on({
  one: one,
  two: two
}, this);
```

After upgrading to 1.2.0 we need to set second argument to undefined and define context as third:
```javascript
someview.on({
  one: one,
  two: two
}, void 0, this);

**Comment by jridgewell** [comment]
Dupe of #3603.
