### ISSUE TITLE
Why remove the root's trailing slash when wantPustState on IE8?

### ISSUE THREAD

**Issue by houkanshan** [jashkenas/backbone#3623]
Example:

``` javascript
Backbone.history.start({ pushState: true, root: '/root/' })
```
1. The browser is IE8 (no pushState)
2. Our server will force a trailing slash, a request of `/root` will receive a redirection to `/root/`
3. Visit `/root/aa/bb`

Due to this commit d550b8b , an replaced url will be `/root#aa/bb`, then the server returns a redirection to `/root/`, which lead to an additional request, and at the same time the hash will be lost. The `/root/aa/bb` can't be reached.

I've read the #2656 and #3443. I'm thinking that should the tailing slash here also be optional ? Which means:

``` javascript
Backbone.history.start({ pushState: true, root: '/root/' }) // /root/#aa/bb
Backbone.history.start({ pushState: true, root: '/root' }) // /root#aa/bb
```

**Comment by blzzz** [comment]
+1

**Comment by paulfalgout** [comment]
ping @akre54  maybe this can be closed due to https://github.com/jashkenas/backbone/pull/4008
