### ISSUE TITLE
Prevent a new prototyped method to appear in for loop for keys in object

### ISSUE THREAD

**Issue by kpatel1989** [jashkenas/backbone#3624]
I have a function which I want to make it available to all objects. Its the mergeObject(object) function as defined below :

Object.prototype.mergeObjects = function(object){
    if (typeof object != "object") return;
    for(var key in object){
        if (object.hasOwnProperty(key))
            this[key] = object[key];
    }
    return this;
}

This is my events json:

events : {
    "click #retryBtn":"onRetryBtnClick",
    "click #cancelBtn":"onCancelBtnClick",
    "click .dialogButton":"onDialogBtnClick"
}

In Backbone View's  DelegateEvents() 

delegateEvents: function(events) {
      if (!(events || (events = _.result(this, 'events')))) return this;
      this.undelegateEvents();
      for (var key in events) {                          <---------------------loops through the inherited properties
        var method = events[key];
        if (!_.isFunction(method)) method = this[events[key]];
        if (!method) continue;

        var match = key.match(delegateEventSplitter);
        var eventName = match[1], selector = match[2];
        method = _.bind(method, this);
        eventName += '.delegateEvents' + this.cid;
        if (selector === '') {
          this.$el.on(eventName, method);
        } else {
          this.$el.on(eventName, selector, method);
        }
      }
      return this;
    },

Here the for loop for events iterates through the inherited properties and gives error when "mergeObjects" function is encountered. 
Shouldnt the for loop check for  hasOwnProperty for its own events and then iterate through its parent View but stop before iterating through the base Object's prototype ?

**Comment by jridgewell** [comment]
We certainly could check for own properties, but it would be a mildly — since a plain object is the normal case — breaking change.

However, it's considered an anti-pattern to modify the core JS prototypes. And, if you have to, define your modifications as `{ enumerable: false }`.

**Comment by akre54** [comment]
I'd say best not to modify `Object.prototype` at all. Use a helper function instead.
