### ISSUE TITLE
`router.navigate` doesn't update history after an async request (Opera 12)

### ISSUE THREAD

**Issue by am** [jashkenas/backbone#3634]
This is a singular question, but please bear with me. I faced a strange issue when executing a Backbone app on a rather ancient browser (Opera 9.8) some of the routes were not being registered in the browser history. With a little research saw that this would only happen in the following scenario:
- user interaction
- ajax request
- ajax callback handler that executes a `router.navigate`

In this cases **the url did change**, the app **could navigate to that route** but it **doesn't update the browser history**, hence the user can't navigate back.

This had the smell of a browser bug, created an small demo and bingo, this happens with just updating `document.location.hash` on a ajax request handler, here is [the SO question](http://stackoverflow.com/questions/30457126/change-history-after-async-ajax-request-on-opera-9-8) with that situation.

Looking for a fix for this I found that if I use `document.href` instead of `document.location.hash` on the [Backbone.history._updateHash](https://github.com/jashkenas/backbone/blob/61d18408addb54f4af4d3e14b0d47111ef94de99/backbone.js#L1796-L1804) method it works:
```javascript
Backbone.history._updateHash = function(location, fragment, replace) {
  var href = location.href.replace(/(javascript:|#).*$/, '');
  var url = href + "#" + fragment;
  if (replace) {
    location.replace(url); 
  } else {
    location.href = url;
  }
};
```
App testing are green and looks like my problem it's solved, but I've some question:

1. Is this a new issue? Although I couldn't find anything regarding this it's strange that no one experience this before
2. Is it safe to override a Backbone method the way I did? I see that preceding `_` on the method name so I assume that this wasn't designed to override.
3. Should this be fixed in Backbone instead? If that is the case I could do a PR.
4. Is there any alternative workaround that you can think of?

Thank you

**Comment by braddunbar** [comment]
Hi @am! Thanks for pointing this out. Here are some answers to your questions:

1. It's definitely new to me.
2. Yes! That's why those methods are attached to the prototype and not otherwise hidden. You'll just need to check on it with new releases in case it changes.
3. Maybe? I'd certainly look over a pull if you sent it. The only thing that concerns me is that I don't think anyone actively tests Opera 9.8. We'd be going entirely on faith and passing existing tests.
4. Nah, I've got nuthin'.

**Comment by am** [comment]
Hi @braddunbar =)
As noted before I've tested a simple fix for this that is working in my end, nevertheless I was trying to do some test that prove that I'm on the right path, but got tangled since I can't test `history.length` with the current setup of qunit. 
I'll create the pull and we can discuss there how to make this work.

**Comment by am** [comment]
After some testing realized that this can be solved by using jQuery 1.x.x. For some strange reason, that I could not figure out, using jQuery ^1.8.3 fixes the issue.
