### ISSUE TITLE
Nested attributes in model.save()

### ISSUE THREAD

**Issue by Pleochism** [jashkenas/backbone#3642]
I have a model that contains a sub-object. When attempting to save the model, with an explicit indication to re-save the sub-object, I run into issues.

```json
var diff = {
   "metadata": {
     "a": 1,
     "b": 2
  }
}
```

```javascript
model.save(diff, {wait: true});
```

The nested object is being picked up by the eventsApi method as a map, and is being deconstructed into "change:a" and "change:b" calls that are not correct.

Adding "silent: true" solves this, but I do in fact want to be notified of changes.

**Comment by jridgewell** [comment]
Can you post a [jsFiddle](https://jsfiddle.net/) showing the issue? I'm able to confirm `set` is working properly, and I suspect it's your server's response, or you model's `#parse`.

As a side note: Backbone **highly** encourages simple primitive attributes, not nested objects.
