### ISSUE TITLE
Model destroy method not call its success callback method after server response 200 

### ISSUE THREAD

**Issue by MiracleQsc** [jashkenas/backbone#3654]
my code as below 
var model = collection.findWhere({id:id});
                            model.destroy({
                            	success : function(){
                                                       console.log("1111");
                                             }
                            });
seems the success callback method never executed. 

just check the source code as 

 options.success = function(resp) { 
                if (options.wait || model.isNew()) destroy();
                if (success) success(model, resp, options);
                if (!model.isNew()) model.trigger('sync', model, resp, options);
            };  
but options.success not be executed.

Please help me.

**Comment by jridgewell** [comment]
Since your model has an `id`, the success callback will be executed asynchronously only if the server responds successfully.

Questions like this are better left for [StackOverflow](http://stackoverflow.com/questions/tagged/backbone.js), though.

**Comment by MiracleQsc** [comment]
Hi Jashkenas,

Thanks a lot for reply my question.

AS you said :"since your model has an id, the success callback will be executed asynchronously only if the server responds successfully."

I know this, my concerns is the server already response 200 to client,  but the success callback method still not executed.

As my understanding, 200 response code means responds successfully.

Could you please kindly help me . This case confused me too much time.

Thanks a lot.




42496379

From: Justin Ridgewell
Date: 2015-06-01 22:56
To: jashkenas/backbone
CC: MiracleQsc
Subject: Re: [backbone] Model destroy method not call its success callback method after server response 200 (#3654)
Since your model has an id, the success callback will be executed asynchronously only if the server responds successfully.
Questions like this are better left for StackOverflow, though.
