### ISSUE TITLE
.trigger('change')

### ISSUE THREAD

**Issue by acjohn** [jashkenas/backbone#3662]
v1.2.0 line 1117 doesn't contain 'model &&'
When setting value (using "silent:true") and then chaining & triggering a "change"  event, it throws an error

model.set({'some':'data'}, {'silent':true}).trigger('change');

I know it says "not" to use silent...

**Comment by jridgewell** [comment]
I'm not sure this needs to be fixed. The `change` event always passes `model` as the first argument, and an `options` object as the second. Anything else is breaking the contract.

`model.trigger('change', model, options)`.

**Comment by acjohn** [comment]
Hi Justin,

It's odd that it only happens when the model is in a collection.
I guess it's in my code somewhere.



Regards,

John Schroeder
johns@artisancolour.com
480-948-0009
