### ISSUE TITLE
Type Error with html 5 canvas 

### ISSUE THREAD

**Issue by billyholt** [jashkenas/backbone#3666]
Hello, I get a type error with backbone 1.2 from the cdnjs when rendering a model from within a view...
$(document).ready(function(){
var Box = Backbone.Model.extend({defaults: {x: 0,y: 0, w: 1,h: 1,}
});
var BoxSet = Backbone.Collection.extend({model:Box });
var BoxView= Backbone.View.extend({
    render : function() {var model=this.model, ctx=this.options.ctx;}
});
var SetView= Backbone.View.extend({ 
    initialize: function() {this.collection.on("all",this.render,this);},
    render: function() {var canvas=this.$el.get(0) , ctx=canvas.getContext("2d");}
});    
var c=new BoxSet();
c.add({x:10,y:10,w:100,h:100});      
var v=new SetView({el:$("canvas"),collection :c});
v.render();
})

**Comment by jridgewell** [comment]
We no longer attach `options` to the view. You're error is in your `#render` trying to access the `ctx` property.

**Comment by billyholt** [comment]
Thanks

Sent from my Sony Xperia™ smartphone

---- Justin Ridgewell wrote ----
