### ISSUE TITLE
Collection.at() behavior change

### ISSUE THREAD

**Issue by bazineta** [jashkenas/backbone#3668]
In release 1.1.2, the Collection.at() function was specified as follows:
```
// Get the model at the given index.
    at: function(index) {
      return this.models[index];
    },
```
Beginning in 1.2.0, this function is specified as:
```
 // Get the model at the given index.
    at: function(index) {
      if (index < 0) index += this.length;
      return this.models[index];
    },
```
Prior to 1.2.0, providing an index < 0 would return undefined; it now may or may not return undefined, depending on the index supplied.  This being a behavior change, would be nice to have it mentioned in the release notes.

**Comment by akre54** [comment]
Definitely. Fixed in 573b2fe. In the future feel free to open a pull request against the documentation and we'll merge.
