### ISSUE TITLE
Drop `include` method use for `includes`

### ISSUE THREAD

**Issue by jdalton** [jashkenas/backbone#3672]
The Underscore method `include` should be dropped in favor of `includes` in BB.

**Comment by akre54** [comment]
Definitely. `col.include` is weird. Maybe add the alias but deprecate the existing method?

**Comment by jdalton** [comment]
Relevant bit I saw was [this](https://github.com/jashkenas/backbone/blob/edc26d1b362fd8186163b33aa0e51fb40665002f/backbone.js#L1131).

**Comment by akre54** [comment]
What do you mean by relevant bit?

Opening an issue is great. A pull request is better. We can always tweak code style.

**Comment by jdalton** [comment]
It's mapping the `include` method over and not the `includes` alias. The `includes` (with an `s`) alias is now the preferred alias with `include` no longer being documented.

**Comment by jridgewell** [comment]
We'd have to bump to v1.8 in order to remove `Collection#include`. We should be able to add `includes`, though, which just won't define `Collection#includes` if only v1.7 is used.

**Comment by jdalton** [comment]
Cool cool.
