### ISSUE TITLE
Replace `_.any` with `_.some`.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/backbone#3677]
I'm wanting to cut aliases in v4 of lodash and wondering if you all would be cool with dropping `_.any` use in favor of the more ES-friendly `_.some` flavor.

**Comment by jridgewell** [comment]
`_.some` is the canonical name in underscore anyways. PR?

**Comment by jdalton** [comment]
Sure.

**Comment by jdalton** [comment]
Moved to #3678.
