### ISSUE TITLE
Using Backbone with Webpack and without jQuery throws errors

### ISSUE THREAD

**Issue by peeter-tomberg** [jashkenas/backbone#3683]
Following the guide:

https://github.com/jashkenas/backbone/wiki/Using-Backbone-without-jQuery

I get the error: Uncaught Error: Cannot find module "jquery". It seems like Webpack is defaulting to AMD and is trying to load jQuery and will throw an error when it fails. I tried forcing Webpack to use CommonJS using the imports loader:

```    
        loaders: [
            {
                test: /backbone.js/,
                loader: 'imports?define=>false'
            }
        ]
```

But the result is the following error message: Uncaught ReferenceError: Backbone is not defined (although Backbone is present in the JS file, not sure why I'm getting this error)

**Comment by akre54** [comment]
Ah sorry, I never added that in. Let me fix it.

That said this loader should work for you ([see my example]( https://gist.github.com/akre54/d7ebd8893128e4bf9235/0c291cf631a732c499aa3d52f70e9786e28821ab)). Can you try to whittle down what might be causing the ReferenceError?

**Comment by peeter-tomberg** [comment]
Yep, that works perfectly. The ReferenceError came from my bad code (Referencing Backbone without importing it :D). 

Thanks :+1:
