### ISSUE TITLE
how can listenTo scroll events?

### ISSUE THREAD

**Issue by xueyuchen** [jashkenas/backbone#3691]
how can listenTo scroll events?

**Comment by xueyuchen** [comment]
how can listenTo scroll events?

**Comment by jridgewell** [comment]
Specifying the `scroll` event in the `events` object works perfectly.

```js
var View = Backbone.View.extend({
  events: {
    scroll: 'onScroll'
  }
});
```

Keep in mind this [caveat](http://api.jquery.com/scroll/):

> The scroll event is sent to an element when the user scrolls to a different place in the element. It applies to window objects, but also to scrollable frames and elements with the overflow CSS property set to scroll (or auto when the element's explicit height or width is less than the height or width of its contents).

**Comment by akre54** [comment]
Please use the mailing list, StackOverflow, or the Gitter channel for questions.
