### ISSUE TITLE
docs for view.remove()

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3694]
jeremy

IMO

http://backbonejs.org/#View-remove

this absolutely positively needs to read:

```
remove - view.remove()
Removes a view from the DOM, *removes/deletes the DOM element*, and calls stopListening to remove any bound events that the view has listenTo'd. 
```

as it is now, it doesn't make it clear that the el goes missing after ```remove()```

this call

this.$el.remove();

is hiding inside remove() and it's dangerous

one thing you could do is pass a boolean to remove() and decide whether or not to delete the DOM element

**Comment by akre54** [comment]
"removes a view from the DOM" isn't clear? Would you rather "removes a view and its `el` from the DOM"?

These kinds of changes you should make in a pull request, not an issue.

**Comment by ORESoftware** [comment]
yes, what you just said would be much much clearer.

**Comment by ORESoftware** [comment]
...I don't know where to make the pull request...
