### ISSUE TITLE
Any plans to modularize backbone? 

### ISSUE THREAD

**Issue by jisaacks** [jashkenas/backbone#3696]
I would love to be able to do something like:

```js
import { events } from "backbone";

Object.assign(myModule, events);
```

**Comment by akre54** [comment]
This [should already work for you](http://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=import%20%7B%20Events%20%7D%20from%20%22backbone%22%3B%0A%0AObject.assign(%7B%7D%2C%20Events)%3B).
