### ISSUE TITLE
Issue about Backbone Collections

### ISSUE THREAD

**Issue by Gywem** [jashkenas/backbone#3697]
Hi everyone! 

I have likely found a bug concerning to backbone collections.
 
First, I have run the next code:
```javascript
var Model = Backbone.Model.extend({idAttribute: '_id'});
var all = new Backbone.Collection();

var model = new Model({_id: 1});
all.add(model);

console.log(all.get(1) === model);
```
If you execute the previous code using latest Backbone version, you will get false. Consecuently, if you are using custom idAttribute and you add it in a collection, you won't be able to get it back through its id by means of the get method. Otherwise, in case you are using Backbone v1.0.0, it truly works as expected.

**Comment by akre54** [comment]
You need to tell the Collection what its model class is:

```js
var Collection = Backbone.Collection.extend({
  model: Model
});
var all = new Collection;
```

We don't support using a Collection without setting its model class.
