### ISSUE TITLE
Collection Won't Reset

### ISSUE THREAD

**Issue by realph** [jashkenas/backbone#3705]
I'm trying to `.reset()` to clear my `collection` before calling `.fetch()` on it to retrieve new data for that page.

But for some reason my `collection` isn't being resetted and fetching the new data when I navigate to another page. It only resets the collection and gets the new data when I manually reload the page.

    class ProjectPostItemsView extends Backbone.View
      template: JST['project_post_items.ejs']
      posts_item_views: []

      initialize: ->
        super()
        @listenTo( @collection, 'add', @displayPostItem )
        @collection.reset().fetch(add: true)

      displayPostItem: (project) ->
        view = new ProjectPostItemView(model: project)
        @posts_item_views.push( view.on('render', =>
          @$('.post-items').append(view.$('>'))) )

      render: (options) ->
        super(options)

I've tried this too:

    @collection.fetch(reset: true, add: true)

But it still doesn't reset, and I get this error:

    Uncaught Error: Duplicate id: can't add the same model to a collection twice

I'm very new to Backbone so I'm not sure if I'm handling this correctly. What am I doing wrong?

Any help is appreciated. Thanks in advance!

**Comment by jridgewell** [comment]
These types of questions are more appropriate for [StackOverflow](http://stackoverflow.com/questions/tagged/backbone.js).

As a side note, you're using a [Backbone version](https://github.com/jashkenas/backbone/tree/0.9.0) from 2012.

**Comment by realph** [comment]
@jridgewell I've literally just jumped into this codebase, what makes you say that about the version? According to the version installed by bower, I'm using 1.1.2...

**Comment by jridgewell** [comment]
Because that [error](https://github.com/jashkenas/backbone/blob/0.9.1/backbone.js#L518) was [removed](https://github.com/jashkenas/backbone/commit/18fba5772430f667c0d3cfb88d880039381c25fa) in v0.9.2.
