### ISSUE TITLE
Model reference still exists in collection after remove

### ISSUE THREAD

**Issue by mauron85** [jashkenas/backbone#3707]
Backbone version: v1.2.1

Description: when you remove model from collection, model is still in collection in model remove handler

Expected: after remove model is not part of collection anymore

Actual: model is still in collection, because model remove event is triggered before model reference is removed

I've located problem in _removeModels method of Collection
```
...
 _removeModels: function(models, options) {
...
        if (!options.silent) {
          options.index = index;
// PROBLEM: Model remove event triggered, before reference is removed
          model.trigger('remove', model, this, options); 
        }
        removed.push(model);
        this._removeReference(model, options);
      }
      return removed.length ? removed : false;
    },
```

How to reproduce:

```

var collection = new Backbone.Collection;
var model = new Backbone.Model;
collection.add(model);

model.on('remove', function (model, collection) {
  if (collection.get(model)) {
    alert('Model is still in collection'); // error thrown (unexpected)
  }
});

collection.remove(model);

if (collection.get(model)) {
  alert('Model is still in collection'); // error not thrown (as expected)
}; 
```

or jsfiddle: https://jsfiddle.net/mauron85/sLoygsk7/1/

**Comment by jridgewell** [comment]
Thanks for the report! We're already tracking in https://github.com/jashkenas/backbone/issues/3693.
