### ISSUE TITLE
Error event not triggered when model destroy fails on ajax call

### ISSUE THREAD

**Issue by mauron85** [jashkenas/backbone#3714]
Hi,

I'm trying to figure out, what is the actual flow of events, when destroying model.

I think I see at least two issue related to model destroy.

1. error event is not triggered when ajax call fails (this is different from model save method, where error event is always triggered in case of ajax failure)
2. model collection removal should be delayed after successful ajax call, meaning that model is only removed from collection when ajax DELETE was successful

Here is the basic test:
Jsfiddle: http://jsfiddle.net/mauron85/115q8vsu/3/

```
var MyCollection = Backbone.Collection.extend({
  url: '/collection'
});

// 1. create instance of collection and model
var collection = new MyCollection;
var model = new Backbone.Model({
    id: '1'
});

// 2. add model to collection
collection.add(model);

// 3. this will be fired first after model.destroy() - EXPECTED
collection.on("request", function (model) {
  console.log('request');
});

// 4. this will be never fired as ajax call fails - EXPECTED
collection.on("sync", function (model) {
  console.log('sync');
});

// 5. this will be never fired, I was expecting this one to be triggered when ajax fails (same as for model save ...)
collection.on("error", function (model) {
  console.log('error');
});

// 6. this is fired last - at least confusing, as destroy ajax call failed
collection.on("destroy", function (model) {
  console.log('destroy');
});

// 7. this is fired right after 4. - at least confusing, as destroy ajax call failed
model.on('destroy', function () {
  console.log('model destroyed');
});

// 8. UNEXPECTED (removing model from collection,
// IMHO should be delayed and done after sucessfull ajax call)
collection.on("remove", function (model) {
  console.log('model removed');
});

model.destroy().always(function () {
  // Expecting collection length to be 1, as destroy was not succesfull, 
  // but it's 0 - model was removed from collection.
  // Should I add model back on ajax failure?
  console.log(collection.length);
});
```

Let's compare it with model save. No issue here. Events are tiggered as expected according to docs.

```
var MyCollection = Backbone.Collection.extend({
  url: '/collection'
});

// 1. create instance of collection and model
var collection = new MyCollection;
var model = new Backbone.Model({
    id: '1'
});

// 2. add model to collection
collection.add(model);

// 3. this will be fired first - EXPECTED
collection.on("request", function (model) {
  console.log('request');
});

// 4. this will be never fired as ajax call fails - EXPECTED
collection.on("sync", function (model) {
  console.log('sync');
});

// 5. this will be fired - EXPECTED
collection.on("error", function (model) {
  console.log('error');
});

model.save().always(function () {
  console.log(collection.length);
});
```

**Comment by jridgewell** [comment]
I think you're looking for `model.destroy({ wait: true })`. That'l make it wait until a successful ajax delete returns before triggering events and before removing the model from the collection.

**Comment by mauron85** [comment]
Will you at least think about it for second? Or you like closing my issues at sight?

Please, read and reconsider at least this one:

error event is not triggered when ajax call fails (this is different from model save method, where error event is always triggered in case of ajax failure)

**Comment by jridgewell** [comment]
> error event is not triggered when ajax call fails

The `error` event will be triggered on the model, but since the model is no longer a part of the collection it won't trigger an error event on the collection. Backbone's optimistic about any server requests it makes, so it's proceeded as if the request will pass. If you'd like for it to wait for the response instead, `{ wait: true}`.

http://jsfiddle.net/115q8vsu/4/

**Comment by mauron85** [comment]
But this is inconsistent with save method, which is also optimistic.

**Comment by jridgewell** [comment]
Because `#save` optimistically adds the model to the collection, hence the events being triggered on the collection. `#destroy` optimistically removes the model from the collection, preventing events from triggering there.
