### ISSUE TITLE
Documentation of options

### ISSUE THREAD

**Issue by Industrial** [jashkenas/backbone#3715]
Hi.

http://backbonejs.org/#Model-set

This (and many other methods of backbone classes) doesn't include documentation of all the arguments. I can not seem to find these options.

**Comment by jridgewell** [comment]
Would you like to work on a PR?

**Comment by Industrial** [comment]
Sure! :+1:

**Comment by macgyver** [comment]
:+1: I had to look at the source code to realize that `.set` has a multi-variate signature

**Comment by paulfalgout** [comment]
@akre54 is there work to be done here?  Looks like the PR for this issue was rejected: https://github.com/jashkenas/backbone/pull/3788/files  Not sure what else this issue would be useful for.
