### ISSUE TITLE
Overriding Backbone model.parse()

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3716]
Hi all

I overrode Backbone.Model instance.parse like so:

```javascript
  parse: function (resp, options) {
                    /*
                     parse converts a response into the hash of attributes to be set on the model.
                     The default implementation is just to pass the response along.
                     */
                    if(resp.success){
                        return resp.success;
                    }
                    else{
                        return {};
                    }
                }
```

BTW this is in my model "class", it is not passed in as an option, hope that's not a problem.

In my API, if everything is successful, I do this with Node

```javascript
res.send({success:model};
```
if there is an error, I do:
```javascript
res.send({error:model});
```
so as you can see, in the my overridden parse function it returns resp.success. I think this part is correct. *However* when I return {}, then some problems seems to happen.

Backbone seems to create whole new Backbone models if I return an empty object {} in the parse function.

In any case, what is the best way to handle different responses from the server in the parse method?

For example, ss this a good idea?

```javascript
  parse: function (resp, options) {
               
                    if(resp.success){
                        return resp.success;
                    }
                    else{
                        return this.attributes; /// is this a good idea?
                    }
                }
```

**Comment by akre54** [comment]
Try asking these questions on the mailing list, the gitter board, or on StackOverflow. Github issues are for maintaining the framework only.
