### ISSUE TITLE
annotated source docs

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3718]
Hi there

I am having a lot of trouble figuring out what this call does in the Model constructor

```javascript
this.set(attrs, options);
```

can the annotated source be updated to speak to what this accomplishes? the source is very confusing. the reason why I care is because I want my Views and Collections to have to have some of the same ability as Models to have default values, so I am trying to mimic the behavior of the Model constructor with my Views and Collections...

**Comment by RusAlex** [comment]
There is a comments regarding this method in backbone source. 

https://github.com/jashkenas/backbone/blob/master/backbone.js#L460

What cant you undesrtand ?

Also models can have default attribute values.  You just define `defaults` property of your model as hash and you will get set the corresponding properties to be set during model instantiation.

https://github.com/jashkenas/backbone/blob/master/backbone.js#L401

**Comment by akre54** [comment]
Try it out for yourself and see. The method is pretty straightforward ([this](https://github.com/jashkenas/backbone/blob/1.2.1/backbone.js#L384) is how Model implements `defaults`, for example.)

In the future, please don't use Github issues to ask questions. Try the gitter channel, the StackOverflow page, or the mailing list.
