### ISSUE TITLE
Bump

### ISSUE THREAD

**Issue by jdalton** [jashkenas/backbone#3720]
This is a placeholder issue for @megawac or @jridgewell to hijack with checklists for the next bump.

I'm prepping for lodash v4 as part of the [Underdash proofing](https://github.com/underdash/underdash/issues/4#issuecomment-118974230) and will wait for the Backbone bump which removes `_.any` use in favor of `_.some`.

**Comment by jridgewell** [comment]
### Relevant changes

- **#3680**
- **#3667**
- #3675
- #3678 
- #3646

### Things that should be considered

- **#3711**
- #3717

Bolded issue numbers are the important ones, non-bolds not so much...

Some one want to take a stab at writing the change log? Writing prose really isn't my thing. @paulfalgout?

**Comment by paulfalgout** [comment]
Sure thing.  I'm all about taking on the small stuff.  I might wait on the considerations?

**Comment by jridgewell** [comment]
> I might wait on the considerations?

Yup, those were just for the contribs to keep a checklist.

**Comment by megawac** [comment]
We can publish a version before addressing all these, yeah?

**Comment by jdalton** [comment]
Anything to do here or is it :shipit: time?

**Comment by paulfalgout** [comment]
If we can pick the issues shipping, I'll go ahead and draft the log.

**Comment by jdalton** [comment]
> If we can pick the issues shipping, I'll go ahead and draft the log.

Let's go with what's merged.

**Comment by jridgewell** [comment]
@paulfalgout: I agree with @jdalton here. Let's just ship what we have, and we can merge the rest in the next version.

**Comment by paulfalgout** [comment]
good deal.. I'll get on it shortly.. was a long weekend.

**Comment by paulfalgout** [comment]
So....

**Comment by jashkenas** [comment]
Bumped and published.
