### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [jashkenas/backbone#3722]
Hey there Backbone devs,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for Backbone in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?

**Comment by jridgewell** [comment]
Thanks for reaching out.

I don't think any of the core contributors use Windows as their main OS, so we generally wait till Sauce tells us there's a problem. Until Sauce supports Edge (or an Edge [VM](http://dev.modern.ie/tools/vms/mac/) is released) I don't think any of us have tried to run the test suite on Edge.

That said, the Backbone tests are hosted at http://backbonejs.org/test/... :smiley:

**Comment by jdalton** [comment]
![image](https://cloud.githubusercontent.com/assets/4303/8807569/531f1b10-2f92-11e5-90a6-02488475293e.png)

Current stable and master branch versions pass in MS Edge.

**Comment by jdalton** [comment]
with support back to 0.9.0 (based on tags it went from 0.5.3 to 0.9.0) and tests were runnable back to 0.9.0.

**Comment by jdalton** [comment]
because the test runner failed to run I suspect the older versions QUnit dep to be the cause of the issue.

**Comment by jridgewell** [comment]
> Current stable and master branch versions pass in MS Edge

:smile: Thanks for testing it!

**Comment by megawac** [comment]
Thanks @jdalton
