### ISSUE TITLE
AJAX_Backbone

### ISSUE THREAD

**Issue by saurabhbh21** [jashkenas/backbone#3728]
I'm doing a project in PHP( Laravel 5) in which requires AJAX and recently started learning backbone JS due to its MVC structure but I'm unable to use AJAX via. Backbone JS in Lavavel, Can anyone help...

**Comment by RusAlex** [comment]
This is backbone development area.

Please post questions about how to use backbone on mailling list:

https://groups.google.com/forum/#!forum/backbonejs

or

http://stackoverflow.com/search?q=backbone

**Comment by jridgewell** [comment]
Thanks @RusAlex.
