### ISSUE TITLE
IE11 compatibility mode IE7 hashchange not work

### ISSUE THREAD

**Issue by chinason** [jashkenas/backbone#3730]
I guess IE8+ compatibility mode IE7 also does not work.
The reason is that IE11 running in IE7 compatibility mode reports true for <b>'onhashchange' in window</b>, even though the event isn't supported.

**Comment by paulfalgout** [comment]
At first glance this looks to be an issue with IE11 and not backbone's handling of `onhashchange`.  Is it not?

**Comment by jridgewell** [comment]
Nah, it's because IE11 is bad at pretending to be IE7, which doesn't have `onhashchange`. We could add a [Modernizer like test](https://github.com/Modernizr/Modernizr/blob/347ddb078116cee91b25b6e897e211b023f9dcb4/feature-detects/hashchange.js)?

**Comment by jdalton** [comment]
I can make a PR.
