### ISSUE TITLE
Collection set causes error with add:false option

### ISSUE THREAD

**Issue by nadarik** [jashkenas/backbone#3731]
Working example:
```
var books = new Backbone.Collection({id: 1, title: 'Book1'});

books.set([{id: 1, title: 'updated title for first book'}, {id: 2, title: 'Book2'}], {add: false});
```
the result will be collection with only one model with id: 1

Not working example:
```
var books = new Backbone.Collection({id: 1, title: 'Book1'});

books.set([{id: 2, title: 'Book2'}, {id: 1, title: 'updated title for first book'}], {add: false});
```

P.S. The result of the second example is: 
Uncaught TypeError: Cannot read property 'id' of undefined

**Comment by jridgewell** [comment]
Worked fine for me on http://backbonejs.org/. I'll reopen if you can post a failing test case.

**Comment by nadarik** [comment]
Sorry, looks like it's already fixed in current version, but it didn't work in 1.1.2.

Thanks.
