### ISSUE TITLE
Can someone tell me whats wrong with this code?

### ISSUE THREAD

**Issue by mahirsiraji** [jashkenas/backbone#3733]
#include <iostream>
#include <cstring>
using namespace std;

double gpay=0, tgpay=0;

struct employee
{
	string number;
	string name;
	double rate;
	int hours;
};

int main() 
{
	employee brain;
	for (int i=0;i<=3;i++)
	{
		cout<<"Enter "<<i+1<<" employee info.";
		cin>> employee[i].number>>employee[i].name;
		cin>>employee[i].rate>>employee[i].hours;
	}cout<<endl;
	cout<<"Payroll report with grosspay: ";
	for (int i=0;i<4;i++)
	{
		cout<<employee[i].number<<employee[i].name;
		gpay=employee[i].rate * employee[i].hours;
		cout<<gpay; gpay+=tgpay;
	}
	cout<<endl;
	cout<<"Total gross pay= "<<tgpay/4.0;
	
	
	return 0;
}

**Comment by jridgewell** [comment]
@mahirsiraji: This is a repo for Backbone.js, a JavaScript library. Please stop posting issues about your C++ code.
