### ISSUE TITLE
Deferring updates until first save succeeds

### ISSUE THREAD

**Issue by dgsan** [jashkenas/backbone#3734]
What is the generally accepted method of delaying additional updates until the first save succeeds (with a model)? 

I'm trying to avoid an issue where save ends up creating additional entries server side because the first few saves all end up getting treated as `create` (POST) requests, I guess because of latency with the first save. I'll see something like POST `{first_name: "John"}`, POST `{first_name: "John", last_name: "Doe"}`, instead of the second request being a PUT for `first_name` and `last_name`, and then end up with multiple DB rows that are near identical as fields are sequentially filled in.

I tried the simple solution of deferring saves with deferred objects, but that just seems to lead to the hash sent back from the server's first save clobbering any local changes before the deferred save fires.

Thought I'd check before writing something complicated that queues/merges pending changes. Most of the related google results seem to be from several years ago (and haven't worked in tests).

**Comment by tsjoberg** [comment]
The save event is an async event so without looking at your code you can try to use the models ```'sync'``` event and listen to that event prior to calling additional updates. 

http://backbonejs.org/#Events-catalog

You can also add a ```success``` callback to the save options as shown in the docs too which is called if 200 response is returned:

http://backbonejs.org/#Model-save

However you will probably need this and other functionality (ex. disabling submit button on ```request``` (or debouncing the actual save to make sure you send the latest data on multiple clicks) and re-enabling submit on successful save etc. These are just a few ideas but hopefully that helps.

**Comment by akre54** [comment]
Please use the mailing list, StackOverflow, or the gitter channel for questions. Github issues are for maintaining the framework only.

That said, there are a few solutions to your problem, but the easiest, as @tsjoberg mentioned, is to [`debounce`](http://underscorejs.org/#debounce) your saves. You might also want to think about why this is happening in your code, and how to avoid it.

**Comment by dgsan** [comment]
I just want to point out the the README.md says "To suggest a feature, report a bug, or general discussion: https://github.com/jashkenas/backbone/issues". I don't have any objections to using other forums, it just looked like the readme was suggesting asking stuff like this here.

**Comment by akre54** [comment]
Ha, we may've outgrown that wording. It's been our policy for a few years that questions should live on a more appropriate medium. Thanks for pointing that out, I'll fix it ASAP.
