### ISSUE TITLE
collection.filter

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3737]
hi all !

why does 

```javascript
collection.filter
```
  return a plain array instead of a Backbone collection?

just curious if there is a rationale behind that. I know all about how Backbone objects inherit Underscore properties, but I was surprised to learn that collection.filter was not tailored to return a collection in turn instead of returning a plain array as surely does this:

```javascript
_.filter(array,fn)
```

**Comment by megawac** [comment]
Consider using BB.VirtualCollection for this use case https://github.com/p3drosola/Backbone.VirtualCollection
