### ISSUE TITLE
Collection triggers 'sync', when a model is fetched

### ISSUE THREAD

**Issue by Kris0** [jashkenas/backbone#3738]
Im not sure if this is intended, but i got some issues in my app due to the collections 'sync' event. 

I expect the collection to trigger a 'sync' after calling the fetch method of the collection. BUT i don't expect a collection 'sync', when a model in the collection is fetched.

This problem is easier explained in code:
```javascript
var aCollection = Backbone.Collection.extend({...});

// here is where i expect a 'sync' event from the Collection
aCollection.fetch();

var aModel = Backbone.Model.extend({...});

aCollection.add(aModel);

// At this point a Model 'sync' is triggered, which perfectly fine
aModel.fetch();

// but a Collection 'sync' is triggered too. :O
```

**Comment by jridgewell** [comment]
Check the first argument to your sync listener, it'll either be the `collection` or the `model`.

**Comment by Kris0** [comment]
I created a fiddle to show the problem.

https://jsfiddle.net/1r69170s/9/

**Comment by jridgewell** [comment]
https://jsfiddle.net/1r69170s/11/

**Comment by Kris0** [comment]
Wow, did Not knowed that the Source Objekt is Passed to the listener function. Thank you, very much.
