### ISSUE TITLE
Old docs still up at http://documentcloud.github.io/backbone/

### ISSUE THREAD

**Issue by krbullock** [jashkenas/backbone#3741]
I recently got tripped up by the fact that http://documentcloud.github.io/backbone/ is hosting out-of-date downloads and documentation, and looks just like the new official site at backbonejs.org. I'm not sure how I first stumbled upon the old URL (probably DuckDuckGo search results). The same situation exists for Underscore: http://documentcloud.github.io/underscore/

Perhaps it would be wise to set up a redirect from the old URL to the new one?

**Comment by akre54** [comment]
Looks like an issue with Github Pages. We changed the repo over to `jashkenas/backbone` [two years ago](f2520913e504cdc17d773f2ca5f452ca090d92fa), and it looks like the Pages branch never got updated.

**Comment by jashkenas** [comment]
I'll open a ticket with Github Support.

**Comment by jashkenas** [comment]
It was a bug when project moving was first implemented. Support has helpfully unpublished the pages for us.
