### ISSUE TITLE
Documentation for Collection#modelId is wrong

### ISSUE THREAD

**Issue by denisw** [jashkenas/backbone#3749]
The [modelId docs on backbonejs.org](http://backbonejs.org/#Collection-modelId) say that the method should return the *name of the ID attribute* that Backbone should use. After a long and painful debugging session, I found out that the method should actually return *the ID itself* instead of the attribute name. This should absolutely be fixed.

**Comment by jridgewell** [comment]
Looks like we fixed this in https://github.com/jashkenas/backbone/pull/3609, but just haven't uploaded the documentation yet. That'll be fixed once we release [v1.3](https://github.com/jashkenas/backbone/pull/3740).

**Comment by mortenson** [comment]
The documentation for this is still vague, I assumed that the string name of the attribute was the expected return value. Did this ever get fixed?

**Comment by jridgewell** [comment]
@akre54: How do we do update the Backbone website docs?

**Comment by akre54** [comment]
Cherry pick the commit to gh-pages.

**Comment by jridgewell** [comment]
@mortenson: It's been updated on http://backbonejs.org/.

**Comment by mortenson** [comment]
:+1:

**Comment by ishaikovsky** [comment]
The example still wrong, doesn't it? I mean it still returns the name of the attribute:

  modelId: function(attrs) {
    if (attrs.type === 'dvd') {
      return 'dvd' + attrs.dvd_id;
    } else {
      return 'vhs' + attrs.vhs_id;
    }
  }


Also 
var library = new Library([
  {type: 'dvd', dvd_id: 1},
  {type: 'vhs', dvd_id: 1}
]);

second object should have "vhs_id".

**Comment by craigmichaelmartin** [comment]
Yeah, it was fixed in https://github.com/jashkenas/backbone/commit/4caa6e6835fdb558b6575bdba882f47b050c5516

**Comment by akre54** [comment]
@ishaikovsky That was fixed on master but not pulled into gh-pages. Fixed now.

**Comment by craigmichaelmartin** [comment]
It still has the second typo ishaikovsky pointed out.

**Comment by akre54** [comment]
Sigh :)

Time to open a pull

**Comment by craigmichaelmartin** [comment]
Out of curiosity, why isn't the commit I referenced being pulled in. It is up to date with head of master for that code.

**Comment by akre54** [comment]
I just did 2e60ab61094e6cc73f31a61e0e324cb2a901fdf0

**Comment by craigmichaelmartin** [comment]
Was https://github.com/jashkenas/backbone/commit/8011b5c75b60a88a61abe0a3779b70b1b2bbeda9 skipped in the cherry-pick? The second typo is still alive and well :(

**Comment by craigmichaelmartin** [comment]
Or actually, it looks like https://github.com/jashkenas/backbone/commit/b434d06fd0783815161665840373cd4f09414b71 is where it's coming from.

**Comment by akre54** [comment]
By second typo do you mean the second object should have `vhs_id`? This was fixed by using a shared `id` instead of `vhs_id` / `dvd_id`.

**Comment by ishaikovsky** [comment]
But what about:

```
var library = new Library([
  {type: 'dvd', **dvd_id**: 1},
  {type: 'vhs', **dvd_id**: 1}
]);
```

**Comment by craigmichaelmartin** [comment]
They should both have have their appropriate `type` and and an `id`; or else an `idAttribute` of `dvd_id`, no?

**Comment by akre54** [comment]
Yeah we could make a `LibraryItem` Model that would set its own `idAttribute` but I thought a) the example was getting long enough, and b) it demonstrates the behavior of `modelId` a bit better to leave `idAttribute` out of it.

**Comment by craigmichaelmartin** [comment]
Then the models should have `type` and `id`, right. Where is `dvd_id` coming from?

**Comment by craigmichaelmartin** [comment]
Anyway, the example code on the website now saves `dvdundefined` and `vhsundefined` before throwing a `TypeError` at `library.get('dvd1').id`.

**Comment by akre54** [comment]
Looks like a bad merge into gh-pages. Should be fixed now.
