### ISSUE TITLE
Nutch 2.3 Tika parsing issue

### ISSUE THREAD

**Issue by pradumnapanditrao** [jashkenas/backbone#3756]
I am trying to crawl specific data as per requirement by using nutch 2.3. I have tried to make changes into parse-tika plugin, but it got impacted if i make small changes into the same while compiling as it's connectivity with different classes as storage, parse,crawl etc.
So please suggest on the same.

**Comment by au-phiware** [comment]
Please direct your questions to the [Gitter chatroom](https://gitter.im/jashkenas/backbone), the [Google Group](https://groups.google.com/forum/#!forum/backbonejs), or Freenode IRC in the #documentcloud channel.
