### ISSUE TITLE
Should the events hash be responding to jQuery's triggerHandler method?

### ISSUE THREAD

**Issue by MeoMix** [jashkenas/backbone#3761]
Hey,

I'm working with some legacy code at the office and this plugin we use seems to use `triggerHandler` rather than `trigger` for firing events. I don't have a ton of XP with `triggerHandler`, so maybe this functionality makes sense, but I was really confused with unexpected results from the following:

	var TestView = Backbone.View.extend({
	  template: _.template('<div class="foo"></div>'),
	  events: {
		'custom.event .foo': function(){
		  console.log('custom.event ran');
		}
	  },
	  render: function() {
	    this.$el.html(this.template());
      
        this.$('.foo').on('custom.event', function(){
            console.log('custom.event is in here');
        });
      
	    return this;
	  }
	})

	var testView = new TestView();
	testView.render();
	jQuery.event.trigger('custom.event', null, testView.$('.foo')[0], true);

In this example only the the event handler bound in render fires, but I thought "on" and "events" were bound identically.

This appears to be because of how event delegation works inside of Backbone.View's events hash. Is this intended behavior, something that is a known issue but is just "lived with," or ?

Thanks!

**Comment by akre54** [comment]
I think @paulfalgout [put it well](https://github.com/marionettejs/backbone.marionette/issues/2669#issuecomment-120759143) on the Marionette issue. 

Backbone [binds events to the view with delegation](https://github.com/jashkenas/backbone/blob/1.2.1/backbone.js#L1267-L1270), not directly to the el.

```js
// Your example:
this.$('.foo').on('custom.event', ...);

// Backbone:
this.$el.on('custom.event', '.foo', ...);
```
