### ISSUE TITLE
No Error Fired on broken connections

### ISSUE THREAD

**Issue by ericrange** [jashkenas/backbone#3762]
Why is there no error event firing when my app do not reach the server? e.g. on "net::ERR_CONNECTION_RESET"?? or on "404". My error: function(...) in my fetch method is not touched at all??

**Comment by mr47** [comment]
What jquery version you use? 
It's can be jquery bug or some times browser,  like in ff 38 with utf16 requests it's don't fire events at all. (xhr)

**Comment by jridgewell** [comment]
This is unlikely to be a Backbone issue, but a jQuery one. Mind opening an issue on there [tracker](https://github.com/jquery/jquery/issues)?
