### ISSUE TITLE
Collection.create should return the xhr

### ISSUE THREAD

**Issue by lededje** [jashkenas/backbone#3764]
or an option to have the xhr returned instead of just the events triggered.

The events that are triggered don't let you interfere with the request, for example aborting it.

Thoughts?

**Comment by mr47** [comment]
For ```Collection.create``` result is right - its model, for control of the process you can rewrite ```Collection.sync``` method so you can control xhr how you want. For request progress you can use ```options.success``` -  ```Collection.create(model, options)``` see [Collection.create](https://github.com/jashkenas/backbone/blob/master/backbone.js#L1022) and [Backbone.sync](http://backbonejs.org/#Sync)

**Comment by lededje** [comment]
Fair point.

**Comment by jridgewell** [comment]
This should be part of the [V2 Promises](https://github.com/jashkenas/backbone/pull/3651).

```js
collection.create({attr: 'value'}).then((model) => {
  // Model created successfully
}, (error) => {
  // Some error happened with creating locally
});

collection.create({attr: 'value'}, { wait: true }).then((model) => {
  // Model created successfully
}, (error) => {
  // Some error happened with creating locally or on the server
});
```

**Comment by mr47** [comment]
@jridgewell it's near future :)

**Comment by lededje** [comment]
@mr47 I tried what you suggested and it's a little more painful that just modifying sync. I pretty much want the same functionality, but just changing the return to be the xhr. To do that I need to copy out two other private function dependencies too (_prepareModel, _isModel). Not very fun :(

Is this something you'd consider changing or am I better off waiting for promises v2 that @jridgewell is talking about.

**Comment by jridgewell** [comment]
> Is this something you'd consider changing or am I better off waiting for promises v2 that @jridgewell is talking about.

This won't be changing in v1.X.
