### ISSUE TITLE
How to add new 10 rows in existing page?

### ISSUE THREAD

**Issue by amitkushwaha1710** [jashkenas/backbone#3768]
![more](https://cloud.githubusercontent.com/assets/5512426/9378846/48da5616-4742-11e5-9b22-b4722d1c009b.JPG)

Please tell me how can i add more 10 rows below these rows after click on more.

**Comment by akre54** [comment]
Please use the mailing list, StackOverflow, or the Gitter channel for questions. Github issues are for maintaining the framework only.
