### ISSUE TITLE
Is Backbone.history a part of the public API?

### ISSUE THREAD

**Issue by uzikilon** [jashkenas/backbone#3769]
Could we expect the Backbone.history object to exist as it is moving on?
If so, will it be added to the documentations?

**Comment by jashkenas** [comment]
It's documented.

http://backbonejs.org/#History-start

**Comment by uzikilon** [comment]
Sorry for not being specific, I was referring to the [undocumented methods](https://github.com/jashkenas/backbone/blob/master/backbone.js#L1571), and `loadUrl` specifically which was used by one of our devs.
Could we assume that these methods will stay a part of the API?
