### ISSUE TITLE
router.navigate stopped working in 1.2.2

### ISSUE THREAD

**Issue by subpublic** [jashkenas/backbone#3773]
Hi

I'm using backbone/marionette in a webpack project. Using webpack-dev-server as server.
I had a problem though, that

```
router.navigate('/hello', {trigger: true});
```

didn't work. Nothing happened. No error either.

But rolling back to 1.2.1 solved the problem, so something strange sneaked in to the router.

**Comment by jridgewell** [comment]
Only three changes happened in the routing layer between v1.2.1 and 1.2.2:

- https://github.com/jashkenas/backbone/pull/3675
- https://github.com/jashkenas/backbone/pull/3678
- https://github.com/jashkenas/backbone/pull/3751

Of them, I'd wager it was #3751 that's causing the problem. Can you give us a bit more information on what's happening?

**Comment by subpublic** [comment]
Hmm I'm not sure.
"navigate" inside backbone.js seems to be called at
```Backbone.history.start({pushState: true});```
but never again. Not when calling router.navigate() later.
I've put console.log inside backbone.js but they (found two) are not called.

**Comment by jridgewell** [comment]
What browser are you using?

**Comment by LKay** [comment]
The same thing happens for me after dumping Backbone from 1.2.1 to 1.2.2. Routers are initialised before ```Backbone.history.start()``` but seems app freezes as they don't get executed upon navigation. Works fine with 1.2.1. Both cases ```pushState``` and has bang routing have the same behaviour. 

BTW. It also break Backbone Marionette routing.

**Comment by jridgewell** [comment]
What browser you using? And can you post a code sample?

**Comment by LKay** [comment]
I'm using the latest Chrome 45.0.2454.85. About code sample it's more difficult. Actually it's an Marionette app, quite complex with modularised routers.

**Comment by filipmares** [comment]
Weirdest thing. I'm running into the same issue 1.2.1.

**Comment by alannesta** [comment]
I got exactly the same issue on backbone 1.2.3 as @filipmares, the Backbone.history.handlers array is empty

**Comment by blikblum** [comment]
I was having a similar problem. After some research i found that two Backbone versions was being bundled by Webpack. 
The project depends of 1.2.3 and Backbone.Syphon was dependent of 1.2.1
I updated Backbone.Syphon dependency to accept 1.2.3, run npm dedupe and rebuild the app: worked
Tip: run webpack --display-modules to know if two versions are bundled

**Comment by filipmares** [comment]
That is correct. Thanks for the tip.

On Sun, Oct 18, 2015 at 1:12 PM Luiz Américo <notifications@github.com>
wrote:

> I was having a similar problem. After some research i found that two
> Backbone versions was being bundled by Webpack.
> The project depends of 1.2.3 and Backbone.Syphon was dependent of 1.2.1
> I updated Backbone.Syphon dependency to accept 1.2.3, run npm dedupe and
> rebuild the app: worked
> Tip: run webpack --display-modules to know if two versions are bundled
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jashkenas/backbone/issues/3773#issuecomment-149043211>
> .
>
-- 
-Filip

**Comment by paulfalgout** [comment]
@akre54 I think this can be closed.  This issue is most likely described here: https://github.com/jashkenas/backbone/issues/3773#issuecomment-149043211
