### ISSUE TITLE
passing options to url function from Backbone.sync function, in model, collection

### ISSUE THREAD

**Issue by ORESoftware** [jashkenas/backbone#3774]
this seems like a no-brainer

in order to construct a URL and add query params, or what not, we need to know what type/method the request will be and what options to take for the request

in the source we have:

```javascript
 sync: function(method, model, options) {
                    var type = methodMap[method];

                    // Default options, unless specified.
                    _.defaults(options || (options = {}), {
                        emulateHTTP: Backbone.emulateHTTP,
                        emulateJSON: Backbone.emulateJSON
                    });

                    // Default JSON-request options.
                    var params = {type: type, dataType: 'json'};

                    // Ensure that we have a URL.
                    if (!options.url) {
                        params.url = _.result(model, 'url') || urlError();   // <=== why this ?? No params passed to url function?
                    }
                ....
```

why isn't it this instead:

```javascript
 sync: function(method, model, options) {
                    var type = methodMap[method];

                    // Default options, unless specified.
                    _.defaults(options || (options = {}), {
                        emulateHTTP: Backbone.emulateHTTP,
                        emulateJSON: Backbone.emulateJSON
                    });

                    // Default JSON-request options.
                    var params = {type: type, dataType: 'json'};

                    // Ensure that we have a URL.
                    if (!options.url) {
                        params.url = model.url(method,options);   // <===== why not pass method/options to url function?
                    }
                 ...
```

am I missing something? We may want to construct a url and add query params given certain options passed to Backbone.sync, right?

**Comment by jridgewell** [comment]
We'd have to update [`#url`](https://github.com/jashkenas/backbone/blob/91d0824190030f9e39ec3a88fe14cd10bf62395c/backbone.js#L689-L697), too. Want to work on a PR?

**Comment by ORESoftware** [comment]
yeah I would like to, yep would have to update url to have the 2 given params

**Comment by ORESoftware** [comment]
it should be backwards compatible with no issues that I can foresee

**Comment by akre54** [comment]
#648 #1476 #3109 #3108

**Comment by ORESoftware** [comment]
@akre54  can you tell me what you're thinking with more words?

**Comment by ORESoftware** [comment]
I will create a pull request, the url function needs to be passed some params from sync by default.

**Comment by akre54** [comment]
There's a pretty sizeable thread in #3109. Read that first (and please do a search before opening issues).

Essentially you should make use of the `data` prop to jQuery.ajax if you need to set querystring values. Any futzing with the actual URL string should be done with instance props and the `url` method.
