### ISSUE TITLE
Why events not work

### ISSUE THREAD

**Issue by Fishfaceeast** [jashkenas/backbone#3777]
I recently write a city select component demo using backbone.js.  The window.CityModalView events ("click span.confirm": 'confirm') failed. But the window.CityView  events("click span.confirm2": 'confirm') works. Can any one tell me what's wrong with my code and how to fix it? Thank you very much.

The code is in jsfiddle: http://jsfiddle.net/40phzeqd/

**Comment by akre54** [comment]
Please use StackOverflow for debugging. Github issues are for maintaining the framework only.
