### ISSUE TITLE
Potential regression when setting `id` directly from 1.2.1 to 1.2.2

### ISSUE THREAD

**Issue by swanson** [jashkenas/backbone#3778]
As part of upgrading from 1.2.1 to 1.2.2, we noticed an issue in our app where we were directly setting `id` on a model. I don't think this is the best way to set the id, but it is what it is.

```js
model.id = SOME_ID
```

After setting additional properties via `set` later in our code, `model.id` started to return `undefined`.

Below is a minimal example. The expected behavior is that both `console.log`'s will output "123". In 1.2.2 calling `set` is wiping out `model.id` (appears to be from this commit: https://github.com/jashkenas/backbone/commit/be7fc959641a3ccaa362110023ea7d697bc3f93b)

You can run these fiddles and see the output in the console.

1.2.1: https://jsfiddle.net/jktms1xx/2/
```sh
> 123
> 123
```

1.2.2: https://jsfiddle.net/g1am1otw/1/
```sh
> 123
> undefined
```

---

We've resolved this issue by changing our code to call `model.set('id', SOME_ID)` - but we were wondering if setting `model.id` directly should continue to work. Thanks!

cc @jbrad

**Comment by akre54** [comment]
Setting `id` directly was never really supported (in my experience it's always been a read-only property to keep you from needing to do `model.get('_id')` every single time). That said, we could do something like the following to at least avoid the `set` case messing up:

```diff
diff --git a/backbone.js b/backbone.js
index 2aac5cb..594f14e 100644
--- a/backbone.js
+++ b/backbone.js
@@ -506,7 +506,8 @@
       }
 
       // Update the `id`.
-      this.id = this.get(this.idAttribute);
+      var id = this.get(this.idAttribute);
+      if (id != null) this.id = id;
 
       // Trigger all relevant attribute changes.
       if (!silent) {
```

**Comment by swanson** [comment]
Thanks for the quick response; I agree that setting `id` directly is probably not the way to go, but sometimes you've got to work with what you've got :)

If setting `id` directly is not supported, I'm fine with having the issue closed as well. At the very least, we've got this documented here if others run into while upgrading.

**Comment by akre54** [comment]
> but sometimes you've got to work with what you've got :)

Why do you need to mutate `id` on the client-side? Isn't this typically something set and sent by the server?

**Comment by swanson** [comment]
> Why do you need to mutate id on the client-side? Isn't this typically something set and sent by the server?

Reasons are specific to some other code within the app. I agree that it is a smell.

**Comment by patrixd** [comment]
I had the same problem. 
I added idAttribute in all my models and removed the direct assignments to id and everything work perfect. 
If I had any custom value to id, not setting in other property I added a new one and assigned the new property name to idAttribute.
