### ISSUE TITLE
1.2.2 Router reloading page hash changes in Chrome

### ISSUE THREAD

**Issue by sterpe** [jashkenas/backbone#3781]
So I've created the most simple Router application here with `backbone@1.2.2`:

```
var Backbone = require('backbone');
var Router = Backbone.Router.extend({
	routes: {
		":codename(/*path)": "onRoute"
	},
	onRoute: function () {
		var p = document.createElement('p');
		var args = Array.prototype.slice.call(arguments);
		p.innerText = args.join(", ");
		document.body.appendChild(p);
	}
});

new Router();

Backbone.history.start();
```
Using `browserify` and `beefy` to run this on `localhost:1337`.

To duplicate in `Chrome Version 44.0.2403.157 (64-bit) (OSX Yosemite)`

1.  Open the developer tools

2. In address bar type some random fragment: `#foo` -- See `foo, ,`
3. In address bar type some next random fragment: `#bar` -- See now `foo, , \n bar, ,` 
4. Ok that seems normal.

5.  Close the developer tools
6.  Repeat steps 2 and 3 a couple of times:  Be sure to occasionally type fragments that you've used before.  The router is continually reloading the page when the fragment changes.

Expected:
Should not reload the page on fragment changes.

It seems like for some reason Backbone Router behaves correctly when the developer tools are open, and poorly when they are closed.  Safari also seems to suffer from this to some lesser degree.

Maybe related to #3773 ?

_Note that this seems apart from the known Webkit issue when loading the same url + fragment twice._

https://bugs.webkit.org/show_bug.cgi?id=24578

**Comment by sterpe** [comment]
This may be an issue in Chrome/Webkit.  Testing with `flatiron/director` reveals the same behavior.

**Comment by sterpe** [comment]
Ok.  FWIW - this issue appears to be caused by a combination of `beefy index.js 1337 --live -- -d` + Chrome/Webkit + a catch-all type of Route like `"*notFound"` or `":codename(/*path)"` with Backbone.Router (or in `director` something like `"/(.*)"`).

Running `python -m SimpleHTTPServer` results in the expected behavior of the router.

Removing the `--live` flag from `beefy` also results in correct behavior.

Interestingly that turning  on the Chrome Developer Tools somehow "fixes" this problem when `beefy` is in "live" mode.

**Comment by manpreetssethi** [comment]
Referring to the changes in 1.2.0: 
"As a neat side effect, Backbone.History no longer uses jQuery's event methods for pushState and hashChange listeners. We're native all the way."

Changing this;
```
$(window).on('hashchange', hashChangeCallback);
```

to this, worked for me;
```
window.addEventListener('hashchange', hashChangeCallback);
```

**Comment by sterpe** [comment]
I eventually found this to be rooted in a Chrome instability, shutting down Chrome and restarting it fixed the behavior
