### ISSUE TITLE
Model.prototype.get() and .has() counts own properties

### ISSUE THREAD

**Issue by winhillsen** [jashkenas/backbone#3782]
Hi all! I stumbled on the following behaviour:

```javascript
var model = new Backbone.Model();
console.log( model.get( 'constructor' ) );
```
returns the constructor function of the `model.attributes` object.

I was rather expecting the `get()` method to filter own properties and return `undefined`. The same should also hold true with `has()` (in line with Underscore's `_.has()`, which does filter own properties). Without this, a model's `attributes` object would not be a [true hash](http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/).

Thoughts?

**Comment by Florian-R** [comment]
See #1495

**Comment by akre54** [comment]
Something to address for v2? [Object.create is IE9+](http://kangax.github.io/compat-table/es5/#Object.create), might be worth looking into if we drop IE8.

**Comment by jridgewell** [comment]
It can be polyfilled with black magic in IE7 and 8. I think we should do it.

**Comment by akre54** [comment]
There's [prior](https://github.com/paulmillr/exoskeleton/commit/550265b9f41e844506467681bcf7ab04d7a2d2e5) [art](https://github.com/paulmillr/exoskeleton/commit/ffe51bba68a01b11cf3642ac54787b379801190b) in Exoskeleton for `model.attributes` and `collection._byId` from `Object.create(null)`. (see #3411, #1783, etc.)

In general, I'd say that #1783 is right in that there generally isn't a real-world use case for naming your keys "constructor" or "hasOwnProperty" (keep in mind [an object is not a hash](http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/)) but if this change is easy and comes with minimal side effects, let's bite the bullet.

**Comment by jashkenas** [comment]
There may be good reasons to eventually drop IE7 and IE8, but using properties like `constructor` isn't one of them. Let's leave it for now.

**Comment by komaval** [comment]
> There may be good reasons to eventually drop IE7 and IE8, but using properties like constructor isn't one of them. Let's leave it for now.

this trouble is actual on my current project
you made me sad 

in my case treatment is to overwrite `get` for collection 

```
get: function(obj) {
	if (obj == null) return void 0;
	var id = this.modelId(this._isModel(obj) ? obj.attributes : obj);
	return this._byId[obj] || this._byId.hasOwnProperty(id) && this._byId[id] || this._byId[obj.cid];
},
```
