### ISSUE TITLE
On saving a model which is a part of a collection, a "sync" event is triggered on the collection

### ISSUE THREAD

**Issue by manpreetssethi** [jashkenas/backbone#3786]
I'm not able to find the same anywhere in the documentation, and am not sure why that happens.

Any help would be appreciated, thanks in advance.

**Comment by akre54** [comment]
[From the docs](http://backbonejs.org/#Collection): 

> Any event that is triggered on a model in a collection will also be triggered on the collection directly, for convenience. This allows you to listen for changes to specific attributes in any model in a collection, for example: documents.on("change:selected", ...)

**Comment by manpreetssethi** [comment]
Thanks @akre54, should've gone through the documentation thoroughly, my bad.
