### ISSUE TITLE
Undocumented Collection.at behavior

### ISSUE THREAD

**Issue by FishbaitHarry** [jashkenas/backbone#3789]
The functionality introduced by https://github.com/jashkenas/backbone/commit/325a50f2bb556d185d77413cf8c6ede7555221d9 is not documented and may lead to surprising results.

For the record, it is mentioned in the changelog, but it didn't stop me from breaking my app's tests in some obscure cases.

I would be happy to add a sentence about it to the method's doc if you agree.

**Comment by jridgewell** [comment]
:+1:

**Comment by platinumazure** [comment]
Any reason this needs to stay open? Looks like the linked PR is closed.
