### ISSUE TITLE
'update' event fails to fire at times

### ISSUE THREAD

**Issue by Heedster** [jashkenas/backbone#3790]
I use Backbone - React - Flux to build an application. (uses ES6 - babel). 
So I listen to add, remove, update and change events of a backbone collection from a react component.  The collection polls the server at times to fetch some models and adds it to the collection. It works fine. Just that a lot of add and remove gets fired in some cases where all of my models are replaced. 
To avoid this, I removed add and remove, so that it will fire only one update to the component. Sometimes it work fine, sometimes it wont. I observed this in situation when all models returned are new and the whole collection is now changed. There is no problem with the network response, I verified it. It just never fires the update event. To confirm, I also did a "this.bind('update',function().....} and tried logging.. but same problem there. It just does not fire.

When i added add and remove statements back into the on() statement, it works fine. But as I said, I am not interested in each addition and this causes my react components to rerender too many times. 

Can you look into this issue? Happy to give any more details.

**Comment by jridgewell** [comment]
I'd be happy to look into if if you can provide a test case.

**Comment by Heedster** [comment]
I am not sure how to ..

**Comment by jridgewell** [comment]
Whatever you're calling `#set` with that causes an `add`/`remove` event but not an `update`. Also the state of the collection beforehand.

**Comment by Heedster** [comment]
I have overrided parse() and this is what it looks like. The console.log prints "response received" every time and fires adds and removes, but not update. 
```
 parse(response){
          if(response["pageToken"]){
            this.pageTokens[this.currentPage+1]=response["pageToken"];
          }
          else{
            this.pageTokens[this.currentPage+1]=null
          }
          console.log("response received")
          return response["users"];
    }
```

**Comment by Heedster** [comment]
Adding to this. I found out that another one of my collection is not firing 'change' event too. I bypassed it by binding to sync. But seems like a hack.

**Comment by jridgewell** [comment]
Can you write a jsfiddle to demonstrate?

**Comment by anoopmd** [comment]
@Heedster , I remember encountering a similar issue in Ver 1.1.0. I upgraded to ver 1.2.0 and it solved the problem.

**Comment by seancorgan** [comment]
I had this same weird issue.  Update would not fire.  I was using V1.1.0 , upgraded to 1.2.0 Problem fixed.

**Comment by jridgewell** [comment]
`updated` was added in [v1.2.0](https://cdn.rawgit.com/jashkenas/backbone/1.2.0/index.html#changelog). (Notice, that changelog incorrectly spelled it `updated`, that's been corrected)
