### ISSUE TITLE
Make some of the model's attribute do not to sync to server

### ISSUE THREAD

**Issue by anianj** [jashkenas/backbone#3791]
Hi,

I have saw in some cases, we have to store some states of the view, like
in a dropdown of countries, the data of country list is get from the server:
```javascript 
[
    {
      "name":'USA',"id":1
    },{
      "name":"England","id":2
    }
...
]
```
But i want to add a "selected" attribute to country model so that i just need to change this "selected" value, my view get to rendered.

But this "selected" attribute is meanless to the server, i don't want to sent it to the server.

So i am about to have a "local" attribute on Backbone.Model, which you can use set,get to set to modify some attributes of this "local" attribute, it also fires events,but it will not to be sync to the server

Is that a right way?

**Comment by akre54** [comment]
Hi! Please use the mailing list or StackOverflow for questions like this. Github issues are for maintaining the framework only.
