### ISSUE TITLE
Incorrect behavior of collection 'at' method

### ISSUE THREAD

**Issue by ybalytskyi** [jashkenas/backbone#3793]
// Get the model at the given index.
    at: function(index) {
      if (index < 0) index += this.length;
      return this.models[index];
    }
If I'm retrieving model by unexisting index I expect undefined value.
This check  "if (index < 0) index += this.length;" does nothing if index is less than -this.length(for example index is -5 and collection length is 3).

Please remove this line "if (index < 0) index += this.length;" as a cause of bug.

**Comment by danielstreit** [comment]
A negative number indicates select from the end of the collection. So, `-1` would indicate the last item in the collection and so on.

I believe this works as expected. If you need a negative number to indicate not found, I'd suggest a check before calling `at`.

**Comment by jridgewell** [comment]
> I believe this works as expected. If you need a negative number to indicate not found, I'd suggest a check before calling at.

Agreed.
