### ISSUE TITLE
Chainable Routes

### ISSUE THREAD

**Issue by AndrewHenderson** [jashkenas/backbone#3796]
An alternative or interim step to [overhauling the Router](https://github.com/jashkenas/backbone/issues/3653), could be adding the ability to [chain routes](https://github.com/AndrewHenderson/backbone.chain-router).

I have built several applications, all of which required executing routes with varying combinations of the same rendering, so [I wrote a lightweight plugin](https://github.com/AndrewHenderson/backbone.chain-router) to handle it more simply.

I'm wondering if this is something that the community is open to including in the library rather than as a plugin before creating a pull request.

Below are some examples of the implementation. The full documentation can be [found here](https://github.com/AndrewHenderson/backbone.chain-router/blob/master/README.md).

#### Example Usage

Using dot syntax within callback names, we'd be able to chain our callbacks, executing one after the other.
```js
Backbone.Router.extend({
  routes: {
    'posts/new': 'posts.new'
  },
  posts: function () {
    console.log('posts'); // called first
  },
  new: function () {
    console.log('new'); // called second
  }
});
```
Chained routes with parameters would be passed their parameters respectively.
```js
routes: {
  'post/:post_id/comment/:comment_id': 'post.comment'
},
post: function (post_id) {
  console.log(arguments); // [post_id, null]
},
comment: function (comment_id) {
  console.log(arguments); // [comment_id, null]
}
```
If we want to include an additional route in the middle of the chain which is not intended to be passed parameters, we bracket that callback.
```js
routes: {
  'post/:post_id/comments/:comment_id': 'post.[comments].comment'
},
post: function (post_id) {
  console.log(arguments); // [post_id, null]
},
comments: function () {
  console.log(arguments); // [null] was not passed comment_id
},
comment: function (comment_id) {
  console.log(arguments); // [comment_id, null]
}
```

**Comment by akre54** [comment]
Nice suggestion, but there are plenty of times where you *wouldn't* want all of the previous routes to run (a view / edit comment page, for example, doesn't need the post's data).

As a counterpoint, couldn't you have a common `_renderPost` method, called by each of your routes that need it?

**Comment by AndrewHenderson** [comment]
> As a counterpoint, couldn't you have a common _renderPost method, called by each of your routes that need it?

Yes, this is typically how that is solved.

> ... there are plenty of times where you wouldn't want all of the previous routes to run

Agreed. For those routes you simply would not pass a "chained" callback string.

**Comment by akre54** [comment]
> For those routes you simply would not pass a "chained" callback string.

Ah. You should note this in the readme then.

This is a cool concept, but in my opinion it's just too "magical" for the problem it is ultimately trying to solve, which is data and view dependencies. Some of the MetaFrameworks (like Marionette and Chaplin) use "regions" or "layouts" to help with this, but I'm not sure this is the tack we should take. Doing it yourself gives you more flexibility and control without having to learn an esoteric router syntax.

**Comment by jridgewell** [comment]
As an aside, you should be able to implement this with the `route` event on the router. Something like:

```js
ChainedRouter = Backbone.Router.extend({
    constructor() {
        Backbone.Router.apply(this, arguments);
        this.on('route', this.chainedRoutes, this);
    },

    chainedRoutes(event, args) {
      var chained = event.split('.');
      _.each(chained, (method, index) => {
        this[method](args[index]);
      });
    }
});
