### ISSUE TITLE
SyntaxError: Unexpected token P at Object.parse (native) at K.parseJSON

### ISSUE THREAD

**Issue by vinimxit** [jashkenas/backbone#3798]
Backbone tries to call Object.parse by default?

Object {validate: false, parse: false, createUrl: "https://something/v1/api/sku/download", url: "https://something/v1/api/sku/download", contentType: "application/json"}
beforeSend: (t)
contentType: "application/json"
createUrl: "https://something/v1/api/sku/download"
emulateHTTP: false
emulateJSON: false
error: (t,e,n)
errorThrown: SyntaxError: Unexpected token P at Object.parse (native) at K.parseJSON (http://localhost:8080/dist/js/bundle.js:10:9167) at j (http://localhost:8080/dist/js/bundle.js:8:10898) at n (http://localhost:8080/dist/js/bundle.js:10:10566) at XMLHttpRequest.K.ajaxTransport.Q.cors.t.crossDomain.send.e (http://localhost:8080/dist/js/bundle.js:10:16627)
message: "Unexpected token P"
stack: (...)
get stack: ()
set stack: ()
__proto__: Error
parse: false
success: (t)
textStatus: "parsererror"
url: "https://something/v1/api/sku/download"
validate: false
xhr: Object
__proto__: Object
temp1
Object {validate: false, parse: false, createUrl: "https://something:4242/v1/api/sku/download", url: "https://something.com:4242/v1/api/sku/download", contentType: "application/json"…}
beforeSend: (t)
contentType: "application/json"
createUrl: "https://something:4242/v1/api/sku/download"
emulateHTTP: false
emulateJSON: false
error: (t,e,n)
errorThrown: SyntaxError: Unexpected token P at Object.parse (native) at K.parseJSON (http://localhost:8080/dist/js/bundle.js:10:9167) at j (http://localhost:8080/dist/js/bundle.js:8:10898) at n (http://localhost:8080/dist/js/bundle.js:10:10566) at XMLHttpRequest.K.ajaxTransport.Q.cors.t.crossDomain.send.e (http://localhost:8080/dist/js/bundle.js:10:16627)
message: "Unexpected token P"
stack: (...)
get stack: ()
set stack: ()
__proto__: Error
parse: false
success: (t)
textStatus: "parsererror"
url: "https://something:4242/v1/api/sku/download"
validate: false
xhr: Object
__proto__: Object

**Comment by jridgewell** [comment]
Closed by http://stackoverflow.com/a/32649987/323767.

PS. You should mark his answer as correct.
