### ISSUE TITLE
Constructor delegateEvents regression bug

### ISSUE THREAD

**Issue by berryd** [jashkenas/backbone#3802]
Old Backbone.View
  var View = Backbone.View = function(options) {
    this.cid = _.uniqueId('view');
    options || (options = {});
    _.extend(this, _.pick(options, viewOptions));
    this._ensureElement();
    this.initialize.apply(this, arguments);
    this.delegateEvents();
  };

new 
  var View = Backbone.View = function(options) {
    this.cid = _.uniqueId('view');
    _.extend(this, _.pick(options, viewOptions));
    this._ensureElement();
    this.initialize.apply(this, arguments);
  };

Why was delegateEvents removed?  Many patterns rely on collections or models being set in initialize.

**Comment by jridgewell** [comment]
See https://github.com/jashkenas/backbone/pull/3060.
