### ISSUE TITLE
Multi inheritance

### ISSUE THREAD

**Issue by vin100bk** [jashkenas/backbone#3805]
Hi,
For a project I needed a multi inheritance capability for Backbone so I implemented it.
https://github.com/vin100bk/backbone/tree/modules

Feel free to give my any feedback (positive or negative) and if this feature could be useful for you.

**Comment by jashkenas** [comment]
There is no such thing as multiple inheritance in JavaScript.

You can mix in properties instead.

**Comment by vin100bk** [comment]
Hum yep, it is precisely the purpose of that.. Avoid mixing manually properties.

**Comment by jashkenas** [comment]
You are doing precisely that: mixing in properties to the prototype:

    // Add multi inheritance properties from modules to the constructor function, if supplied
    if(modules) {
      modules.unshift(protoProps);
      _.extend.apply(this, modules);
    }

That's not multiple inheritance.

**Comment by vin100bk** [comment]
Yes it simulates a multiple inheritance but the final result is the same. You can use as many module as you want.

```js
test("extend with multi inheritance", 2, function() {
    var module1 = {
      function1: function() {
        return 'return1';
      }
    };

    var module2 = {
      function2: function() {
        return 'return2';
      }
    };

    var Model = Backbone.Model.extend({}, {}, [module1, module2]);
    var model = new Model();
    equal(model.function1(), 'return1');
    equal(model.function2(), 'return2');
  });
```
