### ISSUE TITLE
npm tarball for 1.2.3 is missing LICENSE

### ISSUE THREAD

**Issue by danc86** [jashkenas/backbone#3807]
The LICENSE file was present up until 1.2.2 but in the [1.2.3 tarball](http://registry.npmjs.org/backbone/-/backbone-1.2.3.tgz) it is missing. I guess due to #3765. Can you please add it back?

**Comment by akre54** [comment]
The license (MIT) is in package.json. Is this sufficient for your needs?

**Comment by danc86** [comment]
package.json just has ``"license" : "MIT"`` not the whole license text. That's not sufficient according to the license itself, which requires a copy of the license text to be included.

(The reason I care is because I maintain the Fedora package of backbone and so I am required to ship the license text with the package.)

**Comment by akre54** [comment]
I don't understand. You're using the npm package but not npm to download it? Can you just use git or the [github releases](https://github.com/jashkenas/backbone/releases) for this? Why is the fedora package manager tied to npm?

**Comment by danc86** [comment]
How the tarball is downloaded makes no difference, the problem is that it doesn't contain the license text.

To answer your question about the Fedora package... It uses npm so that other packages with an npm dependency on backbone can be satisfied. The actual build output is two binary packages: ``js-backbone`` which contains just the actual JS for people who don't care about npm, and ``nodejs-backbone`` which requires ``js-backbone`` but also provides npm metadata so that npm requirements can be satisfied. This is a common way of packaging JS libraries in Fedora nowadays.

The .spec file is here if you are interested:

http://pkgs.fedoraproject.org/cgit/nodejs-backbone.git/tree/nodejs-backbone.spec

I can change the Fedora package to use the Github tarball if you prefer. But we are getting a bit off-topic for this issue...

Putting aside the Fedora packaging stuff, npm itself will pull down a tarball which does not include the license text. Like this:

```
$ mkdir asdf
$ cd asdf
$ npm install backbone
[...]
$ ls -l node_modules/backbone/
total 140
-rw-r--r--. 1 dcallagh dcallagh 71415 Sep  4 01:56 backbone.js
-rw-r--r--. 1 dcallagh dcallagh 23097 Sep  4 01:56 backbone-min.js
-rw-r--r--. 1 dcallagh dcallagh 33550 Sep  4 01:56 backbone-min.map
drwxr-xr-x. 3 dcallagh dcallagh    23 Oct  2 08:26 node_modules
-rw-r--r--. 1 dcallagh dcallagh  3565 Oct  2 08:26 package.json
-rw-r--r--. 1 dcallagh dcallagh  1865 May 14 08:07 README.md
$
```

**Comment by akre54** [comment]
Hmm so it seems #3765 was incorrect. Reverting it.

Not sure of the logic keeping a js library in an os package manager, but what do I know.
