### ISSUE TITLE
yii select2 extension, how to display the selected value in update view?

### ISSUE THREAD

**Issue by usman10scorpio** [jashkenas/backbone#3812]
This is not an issue, just a query which i have been trying to solve. 
i am stuck at a point, please solve this mystery, I am using select2 extension fortunately it is a searchable drop down, like when i start typing, it loads the stored data from my business table. Just a query how can i show my selected business in update view, I am currently in address view, where there are four fields, sector, city, business, street. I am getting business name using select2 extension, it is working but when i update an address, every stored field's data comes up, except the business. HERE is my code of address/views/_form
<?php
/* @var $this AddressController */
/* @var $model Address */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.BsActiveForm', array(
    'id'=>'address-form',
    // Please note: When you enable ajax validation, make sure the corresponding
    // controller action is handling ajax validation correctly.
    // There is a call to performAjaxValidation() commented in generated controller code.
    // See class documentation of CActiveForm for details on this.
    'enableAjaxValidation'=>false,
)); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">

        <?php echo $form->textFieldControlGroup($model,'street_number',array('size'=>45,'maxlength'=>45)); ?>
        <?php echo $form->error($model,'street_number'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'business_id'); ?>
         <?php

  $this->widget('ext.select2.ESelect2',array(
  'name'=>'Address[business_id]',
  'data'=>CHtml::listData(Business::model()->findAll(), 'id', 'business_name'), //the whole available list
  'htmlOptions'=>array(
       'placeholder'=>' search business name?',
    //'options'=>$options, //the selected values
    //'multiple'=>'multiple',
    'style'=>'width:530px',
  ),
  ));
    ?>
    </div>
       </br>

    <div class="row">

        <?php echo $form->textFieldControlGroup($model,'sector',array('size'=>45,'maxlength'=>45)); ?>
        <?php echo $form->error($model,'sector'); ?>
    </div>

    <div class="row">

        <?php echo $form->textFieldControlGroup($model,'city',array('size'=>45,'maxlength'=>45)); ?>
        <?php echo $form->error($model,'city'); ?>
    </div>

    <div class="row buttons">
        <?php echo BsHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
    </div>

<?php $this->endWidget(); ?>

</div>

**Comment by ErSKS** [comment]
This question is right but closed without giving the right answer.

**Comment by paulfalgout** [comment]
@ErSKS This was closed and marked as inappropriate for the following reasons:

1. Readme states:
> For questions on working with Backbone or general discussions: https://groups.google.com/forum/#!forum/backbonejs, http://stackoverflow.com/questions/tagged/backbone.js, or https://gitter.im/jashkenas/backbone

2. Contributing doc states:
> Do not use tickets to ask for help with (debugging) your application. Ask on the mailing list, in the IRC channel (#documentcloud on Freenode), or if you understand your specific problem, on StackOverflow.
