### ISSUE TITLE
Unit tests are using QUnit 1.x syntax

### ISSUE THREAD

**Issue by platinumazure** [jashkenas/backbone#3813]
The unit tests are using QUnit 1.x syntax (i.e., `module` global instead of `QUnit.module`, not using the `assert` object, etc.). And why should they do otherwise when QUnit 2.0 isn't out yet? However, as you probably know, most or all of the QUnit 2.0 syntax is in fact available now (as of QUnit 1.16, and we're consuming 1.18+). So it's possible to migrate everything over now, in order to make an eventual consumption of QUnit 2.0 easier.

Unless strong objections are raised in this discussion, I am happy to migrate the tests. I have a tool [platinumazure/qunit2-migrator][1] which makes the job a lot easier. I can do so all at once or in batches-- it doesn't matter.

  [1]: https://github.com/platinumazure/qunit2-migrator

**Comment by jridgewell** [comment]
:+1:

**Comment by akre54** [comment]
Awesome. Looking forward to that pull.

**Comment by platinumazure** [comment]
Any strong preferences on whether to do it all at once or in batches? I think I would prefer batches to avoid possible merge hell scenarios but I can do it all at once if that's better for you guys.
