### ISSUE TITLE
Collection model attribute

### ISSUE THREAD

**Issue by pickled-plugins** [jashkenas/backbone#3814]
The ``model`` attribute of a collection expects a constructor, as opposed to the ``models`` attribute, which is an array of model instances. I personally find this syntax confusing, and would prefer one where the constructor attribute is uppercased (or if both formats are supported). I take it there may be a very good reason for this syntax, which I would find helpful to know. Any thoughts?

**Comment by jridgewell** [comment]
See https://github.com/jashkenas/backbone/issues/1765. I personally hate the lowercased name... :sigh:
