### ISSUE TITLE
model id change and collection.get() event order

### ISSUE THREAD

**Issue by gocoffeecup** [jashkenas/backbone#3826]
"change:_id" is triggered before _onModelEvent has swapped the id from the collection so any call to collection.get(<newid>) fails.

    var m = new bb.Model()
    var c = new bb.Collection({model : m })

    c.add(m)
    //this fails
    c.on('change:id',function(x){
      console.log(c.get(x.attributes.id))
    })
    //this works
    c.on('change',function(x){
      console.log(c.get(x.attributes.id))
    })
    m.set({id:23452345})

**Comment by anoopmd** [comment]
Going through Backbones Source code of the set method.

```javascript
if (!silent) {
  if (changes.length) this._pending = options;
  for (var i = 0; i < changes.length; i++) {
    this.trigger('change:' + changes[i], this, current[changes[i]], options);
  }
}
if (changing) return this;
if (!silent) {
  while (this._pending) {
    options = this._pending;
    this._pending = false;
    this.trigger('change', this, options);
  }
}
```
1. The changes are triggered for all the changed attributes one by one
2. And later the change event is fired. 

I do not see any assignments happening in between these two points.
Don't know how the id is getting updated between these two points.

By the way if you are looking to get the updated model, this works
```javascript
c.on('change:id',function(model, value, options){
  console.log(model)
})
```

**Comment by jridgewell** [comment]
`#_onModelEvent` is [only listening](https://github.com/jashkenas/backbone/blob/master/backbone.js#L1153-L1160) to the `change` event to change the `id` (which happens after the `change:attr` event). If you need the model, follow @anoopmd's suggestion:

```js
c.on('change:id',function(model, newId, options) {
  // You're already given the model
})
```
