### ISSUE TITLE
dropping IE8 support

### ISSUE THREAD

**Issue by jdalton** [jashkenas/backbone#3828]
On Jan 12, 2016 MS is [essentially dropping support for IE8](https://support.microsoft.com/en-us/gp/microsoft-internet-explorer). With that in mind jQuery and Lodash are dropping IE8 support in their 3.0 and 4.0 releases. So let's discuss dropping it in the next major bump of Backbone.

**Comment by braddunbar** [comment]
Yep, this seems like a good idea to me. As dependencies drop support Backbone will implicitly lose support anyway. Syncing those up seems like a good plan.

**Comment by Archie22is** [comment]
+1

**Comment by akre54** [comment]
I'm down with this but what specifically do we need to fix? We can finally use `Object.create`, but still can't use `history.pushState`. We could get rid of the iframe, but to what end? What are we missing out on by supporting older browsers?

**Comment by jdalton** [comment]
Besides being able to adopt various ES5 methods I scanned Backbone I see fixes for [IE < 9](https://github.com/jashkenas/backbone/blob/fee53ab46463b2e1e938c481d26c53be1ac5b72c/backbone.js#L1681), [old IE](https://github.com/jashkenas/backbone/blob/fee53ab46463b2e1e938c481d26c53be1ac5b72c/backbone.js#L1544-L1546), [IE6](https://github.com/jashkenas/backbone/blob/fee53ab46463b2e1e938c481d26c53be1ac5b72c/backbone.js#L1596-L1597), [IE7 and earlier](https://github.com/jashkenas/backbone/blob/fee53ab46463b2e1e938c481d26c53be1ac5b72c/backbone.js#L1806-L1808) that can be dropped.

**Comment by akre54** [comment]
Again, those are all iframe issues. How do they affect us from moving forward on things?

**Comment by jdalton** [comment]
Dropping support means less code, less workarounds, less testing overhead, less headaches, and allows expanding features to the new lowest common denominator (instead of boxing features to what's doable in IE6 or IE8).

**Comment by jdalton** [comment]
> We got rid of those from Underscore, remember? It's mostly just Object.create as I can see.

`Object.create(null)` is super handy :D

**Comment by akre54** [comment]
> instead of boxing features to what's doable in IE6 or IE8.

Can you give me an example of where that's happening currently?

It seems we're mostly talking about minor code changes, not anything fundamentally different with Backbone. The iframe section could be removed, but it's not a ton of code.

**Comment by jdalton** [comment]
> Can you give me an example of where that's happening currently?

I'm not really involved in the day-to-day of Backbone so not in the position to comment on it. Maybe @jridgewell or @braddunbar could comment on that more. I know developing Lodash that scoping features to the lowest supported environment comes up plenty for things like Map/Set/WeakMap, null prototypes, etc.

> It seems we're mostly talking about minor code changes, not anything fundamentally different with Backbone. The iframe section could be removed, but it's not a ton of code.

The reduction is source is nice but I think the support angle may be a bigger win. I know debugging older IE issues isn't the easiest and many devs lack the vms for it. If you're volunteering to be the old IE support contact that's cool too though.

**Comment by jridgewell** [comment]
> The iframe section could be removed, but it's not a ton of code.

Don't discount all the History fixes we've done (more than just the iFrame). I've tried refactoring router code a few times, and I'm always frustrated with all of the legacy code there.

> I'm not really involved in the day-to-day of Backbone, maybe @jridgewell or @braddunbar have more insights into that.

Thankfully, jQuery took the brunt of the IE code fixes. History is the only code I know of where we've had to work around it.

**Comment by jdalton** [comment]
> Thankfully, jQuery took the brunt of the IE code fixes. History is the only code I know of where we've had to work around it.

As jQuery moves away from IE8 support would Backbone then take on the support mantle for those fixes?

**Comment by jridgewell** [comment]
> As jQuery moves away from IE8 support will Backbone take on the support burden for those fixes?

Nah, that's all end-dev code in the Views and Ajax requests. It's up to them to backfill anything they're missing by updating to the latest jQuery.

**Comment by jdalton** [comment]
So the statement by Backbone is it won't drop IE8 support, even though jQuery will and Microsoft is?

**Comment by jridgewell** [comment]
If we can get rid of the IE workarounds in History, I'm :+1:.

**Comment by braddunbar** [comment]
:+1: I'm not certain what extra features we'll gain by dropping IE8 support but I am certain we won't gain anything by keeping it past it's end of support.

**Comment by jridgewell** [comment]
Re: https://github.com/jashkenas/backbone/issues/3778

We could define a getter/setter to stop this:

```js
Model.prototype = {
  // ...
  get id() {
    return this.get(this.idAttribute);
  }
  set id(id) {
    this.set(this.idAttribute, id);
  }
}
```

**Comment by paulfalgout** [comment]
So is there news about jQuery somewhere?  I know 2.x doesn't support IE8.. neither does 3.x, but are they stopping development of their 3.x-compat branch?

**Comment by jdalton** [comment]
@paulfalgout Yes the plan is to not have a 3.x-compat branch. There is no official post yet.

**Comment by Inateno** [comment]
Here we were using a lot of IE8 fallbacks stuff, now (at Airbus company) they are moving to IE11 before 2016.
If companies like this make the jump I think IE8 can die (finally!)

**Comment by luisfmsouza** [comment]
:+1:

**Comment by akre54** [comment]
#4008
