### ISSUE TITLE
History._updateHash with correctly encoded fragment breaks URI in Safari Browser

### ISSUE THREAD

**Issue by jirgn** [jashkenas/backbone#3830]
## FYI
When coding my first Backbone / Marionette Project I run into a strange URI encoding Problem. This means I am far from being a Backbone Professional and maybe I'm getting something wrong.

## Problem Description
I'm having the following route in my Marionette Router, that handles searches with GET style query parameters.

    var Router = Marionette.AppRouter.extend({
        appRoutes: {
            'search(?*query)' : 'search'
        }
    });

When trying to persist my Application State, I need the URL Fragment to be able to handle special Characters like ö,ä,ü correctly. Therefore I encode the Query (e.g. ?loc-city[]=Berlin&loc-cty[]=München) and call

    router.navigate('search?loc-city%5B%5D=M%C3%BCnchen&loc-city%5B%5D=Berlin');
 
This works perfectly in most Browsers. But when testing on Safari, I encountered, that in the navigation routine, the fragment will be decoded and then given to Backbone.History._updateHash, which updates the windows location. At this Point Safari (Desktop and Mobile Version) encodes the given fragment in ISO and the query then will be

    ?loc-city[]=Berlin&loc-city[]=M%FCnchen // notice the %FC which is the url encoded iso char

which cannot be consumed by Javascript/Backbone anymore, and break the Code with an URIError (when calling decodeUriComponent in Backbone.Router._extractParameters).

Because I find not much Information on the Web, I call for your help here, if there's an obvious bug anywhere, or if i got something wrong, please give me a hint. 
I already checked the encoding on all sides, the documents are utf-8, the server delivers the correct encoding as well and the headers also say so.

**Comment by jridgewell** [comment]
@braddunbar, mind taking a look?

**Comment by jridgewell** [comment]
@jirgn: Looked into this today, and I'm not able to replicate. I'll reopen if you can provide a jsfiddle that causes the error.
