### ISSUE TITLE
"all" event documentation: add all arguments

### ISSUE THREAD

**Issue by fjanon** [jashkenas/backbone#3831]
Documentation:
"Catalog of Events"
 "all" — this special event fires for any triggered event, passing the event name as the first argument.

It would be great if something was added to specify that ALL arguments passed in by the trigger function are also passed to the "all" listener function

**Comment by jridgewell** [comment]
Want to work on a PR?

**Comment by cherouvim** [comment]
@fjanon @jridgewell I've improved the documentation. Please let me know if it is not clear.

**Comment by cherouvim** [comment]
The fix was pulled into the master branch so this issue should be closed.
