### ISSUE TITLE
Backbone object is duplicated when imported

### ISSUE THREAD

**Issue by jisaacks** [jashkenas/backbone#3838]
When Backbone is imported into a file a new copy of `Backbone` is created each time.

Consider these 2 files:

__router.js:__

```javascript
import Backbone from 'backbone';

window.BB1 = Backbone;

export default Backbone.Router.extend( /* stuff here */ );
```

__main.js:__

```javascript
import Backbone from 'backbone';
import Router from './router';

window.BB2 = Backbone; // NOT THE SAME OBJECT AS window.BB1

new Router();

// DOES NOT TRIGGER ROUTER
// BECAUSE ROUTER IS USING A
// DIFFERENT COPY OF BACKBONE
Backbone.history.start();
```

When I make the same test with another library like jquery.

```javascript
import $ from 'jquery';
```

It is always the same object (never duplicated.) I have looked at the source of both and I am not seeing what is causing backbone to get duplicated each time. I may try again later though, if I figure out the cause I'll make a PR (assuming that would be wanted -- I don't see why it would be intentionally duplicated.)

**Comment by akre54** [comment]
This looks like a problem with your module loader setup or your package.json dependencies (usually if Marionette is depending on a different version of Backbone than the one in your package.json). 

Try StackOverflow, the mailing list, or the Gitter page to debug this further, Backbone isn't doing anything special here.
