### ISSUE TITLE
v1.2.4

### ISSUE THREAD

**Issue by jridgewell** [jashkenas/backbone#3839]
Features

- [x] Use `_.create` in `.extend` https://github.com/jashkenas/backbone/pull/3553
- [x] Add `#findIndex` and `#findLastIndex` to `Collection` https://github.com/jashkenas/backbone/pull/3811

Bug Fixes

- [x] `#_removeModels` model still in collection regression https://github.com/jashkenas/backbone/pull/3803
- [x] `#set` model id regression https://github.com/jashkenas/backbone/pull/3833
- [x] `#remove` returning `false` regression https://github.com/jashkenas/backbone/pull/3837
- [x] `#reduce` and friends regression https://github.com/jashkenas/backbone/pull/3820

Maybe

- [ ] ~~Deopt Underscore methods containing `arguments` https://github.com/jashkenas/backbone/pull/3840~~
- [ ] Add `#preinitialize` https://github.com/jashkenas/backbone/pull/3827
- [ ] Add `update` event feedback https://github.com/jashkenas/backbone/pull/3711
- [ ] `Object.prototype` conflicts with `_.defaults` https://github.com/jashkenas/backbone/pull/3843

/cc @paulfalgout. :smile:

**Comment by akre54** [comment]
Well Jeremy is [currently taking on the Americas](https://instagram.com/jashkenas) on his bike, so I believe the decision falls to @braddunbar on how and when to cut a release.

#3827, #3820 and  are pretty ugly hacks. Are you sure they're necessary?

**Comment by jridgewell** [comment]
I scaled #3820 back to just deopting `#reduce`, not the `arguments` check that's now in #3840. The arguments check isn't necessary.

- - -

As for #3827, I think it should go out with this release, since I don't imagine any more `v1` releases (I'd rather start merging v2 PRs). Non-breaking, generic, and people can choose to incorporate ES6 without redoing the entire app for v2.

I think it's pretty good solution... Do you have a particular objection to it?

**Comment by akre54** [comment]
> The arguments check isn't necessary.

Right, I was referring to pre-split. I'm still not a fan of #8040. 

> I'd rather start merging v2 PRs

What've you got in mind for v2? A complete overhaul? Something more gradual?

> I think it's pretty good solution... Do you have a particular objection to it?

(Responding there for clarity)

**Comment by jridgewell** [comment]
Adding https://github.com/jashkenas/backbone/issues/3842 as a needed bugfix.

**Comment by paulfalgout** [comment]
updates?

**Comment by jdalton** [comment]
Ping.

**Comment by jdalton** [comment]
For the remaining new features of
> Add #preinitialize #3827
> Add update event feedback #3711

I think they can be cut unless there are PRs ready to merge. It looks like there's a PR for #3711 but it has fallen idle with merge conflicts.

**Comment by jridgewell** [comment]
Agreed, I think this is ready to go.

**Comment by jdalton** [comment]
@braddunbar 
![](http://stream1.gifsoup.com/view4/4359657/voltron-unite-o.gif)

**Comment by megawac** [comment]
Anyone want to draft up a pull request with changelog/documentation updates?

**Comment by jdalton** [comment]
Ping? @braddunbar

**Comment by jdalton** [comment]
If not I'll try to get a PR out tonight.

**Comment by jridgewell** [comment]
It's usually @paulfalgout. :smile:

**Comment by jdalton** [comment]
First one with the PR wins!

**Comment by paulfalgout** [comment]
ha!  Yeah @jdalton take it if you're up for it.  I am a bit snowed under this week.  If you don't get around to it, I'll jump in later.

**Comment by jdalton** [comment]
Draft changelog at #3921.

**Comment by jridgewell** [comment]
Closing with #3921.
