### ISSUE TITLE
Collection.remove behavior in 1.2.X

### ISSUE THREAD

**Issue by gaperton** [jashkenas/backbone#3847]
In previous versions, when model was removed from collection, you first cleaned up the index (`this._byId`), and only then you trigger `remove` event. Which was okay.

In 1.2, you first remove the model, trigger `remove`, and only then clean up the index in `_removeReference`. Thus, in the `remove` event handler model is still present in the index (while absent in collection), resulting in successful `get`. Which leads to weird things, like infinite loop when trying to remove the same model again in 'remove' event handler.

Is there any specific reason you now triggering 'remove' while collection is in inconsistent state, or it's just a bug?

```javascript
    _removeModels: function(models, options) {
      var removed = [];
      for (var i = 0; i < models.length; i++) {
        var model = this.get(models[i]);
        if (!model) continue;

        var index = this.indexOf(model);
        this.models.splice(index, 1);
        this.length--;

        if (!options.silent) {
          options.index = index;
          model.trigger('remove', model, this, options);
        }

        removed.push(model);
        this._removeReference(model, options);
      }
      return removed.length ? removed : false;
    },
```

**Comment by akre54** [comment]
Are you referring to #3835?

**Comment by akre54** [comment]
Are you referring to #3693 and #3803?

**Comment by gaperton** [comment]
Yes, I guess it's the same.

**Comment by akre54** [comment]
Cool. Feel free to weigh in there.

**Comment by gaperton** [comment]
Thanks for invitation. Quite recently I have decided that I don't need dependency from backbone in my framework any more. I would rather have my own implementation of collections. Have fun with tickets.
