### ISSUE TITLE
Backbone.js 1.2.0 when view.remove() 

### ISSUE THREAD

**Issue by zhaozailin** [jashkenas/backbone#3848]
sorry for my poor english, my project use backbone.js 1.2.0;when I execute view.remove(), it throw a exception: obj is null. By debug i find it occur at 186 line in backbone.js . it is in Events.stopListening method : "listening.obj.off(name, callback, this);" the obj is null

**Comment by mr47** [comment]
Please make jsfiddle for your case.

Thanks.

**Comment by paulfalgout** [comment]
It doesn't sound related but there was a bugfix in 1.2.1 addressing `view.remove`  Can you test `1.2.3` to see if you're still getting this issue?

**Comment by paulfalgout** [comment]
Seems like this can be closed.
