### ISSUE TITLE
Backbone 1.2.3 - cannot get route name from execute() method

### ISSUE THREAD

**Issue by mookfist** [jashkenas/backbone#3854]
``` javascript
Backbone.Router.extend({
        /**
         * Routes
         */
        routes: {
            filters: function() {
                console.log(arguments);
            }
        },

        execute: function(callback, args, name) {
            console.log(arguments);
            if (callback) callback.apply(this, args);
        }
});
```

This is my basic router. When navigating to http://url#filters however, the output from the execute() method is this:

``` javascript
[function(), [null], ""]
```

I had thought that the name argument is the route name but as you can see it is an empty string. This does not match the documentation.

edit: title should be CAN'T get the name ;)

**Comment by mookfist** [comment]
From Backbone.Router:

```javascript
      if (_.isFunction(name)) {
        callback = name;
        name = '';
      }
      if (!callback) callback = this[name];
```

so it seems as designed, but I feel the nomenclature is a bit misleading.

My goal here is to have external modules for my different routes. Since I use AMD for module loading, I might do something like this:

```javascript
define(function() {
    var model;
    var view;
    return function()
    {
        // boilerplate MVC whatever
        model = new Model();
        view = new View();
        
        model.on('change', view.render);
    };
});
```

then I can do

```javascript
define(['backbone', 'filterModule'], function(Backbone, FilterModule) {
    return Backbone.Router.extend({
        routes: {
            'filters': FilterModule
        }

        execute: function(callback, args, name) {
            // here I think name is the route name
            Backbone.Router.execute.apply(this, arguments);
            // Some generic functionality I want executed when a route changes
            $('#' + name).show();
        }
    });
});
```

this is not exactly my code but you get the idea of what I'm trying to accomplish here. I am now unclear how I can do what I want to do. the route event also does not carry with it the route name.

**Comment by mookfist** [comment]
hmmmmmmmm

I can do something like this, but architecturally speaking I am not a fan:

```
Backbone.Router.extend({
    initialize: function() {
        this.route('filters','filters',FilterModule);
    },

    execute: function(callback, args, name) {
        Backbone.Router.execute.apply(this, arguments);
        console.log('name'); // works!
    }
});
```

now I don't like it because it seems to blur the line between what a factory typically does and what a constructor typically does. I could move calls to route() outside of the object though but it feels to me like it's a bit much, so I'm open to some ideas here :)

**Comment by jgonggrijp** [comment]
A route has **three** parts: the *pattern*, the *name* and the *handler*.

The *pattern* describes what you see in the browser address bar. It can be just a single word like `filters`, but it can also contain optional parts like `'filters(/advanced)'` or named parameters like `'filters/:key'`. It can even be a regular expression with capturing groups, like `/filters(?:\/(\w+))?/`.

The *name* is a single word, preferably a valid JavaScript identifier, which is primarily used to trigger `route:name` events. It is optional.

The *handler* is a function that should run when the *pattern* (**not** the *name*) is matched. It is optional, too. If you specify a *name* but no *handler*, Backbone will use `router[name]` as the handler if it exists.

When you call `route`, you pass the arguments in that order. When you set a `routes` hash, each key is a *pattern*, **not** a *name*. Each value is **either** a *name* **or** a *handler*. To specify both with a `routes` hash, simply use method names as values.

You can get what you want with code like the following:

```js
define(['backbone', 'filterModule'], function(Backbone, FilterModule) {
    return Backbone.Router.extend({
        routes: {
            'filters': 'filters'
        },
        
        filters: FilterModule,
    });
});
```

I believe that this is sufficiently documented in https://backbonejs.org/#Router-routes and https://backbonejs.org/#Router-route. However, I welcome pull requests to improve on those sections.
