### ISSUE TITLE
upload file using backbone.js

### ISSUE THREAD

**Issue by umeshshivu** [jashkenas/backbone#3863]
i have spring mvc, jpa and backbone.js application. i want to upload file using backbone.js. please tell how i want do.

**Comment by jdalton** [comment]
Try the Backbone [gitter room](https://gitter.im/jashkenas/backbone) for general support.

**Comment by jridgewell** [comment]
Agreed.

> For questions on working with Backbone or general discussions: https://groups.google.com/forum/#!forum/backbonejs, http://stackoverflow.com/questions/tagged/backbone.js, or https://gitter.im/jashkenas/backbone
