### ISSUE TITLE
Collection.remove doesn't remove all given models

### ISSUE THREAD

**Issue by niuage** [jashkenas/backbone#3868]
For some ugly "flexbox" reason, I want to append fake models to the end of my collection, even after fetching more models. So on sync, I remove the previous fake models, then add new ones at the end.

Anyways, here's my issue:

```
onSync: ->
  modelsToRemove = @where({id: 0})
  console.log modelsToRemove, modelsToRemove.length
  // this prints:
  // [child, child, child, child, child]  5
  // which is expected
  @remove(modelsToRemove)

  modelsToRemove2 = @where({id: 0})
  console.log modelsToRemove2, modelsToRemove2.length
  // this should print
  // [] 0
  // right?
  // but it prints:
  // [child]  1
  // and the cid of the child is actually present in the first list...

  @add({}) for [1..@fakeCount]
```

If someone could shed some light on this issue for me, I'd appreciate it!

**Comment by niuage** [comment]
Got it to work properly by using the `cid`s.

```
onSync: ->
      modelsToRemove = _.map @where({id: 0}), (m, i) -> { cid: m.cid }
      @remove(modelsToRemove)
      @add({}) for [1..@fakeCount]
```
The issue seems to be related to the fact that several models are exactly the same except for the cid?

**Comment by jridgewell** [comment]
Using duplicate `id`s will break `#get`. Instead, give them unique ids and identify them with some other property like `{ fake: true }`.

**Comment by niuage** [comment]
Ok, thanks.
