### ISSUE TITLE
Unable to find elements inside a jqplot, canvas graph

### ISSUE THREAD

**Issue by SwatiKhandelwal** [jashkenas/backbone#3869]
I want to write an automation script which loads the webpage (http://www.kathyw.org/jQPlot/LinkTest.html), moves the control to the graph, find the tooltip corresponding to the bar and then clicks on any bar so as to find the title of next page.

Please suggest me any tool which could perform all these tasks. The major problem (as per my findings) is with inspecting the graph elements. Hence, I am unable to use Protractor and Selenium. Plus, using Sikuli is also not an efficient approach as I have large number of graphs and capturing all the expected results would be a tedious task.

Please help me in this regard.

**Comment by adelgado** [comment]
I don't think this is the proper forum for this discussions. Here tends to be for Backbone-development-related topics only. Maybe try asking your question on StackOverflow or elsewhere?
