### ISSUE TITLE
Collection.set behavior changed in 1.2.3

### ISSUE THREAD

**Issue by Flamefork** [jashkenas/backbone#3871]
This change https://github.com/jashkenas/backbone/commit/a082d2fdf9d0509ae7082296e41a0b7efe6878d2#diff-0d56d0d310de7ff18b3cef9c2f8f75dcR797
changes the behavior if collection's `parse` method return falsy value.

Before: empty collection
After: collection with 1 "blank" model

Is it and intended change? My personal consideration is that having 1 empty model in this case is unexpected and unwanted behavior.

**Comment by jashkenas** [comment]
Good question!

**Comment by jridgewell** [comment]
Looks like an oversight on my part. Want to work up the PR?
