### ISSUE TITLE
How to identify and set reverse normals programmatically using Arcobjects?

### ISSUE THREAD

**Issue by chandugithub** [jashkenas/backbone#3872]
I am working a 3D-Buildings project, where deliverables are * .dgn and Esri Multipath, after conversion of  *.dgn to multipath in ArcMap, noticed that few facades normals reversed ,results looks likes portions of the multipatch are missing. So, I have to fix those faces (inverted) programmatically. Please suggest how to fix these issues and also provide which interfaces can help to resolve these issues.

**Comment by chandugithub** [comment]
Hi justin,

Please let me know why request closed without answer?

**Comment by jridgewell** [comment]
This has nothing to do with Backbone.js.
