### ISSUE TITLE
Object.prototype collisions of model values in Collection._byId lookup

### ISSUE THREAD

**Issue by msiconolfi** [jashkenas/backbone#3874]
This issue seems related to [#3842](https://github.com/jashkenas/backbone/issues/3842) but this also happens for values as well as keys.

In FireFox if you create a collection that uses the `idAttribute` field to do a id lookup. The lookup will return the wrong value if the value of a models idAttribute is also a value on Object.prototype. For example, `watch`.

In the referenced issue, people have mentioned not using prototype names as default properties, which I can understand, but attribute values should not have a limitation as we aren't always in control of what those values may be.

Here is an example:
```javascript
var M = Backbone.Model.extend({
    idAttribute: 'type',
    defaults: {
        'type': '',
        'name': ''
    }
});

var model1 = new M({'type': 'watch', name: 'Watch'});
var model2 = new M({'type': 'other', name: 'Other'});

var C = Backbone.Collection.extend({
    model: M
});

var collection = new C();

// add the models
collection.add(model1);
collection.add(model2);

// try and get the model with type: 'watch'
console.log(collection.get('watch'));
console.log(collection.length);

// LOG: function watch()
// LOG: 1
```

The above example only happens in firefox but in Chrome you can see the same behavior if you add the following:

```javascript
var model3 = new M({'type': 'constructor', name: 'Constructor'});

collection.add(model3);
console.log(collection.get('constructor'));

// LOG: function Object() { [native code] }
```

**Comment by msiconolfi** [comment]
I think the problem is in the `Collection.get()` [method](https://github.com/jashkenas/backbone/blob/master/backbone.js#L970), it simply returns the first truthy object that indexes into `_byId` lookup. In Firefox, `Object.prototype` has the `watch` property so this will always return a truthy result, and because `set()` tests for [existence](https://github.com/jashkenas/backbone/blob/master/backbone.js#L854) using `.get()` the `watch` model will never be added.
```javascript
return this._byId[obj] || this._byId[id] || this._byId[obj.cid];
```

It's a little ugly but we could do something like the following:

```javascript
   if (this._byId.hasOwnProperty(obj)){
      return this._byId[obj];
   } else if (this._byId.hasOwnProperty(id)){
      return this._byId[id];
   } else {
     return this._byId[obj.cid];
  }
```

**Comment by msiconolfi** [comment]
I will try to add a PR with this change as well as some tests later today.

**Comment by msiconolfi** [comment]
So I missed it before, but this [Issue](https://github.com/jashkenas/backbone/issues/1783) also seems pretty related also. The only difference is this affects the values of the `idAttribute` field in a model.

**Comment by msiconolfi** [comment]
So it looks like I found the same issue. [Issue 3411](https://github.com/jashkenas/backbone/issues/3411), and it seems the solution/workaround should be **"...you shouldn't be using arbitrary strings as your model ids." **

I'll leave this open, but I imagine it will be marked as duplicate and closed shortly.

**Comment by akre54** [comment]
Yup. The alternative is to run `hasOwnProperty` checks on every lookup, which as the other comment notes, would be expensive in a very hot path.

A potential v2 of Backbone might be built around ES2015 Maps and Sets if this is high enough of a priority. Right now though, stick to your JS best practices and just take care with your keys. You could also do what `d3.map` and a few others do, by prefixing keys with some namespace to emulate a hash.

A plugin might look something like the following:

```js
const prefix = 'bb_'
const BaseModel = Backbone.Model.extend({
  get(attr) {
    return Backbone.Model.prototype.get(prefix + attr)
  },

  set(attr, value, opts) {
    if (typeof attr === 'string') attr = prefix + attr
    return Backbone.Model.prototype.set(attr, value, opts)
  }
})
```
