### ISSUE TITLE
in amd mode, backbone router error

### ISSUE THREAD

**Issue by mishe** [jashkenas/backbone#3876]
Backbone.Router.extend({
    initialize:function(){
            this.bind('route',function(){
                console.log(1)
            });
        },
        routes:{
            "":"home"
        },
        home:function(){
            console.log(2)
        }
});
console log 2 -> 1 
I want log 1 -> 2

**Comment by akre54** [comment]
This is the order of router calls: https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L1473-L1476

It goes 
1. callback
2. router.trigger('route:home', args)
3. router.trigger('route', args)
4. Backbone.history.trigger('route', args)

The callback is always called first. This wouldn't be affected by AMD.

**Comment by mishe** [comment]
good job

**Comment by mishe** [comment]
this bug  find in Nov 02 2013

this changed is fixed bug in AMD, but with CommonJS, this bug is Still exist.
