### ISSUE TITLE
Routers: _bindRoutes() after initialize function call

### ISSUE THREAD

**Issue by PipOlt** [jashkenas/backbone#3877]
Wouldn't it be better to call _bindRoutes() after the initialization.

``` javascript
var Router = Backbone.Router = function(options) {
    options || (options = {});
    if (options.routes) this.routes = options.routes;
    this._bindRoutes();
    this.initialize.apply(this, arguments);
  };
```

I try to use object-methods in the route object. The initialization of the objects is in the initialize method. The route-object looks like this:

``` javascript
route: {
    'path/to/:id': this.object.method
  {
```

This causes an Error because the Object doesn't exist at the time of the _bindRoutes() call. Currently I'm using a small Workaroud. I set route in the initialize method and then call _bindRoutes() manually.

**Comment by paulfalgout** [comment]
initialization should pretty much always be last.  However you may be interested in https://github.com/jashkenas/backbone/pull/3827

In your case though you could define the routes in the initialize using http://backbonejs.org/#Router-route
You could also potentially pass the routes in when instantiating assuming you have the object in question at that point.
```js
new Backbone.Router({ 
  routes: { 
    'path/to/:id': myObject.method
  },
  object: myObject 
});
```

**Comment by PipOlt** [comment]
Thanks for the response!
 I thought in this special case it makes sense to call _bindRoutes after the initialization, because it is something that may depend on the initialize method. If it's a convention always to call it in the end of the constructor I have to do it like you said.

**Comment by paulfalgout** [comment]
@akre54 can be closed :-)
