### ISSUE TITLE
Route arguments not properly parsed

### ISSUE THREAD

**Issue by RemiBloch** [jashkenas/backbone#3878]
Hi, based on the documentation, if i've the following route 

```javascript
'myself(/:opt(/:opt2))': 'displayMyself'
```

The function that handles this route is defined as (yes this is es6)

```javascript
displayMyself(tab, path){
    console.info(tab,path);    
}
```

Here are the arguments i receive based on the url hash i give

| Url hash        | tab           | path  |
| ------------- |:-------------:| -----:|
| #myself      | null | null |
| #myself/titi      | titi      |   null |
| #myself/titi/tata | titi      |    /tata |

Why do i have a */* in front of *tata*? Based on the documentation shouldn't i get just *tata* ?

I think that there is a parsing issue here.

**Comment by akre54** [comment]
The proper syntax is `myself(/:opt1)(/:opt2)`.

In the future, please try StackOverflow, the mailing list, or the gitter channel for debugging help.

**Comment by jridgewell** [comment]
@akre54 We might want to add that example to the docs, this trips me up as well.

**Comment by akre54** [comment]
Definitely. There aren't enough routing examples in general.
