### ISSUE TITLE
ES6 Module Conventions with $, _ and Backbone libraries

### ISSUE THREAD

**Issue by msiconolfi** [jashkenas/backbone#3881]
I am in the process of refactoring my code Backbone codebase to leverage new the ES6 features. One of the features I am most excited about is the Module system introduced in ES6. I am still playing around with different bundlers to be able to load it into current browsers that don't support ES6 yet.

**Just curious to see how people are using Backbone in conjunction with ES6 Modules?**

I have seen two approaches with regards to Underscore, jQuery, and Backbone libraries:

Assuming the following html file:
```html
<!-- index.html -->
<script src="underscore.js"></script>
<script src="jquery.js"></script>
<script src="backbone.js"></script>
<script src="one.js"></script>
<script src="two.js"></script>
<script src="main.js"></script>
```

**Load the libraries onto the global window object and access them via the window object.**
This seems like the traditional way of declaring library dependencies. It doesn't require adding boilerplate imports in all of your custom Backbone files/modules.

```javascript
// File: one.js
// access Backbone via the global object
export default OneView = Backbone.View.extend({
  el: '.one'
});
```
```javascript
// File: two.js
// access Backbone via the global object
export default TwoView = Backbone.View.extend({
  el: '.one'
});
```
```javascript
// File: main.js
import OneView from './one.js';
import TwoView from './two.js';

// access backbone via global
var m = new Backbone.Model();
var v1 = new OneView();
var v2 = new TwoView();
```

**Explicitly import the libraries for each new module you create**
This is very explicit but each individual file is very clear about what it is dependent on. If you unit test a file in isolation, all of it's dependencies are stated and should be more self-contained. It feels kind of bloated though to include all those imports in each custom Backbone file. This type of format will also play nicely with browserify/webpack and other bundlers. It also feels like how other languages module systems work.

```javascript
// File: one.js
import $ from 'jquery';
import _ from 'underscore';
import Backbone from 'backbone';

export default OneView = Backbone.View.extend({
  el: '.one'
});
```
```javascript
// File: two.js
import $ from 'jquery';
import _ from 'underscore';
import Backbone from 'backbone';

export default TwoView = Backbone.View.extend({
  el: '.one'
});
```
```javascript
// File: main.js
import $ from 'jquery';
import _ from 'underscore';
import Backbone from 'backbone';

import OneView from './one.js';
import TwoView from './two.js';

// access backbone via global
var m = new Backbone.Model();
var v1 = new OneView();
var v2 = new TwoView();
```

I could probably combine the jquery, underscore and backbone imports into one helper module that exports all three so that it would only be one export:
`export {$, _, Backbone} from './BackboneHelper';`

Curious to see if anyone else has found some useful conventions or wanted to discuss the tradeoffs they've experienced between the two methods.

**Comment by mr47** [comment]
I think second is better. It's more cleaner for future reader. He know where and what we are using.

For backbone more important things to be clear.

Bad idea is webpack define plugin.

**Comment by akre54** [comment]
This is really a question for StackOverflow or the mailing list, but personally I prefer the import everything way. It's much more explicit and easier to refactor.

**Comment by jridgewell** [comment]
> Explicitly import the libraries for each new module you create

:+1:
