### ISSUE TITLE
Cobertura for manual gui testing in maven

### ISSUE THREAD

**Issue by balaji-raj** [jashkenas/backbone#3887]
Hi,

I am trying to generate the reports for my gui manual testing using cobertura. I need to use without junit, 

I have done instrumenting the class using cobertura:instrument and generate the instrumented classes.

But while doing manual testing it shows no data to be stored in ser file even after server shutdown.

Help me to come out of this issue.

Thanks in advance

**Comment by balaji-raj** [comment]
Hi jridgewell,

Can I know why you close this without any reply?

**Comment by jridgewell** [comment]
These have nothing to do with Backbone.

**Comment by hegdeashwin** [comment]
:+1:  Agree with @jridgewell
