### ISSUE TITLE
Cobertura for delta changes testing

### ISSUE THREAD

**Issue by balaji-raj** [jashkenas/backbone#3888]
Hi,
 
I already post about the cobertura issue in my last post, 
https://github.com/jashkenas/backbone/issues/3887

I also need to do report generation for my delta changes

Thanks in advance.

**Comment by balaji-raj** [comment]
Hi jridgewell,

Can I know why you close this without any reply?

**Comment by RobertCZ** [comment]
Any chance to have automatic responses to the new issues saying the usual Backbone/Stackoverflow thing? Maybe like [this](https://github.com/eslint/eslint/issues/4681#issuecomment-164174723)?
