### ISSUE TITLE
After extending Collection.prototype.fetch the collection comes malformed

### ISSUE THREAD

**Issue by asantos00** [jashkenas/backbone#3890]
In a project at the place I work we have the need to have a global error handler for collection/model fetch errors and for models we are doing it with no problems. 
When we try to extend the fetch method in collection prototype the collection comes malformed and we cant "toJSON()" the collection anymore.

```
// Default error on fetch
		var originalColFetch = Backbone.Collection.prototype.fetch;
		Backbone.Collection.prototype.fetch = function(options){
		    if(options){
		        var originalError = options.error;
		        options.error = function(collection, error, request){
		            if (originalError){ originalError(collection, error); }
		            
		            App.Helpers.fetchErrorHandler(error)

		        }
		    }
		    originalColFetch.apply(this, arguments);

		};
```

The code I have to extend the collection fetch is this, at the moment I am calling the fetch with no arguments. The code for the model is pretty similar and it works. Do you guys know what could it be?

Thanks!

**Comment by akre54** [comment]
Can you create a JSFiddle / Codepen example demonstrating the problem? Hard to tell without some actual code.

Also, Github issues aren't the place for debugging help. Please try StackOverflow or the Gitter channel before posting an issue.
