### ISSUE TITLE
Model with id "undefined"

### ISSUE THREAD

**Issue by duskpoet** [jashkenas/backbone#3905]
If you put model with id "undefined" in collection first, .get method of collection will always return this model.

https://jsfiddle.net/duskpoet/rg74hL4p/

**Comment by jridgewell** [comment]
This actually comes from the `#set` model, where we try to determine if `{id: 1}` is in the collection already. The set uses `#get({id: 1})`, which tries `this._byID[model.cid]`, and since the model doesn't have a `cid` property, it fetches the `undefined` model.

Can we [please](https://github.com/jashkenas/backbone/search?q=byId&type=Issues&utf8=%E2%9C%93) split up `byId` and `byCid`?

**Comment by akre54** [comment]
Under what circumstances would you have an id of `"undefined"`?

This sounds like a bug in your code, and there are better places for bugfixes than in Backbone proper.

**Comment by duskpoet** [comment]
I have categories, coming from external API, and one of them is... "undefined". I'd like to keep them as `id`, cause I need to get models from collection by category often.

**Comment by craigmichaelmartin** [comment]
PR https://github.com/jashkenas/backbone/pull/3936 will allow for this. Examples are contrived, until they're not. I'm in favor of [adding tests back](https://github.com/jashkenas/backbone/pull/3953) to ensure backbone is un-opinionated about what is 'reasonable' and ensures this case is tested for.

**Comment by duskpoet** [comment]
There is also a similar case with id: '[object Object]'
https://jsfiddle.net/duskpoet/yg1mnvhz/

**Comment by craigmichaelmartin** [comment]
I've update my PR for this case. Given the nature of accepting such a wide range of values for `get`, i think these are judicious measures. I don't think Adam is going to agree though :P

**Comment by akre54** [comment]
@duskpoet that's really not how Model ids are supposed to be used.

Your best bet is to do `collection.findWhere({category: "undefined"})` for your first case and fix the bug for your second.
