### ISSUE TITLE
Make backbone play nicer with NoSQL REST APIs

### ISSUE THREAD

**Issue by Risto-Stevcev** [jashkenas/backbone#3908]
Backbone currently doesn't play nicely with NoSQL REST APIs, like MongoDB, because it rely's substantially on a [specific format](http://backbonejs.org/#API-integration) for the API.

This can all be overridden, but it results in a lot of boilerplate code. For MongoDB, you would use `idAttribute` to set something like the book name to as the main identifier, so the API would look like:

    GET  /books/ .... collection.fetch();
    POST /books/ .... collection.create();
    GET  /books/:name ... model.fetch();
    PUT  /books/:name ... model.save();
    DEL  /books/:name ... model.destroy();

But since MongoDB uses a document attribute as the unique key, backbone will erroneously assume that `isNew` is false when trying to create a new entry on [save](http://backbonejs.org/#Model-save):

> If the model isNew, the save will be a "create" (HTTP POST), if the model already exists on the server, the save will be an "update" (HTTP PUT).

One solution is to pass in the request method (ie. `post`) manually on `.save` requests. But then the burden is on the coder to add extra boilerplate to figure out when to CREATE or UPDATE in any given view.

The easier solution to this is to override `isNew` under [Backbone.Model](http://backbonejs.org/docs/backbone.html#backbone-model) with something that plays nicer with MongoDB. The problem creating all of this boilerplate is written in the comments for `isNew`:

> A model is new if it has never been saved to the server, and lacks an id.

NoSQL databases like MongoDB don't rely on ids like RDMS solutions do. Thus it confuses a new document as an old one and issues a PUT request instead of POST, which requires either boilerplate on the `.save` calls, or overriding `isNew` somehow.

Backbone already is pretty unopinionated, but this is something that just feels a little to hacky to be considered clean. It should be able to support NoSQL better for this particular scenario. 

My suggestion is to update the `isNew` method to return `false` if the model has not been synchronized with the server. Implicitly this would mean that the model is new. Or if backwards compatibility is an issue, have an option, such as `emulateNoSQL`, that will properly set up the API and `isNew` to play nicely with NoSQL database APIs.

**Comment by elgubenis** [comment]
im always using idAttribute: '_id' and never had an issue since, I don't really get the problem you are facing.

**Comment by jridgewell** [comment]
What @elgubenis said.

**Comment by Risto-Stevcev** [comment]
@elgubenis The '_id' attribute would need to be passed into the API calls. This works fine if it's just your app and not yours users that will be making API calls. But if you want to open up your API to users, this would make the API harder to use, because API calls would like ugly like this:

    GET  /books/507f1f77bcf86cd799439011 ... model.fetch();
    PUT  /books/507f1f77bcf86cd799439011 ... model.save();
    DEL  /books/507f1f77bcf86cd799439011 ... model.destroy();

when, supposing each book would have a unique identifier such as a name, should *ideally* work like this:

    GET  /books/Alice ... model.fetch();
    PUT  /books/Alice ... model.save();
    DEL  /books/Alice ... model.destroy();

@jridgewell This wasn't a question, this was a suggestion for Backbone to be less opinionated about how the API is structured for NoSQL APIs. You didn't even let me respond before closing this issue.

**Comment by mr47** [comment]
@Risto-Stevcev I think @jridgewell closed your question becouse backbone default using REST but if you want use ```GraphQL``` just rewrite ```Backbone.sync``` and you ready to go with NoSQL solution.
Simple version of ```Backbone.sync```
```javascript 
Backbone.sync = function(method, model, options) {
  options || (options = {});

  switch (method) {
    case 'create':
    break;

    case 'update':
    break;

    case 'delete':
    break;

    case 'read':
    break;
  }
};
```
PS: I have done this for websokets its simple but powerfull.

**Comment by Risto-Stevcev** [comment]
@mr47 My suggestion (not a question) wasn't about how to not use REST, it was about how Backbone is relying headily on `:id` to do API requests. In particular, it doesn't work elegantly if the `idAttribute` is set to something else when doing `.save`. I wasn't asking a question, and I'm not looking to use Object Id, and I mentioned a very good reason why. My original post explains the issue.

I don't see the why this problem doesn't deserve consideration. AngularJS is agnostic about how the REST API is structured, and Backbone is *almost* agnostic by allowing you to set an `idAttribute`. I mentioned a problem with that approach by providing an example where it breaks down.

**Comment by mr47** [comment]
@Risto-Stevcev how i said before. Rethink you arhitecture. Id in DB world is unique identifier name - not.
If you want to do someting with it change the sync method, if not use @elgubenis solution.

There is no other options. If you try to find a way to do this - Rethink you arhitecture.

**Comment by Risto-Stevcev** [comment]
@mr47 
> Id in DB world is unique identifier name - not.

Actually anything that is a unique key in the DB is a unique identifier. And if that identifier makes the API easier to use than an id, then it should be used instead of an id. Why eat up the user's API request limit (and add additional load to the server), by having the user send an additional request to figure out an id for something, when they don't have to?

There are [many](https://developer.github.com/v3/) [real](https://www.mediawiki.org/api/rest_v1/?doc) [world](https://www.flickr.com/services/api/), popular APIs that either do not use an id number as a unique identifier, or have an REST API that looks completely different than the one Backbone forces you into.

The answer shouldn't be "you need to rethink your architecture". Sometimes a different architecture makes sense, and sometimes the architecture isn't up to you. Backbone should be flexible enough to work with any kind of API structure without internally changing the REST API that Backbone relies on. To say that they all got it wrong because the Backbone REST API is the gold standard is frankly a little arrogant, elitist, and impractical.

**Comment by jridgewell** [comment]
This one isn't going to change, Backbone sync is designed for a REST architecture because it's absurdly common. If you want to use a an arbitrary identifier (`name`, in your case), just override `isNew`.

**Comment by Risto-Stevcev** [comment]
Backbone is not designed for REST architecture overall like you're implying, it's designed for a particular flavor of a REST API.

You work for Google right? tell me how you would write a model in Backbone for this [Google+ REST API Endpoint](https://developers.google.com/+/web/api/rest/latest/):

listByActivity 	GET  /activities/**activityId**/people/**collection** 	List all of the people in the specified collection for a particular activity.

Backbone's expected REST API only supports one identifier per Model. This endpoint has two identifiers, **activityId** and **collection**. In AngularJS this is simple to do and in Backbone it's not and requires additional boilerplate. Almost every REST API you come across has at least one endpoint which is looking for two or more identifiers. Don't get me wrong, angular has it's own issues, but I think this makes my point clear.

**Comment by jridgewell** [comment]
That's a collection with an `#url` like: ```return `/activities/${this.activityId}/people/{$this.id}`;```, which each person in this collection having their own url like `/activities/.../people/.../${this.id}`.

**Comment by Risto-Stevcev** [comment]
?. `return '/activities/${this.activityId}/people/{$this.id}';` is not valid syntax in backbone. You can do something like that in angular:

    var CreditCard = $resource('/user/:userId/card/:cardId',
     {userId:123, cardId:'@id'}, {
      charge: {method:'POST', params:{charge:true}}
     });

Backbone's expected REST API for collections looks like this (unless you want to add a considerable amount of additional wiring because your API doesn't match):

    GET  /books/ .... collection.fetch();
    POST /books/ .... collection.create();
    GET  /books/1 ... model.fetch();
    PUT  /books/1 ... model.save();
    DEL  /books/1 ... model.destroy();

**Comment by jridgewell** [comment]
That was an ES6 template string...

```js
var Collection = Backbone.Collection.extend({
  url() {
    return `/activities/${this.activityId}/people/{$this.id}`;
  }
});
var c = new Collection();
c.id = 'test';
c.activityId = '123';

var m = Collection.create({ ... });
m.url(); // => /activities/123/people/test/1
```

**Comment by Risto-Stevcev** [comment]
Ok, so you could do that and transpile ES6 using babel, or `return '/activities/' + this.activityId + ...` in ES5, but it still doesn't neatly match the backbone API structure if you look at the table. Why did you have `collection` as the main id instead of `activityId`? When in reality both for the unique identifier for a resource? Both are required to form a unique resource for a model, but backbone only allows one id for that. It's really **not** that uncommon to have two or more identifiers in an endpoint forming a unique resource.

And what about Moments? possibly a better example. Here's the CRUD for that:

    insert 	POST  /people/userId/moments/collection 	Record a moment representing a user's action such as making a purchase or commenting on a blog. Writing moments involves specifying the type, which is a moment type, and posting that type of moment's required fields.
    list 	GET  /people/userId/moments/collection 	List all of the moments that your app has written for the authenticated user.
    remove 	DELETE  /moments/id 	Delete a moment that your app has written for the authenticated user. 
 
Insert and list fits the backbone structure. But remove (DELETE) should be ` /people/userId/moments/collection/momentId` to match the backbone API structure, but it's `/moments/id` instead.

You might say it's close enough to fitting and that you could just get DELETE to fit that url structure. But what if you want to access a larger API, and the issue pops up constantly? Why would you feel okay forcing the coder to write a bunch of extra boilerplate when backbone can be redesigned to work better? The GitHub, Wikimedia and Flickr APIs that I mentioned earlier don't fit anywhere near as neatly, and those are very mainstream APIs. Should the coder have to hack all of their backbone code to get them to fit its structure because it has a strong opinion about how APIs should look?

Like I mentioned initially, I'm not arguing that you can't find a way to make any API work with backbone, because you can override any of the methods. What I'm arguing is that it adds a bunch of *extra boilerplate*, and it should instead play nicer with any kind of API structure, because of reasons mentioned. Any extra boilerplate to backbone should only be there for specific use cases that aren't common in all applications.

**Comment by elgubenis** [comment]
Don't fight it, accept and learn. With the url method, idAttribute and overriding the sync method you have plenty of options to connect with all these rest-'flavors'. Never heard of such issues, because Backbone offers so many different ways to use rest backends.

**Comment by Risto-Stevcev** [comment]
@elgubenis You're missing the point of what I'm trying to say. You can make anything work with Backbone, I don't deny that at all. What I'm saying is that for APIs that don't conform well enough with the Backbone's expected API, then it requires considerable boilerplate, even with the url method and idAttribute.

For example, Flickr's REST [request](https://www.flickr.com/services/api/request.rest.html) format looks like this:

     https://api.flickr.com/services/rest/?method=flickr.test.echo&name=value

Which looks completely different than what Backbone expects.
For `flickr.groups.discuss.replies.`[add](https://www.flickr.com/services/api/flickr.groups.discuss.replies.add.html)/[edit](https://www.flickr.com/services/api/flickr.groups.discuss.replies.edit.html)/[delete](https://www.flickr.com/services/api/flickr.groups.discuss.replies.delete.html) methods, all of them require HTTP POST (no PUT and DELETE here), and differ enough from Backbone to where, if you didn't want to override Backbone.sync because you're accessing two or more APIs for your app, you have to enter in a different method and url for fetch, save, and destroy.

So now you've heard of such an issue. If you look up enough Backbone criticisms, you'll find people talking about this. AngularJS lets you interface with any API easily, as does EmberJS. From what I'm hearing, Backbone is too proud to change. In the real world you deal with all kinds of endpoints, so why make coders add more boilerplate to a library/framework that already requires a bunch of boilerplate? 

From a business perspective, you might not have the option to change the API your company uses. Especially if a lot of clients are already using it. You could come out with a new version. I just don't know how it would go down with your boss if you told him to change not fight it, accept, and learn.

You can fight what I'm saying all you want, and not accept it or learn from it. You've made your point that there are lots of APIs that use Backbone's framework or similar. And I've said enough and I've made my point, and you can take it as you wish. My original argument had plenty of merit. If I'm an online library service, and I can identify a unique resource using something like `/books/:publisher/:year/:author/:title`, which will never change, which makes my API easier to use, which is less arbitrary requires less work than using and finding an id, then forgive me for thinking that's not a horrible idea.

**Comment by elgubenis** [comment]
I forgive you.
