### ISSUE TITLE
doc error in Collection modelId

### ISSUE THREAD

**Issue by futurist** [jashkenas/backbone#3913]
below doc error found: 
http://backbonejs.org/#Collection-modelId
**modelId** collection.modelId(attrs) 
````
var Library = Backbone.Collection.extend({
  modelId: function(attrs) {
    if (attrs.type === 'dvd') {
      return 'dvd' + attrs.dvd_id;
    } else {
      return 'vhs' + attrs.vhs_id;
    }
  }
});

var library = new Library([
  {type: 'dvd', id: 1},
  {type: 'vhs', id: 1}
]);

alert('dvd: ' + library.get('dvd1').id + ', vhs: ' + library.get('vhs1').id);
````
`attrs.dvd_id` and `attrs.vhs_id` both is `undefined`, should be `attrs.id` ?

**Comment by akre54** [comment]
Ah yeah my bad. I broke it last time. Should be fixed in 201aa149a484c91520f090dcf847f0f4e2937b16
