### ISSUE TITLE
deeply set in model

### ISSUE THREAD

**Issue by futurist** [jashkenas/backbone#3914]
#### The problem
see below code:
````
var model = new Backbone.Model(
  { a: { b: { c:'some value' } } }
)

// deeply get is handy
var val = model.get('a').b.c

// deeply set is not
var temp = _.clone( model.get('a') )
temp.b.c = 'another'
model.set('a', temp)
......
````
#### The proposal
When `model.attributes` should not contain space, so maybe the below form can be better:
````
// deeply get
model.get('a b c')

// deeply set
model.set('a b c', 'another')
````

**Comment by rafde** [comment]
I found #2826 which was cloned as a wont fix.
You have to keep in mind that if any values in the attribute are models or collection then the deep set/get, how will it work for those cases?

**Comment by jridgewell** [comment]
@futurist: We don't support deep properties at all. In fact, we recommend everything in `attributes` be simple primitive values.
