### ISSUE TITLE
Can I get method name from event handler?

### ISSUE THREAD

**Issue by mqklin** [jashkenas/backbone#3922]
I have a simple model that intercepts error. How can I get name of method that has created an error?

    export class CommonModel extends Backbone.Model {
      constructor(options) {
        super(options);
        this.on("error", this.onError);
      }

      onError(model, response, options) {
        let method = ???
        console.log(method); // GET or POST or PUT or DELETE
      }
    }

**Comment by mr47** [comment]
Please read about wrapError parameters http://backbonejs.org/docs/backbone.html

**Comment by mqklin** [comment]
@mr47 , it takes `model` and `options` as parameters, but they don't contain `method`. Do you know the answer?

**Comment by mr47** [comment]
Almost you can't directly get method because of wrapError but if response
is jqxhr - you can.
11 янв. 2016 г. 13:20 пользователь "Maksim" <notifications@github.com>
написал:

**Comment by mr47** [comment]
Second solution is rewrite backbone.sync

**Comment by jridgewell** [comment]
Questions like this are better left to one of the other channels:

> For questions on working with Backbone or general discussions: https://groups.google.com/forum/#!forum/backbonejs, http://stackoverflow.com/questions/tagged/backbone.js, or https://gitter.im/jashkenas/backbone

**Comment by mqklin** [comment]
Answer: http://stackoverflow.com/questions/34717933/get-method-name-on-event
