### ISSUE TITLE
Lodash _.flatten function work differently from v3.0.0

### ISSUE THREAD

**Issue by bbkingtw** [jashkenas/backbone#3925]
Hi, I wrote a small piece of code for test _.flatten. the code is as below

    objects = [{ 'a': [1] }, { 'a': [2, 3] }];
    console.log(_.flatten(objects, 'a')); 

version<=2.4.2  the result is [ 1, 2, 3 ]
but while I use version>=3.0.0  result is [ { a: [ 1 ] }, { a: [ 2, 3 ] } ]

I got some confused here, is there any definition change for this function?

**Comment by jridgewell** [comment]
lodash has `_.flattenDeep` that follows the v2 behavior.

PS. this is the Backbone.js repo, not lodash.
