### ISSUE TITLE
collection create

### ISSUE THREAD

**Issue by MeterSoft** [jashkenas/backbone#3931]
my model.toJSON() return

{
   name: "test",
   phone_numbers: [
      {
           id: 1,
           number: "111111111"
      }
   ]
}

then i try set value

model.set({
   name: "test update",
   phone_numbers: [
      {
           id: 1,
           number: "2222222"
      }
   ]
})

and after model.toJSON() return 

{
   name: "test update",
   phone_numbers: [
      {
           number: "2222222"
      }
   ]
}

Why id removed and how i can update my nested model?
for now i do:

model.set({ value })
collection.create({
   model
})

**Comment by akre54** [comment]
Please use StackOverflow, the gitter channel, or the mailing list for questions. Github issues are for maintaining the framework only.
