### ISSUE TITLE
Integrating qdelaunay and qvoronoi function of qhull in c++

### ISSUE THREAD

**Issue by changdongyang** [jashkenas/backbone#3937]
Hi,

I know basics of visual studio and c++, but I am not an advanced user or programmer. What I want to do is to perform delaunay triangulation and generate voronoi grids using qhull library (using visual studio c++ in windows). I have no problem with preparing necessary data for calculation. My questions are:

What is the minimum necessary files to be included from qhull? (from what publicly free, the qhull is very powerful and contains a huge amount of files)

How can I easily perform the delaunay triangulation and generate voronoi grids? (like in delaunayn.m file of Matlab it calls " t = qhullmx(x', 'd ', opt); " then get the delaunay triangulation. )

Thank you so much for sharing your experience!

**Comment by captbaritone** [comment]
@changdongyang I believe you are commenting on the wrong repository.

**Comment by changdongyang** [comment]
@captbaritone Thank you. You are right. I will put it in the correct repository. Thanks
