### ISSUE TITLE
Collection factory-ing Models should set urlRoot.

### ISSUE THREAD

**Issue by sam-at-github** [jashkenas/backbone#3944]
I propose Collection should set the `urlRoot` of Models it creates or that are explicitly added to it, if and only if the added Model does not already have a urlRoot set. 

Why? Currently if an item Model instance is removed from a collection it can no longer talk to remote because it does not have a urlRoot, or a collection.url. But the remote object still exists, and the Model instance proxying it still exists. Being removed from the collection does not mean the Model instance is invalid in anyway, yet it gets broken by this. Consider this example: A Collection representing the first page of results on a server. If we do a Collection.fetch({reset: true}), a Model instance may be removed and its ability to talk to remote broken.

(Side note: I also think Model.collection.url should override Model.urlRoot,or alternatively urlRoot should be set to the last collection it was added to. But the above can be considered standalone, so I'll argue that in another issue)

**Comment by akre54** [comment]
Is this any different from #1705 #2416 #2426 #2430 #2533 #2578 #2797 #2426, etc?

As I recall correctly we stopped passing the `url` along to avoid shadowing the model url from the collection, but I don't remember why we stopped passing `urlRoot`.

**Comment by akre54** [comment]
(Also in the future, please open just one issue or pull request per change. No need to do it in two places).

**Comment by sam-at-github** [comment]
Hi, it's different. #1705, #2800 are asking for the ability to pass `url` to Collection at init. This seems to have been added somewhere between #1705 and #2426 because it was deprecated in #2426 to fix a bug that all the other tickets you mentioned are about. the convo in #2424 resulted in #2426 not allowing `url` or `urlRoot` to be pased as options to Collection, Model constructors respectively. Not allowing `url` to Collection somewhat indirectly solves the bug. The argument for not allowing `urlRoot` was merely be consistent with the change to Collection as far as I can see.

Essentially what I'm proposing is, that in the absence of more specific instruction from the Model class, when a Collection creates a Model instance it should set its url (or rather 'urlRoot'). I don't care how its done. To implement this originally I made urlRoot an option to the constructor again. But actually thats wrong. If the Model specifies a urlRoot it should take precedence. I have pushed and squashed this amendment into the PR.

It's a minor thing and easy enough to hack around - like below - but I feel this is the correct inutitive behavior.

    var MyModel = Backbone.Model.extend({
      initialize: function(options) {
        if(!this.urlRoot && this.collection.url) {
          this.urlRoot = this.collection.url
        }
      }
    })

> (Also in the future, please open just one issue or pull request per change. No need to do it in two places).

No problem will try to think of PR before opening issue in future when its simple.

**Comment by jridgewell** [comment]
I'm actually on board with this. It's not the same as passing `url` to the Model constructor, since `url` may mean the ajax url not the model url. `urlRoot` doesn't have the same confusion.

**Comment by akre54** [comment]
The consistency argument is pretty compelling. Why should urlRoot work but not url?

**Comment by jridgewell** [comment]
Only because we can't differentiate between jQuery's `url` and the model's `url`. Maybe open up a `modelOptions` object that'll be passed down as the options to the model?

**Comment by akre54** [comment]
Right that's my point. If we are going to do one than we should do the other. If one is broken, then we shouldn't do the other.

`modelOptions` seems kind of gross though. What's a use case for not setting it yourself (either in the `initialize` or in a `url` / `urlRoot` method of your own)?

**Comment by jridgewell** [comment]
@sam-at-github brought up the `urlRoot`

**Comment by jridgewell** [comment]
@sam-at-github brought up the `urlRoot` use case above: if a model is created through a collection, it should be tied to the collection's `urlRoot`.

I don't know of any use case for passing `url` as an option to a model/collection.

**Comment by akre54** [comment]
> if a model is created through a collection, it should be tied to the collection's urlRoot.

It [already is](https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L690-L692)?

If it absolutely has to be set by the collection couldn't that logic live on the Collection? Why does it have to be passed down as an option?

Something like:
```
_prepareModel: function(attrs, options) {
  // ...
  if (model.url !== Model.prototype.url && !model.urlRoot) model.urlRoot = this.url
}
```

**Comment by jridgewell** [comment]
> Currently if an item Model instance is removed from a collection it can no longer talk to remote because it does not have a urlRoot

It is an edge case, but it would make sense to me that the model keeps the collection's `urlRoot`.

> Why does it have to be passed down as an option?

It doesn't. The `#_prepareModel` code would be a perfect spot for it.

**Comment by akre54** [comment]
Wait so the use case is creating a model through a collection, but then removing the model from that collection and being surprised the model doesn't keep the collection's url? I don't like it.

I think the behavior we have currently is the right one. If the model is in a collection and doesn't have its own url / urlRoot set, check on its collection. If it isn't in a collection, you're responsible for setting it yourself. Why should a model be tied to a collection it's no longer in?

**Comment by sam-at-github** [comment]
> Wait so the use case is creating a model through a collection, but then removing the model from that collection and being surprised the model doesn't keep the collection's url?

Well yes, that is was the unexpected behavior that motivated this PR. Note however that it's not the user removing the model. Backbone will remove model from collections in certain situations leaving them hanging around but without a way to talk to the remote - unless your specifically aware of this behaviour and set things up accordingly.

> I think the behavior we have currently is the right one. If the model is in a collection and doesn't have its own url / urlRoot set, check on its collection. 

I agree. That is still the case.

> If it isn't in a collection, you're responsible for setting it yourself. Why should a model be tied to a collection it's no longer in?

Its not still tied to the  Backbone.Collection but it *is* still tied to an item in the remote collection for the model is a proxy. Why should Backbone.Collection factory Backbone.Models proxies that don't work standalone?

Maybe its a subtle difference in how we view the responsibilities of Backbone.Model and Backbone.Collection, and the semantics of remove as opposed to destroying a model. I don't think Backbone.Collection is a reflection of the *entire* remote collection. I don't think it can be. It's a view into it. So removing a model from a collection is not synonymous with deleting it from the remote collection. To me it's more "hey this model just fell out of view".

This PR was driven by me being a newb and scratching my head when a Model part of my UI was referencing got removed from a collection on a sync and no longer worked. I thought that was wrong. At the end of the day, once you understand the behavior its easy enough to hack around it. It took me a while to think about it all though. The way models / collection / urls / and membership is all related is a bit to think about.

**Comment by akre54** [comment]
I agree it's a surprise but I feel like there are just too many edge cases here (how would Backbone determine that a URL or urlRoot hadn't been set?), and the opposite behavior would be just as surprising.

Your  best bet is probably to set a urlRoot in your model's initialize method if you know you could potentially reference models outside of a collection.

You're right that a Collection may not reference all models at a resource, but I'd argue that if you've removed a model from a collection there's usually some reasoning behind it (why is your sync removing the model?), and it'd be surprising to still tie a removed model to a collection of which it is no longer a member.

**Comment by jashkenas** [comment]
@akre54 is entirely on the money here.
