### ISSUE TITLE
options.index in add event sometimes exceeds the collection length

### ISSUE THREAD

**Issue by ralfstx** [jashkenas/backbone#3951]
When adding models to a collection `{at: }` an index that is greater than the collection length, the models are added at the end. As the test case below shows, the index provided in the corresponding `add` events reflects the requested indices, not the actual insertion indices.

Not sure if this qualifies as a bug, but for tracking the exact changes to a collection, it would be great if the `options.index` provided in the `add` event would reliably reflect the *actual* insertion index.

Some background: we need this to back native CollectionViews in our [mobile framework](https://github.com/eclipsesource/tabris-js/) with Backbone Collections.

```js
describe('Collection', function() {

  var collection, events;

  beforeEach(function() {
    events = [];
    collection = new Backbone.Collection();
    collection.add([{name: 'A'}, {name: 'B'}]);
    collection.on('add', function(model, collection, options) {
      events.push('add ' + model.get('name') + ' @' + options.index);
    });
  });

  it('set provides correct indices in add events', function() {
    // before: A B
    collection.add([{name: 'C'}, {name: 'D'}], {at: 5});
    // after: A B C D
    expect(names(collection)).toBe('A B C D');

    // Backbone incorrectly returns indices 5 and 6 instead of the actual incices 2 and 3
    expect(events).toEqual(['add C @2', 'add D @3']);
  });

  function names(collection) {
    return collection.toArray().map(function(model) {
      return model.get('name');
    }).join(' ');
  }

});
```

**Comment by akre54** [comment]
The fix for this should be to move [the `Math.min` logic](https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L769) up to [where we figure out the `at`](https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L829-L831). Or guard [this line](https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L901). @jridgewell thoughts?

In the future, can you open a runnable JSFiddle / CodePen to assist in debugging? (And minor code golf, your `names` function could be written as `collection.pluck('name')`)

**Comment by jridgewell** [comment]
> The fix for this should be to move the Math.min logic up to where we figure out the at. Or guard this line. @jridgewell thoughts?

Yup.

**Comment by akre54** [comment]
Take a look at b0161947eb731f936cb986b1cf669af9370adbc9, should solve this for you.

**Comment by jridgewell** [comment]
Reopening due to https://github.com/jashkenas/backbone/commit/b0161947eb731f936cb986b1cf669af9370adbc9#commitcomment-15896632.

**Comment by jridgewell** [comment]
Whooops.
