### ISSUE TITLE
Collection for-of support 

### ISSUE THREAD

**Issue by RobertCZ** [jashkenas/backbone#3954]
Would be nice if we could write 

`for (let model of collection) ...`

Maybe all it would take is adding:

```
if (areSymbolsAndGeneratorsSupported) {
  Collection.prototype[Symbol.iterator] = function* () {
    for (let model of this.models) yield model
  }
}
```
Browsers without symbols and generators (probably) don't have for-of anyway and if you transpile you have all of them. 

What do you think?

**Comment by akre54** [comment]
Unfortunately unsupported browsers will throw a SyntaxError, and we're not up to the point of requiring Backbone to be transpiled. This would make a great plugin for your own projects.

**Comment by jdalton** [comment]
Support is doable without throwing a SyntaxError.

For example Lodash works as an iterable w/o throwing:
```js
for (let value of _({ 'a': 1, 'b': 2, 'c': 3 })) console.log(value)
``` 
or
```js
[..._({ 'a': 1, 'b': 2, 'c': 3 })]
```

All you need is to detect `Symbol.iterator` then the func assigned to `Symbol.iterator` just returns `this`.
```js
var wrapped = _([1, 2]);
wrapped[Symbol.iterator]() === wrapped;
```
and add a `next` function to the wrapper that returns `{ 'done': doneState, 'value': currValue }`.

**Comment by jdalton** [comment]
Iterator support makes me happy. It's pretty fun to have things just work with the newer APIs by just adding a `next` method and a little `Symbol.iterator` function.
