### ISSUE TITLE
Backbone.Collection:set - add events may send wrong options.index

### ISSUE THREAD

**Issue by jrdb** [jashkenas/backbone#3960]
Bug Preconditions:
-   options.remove = true 
-   options.at == null
-   passed in attrs has elements to add and collection has elements to remove

Bug Manifestation:
- _removeModels will set options.index when sending out its triggers.
- If options.at == null, the set method does not clear out the options.index set by _removeModels before triggering the add events. In that case, the last options.index from the remove events is reused in the add events.

`

        var array = _.map([1,2,3,4], function(val) {
            return {property:val};
        });

        var collection = new Backbone.Collection(array);

        collection.on('add', function(model, collection, options){
            // BUG!!: options.index (0) != collection.indexOf(model) (3)
            console.error(
                'BUG!!: options.index ('
                + options.index +
                ') != collection.indexOf(model) ('
                + collection.indexOf(model) +
                ')'
            );
        });

        array = collection.toArray();
        array.shift();
        array.push({property:5});
        collection.set(array);
`

**Comment by megawac** [comment]
Want to make a pull request adding a unit test?

**Comment by akre54** [comment]
Look at the [change log](http://backbonejs.org/#changelog) for 0.9.9:

> To improve the performance of add, options.index will no longer be set in the `add` event callback. collection.indexOf(model) can be used to retrieve the index of a model as necessary.

We don't set `options.index` unless you've passed an `at` index.

**Comment by jrdb** [comment]
> We don't set options.index unless you've passed an at index.

That's the bug. In the add event, Backbone is actually sending a stale options.index that was set by _removeModels.

The end of _removeModels needs a 
`delete options.index` 

The documentation is not explicit about what is sent in the options parameter of the callback.  If it is there, you should be able to rely on it.  In this case, there is stale data leftover from the remove event.

**Comment by akre54** [comment]
Sure, let's fix this.

**Comment by jrdb** [comment]
Pull request on the related open issue, #3961
