### ISSUE TITLE
In the docs for collection.add(model, {at: <addIndex>})

### ISSUE THREAD

**Issue by ashivkum** [jashkenas/backbone#3969]
So I was doing a project for work recently that involved the following workflow

1. Hit a web endpoint that returns a list of stanzas that is a comma separated string in the order they should be displayed in some UI
Ex: /endpoint/stanzas => "stanza1,stanza2,stanza3,stanza4"
2. Split into list, and hit the endpoints for all those stanzas to get more detail about them for the display
Ex /endpoint/stanzas/stanza{1-4} => { some: data, etc: [1,2,3] }

So since all of them were getting asynchronously sent, I also wanted to add them to my collection in the order that the list in step 1 was ordered.  For this, I ran _.map() on the comma split list of that string, and stored the index as the point to insert at.  Ex: collection.add(fetchedModel, {at: storedIndex});  However, it turns out that the collection doesn't quite behave like a Javascript array and you cannot insert it at a non-existing index since the collection doesn't dynamically resize.  Being Javascript, I thought Backbone would intuitively do this, and I lost a lot of time debugging an error as a result.

My suggestion would be the following:

1. Add in the docs for collection.add() at backbonejs.org that providing an index to the "at" option that is larger than the size of the collection will not dynamically resize the collection.
2. I am happy to implement a branch and create a pull request that will actually provide this functionality if it is desired.

**Comment by mr47** [comment]
@ashivkum its pretty simple to use ```Backbone.Collection```. If you want to make it clear make PR.
@akre54 close please.

Thanks.

**Comment by megawac** [comment]
Yeah, feel free to make a pull request and we'll review @ashivkum
