### ISSUE TITLE
Brackets support for Backbone.Collection

### ISSUE THREAD

**Issue by stalniy** [jashkenas/backbone#3970]
Backbone.Collection is actually a subset of Array however currently it doesn't allow to access its value using brackets and instead we need to use `at`

**Comment by stalniy** [comment]
@jashkenas let me know your opinion and if you are ok I'll send PR

**Comment by megawac** [comment]
I'm not sure that would be a good idea, but first what would be your approach? Defining a property whenever the user adds/removes an item from the collection?

Just to point out this can be easily mixed in yourself (something like below). I'd be :-1:  for core inclusion

```js
var IndexedCollection = Backbone.Collection.extend({
  constructor: function() {
    Backbone.Collection.apply(this, arguments);

    var highestIndex = 0, self = this;

    function defIndex(index) {
      Object.defineProperty(self, index, {
        get: function () {
          return self.models[index];
        },
        set: function(model) {
          self.set(model, {at: index});
        },
        enumerable: false
      });
    }

    function reindex() {
      for (var i = highestIndex; ++i < self.length;) {
        defIndex(i);
      }
      for (var i = highestIndex; --i < self.length;) {
        delete self[i];
      }
    }

    this.on("update", reindex);
    reindex();
  }
})
```

**Comment by stalniy** [comment]
that's pretty complicated, I don't like that. What about subclassing `Array`? This fiddle works pretty well: https://jsfiddle.net/stalniy/18eco2ob/

The only difference which I currently see is that settings `length` property doesn't update the internal object array. (so, `collection.length = 0` doesn't remove items inside)

Another technic can be this but it relies on `Object.setPrototypeOf`:
```js
var collection = [];

// extend Backbone.Collection.prototype properly from Array.prototype and then
Object.setPrototypeOf(collection, Bacbone.Collection.prototype);
```

**Comment by stalniy** [comment]
rivets.js library doesn't support iteration over complex collections (only arrays). And the bad thing about using `forEach` is that it's 100ms slower than `for` loop for 2000 items.

So, I though it won't be a big deal to implement this for `Backbone.Collection` as it's actually a subset of `Array`

**Comment by megawac** [comment]
Subclassing `Array` has its own issues that have weird side effects in different Javascript environments. I don't see that happening in Backbone core. It will also lead to quite confusing scenarios if the user tried to do `collection[5] = {}` as there would be no way for Backbone to intercept this (without defined properties, which has its own mixed bag of issues).

@stalniy I would suggest you just make rivets use `collection.models` for iteration or use a Collection mixin that defines properties as I posted above (something like that might be cool to have as a Backbone plugin)

**Comment by stalniy** [comment]
make sense, haven't thought about setting items just about reading =)
