### ISSUE TITLE
Properly contributing to someone elses respository

### ISSUE THREAD

**Issue by jlopez92** [jashkenas/backbone#3971]
Hello all, I'm  using GitHub for the first time for a school project. I was under the impression I had it all figured out but I just realized that wasn't the case.

The problem: My partner created our group's repository. I made a fork of his repository and started adding commits and pushed it to github, but I'm getting this on my repository: "This branch is 2 commits ahead of myPartnersName:master. "

I read some tutorial and I thought it said to fork their repository, but maybe it was a tutorial for something else. I want to use his repository. I check his repository and sure enough, it's missing the 2 commits that I made that appears on my fork.

Pretty simple I guess. I hope it's a simple fix and that someone can help!

**Comment by Florian-R** [comment]
This is a repository of Backbone, a js lib so this question is out of the scope of this issue tracker.
Anyway, you can find good resources on Github and Git here : https://help.github.com/articles/good-resources-for-learning-git-and-github/

**Comment by jlopez92** [comment]
Aw jeez I'm really sorry about that. Thanks for redirecting me

**Comment by jridgewell** [comment]
Wait, before you go! You found the Backbone issue tracker, but how? Was there some website that pointed you here?

**Comment by jlopez92** [comment]
Hmm not really sure what it was exactly, I think it was some combination of googling "github" and "help," as well as not paying very much attention to where I was exactly that got me here.

**Comment by jridgewell** [comment]
Can you backtrack through your history? You wouldn't believe how often this happens, and I'd love to figure out why this happens.

**Comment by jlopez92** [comment]
Got it. I just googled "github questions" and the second result was this: https://github.com/jashkenas/backbone/issues/287

Without paying too much attention it seemed like I found what I was looking for.
