### ISSUE TITLE
listenTo function call not triggering on page load

### ISSUE THREAD

**Issue by kedarmanure** [jashkenas/backbone#3972]
Hi,

My html contains scripts in the following order

```
<script type="text/javascript" src="js/views/main-app.js"></script>	
<script type="text/javascript" src="js/routers/router.js"></script>
<script type="text/javascript" src="js/home-app.js"></script>
```
Following are the code snippets from each file

main-app.js

```
var app = app || {};

app.mainView = Backbone.View.extend({
	el : this.$("#main-app"),
	initialize : function(){		
		this.listenTo(Backbone, 'list:all', this.showLists);		
	},
	showLists : function(){
/*
This function should get executed.
Backbone is successfully triggering the list:all event 
*/
		var lists = new app.Lists();
		var listsView = new app.ListsView({collection: lists});
	}
})

```
router.js

```
var app = app || {};

var ListRouter = Backbone.Router.extend({
	routes : {
		'' : 'showLists'
	},
	showLists : function(){
		console.log("Accessing Home");//This is getting printed to the console
		Backbone.trigger("list:all");
	}	
});

app.listRouter = new ListRouter();
Backbone.history.start();
```

home-app.js
```
var app = app || {};
new app.mainView();
```

There seems to be some issue with listenTo when the page is loaded, once the page is loaded everything works as expected.

**Comment by mr47** [comment]
@kedarmanure Please use [stackoverflow](http://stackoverflow.com) for questions.

PS: Solution: read about ```backbone.events``` [here](http://backbonejs.org/#Events)
Try [this fiddle](https://jsfiddle.net/mr47/1ekpgz72/) its fires an event after 5 sec.

```Backbone``` its an singleton extended from Backbone.Events.

Thanks.

**Comment by mr47** [comment]
@akre54 or someone close. #287

**Comment by akre54** [comment]
Yep, StackOverflow or the Gitter Channel are better places to help debug your app. Thanks @mr47.

It looks like your listener is set up after the route is triggered from `showLists`. One solution is to move your `Backbone.history.start()` call to after setting up the `app.mainView`.

**Comment by kedarmanure** [comment]
@akre54 Sorry for posting this here before doing a extensive research on Google/SO. You are right. Backbone.history.start() should be called after setting the `app.mainView` . That fixed the issue.
