### ISSUE TITLE
Event.once callback context change in Backbone 1.3.1

### ISSUE THREAD

**Issue by onehorsetown** [jashkenas/backbone#3979]
Concerning this change:

https://github.com/jashkenas/backbone/commit/00f5c39e2784602f89f4f036323ba3688ee45af4#commitcomment-16539120

If you look on line 144, Backbone relied on the 'void 0' value:

```
if (callback !== void 0 && 'context' in opts && opts.context === void 0) opts.context = callback;
```

The fallout of this change is that in BB 1.3.1, the callback context (that is, the 'this' pointer of the callback) is now defaulting to the callback function itself. In Backbone 1.2.3, the this pointer defaulted to the original this pointer when where the callback was registered.

I am not trying to imply that the change is wrong.  Backbone does not appear to document what the context will be if the third parameter to the Events.once call is left off.   I am simply pointing out that the default behavior has changed. 

One fallout of this change is that Marionette.Backbone CollectionView no longer works with Backbone 1.3.1.   This is because of the following:

```
this.once('render', this._initialEvents);
```

https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L25

The Marionette CollectionView is registering a callback, leaving off the third "context" parameter.   In Backbone 1.2.3, the callback context defaulted to the 'this' pointer.   In Backbone 1.3.1, the callback context defaults to the callback function itself.

The fix to Marionette is simple:

```
this.once('render', this._initialEvents, this);
```

Problem solved.   However, I am simply opening this issue because it represents what might be considered by some to be a breaking change.

**Comment by cutandpastey** [comment]
:+1: This caused major headaches for my team, finding this issue really helped. Thanks @onehorsetown

**Comment by paulfalgout** [comment]
Fixed here: https://github.com/jashkenas/backbone/pull/3980
