### ISSUE TITLE
Update Backbone version number in backbone.js comment to match package.json

### ISSUE THREAD

**Issue by merusso** [jashkenas/backbone#3981]
I've noticed that, when trying to download Backbone v1.3.1, the head comment block in this file refers to itself as Backbone.js v1.2.3. Obviously, this is misleading.

**Comment by jridgewell** [comment]
Hi @merusso. Nice eye, but we've got https://github.com/jashkenas/backbone/pull/3978 open to resolve a few issues with the `1.3.x` releases.
