### ISSUE TITLE
How to upload image in database and display it like avatar.

### ISSUE THREAD

**Issue by NikolayTeodor** [jashkenas/backbone#3984]
I need only getting from database and displaying it.

**Comment by captbaritone** [comment]
@NikolayTeodor This issue tracker is intended for reporting bugs for feature requests and not for help writing your app. I would recommend rewriting your questing with lots more detail, including examples of what you have so far, where you are stuck, and exactly what errors you are getting, and then asking for help on a site like http://stackoverflow.com/.

Good luck!
