### ISSUE TITLE
Feature Request:  Make clones identifiable

### ISSUE THREAD

**Issue by andrewkfiedler** [jashkenas/backbone#3989]
I'm overriding the clone function in my own codebase in order to identify clones.  I'm not sure if other people would find it useful to be able to identify clones.

```
var clone = Backbone.Model.prototype.clone;
Backbone.Model.prototype.clone = function(){
        var cloneRef = clone.call(this);
        cloneRef._cloneOf = this.id || this.cid;
        return cloneRef;
};
```

Honestly, this might only be useful for my specific use case.  I'm dealing with a ton of legacy code, some of which uses 2-way data binding and I don't want to update the actual model until the user clicks save.  Hence I use a dummy model (clone), and when the user clicks save I use the extra information within _cloneOf to drive what happens next.  Of course, ideally I would just rip out the 2-way data binding and use the actual model to drive the view.  

As such, I'm wondering if anyone else would find this useful?  I'm not sure what another use case might be, and my current use case feels too specific to my own situation (in other words, other people who want this should just monkey patch it as well).

**Comment by russplaysguitar** [comment]
Isn't this already possible for models with an `id`? The cloned model should have the same `id` as the original model.

**Comment by akre54** [comment]
Yep, using the old `id` is a fine idea. You can always go more advanced if you need it.
