### ISSUE TITLE
Dead links to MDN docs

### ISSUE THREAD

**Issue by emileber** [jashkenas/backbone#3990]
There are at least 3 external links inside the `index.html` file that are dead.

1. Collection.slice [Array#slice](https://github.com/jashkenas/backbone/blob/65952402687569aaf28abab305a14680f1f48f16/index.html#L2088)
1. Collection.comparator [sort](https://github.com/jashkenas/backbone/blob/65952402687569aaf28abab305a14680f1f48f16/index.html#L2109) same at line [4860](https://github.com/jashkenas/backbone/blob/65952402687569aaf28abab305a14680f1f48f16/index.html#L4860)

The right link I guess would be:

- Array slice : https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
- Array sort : https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by akre54** [comment]
Fixed. Thanks!

**Comment by emileber** [comment]
Collection.comparator "sort" link ([Line 2109](https://github.com/jashkenas/backbone/blob/f5b8589eda9bf91ed91d1953ae5b3b50209ec8d0/index.html#L2109)) still points to a dead link on the MDN docs.

**Comment by akre54** [comment]
Feel free to open a pull request and we'll merge that in. Thanks!
