### ISSUE TITLE
Backbone.history.navigate removes hash

### ISSUE THREAD

**Issue by just-boris** [jashkenas/backbone#3992]
I am using Backbone router and I'd like to load URLs without full page reload. I add handler that calls `Backbone.history.naviagate()` on links.

The issue here is that hash from url is stripped. I'd like to pass url with a hash as an anchor for some section on a page like it is done in [Backbone documentation](http://backbonejs.org/#Router-extend), but it doesn't work.

Here is an example where you can see it: http://jsbin.com/wevigoxuqa/1/edit?html,js,output
I expected that after click on link url will be as is: `my-page#anchor`, but I am getting `my-page`.

Related https://github.com/jashkenas/backbone/issues/2968

**Comment by elgervb** [comment]
+1

**Comment by luc-tielen** [comment]
Any update on this? 
Also running into this with routes containing for example `...?filter["key"]=true`

**Comment by prma85** [comment]
It is old, but I decided to put an answer here:
So, what happens is that you are using the getFragment, while the `#anchor` is a hash and the `my-page` is the fragment. To get what you need, you will do: `const my link = Backbone.history.location.pathname + Backbone.history.location.hash`
