### ISSUE TITLE
v1.3.2 backbone.js and backbone-min.js are not the same

### ISSUE THREAD

**Issue by sarkasm** [jashkenas/backbone#3993]
The minified version of 1.3.2 does not appear to include 
https://github.com/jashkenas/backbone/commit/1db79ddd33f65e4ca93beb3174496cf148baebe5
while the unminfied version does.

Unminified
```javascript
Events.once = function(name, callback, context) {
    // Map the event into a `{event: once}` object.
    var events = eventsApi(onceMap, {}, name, callback, _.bind(this.off, this));
    if (typeof name === 'string' && context == null) callback = void 0;
    return this.on(events, callback, context);
  };
```

Minified
```javascript
l.once=function(t,e,r){
  var n=f(p,{},t,e,i.bind(this.off,this));
  return this.on(n,e,r)
}
```

@jridgewell @megawac

**Comment by sarkasm** [comment]
I have verified that the tests around this fails when you replace backbone.js with backbone-min.js in the test.html

**Comment by jridgewell** [comment]
Sigh. @megawac, can you create a v1.3.3 PR since I can't seem to get it right?

**Comment by sarkasm** [comment]
I just offered up https://github.com/jashkenas/backbone/pull/3994
I considered changing the index.html file to use the minified version, but wasn't sure if everyone would build before testing.

**Comment by elgubenis** [comment]
will there be any marionette compatible minified backbone v1.3.x soon? none existing yet afaik

**Comment by megawac** [comment]
1.3.2 works with Marionette 2.4.5 @elgubenis

**Comment by sarkasm** [comment]
Actually, Mn 2.4.5 composite views have an issue with minified backbone 1.3.2, that's how I found this problem to begin with.  

CollectionViews bind via once
```this.once('render', this._initialEvents);```
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L25

Composite views, which extend CollectionView
have _initialEvents that start with   ``` if (this.collection) { ```
https://github.com/marionettejs/backbone.marionette/blob/master/src/composite-view.js#L23
at that point, the ```this``` context is lost (Due to the need for fix https://github.com/jashkenas/backbone/commit/1db79ddd33f65e4ca93beb3174496cf148baebe5 ), so this.collection is falsey and therefor it does not start listening for the collection events appropriately

So be careful if you are using CollectionViews of CompositeViews which have a collection set on them prior to rendering.

**Comment by megawac** [comment]
Okay, yeah we have to republish a version with an updated minified file but the `backbone.js` file on master should work with 2.4.5.
