### ISSUE TITLE
collections#parse is never called with backbone.js 1.3.2

### ISSUE THREAD

**Issue by Mamonaku** [jashkenas/backbone#3995]
Hello everyone,
I'm using latest backbone.js 1.3.2, and I can't manage to get parse() called when a collection.fetch() completes. Here's the code that reproduces the problem:

 ```
   var ABC =  Backbone.Model.extend({
        defaults: {
            avatartUrl: "whatever.jpg",
            location:"XYZ",
            phone:"12345678"
        },
        parse: function(data) {
            console.log("ABC Model is parsed");
            return data;
        }

    });

    var ABCCollection = Backbone.Collection.extend({

        initialize: function(){
            console.log("ABCCollection is initializing");
        },
        model: ABC,
        parse: function(data) {
            console.log("ABCCollection is parsed");
            return data;
        },
        reset:function(){
          console.log("complete "+ this.models);
        },
        error:function(e){
          console.log(e);
        },
        url: 'http://jsonplaceholder.typicode.com/users'
    });

var myabc = new ABCCollection();
myabc.fetch({reset: true,parse:true}};
```
neither Collection.parse() nor Model.parse() are called.

**Comment by Mamonaku** [comment]
mmm... sorry to reopen this one. As a consequence of calling myabc.fetch() without parameters, the 'reset' event isn't fired, so a Backbone.View doesn't react to Backbone.Collection new data. Or in other words, if a view contains the following code (say in initialize):

`this.collection.on('reset', this.addAll,this);`
with 
`this.collection = new ABCCollection();
this.collection.fetch()
`
then this.addAll is never called, and so the view never drawn.

Am I missing something?

**Comment by akre54** [comment]
Can you create a JSFiddle demonstrating the issue? It will help track this down.

**Comment by Mamonaku** [comment]
mmm... seems unlikely to work or help. JSfiddle doesn't log JS console. I've added the necessary HTML, you just need to save it to a file, and run it.

**Comment by akre54** [comment]
I can't help you without a reproducible test case. JSFiddle certainly does log to the console (here's [an example I found](http://jsfiddle.net/thomas/C9wew/4/) with 30 seconds of googling). Try CodePen or another one if you'd prefer those better.

**Comment by Mamonaku** [comment]
uh? you just have to copy paste the code above into an html page, and run it with the web inspector up,            
 a) myabc.fetch({reset: true}) then b) myabc.fetch();

In a) ABC.parse is not called.
in b) ABC.parse is called.

And JSFiddle doesn't log console message, i tried.

**Comment by jridgewell** [comment]
`#reset` (indirectly) calls `#set`, which does the parsing. Don't override `#reset` unless you know what you're doing.
