### ISSUE TITLE
self (or global) may be null and self.self will throw a exception

### ISSUE THREAD

**Issue by jerrydotlam** [jashkenas/backbone#3996]
`var root = (typeof self == 'object' && self.self === self && self) ||
            (typeof global == 'object' && global.global === global && global);`

so is it `typeof self == 'object' && self && self.self === self` right?

**Comment by akre54** [comment]
Under what circumstances would this occur?

**Comment by jerrydotlam** [comment]
when someone define a `self = null` before, hehe, maybe i think it too more.
