### ISSUE TITLE
Why I can't name my event as 'constructor'?

### ISSUE THREAD

**Issue by unclechu** [jashkenas/backbone#3999]
``` javascript
_.extend({}, Backbone.Events).on('constructor', function () {});
```

Throws exception:

``` text
TypeError: handlers.push is not a function
```

Is it a bug?
I can reproduce it in developer console on backbonejs.org site.

**Comment by Florian-R** [comment]
FWIW, this is not the same bug but somehow related to #1495, which was closed as wontfix.

**Comment by megawac** [comment]
This can be fixed by checking if the [`handler` is an array](https://github.com/jashkenas/backbone/blob/master/backbone.js#L206). 

```js
var handlers = _.isArray(events[name]) ? events[name] : (events[name] = []);
```

Thoughts @jridgewell @akre54

**Comment by akre54** [comment]
Eh. I think our short circuit pattern is fairly common in JS. The advice around edge cases in #1495 applies here too.

**Comment by jridgewell** [comment]
Can we just drop IE8 now? Hell, even IE8 can do a prototype-less object with [black magic](https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L225-L260).

**Comment by akre54** [comment]
What you got in mind? Object.create everywhere?

On Tue, Mar 29, 2016, 13:08 Justin Ridgewell <notifications@github.com>
wrote:

> Can we just drop IE8 now? Hell, even IE8 can do a prototype-less object
> with black magic
> <https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L225-L260>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jashkenas/backbone/issues/3999#issuecomment-203002167>
>
-- 

Adam K (mobile)

**Comment by mr47** [comment]
@jridgewell my god.

**Comment by megawac** [comment]
> Hell, even IE8 can do a prototype-less object with black magic.

You're not kidding, I'm pretty sure that `ActiveXObject` is literally a gate to hell

**Comment by akre54** [comment]
That's insane

On Tue, Mar 29, 2016, 13:30 Graeme Yeates <notifications@github.com> wrote:

> Hell, even IE8 can do a prototype-less object with black magic.
>
> You're not kidding, I'm pretty sure that ActiveXObject is literally a
> gate to hell
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jashkenas/backbone/issues/3999#issuecomment-203012863>
>
-- 

Adam K (mobile)
