### ISSUE TITLE
Backbone Security

### ISSUE THREAD

**Issue by KraytsMan** [jashkenas/backbone#4005]
Hi)
I'm offering you to write new module(Security module), which will be based on Backbone framework, but will be separated from it. For beginning will be enough  to provide Oauth2 realization of security.
Main features of this module will: easy to configure(just overwrite based class and include routers, models, collection, witch will be use this provider), provider will be created only once and manage token session(expired time of token), after succeed authorization this provider will be adding "Authorization" header with values witch it got after authorization, and of course provider have to provide "logout" function.
What you think about my idea?

**Comment by elgubenis** [comment]
cool idea, go ahead, backbone plugins are always welcome

**Comment by akre54** [comment]
Yup! Sounds like a great plugin. Looking forward to see it.
