### ISSUE TITLE
How can i use [] or new Array() for model properties ?

### ISSUE THREAD

**Issue by luki2678511** [jashkenas/backbone#4010]
I want use [] or new Array() for model properties, but different model will get single array.
just like:

    Defaulted = Backbone.Model.extend({
      defaults: {
          array: []
      }
    });
    model = new Defaulted();
    assert.equal(model.get('array').length, 0);
    model.get('array').push("obj1");
    model = new Defaulted();
    // array length is 1, this array is single, but i want a new array
    assert.equal(model.get('array').length, 0);

**Comment by rafde** [comment]
```
Defaulted = Backbone.Model.extend({
  defaults: function() {
      return {array: []};
  }
});
```
per http://backbonejs.org/#Model-defaults
> The defaults hash (or function)

Also, this isn't a forum. Try https://gitter.im/jashkenas/backbone next time

**Comment by jridgewell** [comment]
Thanks @rafde.
