### ISSUE TITLE
Backbone 1.3.3 have old underscore as dependency.

### ISSUE THREAD

**Issue by inferusvv** [jashkenas/backbone#4013]
When I am installing backbone 1.3.3 using npm it installs underscore 1.7.0 as dependency instead latest 1.8.3. In this reason I am getting error when trying to define view for example. (`_.create` is not a function)

**Comment by megawac** [comment]
That shouldn't be possible. Likely a problem with your local npm modules

https://github.com/jashkenas/backbone/blob/1.3.3/package.json#L16
