### ISSUE TITLE
colletcion.get(cid) is undefined

### ISSUE THREAD

**Issue by bbrui** [jashkenas/backbone#4015]
``// Model class for each Muppet item
var MuppetModel = Backbone.Model.extend({
  defaults: {
    id: null,
    name: null,
    occupation: null
  }
});

// Collection class for the Muppets list endpoint
var MuppetCollection = Backbone.Collection.extend({
  model: MuppetModel,
  url: '/muppets',

  parse: function(data) {
    return data.muppets;
  }
});

// View class for displaying each muppet list item
var MuppetsListItemView = Backbone.View.extend({
  tagName: 'li',
  className: 'muppet',
  template: _.template($('#muppet-item-tmpl').html()),

  initialize: function() {
    this.listenTo(this.model, 'destroy', this.remove)
	  this.listenTo(this.model, 'sync change', this.render);
  },

  render: function() {
    var html = this.template(this.model.toJSON());
    this.$el.html(html);
    return this;
  },

  events: {
    'click .remove': 'onRemove'
  },

  onRemove: function() {
    this.model.destroy({success: function(model, response) {
					
		},wait: true});

  }
});

// View class for rendering the list of all muppets
var MuppetsListView = Backbone.View.extend({
  el: '#muppets-app',
  _tempcId:"",
  initialize: function() {
    this.listenTo(this.collection, 'sync', this.render);
  },

  render: function() {
    var $list = this.$('ul.muppets-list').empty();

    this.collection.each(function(model) {
      var item = new MuppetsListItemView({model: model});
      $list.append(item.render().$el);
    }, this);

    return this;
  },

  events: {
    'click .create': 'onCreate'
  },

  onCreate: function() {
    var $name = this.$('#muppet-name');
    var $job = this.$('#muppet-job');
    if ($name.val()) {
			var  kermit = new MuppetModel();
			kermit.set({
        name: $name.val(),
        occupation: $job.val()
      });
		  this._tempcId=kermit.cid;
      this.collection.create(kermit,{wait: true});

                        
**			console.log("get cid model "+this._tempcId);
			console.log(this.collection);
			_.each(this.collection.models,  function(o){  
					console.log(o.cid);  
				}
			);**
                      
                       console.log(this.collection.get(this._tempcId));

			this.collection.fetch();
      $name.val('');
      $job.val('');
    }
  }
});

// Create a new list collection, a list view, and then fetch list data:
var muppetsList = new MuppetCollection();
var muppetsView = new MuppetsListView({collection: muppetsList});
muppetsList.fetch();``

# chomre debbuger out is:

> get cid model c14
> 
> > child{length:2,models:Array[2],_byId:Object,_listenId:"l2",_events:Object...}
>   modes:Array[3]
>     0:child
>         id:null
>         cid:"c4"
>         __proto_:Backbone.Model
>     1:child
>       cid:"c8"
>       id:null
>       __proto_:Backbone.Model
>     2:child 
> 	cid:"c14"
>         id:null
>         __proto_:Backbone.Model
> 
> c4
> c8

in the code ,use _each print this.collection.models.but write c4 18.don't print c14.

**_.each(this.collection.models,  function(o){  
                console.log(o.cid);  
            }
        );**

beasuce up probelm ,**this.collection.get('c14')** is undefine.but this.collection.models alread find  cid:'c14'..why??

**Comment by erosb** [comment]
`Collection.get()` accepts an `id` which is not the same as `cid` ( http://backbonejs.org/#Collection-get )

**Comment by bbrui** [comment]
getcollection.get(id) 
Get a model from a collection, specified by an id, a cid, or by passing in a model.

**Comment by bbrui** [comment]
get cid model c12
app.js:89 [child]0: child1: child_changing: false_events: Object_listenId: "l16"_listeners: Object_pending: false_previousAttributes: Objectattributes: Objectchanged: Objectcid: "c12"collection: childid: null__proto__: Backbone.Modellength: 2__proto__: Array[0]
app.js:90 undefined

**Comment by mr47** [comment]
@bbrui Can you provide a jsfiddle, and i think a problem that you don't set a model on collection creation
```js
var MyCollection = Bacbone.Collection.extend({
    model: MyModel
});
var col = new MyCollection();
col.add(new MyModel({test:123}))
```

I think it should help.

@erosb `Backbone.Collection.get` accepts an id or cid or model as param.

**Comment by bbrui** [comment]
i test @bbrui say,run is right.code is follow,but still have problem in issue i send.
var list=new MuppetCollection();
var entity=new MuppetModel({"id":100,"name":"test","occupation":"12121"});
list.add(entity);
console.log('121111111111111111111');
console.log(list.get(entity.cid).id);

**Comment by bbrui** [comment]
i find   this.collection.create(kermit,{wait: false}); to changethis.collection.create(kermit,{wait: false}); print this.colletcion is right ,but console.log(this.collection._byId[this._tempcId].id) is null.  the server don't response. i hope get id in time.

**Comment by mr47** [comment]
@bbrui for this kind of questions please use [stackoverflow](https://stackoverflow.com) or [gitter channel](https://gitter.im/jashkenas/backbone).

Thanks.
