### ISSUE TITLE
ESLint stuck on version 1.10.x

### ISSUE THREAD

**Issue by platinumazure** [jashkenas/backbone#4017]
ESLint is still on version 1.10.x. Would you like to upgrade?

Also, if you'll forgive the self-promotion, I've written an ESLint plugin [platinumazure/eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) which can help detect potentially bad patterns in QUnit tests. If you're interested, I can write a pull request showing how that could work. Obviously these are minor things when compared to end-user-facing bugfixes, enhancements, and features, but it's always useful to be able to enforce code quality automatically so that less time needs to be invested on quality per pull request.

I'm happy to write PRs for one or both of those as needed. Let me know.

**Comment by akre54** [comment]
Go for it, would be great to see a pull (separate pulls, please).

Thanks!

**Comment by platinumazure** [comment]
@akre54 Do you want the pulls not to be attached to this issue slash any issues, then, since you have closed this issue? (I'm used to writing commits that fix/close issues, but if Backbone operates differently that is totally fine, I'm just making sure)

**Comment by akre54** [comment]
We tend to use open issues as a way of saying an issue's resolution is undecided and we welcome further comment from the community (otherwise we'd have even more open issues that are stuck in some sort of limbo state).

In this case, the next step is known; it'd be great to open a pull request with some concrete changes we can actually comment on.

**Comment by platinumazure** [comment]
Can do! Do I ref this issue or just write the PR with no issue ref?

**Comment by akre54** [comment]
Yup, you can ref this issue for completeness sake.

**Comment by platinumazure** [comment]
Got it! I'll have some PRs in the next few days.

**Comment by akre54** [comment]
Awesome. Thanks

**Comment by captbaritone** [comment]
Thanks @platinumazure!

**Comment by platinumazure** [comment]
I said "in a few days" and obviously that was a lie, but I will get something up this weekend.
