### ISSUE TITLE
Reception over SPI using Processing Language on Raspberry-Pi

### ISSUE THREAD

**Issue by ANKITSHA** [jashkenas/backbone#4021]
I am trying to transmit and receive data through SPI using Processing language on Raspberry-Pi. I am able to transfer the messages but am not able to find the correct commands to execute the reception over it. I am also not able to find any documentation of example code available on the site. Please help with the issue.

**Comment by erosb** [comment]
are you sure you posted it in the right project?

**Comment by ANKITSHA** [comment]
Yes, I am sure. Do you have any idea how it works?

**Comment by akre54** [comment]
How did you come to the conclusion this is the right project to post in? Where did you see this link? We don't have anything to do with Raspberry Pi, but we receive a surprisingly large number of open issues from new users and people looking for other projects. Please, tell us!

**Comment by mr47** [comment]
@akre54 its, a spam bot, some kind of. (from git profile: Joined on 22 Apr 2016).
Maybe someone use aka github bots to get answer asap or randomly and use github public api to find projects with huge amount of stars. (Your co :smile: )

**Comment by akre54** [comment]
huh. really interesting. so like for those spammy google results? What a world.

**Comment by mr47** [comment]
Yep, people can't start spent more time to learn or sometimes to think. They write bots.

**Comment by adelgado** [comment]
I don't think it's a spam bot. The original poster ended up [posting the same question](https://github.com/processing/processing/issues/4429) on a repository where it seems to be on-topic.
