### ISSUE TITLE
How about the latest progress of Backbone?

### ISSUE THREAD

**Issue by victoryboss** [jashkenas/backbone#4022]
How about the latest progress of Backbone?

**Comment by jaapz** [comment]
Check out the [milestones](https://github.com/jashkenas/backbone/milestones)

**Comment by akre54** [comment]
We don't really use milestones for the most part, but take a look through the open issues to see where we're at. Any questions in particular should be directed to the gitter channel, the mailing list, or StackOverflow.

**Comment by victoryboss** [comment]
Thank you for your answer !
