### ISSUE TITLE
backbone.router  nomatch event

### ISSUE THREAD

**Issue by kospot** [jashkenas/backbone#4032]
why no event has been trigger, which is no matching route?

I want to do something when there is no matching route.

**Comment by jridgewell** [comment]
You can add the splat route as the final:

```js
routes: {
    "help":                 "help",
    "search/:query":        "search",
    "*nomatch": "nomatch"
  },
```

**Comment by kospot** [comment]
how does it work? i cant not find any key word about "nomatch" in the source

**Comment by amenadiel** [comment]
Splat is like a variable. You can name it whatever you like:

```js
"*anyname": "myfunction"

...

myfunction: function() {
  // Use arguments[] bc there can be any var inputs
}
```
