### ISSUE TITLE
Backbone doesn't suppress duplicate events

### ISSUE THREAD

**Issue by myklemykle** [jashkenas/backbone#4033]
Using Backbone.Event, if I bind the same handler to the same event with the same context N times, the handler will be run N times when I trigger the event one time.

At our company, this is never what we really want.  In fact, it's been the cause of many bugs.  If there's a universe in which that behavior is useful, I'd love to understand it.

In some of our codebase we solve that problem with this ugly pattern: 

```
dispatcher.off(event, function, ctx); // remove any/all handlers
dispatcher.on(event, function, ctx); // add one handler
```

... and in other parts of our codebase, I'm sure it remains un-solved.  Duplicate events creep in, silently.  At best we don't notice them, at worst they cause strange slowness & other behavior that's hard to debug.

In my dream world, Backbone.Event.on() would detect when I try to bind an event that is already bound to that function with that context, and silently do nothing.  

(Perhaps there's a bit more complexity to that for the corner-case of interleaving on() and once().)

**Comment by elgubenis** [comment]
Use this.listenTo so it gets destroyed automatically

**Comment by kospot** [comment]
when you call the remove method, it will stopListening which is on this.$el and this object. and the listenTo is bind event to the this, so you just call remove.

and if you have other event, you can rewrite the remove method like this:
```
var TestView = Backbone.View.extend({
     remove: function(){
            //do something you want
            Backbone.View.prototype.remove.apply(this);
     }
})
```

**Comment by hakuno** [comment]
Sometimes you may do thus

`dispatcher.off().on(event, function, ctx)`

So you've got a virgin target to begin with.

Of course, it has many other ways. It depends on what is being done really. If you repeat the constructor, if you render between views at this, whatever. If so, then you should call before:

`view.undelegateEvents()`

You don't need to rewrite anything. I manage +20 views (with subviews) called asynchronously.

**Comment by prantlf** [comment]
@myklemykle, how can it happen, that you register the same handler - the same callback twice? I work with fairly big project using Backbone and this has not been a problem.

    dispatcher.on(event, function, ctx);

The `function` is usually local in the object, which registers this handler. Unregistering usually happens in the same scope - in the same object. How could I register it twice, unless it was a clear bug, easily detected in the same module?

**Comment by jgonggrijp** [comment]
The solution is to not bind the same handler multiple times. This issue can only arise if you are binding the handler in the wrong place, i.e., a place that potentially runs multiple times. Bind handlers only in places where either the emitter or the listener is created, or first seen. Unbind handlers in places where either is destroyed (this happens automatically in many cases, as already mentioned in previous comments), or otherwise becomes no longer relevant.
