### ISSUE TITLE
Feature Suggestion: Backbone.Model.prototype.update

### ISSUE THREAD

**Issue by benmccormick** [jashkenas/backbone#4034]
A fairly common pattern I find myself typing when working with Backbone models involves code like this:

```
//iterating
model.set('totalCount', model.get('totalCount') + 1);
model.set('team1Count', model.get('team1Count') + 1);

//updating a max
model.set('maximum', _.max([model.get('maximum'), newValue]));

//updating according to an algorithm

let cost = model.get('cost');
if (!_.isFinite(cost)) {
  //if we haven't calculated the cost yet, do so now
  cost = calculateCost(model);  
} 
model.set('cost', applyCouponCode(cost, couponCode));
```

There's nothing wrong with these examples, but I find myself writing these "get-modify-set" chunks of code a lot.  I think this experience could pretty easily be made nicer.  I'm picturing an `update` method on model that would make the above examples look like this.

```
//iterating
model.update(['totalCount', "team1Count"], count => count + 1);

//updating a max
model.update('maximum', max => _.max([max, newValue]));

//updating according to an algorithm

model.update('cost', function (cost, key, _model) {
  if (!_.isFinite(cost)) {
    //if we haven't calculated the cost yet, do so now
    cost = calculateCost(_model);  
  } 
  return applyCouponCode(cost, couponCode)
});
```

The update function would likely take 3 options: `attrs`, `transform`, `options`. 

`attrs`- an attribute name or array of attribute names to apply the transform to
`transform` - a function (defaults to _.identity) that will be passed 3 arguments `value`, `key`, `model` and will return the new value for each attribute it is run against
`options` - these would be options that would be passed through to the underlying set call that would result from the update

I'm opening this issue basically to gauge interest in having a function like this as part of Backbone core and to receive feedback.  If there is interest I'd be happy to open a PR to explore further.

**Comment by Florian-R** [comment]
Like this idea. Another approach could be to allow Model#set to accept this signature, but maybe it's overcomplicating its API too much.

**Comment by erosb** [comment]
+1 for this, and probably better to imlement in a separate method instead of modifying set()

**Comment by akre54** [comment]
> Another approach could be to allow Model#set to accept this signature

What'd you have in mind?

**Comment by akre54** [comment]
👍  on this idea. Reminds me of ImmutableJS's [`update`](https://facebook.github.io/immutable-js/docs/#/Map/update).

**Comment by Florian-R** [comment]
> What'd you have in mind?

Add a new signature for set like

```js
model.set('foo', myFunc)
```
but with some afterthoughts, I agree with @erosb that a separate method is better.

**Comment by benmccormick** [comment]
I considered suggesting a set modification.  But `model.set('foo', myFunc)` isn't a workable API because its currently valid syntax for `model.attribute.foo = myFunc`.  Also a new method keeps each individual method simple and clear, which I feel is more "Backbone-y".

**Comment by benmccormick** [comment]
I think this can be a pretty small change, the heavy lifting for eventing stuff can still be done by set.  This can just look something like

```

update: function(attrs, transform, options) {
    attrs = _.flatten([attrs]);
    transform = _.isFunction(transform) || _.identity;
    var attrsToSet = _.reduce(attrs, function(setObj, attribute) {
        var value = this.get(attribute);
        setObj[attribute] = transform(value, attribute, this)];
    }.bind(this), {});
    this.set(attrsToSet, options);
}
```

**Comment by jashkenas** [comment]
It's an interesting idea — but I'm not a big fan of this proposed method for a couple of reasons: 

* You enter into a new function context when you don't need to — all you gain from it is being passed in the value of something you just as easily could have accessed from outside.

* The only bit of data given to you within the function is the current value of the thing you're changing. Usually you need more information than that to make an update.

Let's take your third example as the example:
```
model.update('cost', function (cost, key, _model) {
  if (!_.isFinite(cost)) {
    //if we haven't calculated the cost yet, do so now
    cost = calculateCost(_model);  
  } 
  return applyCouponCode(cost, couponCode)
});
```

You could just do this, and it would be clearer:

```
var cost = model.get('cost');
var newCost = _.isFinite(cost) ? applyCouponCode(cost, coupon) : calculateCost(model);
model.set('cost', newCost);
```

**Comment by benmccormick** [comment]
Hey @jashkenas, thanks for taking the time to give feedback!  

I didn't quite understand a few of your criticisms here:

> The only bit of data given to you within the function is the current value of the thing you're changing. Usually you need more information than that to make an update.

My proposed change involved passing 3 arguments into the function: the currentValue of an attribute, the attribute key, and the model.  That should be sufficient context to do most updates I think?  

> You could just do this, and it would be clearer:

So, I think the simplicity of my example may have hurt me here.  I was trying to portray that you sometimes want to have encapsulated, complex business logic for an update.  So while I agree that 

```
var cost = model.get('cost');
var newCost = applyCouponCode((_.isFinite(cost) ? cost : calculateCost(model)), coupon);
model.set('cost', newCost);
```

is comparable or cleaner than this (I modified the examples slightly to be more 1-1 with the same logic, both inlined to one line)

```
model.update('cost', cost => {
   return applyCouponCode((_.isFinite(cost) ? cost : calculateCost(model)), coupon));
});
```

I was really thinking more of the cases where the logic for updating looks something like 

```
export const updateCost = currentCost  => {
    //get starting cost
    let newCost = (_.isFinite(cost) ? cost : calculateCost(model);
    //apply any coupons
    let coupon = getCouponUsed();
    newCost = applyCouponCode(newCost, coupon);
    //apply taxes
    let region = getCustomersRegion();
    newCost = addTaxes(newCost, region);
    // apply shipping costs
    let address = getCustomersAddress();
    newCost = addShippingCost(newCost, address);

    //maybe more business logic here (basically this is a big scary, business logic function that gets its own file
    return newCost;
}
```

where this logic and its helper functions are in a separate file.  Then when we import the function

```
model.update('cost', updateCost);
```

is cleaner than

```
var cost = model.get('cost');
var newCost = updateCost(cost);
model.set('cost', newCost);
```

Basically the benefit of this over get is it makes it easy to provide a transform function to an existing value, and possibly several existing values.  I know that not all logic will be implemented as a function, and I'm not suggesting that this should replace `get`.  

But for those of us who habitually put complex logic into named functions (I don't think I'm alone?), this is an opportunity to turn 3 lines into 1 in multiple places (and x lines into 1 for applying the same transform to multiple properties).   It's a more functional style than Backbone normally gets into, but I think it certainly feels at home next to the underscore/lodash style functions that Backbone devs often use.


> To elaborate — in general, we should provide a fancy API where you can drop into a function context and do some work where there's a real gain. 

Could you explain what you think this would look like?  My first reading was that you didn't see the use case for this function, whereas this last comment read to me more like you think there's a valid use case but don't think my API design is the best (something I'm completely open to).  Any suggestions on how this could be simplified or clarified to meet the need?

**Comment by jashkenas** [comment]
To respond quickly — I don't have a better API design for this particular case. I think that `get` and `set` are fine as atomic operations that you combine as you see fit.

For your example — having an external helper function exported is a little ugly! Updating the cost is a concern of the model. Put it on the model! A more object-oriented version might look something like:

```javascript
updateCost: function() {
  var cost = this.get('cost');
  if (!_.isFinite(cost)) cost = this.calculateCost();
  cost = this.coupon.applyTo(cost);
  cost = this.addTaxes(cost, this.customer.get('region'));
  cost = this.addShipping(cost, this.customer.get('address'));
  this.set('cost', cost);
  // Although to be fair, this is such a different number that you should ...
  // really be storing it in a different slot.
}
```

**Comment by benmccormick** [comment]
Gah, fair enough to "should be on the model" point.  This is what I get for making up examples :) . I can try and find some real world examples that were behind my original inspiration for this.  I think most fall into the more "quick update" case, like incrementing.  

To be perfectly honest, I'm working less with Backbone these days, which is why I didn't push this through to a PR myself to begin with, and why I'm not totally on top of which real world examples originally drove this for me, so I'm not going to fight this one :) I see value in this, but I also understand the desire to avoid API bloat.
