### ISSUE TITLE
Repository has modified files immediately after cloning it

### ISSUE THREAD

**Issue by longlivelance** [jashkenas/backbone#4044]
It looks like someone submitted something that is confusing this repository. If you clone the repository, it will clone with modified files in it. You cannot checkout tags, or do anything with the repository. This is breaking continuous integration that is using this repository. 

This commit is causing git to modify these files on clone. https://github.com/jashkenas/backbone/commit/1bb06dba0668fdfdfc11dfcfa21224075c23f7f0

Can someone please fix this so that people can clone this repository correctly again? Or suggest how one might go about getting this to work with their system?

**Comment by akre54** [comment]
Yep. We are tracking it in #4036 and #4042. Thanks for reporting.
