### ISSUE TITLE
ie10 & safari backbone's router not normal work, when i refresh page in browser

### ISSUE THREAD

**Issue by timestrom** [jashkenas/backbone#4056]
first request page,router has work; i refresh page ,it router's routes has not work;
ex: 
http:/xxx/index.html#sc
routes:"sc" : 'simulationComb',
this is function (simulationComb) has not work;
-----
why not normal work?

**Comment by akre54** [comment]
Please use StackOverflow for questions. Github issues are for maintaining the framework only.
