### ISSUE TITLE
Object returned by changedAttributes is missing object methods.

### ISSUE THREAD

**Issue by malisbad** [jashkenas/backbone#4057]
When I call `model.changedAttributes()`, the object that is returned lacks typical object methods such as `hasOwnProperty`.

`typeof` returns the type `object`, the inspector recognizes it as an object and parses it correctly.

**Comment by akre54** [comment]
Not sure what you mean? This is [the code from `changedAttributes`](https://github.com/jashkenas/backbone/blob/760ad49d1c9113f5a7b33831056c2ff6bbd78d5a/backbone.js#L560-L578), it is just a plain object.

**Comment by malisbad** [comment]
The object seems to have no prototype.

I might need to close this issue though because I just checked and the way the function works is different in exoskeleton.js and...that's what I'm looking at.

**Comment by akre54** [comment]
Ah yeah. In Exoskeleton, the object is created without a prototype. Feel
free to open an issue there if you have any problems (I'm one of the
maintainers there)

On Thu, Jul 7, 2016, 18:25 Matt Williams <notifications@github.com> wrote:

> Closed #4057 <https://github.com/jashkenas/backbone/issues/4057>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jashkenas/backbone/issues/4057#event-716380186>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA42KBw6hHznNHwISFWOPL9YwcefarRfks5qTXzGgaJpZM4JGYrK>
> .
>
-- 

Adam K (mobile)
