### ISSUE TITLE
Feature suggestion: Ability to transform model attributes before saving

### ISSUE THREAD

**Issue by captbaritone** [jashkenas/backbone#4058]
It would be nice to have an analogous method to `.parse()` that, when I call `.save()` is used to transforms a model's attributes into the form expected by my server.

For the case where I have an API response that represents data differently than I would like it represented in my model, I can implement a `.parse()` method to translate the API response into reasonable model attributes. However, when I want to persist that data back to the server, I don't currently see any reasonable way to translate it _back_ into the schema that the server expects.

The only options I currently see is to implement my own `.toJSON()` method. This would work, but `.toJSON()` is already used in marionette for passing model attributes to the template and the object I want to send to the server, is not the same as the object I would like in my template.

A more involved solution would be to create my own `.sync()` method, but that feels like overkill for something that _seems_ to me like a common need.

Is there some other way of achieving this goal? Is the fact that I need to transform my attributes in order to persist them unusual or an indicator of some other anti-pattern?

`.parse()`:`.fetch()`::`.proposedMethod()`:`.save()`

**Comment by jridgewell** [comment]
`#toJSON` is for this exact use case. If I remember correctly, Marionette stopped using it when rendering. Ping @samccone

**Comment by captbaritone** [comment]
It looks to me like they are still using it: https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L40

**Comment by jridgewell** [comment]
:rage1:

**Comment by samccone** [comment]
This was the initial step:
https://github.com/marionettejs/backbone.marionette/pull/1600

The goal was in v3 to drop the direct use of toJSON (since it is a breaking change)

I have stopped working on the Marionette project but.. @jridgewell is correct as this was the intent.

**Comment by rafde** [comment]
@captbaritone https://github.com/marionettejs/backbone.marionette/blob/next/src/view.js#L75 will be the new implementation for Marionette V3

**Comment by captbaritone** [comment]
Closing. Sounds like the right thing to do is use `.toJSON()` and wait for the new version of Marionette to come out.
