### ISSUE TITLE
collection.fetch().abort()?

### ISSUE THREAD

**Issue by luqingxuan** [jashkenas/backbone#4062]
with jquery-1.8.x, collection.fetch() call $.ajax and return xhr object ,it has method abort,
but jquery-1.11.x , $.ajax return promise object , no abort method with this object,
so what can i do to cancel this request

**Comment by rafde** [comment]
not sure where you got that impressing, but http://api.jquery.com/jQuery.ajax/#jqXHR shows `.abort` as part of a list of functions available. What jquery returns is a modified version of their promise.

**Comment by jridgewell** [comment]
Agreed, this is a jQuery issue.

**Comment by jfbrennan** [comment]
Apparently `abort` has been removed from jqXHR/Deferred in version 3: http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/

**Comment by paulfalgout** [comment]
In jQuery v3 `console.log($.get('/echo').abort)` returns the `abort` function so I think it is still there.

**Comment by rafde** [comment]
@jfbrennan https://github.com/jquery/jquery/blob/731c501155ef139f53029c0e58409b80f0af3a0c/src/ajax.js#L512 still there.

**Comment by jfbrennan** [comment]
Sorry for the confusion. That jQuery blog post makes it sound like all non-standard Promise methods are removed from jqXHR in jQuery 3. There's a few Stackoverflows about this with one that has 1,443 up votes and it says `abort` was removed. And I thought consensus always equals the truth ;)
