### ISSUE TITLE
The ES6 `super` keyword is unintuitively limited (Backbone example)

### ISSUE THREAD

**Issue by trusktr** [jashkenas/backbone#4063]
The following simply fails, even if the following `SomeBackboneClass` contains the `someMethod` method:

```js
SomeBackboneClass.extend({
  someMethod() {
    super.someMethod() // will look for `super.someMethod` on Object.prototype, unintuitively!
  }
})
```

More details at https://www.reddit.com/r/javascript/comments/4vuctx/why_the_es6_super_keyword_stinks/.

I believe a dynamic `super` (like `this` is) would be [much better](https://esdiscuss.org/topic/the-super-keyword-doesnt-work-as-it-should).

It would be appreciated if anyone interested will post their replies and thoughts. :]

**Comment by jashkenas** [comment]
That may very well be the case, but we're not in control of ES6's `super`.
