### ISSUE TITLE
As of 1.3.0-1.3.3, you can no longer bind "change" events to be notified when any model in the collection has been modified.

### ISSUE THREAD

**Issue by andrewkfiedler** [jashkenas/backbone#4064]
Here is a CodePen demonstrating the old behavior: http://codepen.io/andrewkfiedler/pen/ZOmXON?editors=0010
Here is a CodePen demonstrating the new behavior: http://codepen.io/andrewkfiedler/pen/BzGwwV?editors=0010

```
(function() {
  MyCodePen = {
    data: {
      books: [{
        author: "Barry Eisler",
        title: "A Clean Kill in Tokyo"
      }]
    }
  };
})();
var Book = Backbone.Model.extend({
  defaults: {
      author: "",
      title: ""
  }
});
var Books = Backbone.Collection.extend({
  model: Book,
  initialize: function(){
    this.listenTo(this, 'change:author', function(){
      alert('author changed');
    })
  }
});
var myBooks = new Books(MyCodePen.data.books);
myBooks.first().set('author', 'test');
```
In previous versions of Backbone, an alert would pop up (as seen in the codepen).  However, updating to the latest Backbone (1.30 and above) causes no alert to pop up.

Based on the documentation (http://backbonejs.org/#Collection), it appears to be a bug.

**Comment by craigmichaelmartin** [comment]
The codepen with the new behavior references a non-existent backbone source file. When the backbone url is updated to 1.3.3 and underscore to 1.8.3, it works.

**Comment by andrewkfiedler** [comment]
Updated the codepen and it works.  Thanks for your help!
