### ISSUE TITLE
How about automatic commit message style validation?

### ISSUE THREAD

**Issue by all3fox** [jashkenas/backbone#4065]
If you look at commit history of projects like [agnuar.js](https://github.com/angular/angular.js/commits/master) or [jquery](https://github.com/jquery/jquery/commits/master), you will notice that they use a consistent commit message style. Would you perhaps like to do the same?

One way to support a single commit message style is to have git perform the check via a hook, like so:

![record_ember](https://cloud.githubusercontent.com/assets/962850/17145358/ddf91c8e-536a-11e6-8087-03e36cb05811.gif)

The process shown above is done via an npm module `commitplease` ([npm][1], [github][2]). It checks your commit message and tells you if it is a poor one (long lines, bad first line and so on). Commitplease is used by  jQuery Core, jQuery UI, jQuery Mobile, Globalize, QUnit and others. It is as simple as

`npm install commitplease --save-dev`

If you are interested, let me know what you think. Disclaimer: I help develop commitplease.

[1]: https://www.npmjs.com/package/commitplease
[2]: https://github.com/jzaefferer/commitplease

**Comment by akre54** [comment]
This seems like a lot of overhead for little gain. A good chunk of our pull requests come from developers new to Git / Github. I don't think we want to add yet another barrier to entry.
