### ISSUE TITLE
How to stop listening and resuming listening for event X when using different objects?

### ISSUE THREAD

**Issue by binarykitchen** [jashkenas/backbone#4069]
That's a tricky questions I am stuck with in my app. Let me get straight to the example:

```js
        objectA.listenTo(submitButtonField, 'click:field', function(e) {
            // code here still gets executed but I don't want to
        })        

        objectB.listenTo(submitButtonField, 'click:field', function(e) {
            objectB.stopListening(submitButtonField, 'click:field')
        })        
```

You see, I have two different objects (in my app in different controllers/namespaces) but both having the same reference to the same button field and both listening to the click event.

Object B does stop listening and I want this to stop object A from listening to these click event as well. But no, object A still listens to them.

Any trick how I can do this? To tell everyone to stop to listen? (also will need the capability to resume listening for all objects)

**Comment by binarykitchen** [comment]
Also, would be cool to have something like `e.preventDefault()` to stop propagating the event to other objects.

**Comment by akre54** [comment]
Unfortunately there's no way to selectively ignore events in Backbone. You can try passing a "flag" in one of your arguments to tell the event listener to selectively ignore an event, or use a "proxy" object to do bookkeeping between your listeners.

Keep in mind also that event listeners are called in the order they were bound. So your objectA listener will always be called before your objectB listener.

**Comment by binarykitchen** [comment]
@akre54 ugh, this makes it very difficult to have a plugin for example run some code before submission within the backbone framework :/

**Comment by akre54** [comment]
Right, but Backbone events don't bubble in the same way DOM events do so there's less of a need to "stop propagation". Even there, binding order matters.

What did you have in mind for a submission plugin? I think setting up your own control flow for submitting is much easier to manage and reason about than opaquely trying to manage which events are called and when.

**Comment by binarykitchen** [comment]
right, that i know - i think someone else helped me and came with a good solution, see https://github.com/wpninjas/ninja-forms/issues/1633 ... but thanks anway for your assistance so far
