### ISSUE TITLE
Backbone not attached to global in node environment

### ISSUE THREAD

**Issue by vsnikkil** [jashkenas/backbone#4072]
backbone.js:27 has:
<code>factory(root, exports, _, $);</code>

Should it be:
<code>var root.Backbone = factory(root, exports, _, $);</code>

Couldn't get it work otherwise.

**Comment by elgubenis** [comment]
Have you tried: global.Backbone = requiere('backbone'); yet?

**Comment by elgubenis** [comment]
I meant require, cannot edit on mobile, sorry.

**Comment by vsnikkil** [comment]
Yes, but it backbone.js doesn't return anything:

This is the function that gets executed on module require. There is no module.exports or anything on case of node. But I guess quick fix would be just to assign backbone to global (<code>root.Backbone = </code>) because some extensions assume Backbone global variable?
<code>
   8 function(factory) {
   9 
  10   // Establish the root object, `window` (`self`) in the browser, or `global` on the server.
  11   // We use `self` instead of `window` for `WebWorker` support.
  12   var root = (typeof self == 'object' && self.self === self && self) ||
  13             (typeof global == 'object' && global.global === global && global);
  14 
  15   // Set up Backbone appropriately for the environment. Start with AMD.
  16   if (typeof define === 'function' && define.amd) {
  17     define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
  18       // Export global even in AMD case in case this script is loaded with
  19       // others that may still expect a global Backbone.
  20       root.Backbone = factory(root, exports, _, $);
  21     });
  22 
  23   // Next for Node.js or CommonJS. jQuery may not be needed as a module.
  24   } else if (typeof exports !== 'undefined') {
  25     var _ = require('underscore'), $;
  26     try { $ = require('jquery'); } catch (e) {}
  27     factory(root, exports, _, $);
  28 
  29   // Finally, as a browser global.
  30   } else {
  31     root.Backbone = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));
  32   }
  33 
  34 })
</code>

**Comment by akre54** [comment]
Backbone works fine in commonJS (node require). The `typeof exports !== 'undefined'` path is specifically for CommonJS.

Please try StackOverflow for help debugging.
