### ISSUE TITLE
Model id not indexed in _byId when Collection.model is a constructor

### ISSUE THREAD

**Issue by ronaldak** [jashkenas/backbone#4073]
The `model` attribute of a `Collection` can be either a model class or a constructor (function), as per http://backbonejs.org/#Collection-model.

A collection obtains the identifier of a model using `modelId`, as below:

```modelId: function(attrs) {
    return attrs[this.model.prototype.idAttribute || 'id'];
},```

If `model` is a function, then the above reference to `this.model.prototype.idAttribute` is invalid. The effect of defining a function for the `model` attribute is that `Collection.get()` no longer works as expected because model identifiers are not retrieved and stored in `Collection._byId`.

(Including @Pleochism for updates on this issue.)

**Comment by craigmichaelmartin** [comment]
Hm? If the model attribute is a factory function, `this.model.prototype.idAttribute` will be `undefined` and `id` will be used, and all is fine (assuming `idAttribute` is `id`). If the polymorphic models use something other than `id` as the `idAttribute`, than you must override `modelId`. The tests have examples of both: https://github.com/jashkenas/backbone/blob/master/test/collection.js#L1730-L1759

**Comment by ronaldak** [comment]
Thanks for the clarification! In hindsight, I see that the docs allude to this (and, indeed, our models utilise `_id` as the `idAttribute`).

Perhaps the doc entry for Collection.model can include a note, pointing one to the modelId entry, to highlight this possible situation?

**Comment by craigmichaelmartin** [comment]
There is a note but it is in the modelId docs. It would be up to the maintainers, but I agree a reference in Collection.model where it addresses using a factory method would be helpful:

```diff
A collection can also contain polymorphic models by overriding this
property with a constructor that returns a model.  
+ If your collection uses a model factory and those models have an idAttribute 
+ other than id you must override <a href="#Collection-modelId"><tt>modelId</tt></a>
```

**Comment by akre54** [comment]
Sure, open a pull :)
