### ISSUE TITLE
when will the var changing be true at line527

### ISSUE THREAD

**Issue by tylerxue** [jashkenas/backbone#4076]
This could be a naive issue as I'm not quite good at JavaScript and backbone.

I changed the the line527 as below, and play with it for a while, and never throw the exception.
`            if (changing) { throw "the changing is changed, WOW . . . I thought this ex won't be trigerred anyway"; return this; }
`

the variable 'changing' won't be true at line527 unless we assign true to it. there is just one assignment in the set function at line 490:
`      var changing   = this._changing;
      this._changing = true;`

but the this._changing is always false unless we assign true to it, i can see it's assigned to true at line 491, but it's assigned to false again at line536:
`      this._changing = false;`

there is one way to skip this asssignment, that's to return at line527:
`    if (changing) return this;`

unforturnetly, the changing is always set to false at the beginning. 

this looks like a evil loop. 

and I went through the whole file and only found another place where use the variable _changing at line566 function changedAttributes, but it's just an read operation so won't have an impact on its' value. 

Thanks

**Comment by akre54** [comment]
This is meant for nested change operations.

In the future please use the mailing list or StackOverflow for questions. Github issues are for maintaining the framework only.
