### ISSUE TITLE
Modularize Backbone

### ISSUE THREAD

**Issue by clozr** [jashkenas/backbone#4081]
Can we modularize backbone so that we can pick only 'model' and 'collection' leaving 'views', 'history' etc. out?
For example, if we want to use backbone.js base projects in react-native, it would make life much easier, to leave views and history and hence all subsequent dependencies such as jquery.

**Comment by jashkenas** [comment]
Nope. Just use backbone.js, and use Model and use Collection — and don't use View. Done.
