### ISSUE TITLE
JQuery not present as a dependency in package.json / bower.json

### ISSUE THREAD

**Issue by gabriellupu** [jashkenas/backbone#4082]
Installing backbone as a dependency trough npm, doesn't raise any warning about the fact that requires a peer dependency or directly installing it.
Would be nice to have jquery as a peerDependency or dependency in package.json / bower.json files.

**Comment by akre54** [comment]
jQuery is an optional dependency of Backbone. You don't need it to build a Backbone app.

If your app uses jQuery, you need to depend on it explicitly. Expose it to Backbone through a script tag or your build tool and Backbone will automatically pick it up.

**Comment by gabriellupu** [comment]
Thanks for the feedback @akre54
