### ISSUE TITLE
If someone adds an Array.prototype.unset method, things break.

### ISSUE THREAD

**Issue by sirugh** [jashkenas/backbone#4086]
We just spent some time tracking down a bug on a site where some of our third-party javascript wasn't working properly. Specifically, when creating a Backbone Model object and passing some attributes to inherit, the attributes never ended up on the object.

After investigation, we found that the site owner was extending the `Array.prototype` with an `unset` function:

[![https://gyazo.com/324f11d004d78c0f17f1c410776ff0a6](https://i.gyazo.com/324f11d004d78c0f17f1c410776ff0a6.png)](https://gyazo.com/324f11d004d78c0f17f1c410776ff0a6)

The `set` function takes [options](https://github.com/jashkenas/backbone/blob/master/backbone.js#L469) that can contain an `unset` [property](https://github.com/jashkenas/backbone/blob/master/backbone.js#L487). In our code, we happen to be passing an array of objects as the `options` parameter. Whether this is supported by Backbone or not, I'm unsure, but I think we have wrapped `Backbone.Model` in something that can consume those options downstream.

And obviously the most immediate answer is "stop extending built-ins". But since us third-party-javascripters rarely have a say in the environment in which our code runs, I figured it was worth it to open an issue.

Anyways, here's a [jsbin](https://jsbin.com/camuyijoza/1/edit?html,js,console) where you can see the problem.

Hopefully this helps somebody :)

**Comment by akre54** [comment]
It's typically never a good idea to modify objects you didn't create in Javascript. But as you said you don't always have control if your app is running in someone else's environment. Lord knows I've had to employ some pretty crazy defensive code to counter the horrific hacks javascript developers put on their site.

Thanks for reporting. Closing.
