### ISSUE TITLE
"update" event on collection reset

### ISSUE THREAD

**Issue by kilemensi** [jashkenas/backbone#4087]
From the docs

`
"update" (collection, options) — single event triggered after any number of models have been added or removed from a collection
`

I would expect the `update` event to be fired whenever a collection is reset (in addition to the `reset` specific event) since `update` event is independent of how models were added/removed from the collection.

**Comment by jashkenas** [comment]
Nope — `reset` is a special function and special event that allows you to optimize large changes to the contents of your collection. If we also fired an `update`, your code would have to be very careful to make sure that you're not doing double-work.
