### ISSUE TITLE
how to Replacing "#" Routes  Using Backbone.js

### ISSUE THREAD

**Issue by cybibo** [jashkenas/backbone#4090]
E.g:
in router.js
`routes: {
            "": "home",
            "first": "first"
        },
.....`

in page:

`<a href="#">home</a>
<a href="#first">link first page</a>`

in brower URL:www.domain.com/#first;
but i want to get 
URL:www.domain.com/first;
 in brower  Address Bar.
how to replacing "#" in routes. 

thanks!

**Comment by akre54** [comment]
You'll want to start `Backbone.history` with [`{pushState: true}`](http://backbonejs.org/#History-start).

In the future, please use StackOverflow for questions like this.
