### ISSUE TITLE
Collection update issue

### ISSUE THREAD

**Issue by AntonioPrimera** [jashkenas/backbone#4093]
Hello,

I have come across an issue when fetching a collection. This appears in a certain scenario, as described below. I must say that I am not very experienced in JS, but I think I managed to track the location of the issue.

Scenario:
1. I fetch 3 objects from the server - everything OK
2. I fetch 0 objects from the server - everything OK
3. I fetch again 3 objects from the server - everything OK
4. I fetch 1 of the 3 objects from the server - here I discovered the bug

At this point in time the list contains 3 objects:
cid: c16 - id: 57
cid: c17 - id: AA
cid: c18 - id: AD
A new object is added:
cid: 25 - id: 57

In the _byId object cache one entry for cid 25 is added (as the one by Id already exists).

Then the collection attempts to remove the previous 3 objects from the list, so it should remove objects with keys: c16, c17, c18, AA, AD and 57 (this last one I am not sure, because the newly added object has the id 57).

In method _removeModels, when calling:
`var model = this.get(models[i]);`
models[i] is the object with cid c16, but the result of this get function is the object with cid 25 (the newly added object), so the c16 object remains in the list and the newly added object is removed.

The visible side-effect of this bug (how I stumbled on it) is that after such ghost entries remain, when I fetch an empty collection from the server, these ghost objects remain in the collection.

Here's a printscreen of the debug session where I think that the issue lies.
<img width="1016" alt="screen shot 2016-10-28 at 23 57 10" src="https://cloud.githubusercontent.com/assets/23128666/19822970/e1923d0a-9d6e-11e6-8171-6c8c6a5d65ac.png">

I don't really know how to solve this, but I guess a better mechanism in the "get" method would fix it.

**Comment by rafde** [comment]
can you provide a jsfiddle/codepen/choice code sharer or this issue?
It's difficult to know the exact issue without display the exact scenario that caused the issue.

**Comment by AntonioPrimera** [comment]
I am using Backbone Marionette to enhance an application I am creating, but everything is still on my local machine, so I can not provide the data source.

I am setting up a page with a search input. When you enter something in your search input, it fetches from the server all users which match that search term and displays them in a table. Everything is set up and working - the users are fetched correctly in the beginning and when searching for some specific users.

I have created this JSFilldle with the JS code from Marionette, which returns the view: https://jsfiddle.net/ojyhjn71/1/

**Comment by rafde** [comment]
OK. I realized the issue. You expect all your fetches to clear out the collection. what you are looking to do is
http://backbonejs.org/#Collection-fetch
collection.fetch({reset: true}) will reset the collection and display what you got back.

Next time, try to ask this question in https://gitter.im/jashkenas/backbone
it's a channel where others can help. Issues are mostly for bugs, not support.

**Comment by AntonioPrimera** [comment]
Thank you and sorry about the issue. I really looked into it, thinking it was a bug in Backbone merging the new result in.
