### ISSUE TITLE
Promise as argument of Collection add, remove, reset, set methods

### ISSUE THREAD

**Issue by redexp** [jashkenas/backbone#4096]
What would you say if add ability to pass to Collection methods not only plain objects, arrays and models, but also promise. Just add code like this to each method
```javascript
add: function(models, options) {
  //...
  if (typeof models.then === 'function') {
    var self = this;
    return models.then(function (models) {
      return self.set(models, options);
    });
  }
  //..
}
```
and so we can do
```javascript
users.add($.get('/users'));
```
very useful if you decided to change some of your methods from sync to async like
```javascript
User = Model.extend({
  getProducts: function () {
    // was
    return products.where({user_id: this.get('id')});
    // become
    return $.get('/products', {user_id: this.get('id')});
  }
});

// but code same for sync and async
bag.add(user.getProducts());
```

**Comment by akre54** [comment]
How about `user.getProducts().then(products => bag.add(products))`?

I think if we're going to add Promises to Backbone we should do so holistically (like #3729, #3651), not in fits and starts.
