### ISSUE TITLE
model.fetch

### ISSUE THREAD

**Issue by shawnemullen** [jashkenas/backbone#4098]
This is not new but I thought I would re-raise it.  There needs to be a way to use model.fetch to fetch only what is on the server.  The fact it merges with what the client already has (actually this isn't really true), is a big problem.  When I do a fetch, I expect the model returned to be the model fetched.

If anyone has a work around I'd like to hear it.

**Comment by elgubenis** [comment]
but thats pretty useful to keep local state moving throughout your app, at least in some of my apps thats useful, i've already seen other examples using it this way, as i understand the idea is to move models or collections of models, forwards and backwards through your views and routers (with Backbone.Radio or window(global)) you could implement a fetch method yourself which clears the model before fetching
```js
clearFetch() {
this.clear();
return this.fetch();
}
```

```md
*clearmodel.clear([options])*
Removes all attributes from the model, including the id attribute. Fires a "change" event unless silent is passed as an option.
```

keep this in mind, the idAttribute (default: id) will be removed also, so if you would like to keep that "link" just preserve it before the .clear and .set it after the .clear

**Comment by alundiak** [comment]
@shawnemullen this can be closed right?

cc/ @jashkenas

**Comment by jgonggrijp** [comment]
I'm assuming that the question has been answered. @shawnemullen feel free to reopen if you feel otherwise.
