### ISSUE TITLE
Call Model.parse on every page load, not just the first

### ISSUE THREAD

**Issue by RichardJECooke** [jashkenas/backbone#4105]
We overrode model.parse() to sanitise (escape) our HTML from the server before displaying it on the browser.

**But why does Backbone call model.parse only the first time the page loads?**  I've looked at our code and nothing else is overriding our parse method, and nothing is caching the data.  What is happening?

Here's the code:
```javascript
  Backbone.Model.prototype.parse = function(resp, options) {
    return escapeStringsRecursively(resp);
  }

  function escapeStringsRecursively(o) { //https://github.com/wesleytodd/recursive-escape/blob/master/index.js
    if (typeof o === 'undefined' || o === null)
      return o;
    if (o instanceof Array)
      for (var i = 0; i < o.length; i++) {
        o[i] = escapeStringsRecursively(o[i]); }
    else if (typeof o === 'object')
      for (var i in o) {
        if (o.hasOwnProperty(i))
          o[i] = escapeStringsRecursively(o[i]); }
    else if (typeof o === 'string')
      o = _.escape(o);
    return o;
  }
```

You can see in the .gif below when I first load the page my parse method catches strings with `script` in them and escapes them to the screen with nice HTML. Then I navigate to another page and return. Now the method never fires, the page is broken, and the script tags have run console.errors

![test](https://cloud.githubusercontent.com/assets/5468805/20670004/9f998c90-b57f-11e6-8522-577c8c0cc5a1.gif)

I logged a SO question here too in case someone can help: http://stackoverflow.com/questions/40842209/how-to-html-escape-strings-from-the-server-in-backbone-js

**Comment by jashkenas** [comment]
> But why does Backbone call model.parse only the first time the page loads?

It doesn't. It calls parse any time it's called. Something else funny is going on in your app.
