### ISSUE TITLE
docs: 'update' event confusing documentation

### ISSUE THREAD

**Issue by olanb7** [jashkenas/backbone#4109]
The current docs for the update event state:

> "update" (collection, options) — single event triggered after any number of models have been added or removed from a collection.

I interpreted this as events should only be fired on add or remove (i.e. not merge), however the event is also triggered on merge from `Collection#set`:

https://github.com/jashkenas/backbone/blob/7da4ed73e7402baf614a50a6551d47ace68b5239/backbone.js#L939

I'm not sure if the docs are just incorrect here or the implementation is not as expected. Docs are probably a safer fix!

**Comment by megawac** [comment]
Yeah, I remember being a bit confused about this when I first tried using the update event. A doc clarification would be appreciated
