### ISSUE TITLE
Protractor - how to select heavily nested dropdown element?

### ISSUE THREAD

**Issue by nikhiletc** [jashkenas/backbone#4117]
`<li ng-show="vm.authenticated &amp;&amp; vm.admin" ng-class="{ active: isActive('/users') || isActive('/suppliers') || isActive('/resources')}" class="dropdown active"><a class="dropdown-toggle ng-binding" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Administrative tools <span class="caret"></span>
                                </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#users" translate="" class="ng-scope">User Accounts</a></li>
                                        <li><a href="#suppliers" translate="" class="ng-scope">Suppliers</a></li>
                                        <li><a href="#resources" translate="" class="ng-scope">Resources</a></li>
                                    </ul></li>`
**How can I get protractor to click the links like "User Accounts" within the dropdown menu?**

**Comment by nikhiletc** [comment]
why its inappropriate?

**Comment by akre54** [comment]
Because your question has nothing to do with Backbone

**Comment by nikhiletc** [comment]
oops sorry,i didn't noticed that
