### ISSUE TITLE
Model is removed from collection even if DELETE command failed

### ISSUE THREAD

**Issue by alex-dow** [jashkenas/backbone#4118]
```javascript
var model = collection.at(0);
model.destroy();
```

This will issue an HTTP DELETE request. But if that request fails, the model is still removed from the collection.

**Comment by craigmichaelmartin** [comment]
http://backbonejs.org/#Model-destroy

> Pass {wait: true} if you'd like to wait for the server to respond before removing the model from the collection.

Hope that helps.

**Comment by alex-dow** [comment]
Well look at that, reading the documentation does help. Very sorry for opening this ticket and creating needless noise!
