### ISSUE TITLE
routes without hash not working for page refresh

### ISSUE THREAD

**Issue by dariusblajan** [jashkenas/backbone#4119]
I'm using Backbone.history.start({pushState: true}) to get rid of the '#' in the URL, and on top of that I created a global event for clicking on a[href] to force the router to navigate to those routes. The issue I have is when I'm refreshing the page. It goes to saying: '404 cannot get localhost:9000/myRoute' and after that I cannot use history anymore(going back and forth). I just want to know if there's a known solution or if it can be fixed somehow by a backbone developer.

**Comment by mateuszwrobel** [comment]
It is not a problem of backbone, but your server configuration. localhost:9000/myRoute is not pointing on your index file
[Here](https://gist.github.com/RaVbaker/2254618) you have solution for index.php (same for index.html) on Apache server. 
If you are using NodeJS solution depends on framework you use, ect.

**Comment by dariusblajan** [comment]
I'm using nodeJS indeed and start my local server with grunt. I dropped the
index.html from the URL and it was OK while I was using the routes with #.
Can you at least point me into the right direction on how to configure my
local server to work with the hashless routes?

On Jan 16, 2017 13:13, "mateuszwrobel" <notifications@github.com> wrote:

It is not a problem of backbone, but your server configuration.
localhost:9000/myRoute is not pointing on your index file
Here <https://gist.github.com/RaVbaker/2254618> you have solution for
index.php (same for index.html) on Apache server.
If you are using NodeJS solution depends on framework you use, ect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jashkenas/backbone/issues/4119#issuecomment-272834213>,
or mute the thread

**Comment by blikblum** [comment]
Google pushstate support nodejs
