### ISSUE TITLE
stopListening(null) removes all registered callbacks

### ISSUE THREAD

**Issue by russplaysguitar** [jashkenas/backbone#4120]
Currently, `object.stopListening(null)` removes all registered callbacks that `object` has. However, I think that `object.stopListening(null)` should be a no-op. It seems like it would be unintentional to pass `null`, since you can simply call `object.stopListening()` instead. 

Here is a test for the logic I'd expect (current behavior causes this to fail): 
```
  QUnit.test('stopListening with null', function(assert) {
    assert.expect(1);
    var a = _.extend({}, Backbone.Events);
    var b = _.extend({}, Backbone.Events);
    var cb = function() { assert.ok(true); };
    a.listenTo(b, 'event', cb);
    a.stopListening(null);
    b.trigger('event');
  });
```

**Comment by akre54** [comment]
Why are you passing `null`?

**Comment by russplaysguitar** [comment]
This situation arises when unintentionally passing `null`. For instance, I could have: `a.stopListeningTo(b);`, which I'd only expect to cause `a` to stop listening to `b`. However, if `b` is set to `null` dynamically, then all of the listeners on `a` are removed, which was not my intention with that line of code.

**Comment by jashkenas** [comment]
This is behaving as intended.

In general in JavaScript APIs, making a distinction between `null` and `undefined` is an antipattern.

**Comment by elgubenis** [comment]
@russplaysguitar 
isnt:
```js
if (b) a.stopListening(b);
// or b !== null
```
an option for you?

**Comment by russplaysguitar** [comment]
Thanks for reviewing this and clarifying the intended behavior. 

@elgubenis Yes, that's the pattern I'll need to remember to use from now on, thanks.
