### ISSUE TITLE
Events trigger as often as there are events in the view.

### ISSUE THREAD

**Issue by Artimon** [jashkenas/backbone#4121]
Hi,

at the events block using custom events, they fire as often as there are events defined in the view.

Example:
When adding the jQuery Plugin tappy.js it provides x-device save click & tap behavior that can be bound to an element with $('.anchor').on('tap', callback);
When using it for Backbone event bindings like this:
events: {
    'tap .element-one': 'callbackOne',
    'tap .element-two': 'callbackTwo',
    'tap .element-three': 'callbackThree'
}

A click on any of the bound elements would trigger it's callback 3 times, as there are 3 events in the setup.

**Comment by akre54** [comment]
Sounds like a problem with tappy. Behind the scenes we use [`delegate`](https://github.com/jashkenas/backbone/blob/v1.3.0/backbone.js#L1316-L1322) and the three-arg version of [`on`](http://api.jquery.com/on/) which binds a delegator to the view element. You might start from there.
