### ISSUE TITLE
Fullscreen video is not working Bootstrap tour step

### ISSUE THREAD

**Issue by bijweswa** [jashkenas/backbone#4122]
here I have created simple html page with bootstrap tour . on second step i have used Video tag ..this video tag is working in minimised screen but when i expand video to fullscreen , fullscreen automatically getting exited

`<!DOCTYPE html>
<html>
      <head>
	   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>My First Hopscotch Tour</title>
        <link href="bootstrap-tour-standalone.min.css" rel="stylesheet">
      </head>
      <body>
	  <button id="startTourBtn" onclick="startBootStrapTour();" >Take a Tour</button>
        <h1 id="swap1">My First Hopscotch Tour</h1>
        <div id="content">
          <p>Hi Swap.......Welcome to Hopscotch</p>
        </div>
		 <div id="swap2" style="width:300px;">
          <p>Different services provided by ABC are </p>
		  
        </div>
		 <div id="swap3">
          <p>Different services provided by ABC are </p>
		  
        </div>
		
		 <div id="swap4">
          <p>Different services provided by ABC are </p>
		  
        </div>
		
        
		<script src="jquery.js"></script>
	    <script src="bootstrap-tour-standalone.min.js"></script>
		<script>
		function startBootStrapTour(){
			var tour = new Tour({
				  steps: [
				  {
				    element: "#swap1",
				    title: "Start Tour",
				    content: "Explore the Databridge By clicking Next Button "
				    
				  },
				  {
				    element: "#swap2",
				    title: "Create Import",
				    content:  '<video id="backgroundvid" controls="control" src="file:///C:/Users/bijweswa/Desktop/swap.MP4" type="video/mp4" width="300" height="240" > </video>'
				    
				  },
				  {
				    element: "#swap3",
				    title: "Import Search",
				    content: "Here you can search for existing Import you have created.<p>you cab search on the basis of Import name, Catagary and Type</p>"
				   },
				  {
				    element: "#swap4",
				    title: "Delete Import Button",
				    content: "You can delete import by clicking  delete button after selecting import"
				  }
				]
			
			});
		
				// Initialize the tour
				tour.init();
				tour.start();
				
				
				if (tour.ended()) {
					  // decide what to do
					  tour.restart();
					}
				
			    //tour.restart();
			
			};
		</script>
		
      </body>
    </html>`

**Comment by megawac** [comment]
I think you have the wrong project
