### ISSUE TITLE
DialogView set focus issue

### ISSUE THREAD

**Issue by lukeyangskywalker** [jashkenas/backbone#4124]
i have a class that extends a dialog view

```
class Views.AddEntityDlg extends Views.DialogView
  initialize: (options) ->
    ...
  onRender: ->
    ...

```

called by 
` @addEntityDlg = new Views.AddEntityDlg (model: new Backbone.Model(mode: 'new'))`

when this dialog pop up is opened in the UI, I was able to press the Tab key and tab though the background as well.

**Comment by paulfalgout** [comment]
A `DialogView` isn't a backbone thing..  so it's going to be hard to know what issue you're dealing with, but I think you should also whoever wrote `DialogView`
