### ISSUE TITLE
Collection `change` event not documented

### ISSUE THREAD

**Issue by Bertuzb** [jashkenas/backbone#4127]
If im correct, a Backbone Collection can also trigger "change" events when one of its models has changed, but that is not documented in http://backbonejs.org/#Events-catalog .

What are the details for this event?

**Comment by akre54** [comment]
See http://backbonejs.org/#Collection:

> You can bind "change" events to be notified when any model in the collection has been modified, listen for "add" and "remove" events, fetch the collection from the server, and use a full suite of Underscore.js methods.
>
> Any event that is triggered on a model in a collection will also be triggered on the collection directly, for convenience. This allows you to listen for changes to specific attributes in any model in a collection, for example: documents.on("change:selected", ...)

Does that answer your question?

**Comment by Bertuzb** [comment]
oh awesome, that wasnt directly clear to me, since it is event related but not listed directly under the paragraph "Events"
