### ISSUE TITLE
Error Build APK {duplicate entry: com/google/android/gms/gcm/INetworkTaskCallback$Stub.class}

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [jashkenas/backbone#4130]
Hi i am trying to build APK but i Fetching this problem in Android Studio.
`Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/gcm/INetworkTaskCallback$Stub.class`

Gradle file :

` apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
     defaultConfig {
      applicationId "com.example.mouad.fixmyphone"
      minSdkVersion 15
      targetSdkVersion 25
      versionCode 1
      versionName "1.0"
      testInstrumentationRunner    "android.support.test.runner.AndroidJUnitRunner"
      // Enabling multidex support.
      multiDexEnabled true
   }
   dexOptions {
        javaMaxHeapSize "4g"
  }
   buildTypes {
      release {
           minifyEnabled false
               proguardFiles getDefaultProguardFile('proguard-android.txt'),   'proguard-rules.pro'
        }
    }
   useLibrary 'org.apache.http.legacy'

 }
 android {
     packagingOptions {
            exclude 'META-INF/DEPENDENCIES.txt'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/license.txt'
            exclude 'META-INF/dependencies.txt'
            exclude 'META-INF/LGPL2.1'
      }
 }

 dependencies {
 compile fileTree(include: ['*.jar'], dir: 'libs')
 androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2',          {
    exclude group: 'com.android.support', module: 'support-annotations'
   })
   compile 'com.android.support:appcompat-v7:25.1.1'
   compile 'com.android.support:design:25.1.1'
   compile 'com.android.support:support-v4:25.1.1'
   compile 'com.android.support:multidex:1.0.1'
   compile 'com.miguelcatalan:materialsearchview:1.4.0'
   compile 'com.google.firebase:firebase-core:10.2.1'
   compile 'com.google.firebase:firebase-messaging:10.2.1'
   compile 'com.firebase:firebase-client-android:2.5.2'
   compile 'com.firebase:firebase-jobdispatcher:0.5.2'
   compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'
   testCompile 'junit:junit:4.12'
   }
    apply plugin: 'com.google.gms.google-services' `

**Comment by paulfalgout** [comment]
Sorry this question is unrelated to backbone.

@akre54 - inappropriate
