### ISSUE TITLE
Let .com variant domain expire?

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/backbone#4135]
Hey all.

I'm 99% sure what the consensus answer to this is going to be, but I'll ask anyway:

Originally, Backbone was just registered under the correct **backbonejs.org** domain name. At some point, a good samaritan registered **backbonejs.com** to prevent anyone from squatting on it, and then eventually transferred it over to me.

At this point, I'm not sure that I really want to keep `.com` variants for all open source projects sitting there as redirects to the `.orgs`. Sure, it's only 30-50 bucks a year, but still, the principle of the thing.

How terrible of an idea would it be to allow **backbonejs.com** to expire?

**Comment by captbaritone** [comment]
Is there an easy way to see what kind of traffic the .com domains are getting?

**Comment by jashkenas** [comment]
Given that it's a permanent 301 redirect, it should be hardly anything — as some google searching for links appears to confirm.

I think that the vast majority of the potential harm here is for someone to grab the `.com` names and do something nasty with them, along with a much smaller impact to folks who just type `backbonejs.com` into their browser bars.

**Comment by jaapz** [comment]
I think with the popularity of the framework you're almost guaranteed that someone is at least going to squat it and fill it with ads, I'm not sure if that's necessarily your problem though.

What might also happen is someone getting the domain, copy-paste the backbonejs.org html and inject some malicious stuff into the downloads. That's probably not only going to be a pain for the people who fall for that kind of stuff, but also for maintainers who probably will need to keep explaining to users that no, backbonejs.com is in fact not the actual backbone website.

**Comment by hakuno** [comment]
The dot-org seems interesting for the framework itself.

But, we can take in account the MariaDB that has both dot-com & dot-env for instance.

**So what?**
I meant we can keep them up for many purposes.

**Why?**
We're a community. An international one. Look, I'm brazilian.

**And..?**
Many people and I would like to contribute more.

**How?**
We can establish a branding and improve the network.

- I'd like to gain hakuno[at]backbone[dot]com
- I'd like to have one directory on dot-com for my BB chapter (see [example](https://www.pmi.org/membership/chapters))
- I'd like to put in my _curriculum vitae_ any special involvement

Mr. @jashkenas Many ones love BackboneJS. So you've the opportunity of make the community stronger. Use your power to create one team to manage it for free. We can do it.

Ps.: My above examples even are capable of generating jobs around the world :stuck_out_tongue:

**Comment by sunnibfgi** [comment]
# sdffsdfsdf## sddsd

**Comment by halfnibble** [comment]
I don't think we need .com domain, but FYI, you're paying 2.5x - 4x the market rate for .com registrations.

**Comment by paulfalgout** [comment]
The domain has already expired and you can make an offer of a minimum of $2500 so this issue can be closed.

**Comment by jaapz** [comment]
Oh well, it's interesting to see what will happen with the domain now :)
