### ISSUE TITLE
Canvas with backbone

### ISSUE THREAD

**Issue by yuvrajm** [jashkenas/backbone#4141]
I wish to integrate canvas tag with backbone.js
I am stuck on the position of defining the view. Would appreciate if some one can direct me. How can we associate a view with the canvas.

**Comment by wesvetter** [comment]
I'm not familiar with canvas but it should be the same as creating any other native HTML element.

If there's no existing canvas element:

```javascript
var CanvasView = Backbone.View.extend({

  tagName: "canvas",

  render: function() {
    // modify canvas element here...
  }

});
```

or if the element already exists on the page:

```javascript
var CanvasView = Backbone.View.extend({

  el: "#my-canvas", // your selector

  render: function() {
    // modify canvas element here...
  }

});
```
