### ISSUE TITLE
Fast clicking between two links freeze VIEW and not render template

### ISSUE THREAD

**Issue by TrofimenkoAI** [jashkenas/backbone#4142]
I have a app with 3 links - MENU, PROFILE, INVOICE. Each of this link render own view and template. If I click very fast between those links at one moment link won't react on my clicking and will freeze render function. I have to refresh-hard my page to fix this problem. But it's not a good solution for UI. Is this a problem inside backbone structure?

**Comment by jashkenas** [comment]
No, it's a bug in your app.

**Comment by paulfalgout** [comment]
@TrofimenkoAI you might ask on: https://gitter.im/jashkenas/backbone
or maybe: https://gitter.im/marionettejs/backbone.marionette

But try and make a jsfiddle or at least have a code sample
