### ISSUE TITLE
What does `options` parameter in built-in events means? 

### ISSUE THREAD

**Issue by xgbuils** [jashkenas/backbone#4143]
Hi!

http://backbonejs.org/#Events-catalog

What does `options` last parameter in built-in events means? 

Is it the same value passed via method. I mean, if in some method like `set`, `add`, is passed the parameter options, then this parameter is passed as the las parameter of event handler?

I think that is not specified well.

Thanks!

**Comment by jaapz** [comment]
As far as I understand, those are the options that are passed into the function that triggers the event.

So when you add a model to a collection like this:

```javascript
let collection = new Collection();
collection.add({id: 10}, {someOption: 'with some value'});
```

The triggered `add` even on collection will have `{someOption: 'with some value'}` in it's `options`parameter.

**Comment by xgbuils** [comment]
Ok! thanks.
