### ISSUE TITLE
model.omit('attr') returns POJO?

### ISSUE THREAD

**Issue by nnnoel** [jashkenas/backbone#4152]
I think #4024 is a working solution to this, but I'm not entirely sure.

Example:
```
let model = new Backbone.Model({ foo: 'bar', baz: 'qux' });
model.omit('foo') // returns { baz: 'qux' }
```
As a proxied underscore method, I can understand the default behavior. It seems like in the context of a backbone model though, it should somehow return the model with the omitted fields by default?

Other than by overriding the method chain, possibly supering or calling another util/_ method to have the intended effect, or by instantiating a new model, I'm not sure what the most ideal solution to this would be and whether or not the entity context should be accounted for by default.

**Comment by jashkenas** [comment]
It's intended to return a plain object copy of the attributes with your desired keys omitted. 

If you want to mutate your model by removing a key, and firing all of the related `change` events, you're looking for `model.unset('foo')`.
