### ISSUE TITLE
hope generate api pages on github.io

### ISSUE THREAD

**Issue by leson** [jashkenas/backbone#4153]
it will easy to browser the api online .because of the official website can't be access in my company.

Thanks .

**Comment by ctl** [comment]
You can download it and use it locally

**Comment by ctl** [comment]
Also, Backbone docs is hosted on Github Pages

**Comment by sdmarsh77** [comment]
Its easy to learn

**Comment by pkonieczniak** [comment]
You can try use http://devdocs.io :)
