### ISSUE TITLE
Don't propagate the internal "unset" option to user code

### ISSUE THREAD

**Issue by marcovc** [jashkenas/backbone#4154]
let m = new Backbone.Model({a:1});
    m.on("change",(model,options)=>console.log(options))
    m.unset(a)

This prints `{unset: true}`

I my opinion the "unset" option is an implementation detail that should not be passed to my handler. 

Would it be possible to clear it before triggering the "change" event on the model "set" method?

(Maybe I could fix it in my code by overriding the set method, and clearing it myself, but I think this is actually a bug).

Thanks
Marco

**Comment by jaapz** [comment]
Why would this be a bug? I think it's useful to know whether a change event was fired because an attribute was unset. The value changed to "nothing".

**Comment by marcovc** [comment]
I think for that you can query changedAttributes(). Moreover, knowing the name of the method that caused the event ("unset" in this case) would be an exception (Backbone does not provide this for any other event).

**Comment by jashkenas** [comment]
Options is where Backbone stashes information about the change, `unset`, `silent`, `wait`, `patch`, etc -- are all options passed along. I think it's fine to have that information there. It doesn't need to affect your handler.
