### ISSUE TITLE
Collection#parse as a string

### ISSUE THREAD

**Issue by jfbrennan** [jashkenas/backbone#4155]
I'd like to suggest Collection#parse be defined as a function _or_ a string. The latter solves for what is probably the most common use case (my apps have this boilerplate function in every Collection):
```
parse: function(response) {
  return response.accounts;
}
```
Wish that could be:
```
parse: 'accounts'
```

**Comment by paulfalgout** [comment]
hmm maybe just change your `parse` function on the prototype to something like:

**Comment by jfbrennan** [comment]
True, but that could be said of url, idAttribute, groupBy, and other properties that support both func and string. I've used func and string for all of those and the convenience would be nice for parse as well.

**Comment by paulfalgout** [comment]
`idAttribute` to my knowledge does not take a function.  

The underscore related functions that take a string are definitely useful in that they all interact with a known data structure in the same manner and is handled in _most_ if not all cases by generating a predicate.

As for `urlRoot` it is primarily a string, but the function allows for it to be dynamically set. 

`parse` is the opposite where it is primarily a method taking multiple arguments.  I can see how there might be a similar pattern in many use-cases, but this isn't a matter of simply adding `_.result(this, 'parse')` to the code where `this.parse` once was..  so it seems in certainly a measure of guessing on my part that being able to override `parse` as a string will increase complexity and lower performance when a suitable alternative as I addressed above is fairly simplistic.

In the case of parse I don't think the convenience justifies the cost.

**Comment by jfbrennan** [comment]
I think I got idAttribute confused with `modelId` but that's function only...  idk! My bad!

Anyway, I really admire the way Backbone has avoided the temptation to become a "does everything!" framework. This proposal stays true to that and so I would hope to see what the community thinks before dismissing it based on unproven perf concerns. 

Being able to override `parse` as a string would not add complexity for _consumers_. It aligns very nicely with existing methods and seems logical assuming this use case is common (it's even given in the docs). Look how nice this:

```
url: function() {
  return '/notes';
},
parse: function(resp) {
  return resp.notes;
},
comparator: function(a, b) {
  return a.get('date') >= b.get('date') ? -1 : 1;
}
```
vs.
```
url: '/notes',
parse: 'notes', 👍
comparator: 'date'
```

Whether or not it adds _code_ complexity and/or lowers performance remains to be seen (there's no proposed code change here). I have my doubts because this shouldn't be much more than a `_.isString()` and both `set` and `sort` use that and those methods are called much more frequently than Collection#parse. This should be a design/philosophical decision rather than implementation imo.

**Comment by jashkenas** [comment]
I don't think we're going to make this change: it's clearer for `collection.parse` to be a function.
