### ISSUE TITLE
response without content

### ISSUE THREAD

**Issue by MetaiR** [jashkenas/backbone#4158]
hello,
I think this must be repeated but I couldn't find any solution with search in google and StackOverflow,

I just want to know how should face to APIs which just return status code,

for example, I have an API in my server which returns :

`200` -> when inserting in db was successful
`208` -> when the same record exist in db

so when I want to save my model if I put `dataType: "text"` my `xhr` argument will be empty and if I don't set that, my js will be hanged (I searched and found out it's because backboneJS waiting for getting a json)

and this is my sample function for sending that request:

```
function form1() {
    require(['user_model'], function (User) {
        
        var user = new User({
            user_id:$("#user_id").val(),
            user_name:$("#user_name").val(),
            user_age:$("#user_age").val(),
            user_phone:$("#user_phone").val()
        });
        
        if(!user.isValid()) {
            alert("there is an error \n" + user.validationError.msg);
            return;
        }
        
        user.urlRoot = user.baseUrl()+"api/users/info";
        
        user.save({}, {
            dataType: "text",
            success: function(model, xhr) {
                $("#result").html("new model is: " + JSON.stringify(user));
            },
            error: function(model, xhr) {
                switch (xhr.status) {
                    case 404:
                        alert("not found");
                        break;
                    case 400:
                        alert("bad request");
                        break;
                    case 500:
                        alert("server error");
                        break;
                }
            }
        });
    });
}
```
so how do I get just response code in this cases? (I mean the cases that response body is empty)

**Comment by TM-Olashyn-Dmytro** [comment]
Why did you write response on switch? You need use xhr.

**Comment by MetaiR** [comment]
@TM-Olashyn-Dmytro  it just a writing mistake, in my code I wrote word `response` instead of `xhr`
I fix that in issue
so any idea for my problem?

**Comment by TM-Olashyn-Dmytro** [comment]
What data contains in xhr? Can you console.log(xhr)? Or xhr ==  null?

**Comment by MetaiR** [comment]
it's empty
```
consol.log(xhr);
""
```

**Comment by TM-Olashyn-Dmytro** [comment]
so strange, because I write:
`  var TestModel = Backbone.Model.extend({});
            var testModel = new TestModel();

            testModel.urlRoot = "api/users/info";

            testModel.save(null, {
                dataType: "text",
                success: function(model, xhr, opts){
                    console.log(model);
                    console.log(xhr);
                    console.log(opts);
                },
                error: function(model, xhr, opts){
                    console.log(model);
                    console.log(xhr);
                    console.log(opts);
                }
            })`
And xhr is not empty. Maybe some fail on server or user.baseUrl()
