### ISSUE TITLE
Documentation of Model#validate can be misleading

### ISSUE THREAD

**Issue by AndresArturo** [jashkenas/backbone#4160]
In the Backbone 1.3.3 docs it is only mentioned in the section for the method `Model#isValid` that it:

>  Run validate to check the model state. 

https://github.com/jashkenas/backbone/blob/master/index.html#L1612

However when inspecting the code it is clear that calling such a method can also trigger an "invalid" event and set the `Model#validationError` state (by means of its internal call to `_validate`).

https://github.com/jashkenas/backbone/blob/master/backbone.js#L737:L739

Such explanations can also be found in the annotated source https://github.com/jashkenas/backbone/blob/master/docs/backbone.html#L1854:L1890

Following the docs to the section for the method `Model#validate` is states:

> If validate returns an error, save will not continue, and the model attributes will not be modified on the server. Failed validations trigger an "invalid" event, and set the validationError property on the model with the value returned by this method.

https://github.com/jashkenas/backbone/blob/0b2835f7fc479d7f2a6ebe4442d33aac5d38f86b/index.html#L1367:L1369

It is true it never mentions that it is the invocation of `Model#validate` what would cause the "invalid" event to be triggered, however the location in which the docs are placed and the order in which they are linked can lead to confusion. It at least happened to me and to some other colleagues when trying to explicitly test for the validity of a model.

My proposal would be to reorder some parts of the documentation between these two methods.

**Comment by jashkenas** [comment]
Do you have a specific change to the docs you'd like to propose?

**Comment by AndresArturo** [comment]
@jashkenas  I've created a PR including my proposal: #4163

**Comment by jashkenas** [comment]
Merged. Thanks.
