### ISSUE TITLE
collections reset  id issue

### ISSUE THREAD

**Issue by gravin** [jashkenas/backbone#4164]
found that when the object contains id field, and use reset to reset collection, it will remove duplicates according to id, but actually i dont want it to remove duplication, any way to do this?
 _this.reset(res.data.list);

**Comment by paulfalgout** [comment]
a model within a collection must have a unique id.  If you need the `.get('id')` to be non-unique then I would recommend setting `idAttribute` to a different attribute name that can be unique or even undefined.
