### ISSUE TITLE
backbone noconflict in typescript not working

### ISSUE THREAD

**Issue by Nanda-Nandan** [jashkenas/backbone#4168]
I have a typescript file which directly used Backbone. But I want to change it use own version of Backbone. export var ownBackbone :typeof Backbone = Backbone.noConflict();

export class UserContainerView extends ownBackbone .View<UserContainerContainerModel> {
    public currentView;
    public hasChanges;
    collection: ownBackbone.Collection<UserContainerContainerModel>;
    constructor(options: any) {
        super();
        this.collection = options.collection;
        this.$el = options.el; 
    }

    initialize(options: any) {
    }

    close() {
    }
}

it throwing error at Build cant find name ownBackbone

**Comment by jaapz** [comment]
You're probably going to get more responses when asking questions like this on StackOverflow.

**Comment by Nanda-Nandan** [comment]
I have asked question in StackOverflow, but I thought its issue regarding Backbone since i have used simple step to use Backbone with no conflict and i am unable to use it

**Comment by paulfalgout** [comment]
I really can't figure out what you're trying to do here.
`noConflict` solves the shared namespace of `window` or `global` when loading a script in particular way.  Assuming you're using a module loader with typescript like webpack or browserify or something, you don't have the problem this solves.
```js
// This isn't a problem at all.. no need for `noConflict`
import BackboneV1 from './version1/backbone';
import BackboneV2 from './version2/backbone';
```

Where as when there is no module loader it is necessary.
```
<script src="./version1/backbone.js"></script>
<script src="./version2/backbone.js"></script>
<script>
var BackboneV1 = Backbone.noConflict();
var BackboneV2 = Backbone;
</script>
```

**Comment by Nanda-Nandan** [comment]
I am using no conflict since the code is plugin to another app which is using another version of backbone,and when I am enabling plugin it is loading my version of backbone, conflicting client version backbone.and assume that it is not using any loader

**Comment by paulfalgout** [comment]
I'm sorry this still doesn't make sense to me.  What object are both plugins exposing Backbone to that is causing the issue `window`?  Do you need to expose `Backbone` or do you want to use another version of `Backbone`?

**Comment by Nanda-Nandan** [comment]
Let me explain it by example,suppose I have main app which is using backbone version 1.1.* or 1.0.*.so in window the loaded backbone is of version 1.1.* or 1.0.0*.when I will load my plugin or my code at that time it will load backbone 1.3.3 which is used by my code.if u will check in console for backbone it will display version 1.3.3.so because of this main app is getting crashed.so as a solution I am storing my version of backbone as no conflict to older one and restoring backbone as old version i.e main app using

**Comment by paulfalgout** [comment]
Is `noConflict` setting `window.Backbone` back to the older version?  If it isn't perhaps your code is being loaded prior to the other plugin.  But calling `noConflict` is really all you need to happen.  There's not much point within your code of using the return value of `noConflict` it just returns `this`.. so you should be able to just use the regular `import Backbone from 'backbone';` everywhere.. no need for `ownBackbone`.  But if you are having issues of conflicting backbone versions, than `noConflict` should work.  If it isn't I would suggest you have an additional copy of backbone loading somewhere.

**Comment by Nanda-Nandan** [comment]
yes it is setting back to older version,so if u will check in console backbone is of version 1.1.* while ownBackbone is of version 1.3.3.I guess you are missing context here,the problem is about typescript build error if i am storing backbone.noconflict in a variable and using it.Specifically i can say how to use backbone noconflict instance in typescript??

**Comment by paulfalgout** [comment]
how do you use any function that returns itself in typescript?  The function seems to be doing it's job and is incredibly simple.  This doesn't seem like an issue in Backbone at all.  Also why do you care what the return of `noConflict` is?  `Backbone === Backbone.noConflict() === Backbone.noConflict()`  `noConflict` only changes the backbone version on the window, the return value of the function isn't particularly useful.

**Comment by Nanda-Nandan** [comment]
the function is doing its job well,i can see its correct behaviour while using in console window i.e. in javascript.But for typescript it is showing error.My point here is does it support typescript perfectly.If yes,Could you please give me an example of noconflict usage of backbone in typescript

**Comment by paulfalgout** [comment]
seems to work: https://jsfiddle.net/chpyyk17/

**Comment by Nanda-Nandan** [comment]
Thanks,it is working perfectly for latest version typescript but not the version i was using 1.4 or 1.5
