### ISSUE TITLE
Broken link on cdnjs.com - "what is a view"

### ISSUE THREAD

**Issue by turbod73** [jashkenas/backbone#4169]
This page:
https://cdnjs.com/libraries/backbone.js/tutorials/what-is-a-router

"What is a view" should point here:
https://cdnjs.com/libraries/backbone.js/tutorials/what-is-a-view

**Comment by paulfalgout** [comment]
you should probably put a comment on cdnjs.com about this.. though the tutorial is about this repo, this repo doesn't maintain or control that information

**Comment by turbod73** [comment]
Thanks for the info, made a comment on the page instead :)
