### ISSUE TITLE
model id is removed from _byId if the model id is not available in the unparsed model

### ISSUE THREAD

**Issue by rianwouters** [jashkenas/backbone#4171]
The following is what I believe is a bug.

Assume my unparsed models do not have 'id' or the idAttribute as a (toplevel) attribute.

If a model is already in the collection, and is added again,
collection.set() will lookup the unparsed model with collection.get(unparsedModel)
It will not find it and add the model again, even it is already there.
After this, the original model is removed and _byId[idAttribute || 'id'] also

Therefore, the model will no longer be available by collection.get(model.id)

This problem does not exists if the unparsed model contain the id or idAttribute.

**Comment by jashkenas** [comment]
That sounds like it's working correctly to me: You're adding raw data, with no id — so you're allowed to add it twice.

If you really think there's a problem here, feel free to provide a test case.

**Comment by rianwouters** [comment]
You misinterpret the issue.
The idea is there but only in the parsed version.

Op 14 nov. 2017 19:09 schreef Jeremy Ashkenas <notifications@github.com>:

That sounds like it's working correctly to me: You're adding raw data, with no id — so you're allowed to add it twice.

If you really think there's a problem here, feel free to provide a test case.

**Comment by blikblum** [comment]
> You misinterpret the issue. The idea is there but only in the parsed version.

A jsfiddle or codepen demonstrating would help to understand the issue

**Comment by rianwouters** [comment]
See https://jsfiddle.net/rianwouters/gmxoa7fj/

________________________________
Van: Luiz Américo <notifications@github.com>
Verzonden: dinsdag 14 november 2017 23:51
Aan: jashkenas/backbone
CC: rianwouters; Author
Onderwerp: Re: [jashkenas/backbone] model id is removed from _byId if the model id is not available in the unparsed model (#4171)


You misinterpret the issue. The idea is there but only in the parsed version.

A jsfiddle or codepen demonstrating would help to understand the issue

**Comment by blikblum** [comment]
I see, the id returned in parse is ignored / removed. Seems a legit bug for me

**Comment by jashkenas** [comment]
No, it's not. You're not passing `{parse: true}`. This works as expected:

```javascript
var Model = Backbone.Model.extend({
  parse: function(r) {
    return {
      id: r.foo.bar,
      lorem: r.lorem,
    }
  }
});

var raw = {
  foo: {
    bar: 10
  },
  lorem: "ipsum"
};
var m = new Model(raw, {parse: true});
console.log(m);
```

**Comment by rianwouters** [comment]
Thanks. Reason  is obviously that collection.set does not parse the models before checking if they are already existing in the collection.

Op 16 nov. 2017 01:03 schreef Luiz Américo <notifications@github.com>:

I see, the id returned in parse is ignored / removed. Seems a legit bug for me

**Comment by rianwouters** [comment]
Your test works because you are not using a collection.
Collection.fetch calls Collection.set with {parse:true}.
However, Collection.set does not parse the model before it is checking if the model is already in the collection.
That's why it will add the model again with a new cid. However it will also remove the old cid after that, which also removed the id from the _byId hash.

My workaround is to add the following to my collection:

// Workaround https://github.com/jashkenas/backbone/issues/4171
parse(models) {
    models.forEach(m => m[m.Idattribute||'id'] = "whatever needed to get the id from m")
    return models;
}

which isn't nice of course because I need to add knowledge about the model parsing to my collection.

I believe the solution could be to move

model = models[i] = this._prepareModel(model, options);

which is now after "if (add) {" to the beginning of the for loop

as a side effect I think you can simplify

var attrs = this._isModel(model) ? model.attributes : model;

to

var attrs = model.attributes



________________________________
Van: Jeremy Ashkenas <notifications@github.com>
Verzonden: donderdag 16 november 2017 02:16
Aan: jashkenas/backbone
CC: rianwouters; Author
Onderwerp: Re: [jashkenas/backbone] model id is removed from _byId if the model id is not available in the unparsed model (#4171)


No, it's not. You're not passing {parse: true}. This works as expected:

var Model = Backbone.Model.extend({
  parse: function(r) {
    return {
      id: r.foo.bar,
      lorem: r.lorem,
    }
  }
});

var raw = {
  foo: {
    bar: 10
  },
  lorem: "ipsum"
};
var m = new Model(raw, {parse: true});
console.log(m);

**Comment by rianwouters** [comment]
why is this closed?

**Comment by paulfalgout** [comment]
If you want to parse the data on model instantiation use `{ parse: true }` as an option:
https://jsfiddle.net/gmxoa7fj/10/
From the docs: "parse is called whenever a model's data is returned by the server, in fetch, and save."  There's no reason to expect parse to happen on every instantiation, and that would be a bad idea in general.  It's for translating server data into workable data.  Try not to use non-workable data directly with backbone.  _But_ if you have to `{ parse: true }` is available.

**Comment by rianwouters** [comment]
I now I see why you miss my point. I did not save my latest jsfiddle update.
As you can see, collection.add and collection.fetch do not call Model.parse before checking if a model exists. Therefore, if idAttribute is not direct property of the raw model, the check will fail.

Therefore the model will be added again, but removed from the id hash.

In my jsfiddle you see 2 tests.
One with plain models, one with Model.parse 
The collections c1 and c2 should be equal but they are not.

**Comment by paulfalgout** [comment]
Can you save the 2 tests in a fiddle with the latest version of backbone?

**Comment by rianwouters** [comment]
https://jsfiddle.net/gmxoa7fj/25/

**Comment by paulfalgout** [comment]
don't expect the parser of the model to be used on `collection.set`  use the `parse` of the collection and this should work.

**Comment by rianwouters** [comment]
it's not clear to me why. It feels really inconsistent.
Anyhow that is my workaround indeed. 
However, it would be easy to solve and would improve the code.
