### ISSUE TITLE
Specifying cid before Model creation

### ISSUE THREAD

**Issue by ppisecky** [jashkenas/backbone#4176]
Hi,

We are currently working on a project using backbone. We have run into the issue where we need to synchronize models in real time across multiple users. We are not using a backend - backbone is only used as a utility to create Models and Collections. The problem is that at the moment a Model gets created at one users machine with a particular cid which we use to identify it later (in collections etc). Unfortunately when the model's JSON representation is sent over the network to another user and it is instantiated as a Model instance on his machine a new cid is generated by backbone which causes the two users enviroments to be desyncronized. Is there a way to tell backbone to use a particular cid when creating a model? I know that I can manually change it after model creation but that breaks our app's flow in terms of event listeners not being able to identify the model properly.

Thanks in advance for any help.

**Comment by mr47** [comment]
@ppisecky You can use, [idAttribute](http://backbonejs.org/#Model-idAttribute) to define, your generated ID, that can be sent over network, and will always be the same.

**Comment by paulfalgout** [comment]
Please use StackOverflow, the gitter channel, or the mailing list for questions. Github issues are for maintaining the framework only.
