### ISSUE TITLE
base backbone class

### ISSUE THREAD

**Issue by taburetkin** [jashkenas/backbone#4177]
is there any chance that Model, Collection and View will be derived from one base backbone class in next release?
```
Backbone.Model.prototype instanceof BaseBackbone == true
Backbone.Collection.prototype instanceof BaseBackbone == true
Backbone.View.prototype instanceof BaseBackbone == true
```
this will help in some cases to determine is a function is known backbone constructor or not

**Comment by jashkenas** [comment]
I'm afraid there isn't any chance.
