### ISSUE TITLE
trigger sticky events

### ISSUE THREAD

**Issue by wellu** [jashkenas/backbone#4181]
I have an app that has a small component for filtering search results. When the search is triggered it triggers an event that some other component is listening to.

Now, sometimes the listening component is not yet instantiated when the event occurs. I'd like to post "sticky" events that once posted stay somewhere and could be read using simple getter.

Pattern I'm looking after is similar to this: http://greenrobot.org/eventbus/documentation/configuration/sticky-events/

So we add a new method, _triggerSticky_, that would deliver the event like _trigger_ but one would need to consume it by calling _getStickyEvent_ or similar call. This would let developers not to worry about the instantiation order of the components as caller could ensure event is not lost even if there would be no listeners at the time event gets posted.

**Comment by jashkenas** [comment]
Sounds fine! Just create an object that is guaranteed to be instantiated before the search component, and have it store any events it hears. When the listening component is created later, it can look at the stored events before starting up. No problem.

**Comment by wellu** [comment]
Did **exactly that** already but was thinking could this be part of Backbone.js itself? So Backbone would take care of storing these sticky events and offer and API for triggering and clearing these.

**Comment by paulfalgout** [comment]
Backbone is very extendable.  If you wanted to add this as standard functionality, perhaps a plugin could suffice.
