### ISSUE TITLE
Documentation of Collection#add/create missing to mention options passed down during Model creation

### ISSUE THREAD

**Issue by AndresArturo** [jashkenas/backbone#4189]
In the Backbone 1.3.3 docs it is only mentioned in the section for the property [Collection#model](https://github.com/jashkenas/backbone/blob/master/index.html#L1807:L1810) that:

> If defined, you can pass raw attributes objects (and arrays) to add, create, and reset, and the attributes will be converted into a model of the proper type. 

Leaving undocumented the fact that `options` can also be provided to be passed along to the creation of the model. As it's visible in:

- https://github.com/jashkenas/backbone/blob/master/backbone.js#L889
- https://github.com/jashkenas/backbone/blob/master/backbone.js#L1137 

The lack of this small comment makes it appear in first instance like a limiting factor when handling creation of models directly through collections.

**Comment by AndresArturo** [comment]
I created a small PR with the proposed changes in https://github.com/jashkenas/backbone/pull/4190

**Comment by jashkenas** [comment]
Thanks!
