### ISSUE TITLE
[Feature Request] Using non-delegatable events in the events hash

### ISSUE THREAD

**Issue by shishirkulkarni** [jashkenas/backbone#4200]
It would be nice if we could specify bindings for non-delegatable events like `scroll` in the `events` hash. That way it would remove the burden from the developer to bind and unbind such events manually. To differentiate such events from delegated ones, we could prefix the event name with some character like `*`: 
Example: 
```
events: {
        "*scroll .my-list": "listScrolled"
}
```

**Comment by jgonggrijp** [comment]
While I appreciate the use case, I agree with https://github.com/jashkenas/backbone/pull/4199#issuecomment-480583243 that it would be better served by a subview. I feel that introducing new syntax for this is scope creep.
