### ISSUE TITLE
Suggestion: Kill some modules and leverage fetch

### ISSUE THREAD

**Issue by jfbrennan** [jashkenas/backbone#4207]
I'd love to see a version of Backbone that has `Model` and `Collection` only and uses `fetch` instead of depending on `$.ajax` under the hood. And a CDN build with Underscore included to top it off.

The web community needs it. They're doing some pretty gross stuff where as the Backbone APIs are so good for Model, Collection, and talking to RESTful services.

**Comment by jashkenas** [comment]
Go for it. It's open source!

**Comment by jfbrennan** [comment]
@jashkenas  Curious to know if something similar has been or is currently being discussed/attempted. If there's enthusiasm, would you support an official release?

**Comment by jashkenas** [comment]
I'm not aware of something along those lines — although it's certainly easy enough to just use `Model` and `Collection`, if that's all you need.

As for switching to `fetch`, that would be a lovely upgrade, and any PR that implemented it would probably be taken.

**Comment by jashkenas** [comment]
Oh, and as to supporting an "official" release that removes the View and Router — I don't think so. Backbone at this point has been stable for a long time. We're not going to remove major APIs.

**Comment by jfbrennan** [comment]
@akre54 you wrote [backbone.fetch](https://www.npmjs.com/package/backbone.fetch), does "any PR that implemented [fetch] would probably be taken" interest you? Happy to help

**Comment by blikblum** [comment]
> I'd love to see a version of Backbone that has Model and Collection only and uses fetch instead of depending on $.ajax under the hood.

I did that, plus implemented as ES6 classes: https://github.com/blikblum/backbone/tree/nextbone
