### ISSUE TITLE
Generate schema from models

### ISSUE THREAD

**Issue by tom-sherman** [jashkenas/backbone#4221]
Is it possible to generate some form of schema in a structured format using backbone models?

**Comment by jashkenas** [comment]
Certainly. I'd perhaps recommend using [AJV](https://www.npmjs.com/package/ajv) to validate your model attributes using JSON Schema in your `model.validate()` function.

**Comment by tom-sherman** [comment]
@jashkenas thanks, but I'm looking at generating some structured data *from* the models. I've got a fairly large code base I want to create types for.
