### ISSUE TITLE
Model.destoy should allow to set a body

### ISSUE THREAD

**Issue by fabianfrz** [jashkenas/backbone#4231]
A delete request may have a body containing some meta data like who deletes the resource and why.
This information is usually not required for the delete process itself but may be required for the process (usually documentation purposes).

For example:

```javascript
model.destroy({
    data: {
       reason: "Deleted due to GDPR delete request"
   }
});
```

```
DELETE /resouces/1 HTTP/1.0
Host: example.com
Content-Type: application/json
Content-Length: xxx

{
  "reason": "Deleted due to GDPR delete request"
}
```

**Comment by paulfalgout** [comment]
This is the current API for backbone.  Granted you may need to `JSON.stringify` `data` and/or set your contentType, but doing exactly what you're doing in the code above works in backbone.

**Comment by fabianfrz** [comment]
Thanks, I will think if I will document that in the Backbone.sync section.
