### ISSUE TITLE
Backbonejs (1.4) version compact with jQuery (3.4.1) ?

### ISSUE THREAD

**Issue by sivaprabug** [jashkenas/backbone#4241]
Hi Guys,

Not an issue just clarify my doubt, My backbonejs version is **1.1.2** shall i proceed with jQuery version **3.4.1** ?

**Comment by jgonggrijp** [comment]
@gsivaprabu Sorry for the long silence. Please clarify: are you using Backbone 1.1.2, Backbone 1.4.0 or upgrading from the former to the latter?

From my experience, Backbone 1.4 works fine with jQuery 3.x, but I haven't tried 1.1.2. If you try it, please report back your findings here. Thanks in advance!

**Comment by jgonggrijp** [comment]
Closing this as the question no longer seems current. In general, the answer to "is Backbone version X compatible with jQuery version Y" is very likely to be "yes".
