### ISSUE TITLE
error event not firing for Collection.create with wait true

### ISSUE THREAD

**Issue by alanhamlett** [jashkenas/backbone#4262]
For [Collection.create](https://backbonejs.org/#Collection-create), the `sync` and `add` events fire correctly, but if `options` are `{wait: true}` and server responds with any error, the `error` event doesn't fire. Without `{wait:true}` the error event fires correctly, but the invalid model is added to the collection.

**Comment by recursivk** [comment]
Any updates on the resolution?

**Comment by jgonggrijp** [comment]
@recursivk I have two full-time weeks to work on Backbone, starting next week. The high priority issues, including this one, will be addressed first.

**Comment by recursivk** [comment]
Thanks, that helps a lot
