### ISSUE TITLE
Misleading line in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jgonggrijp** [jashkenas/backbone#4273]
This line:

> In your pull request, do not add documentation or rebuild the minified `backbone-min.js` file. We'll do that before cutting a new release.

seems to suggest contributors shouldn't edit the `index.html`, but this is not what is intended. They **should** edit the `index.html`! The "documentation" that shouldn't be edited refers to the annotated sources in `/docs`.

"do not add documentation" should be changed into something like "do not regenerate the annotated sources" or something like that.

**Comment by paulfalgout** [comment]
Well.. I _can't_ be :100: sure about this.. But I think Jeremy wrote just about all the `index.html` stuff every release.. regardless of if people modified it.

**Comment by jgonggrijp** [comment]
Alright, so maybe it was intentional. Still, while such an approach might work for Jeremy, it wouldn't work for me, as it would mean I have to double-check at every release whether every function is documented. I rather tell people to contribute user documentation together with new features and then keep going through the review cycle until the text is palatable.

I still expect to update all the links, version numbers and the change log myself, though.
