### ISSUE TITLE
Backbone Model defaults system is not subclass safe

### ISSUE THREAD

**Issue by BradNeuberg** [jashkenas/backbone#476]
Backbone provides a standard 'defaults' object literal that you can add to a Model to establish defaults. However, if you are subclassing models then this is not safe.

For example, imagine if you have:

var Car = Backbone.Model.extend({
  defaults: {
    property1: 'foobar'
  }
});

var Toyota = Car.extend({
  defaults: {
    property2: 'hello'
  }
});

When Toyota is made property2 will be present, but not property1.

Backbone should instead have a getDefaults() method that provides an object literal. Subclasses can over-ride this (and call their super-classes getDefaults() to chain defaults together) so that when Backbone mixes its defaults in it can aggregate them all together, with something like:

Backbone.Model = function(attributes, options) {
    attributes || (attributes = {});
    attributes = _.extend({}, this.getDefaults(), attributes);

Where the default getDefaults() implementation would just be an empty {}.

**Comment by ORESoftware** [comment]
I don't think you should build inheritance in JS yourself. Just avoid it. Use composition.
