### ISSUE TITLE
Don't wrap views if using templates

### ISSUE THREAD

**Issue by meleyal** [jashkenas/backbone#546]
### Problem

Most of my `render` methods end with something like:

```
var template = _.template( $("#asset-template").html(), data);
$(this.el).html(template);
```

With a template like:

```
<script id="asset-template" type="text/template">
  <li class="asset {{ classes }}">
    <img src="{{ img_url }}" data-url="{{ url }}" data-description="{{ description }}">
    <span class="caption">{{ description }}</span>
  </li>
</script>
```

So the template gets inserted into `this.el` (`<div>` by default).

But I tend to write my templates 'fully-formed' (as above), not requiring any extra wrapper elements. This presents 2 problems:
- Your `<li>` is wrapped in a div (producing invalid markup) or another unneeded element
- Your events are more verbose: `'click .asset' : 'select'` instead of just `'click' : 'select'`

One solution would be to exclude the `<li>` from the template, and have Backbone construct it with the `el`, `className`, etc. properties. But a big benefit of using templates is that they are not mixed with the view logic, and that you can write them just like normal HTML.
### Solution(s)

My suggestion would be a new `template` property:

```
App.Views.Asset = Backbone.View.extend({

  events: {
    'click' : 'select'
  },

  template: _.template($("asset-template").html()),

    ...

}
```

If `template` is present, it's presumed the template is fully-formed and no wrapper elements are created.

Another option would be the ability to assign the template directly to `this.el`, while keeping the event delegation working:

```
// this currently works, but you lose event delegation
this.el = _.template( $("#asset-template").html(), data);
```

Could be I'm missing something and it's possible to achieve 'unwrapped templates' now, but after using Backbone for a couple of projects I kept stumbling on this.

**Comment by jvitela** [comment]
Instead of trying to replace the original View's element, why not define tagName as a function and make it return the tag of the root element of the template?
For example, if the template is something like:
```html
<section class="panel" id="panel123">
<!-- contents -->
</section>
```
```javascript
this.tagName() // return 'section'
```

Then the render function has to insert only the template's contents:
```javascript
render: function() {
   // Assuming $template is a jquery object with the rendered template
    this.$el.empty().append( $template.children());
}
```
Here is a working [example](http://jsbin.com/doduvo/latest/edit?html,js,output)

**Comment by ylacaute** [comment]
@jvitela : Your solution works well but sometimes it adds a little delay which I dont have at all when I use partial template (where root tags are generated from the view). Moreover, it is still a workaround.

I have started to learn Backbone for one week so maybe I miss something but your solution is the only one I saw wich is fully functionnal. This is surprising, I think it is an essential feature.

* **Is there a native way to define the root tag template IN the template and not in the View ?** If yes, can you please give us an example ?
* If it's not possible, what is the associated pull request ? this one [Use template as el](https://github.com/marionettejs/backbone.marionette/issues/2357) ?
Thanks.

**Comment by jvitela** [comment]
Hi @ylacaute,

There is NO native way to define the root tag IN the template. This is because Backbone is template agnostic, you are free to choose whatever you want as template system and is imposible to provide a generic way to achieve this.
