### ISSUE TITLE
Pass options to Collection's initialize()

### ISSUE THREAD

**Issue by geddski** [jashkenas/backbone#661]
With a model you can pass data and options like so:

``` javascript
var article = new Article({subject: "CSS Shaders"}, {option1: '7'});
```

that options object will get passed along to my article's `initialize()` function. Yay.

The same is not true for a collection. It has the same API: pass it a model and options. But backbone only uses that options for setting the comparator on the collection `if (options.comparator) this.comparator = options.comparator;` and does not pass the options along to the collection's `initialize()` function. 

Seems like for the sake of consistency it should pass along the options.

My use case is I have a nested collection, and I want to pass in as an option the parent model so that the nested collection's initialize() has access to it, and can pass along the reference to it's models. Contrived (and silly) example: A farmer (model) has some turkeys (collection), and I want the turkeys to know which farmer they belong to so they can plot against him before Thanksgiving.

**Comment by rlynjb** [comment]
i seem to be having the same issue. tried the solution above my @mdeering but no luck.. here is my stackoverflow question http://stackoverflow.com/questions/32168065/backbonejs-in-collection-how-do-we-access-this-var-from-initialize-function

i seem to be missing something here. let me know what you guys think
