### ISSUE TITLE
Serving a Backbone app from a subdirectory isn't supported by Router

### ISSUE THREAD

**Issue by hubsmoke** [jashkenas/backbone#672]
A user should be able to specify a parameter to the Router ( say {root: 'myDir'} ) to specify that the app is being served from a subdirectory. After specifying this, the prefix parameter should be prepended to each route within the Router, so that routes can be properly handled, even when a Backbone application is served from a subdirectory.

**Comment by jtmkrueger** [comment]
This is a really old issue, and I don't think the link that @jashkenas left links to the right place in the code anymore. Is it documented somewhere?

**Comment by akre54** [comment]
Given that the link was posted on 10/15/2011 we can find the most current master git ref, which was ef40512d8441201e01f8d46c271fcf23235e9bc5

The link should be  https://github.com/jashkenas/backbone/blob/ef40512d8441201e01f8d46c271fcf23235e9bc5/backbone.js#L769-L780

(The most up-to-date would code be https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L1633-L1661)

**Comment by jtmkrueger** [comment]
Is it worth putting some documentation about `root` on the website? I don't see it mentioned there under router anywhere. If so, I'd be happy to write something up!

**Comment by akre54** [comment]
It takes some searching but it's documented under http://backbonejs.org/#History-start

> If your application is not being served from the root url / of your domain, be sure to tell History where the root really is, as an option: Backbone.history.start({pushState: true, root: "/public/search/"})

It's really a History option, not a Router one.

**Comment by jtmkrueger** [comment]
Ah, there it is. Thanks for pointing that out!

**Comment by Sendoushi** [comment]
Dear! 

Have you read the latest  article written by me? Just take a  look, it's very interesting. Please read here <http://dunkiliwy.verdantgreenla.com/e4dmgevy>


See you soon, Alberto Martinez
