### ISSUE TITLE
History.navigate should allow setting of state object

### ISSUE THREAD

**Issue by tribalvibes** [jashkenas/backbone#764]
Currently History calls `pushState` with an empty `{}` state object. It's crucial to allow the caller to set the state object. At the very least  using `window.history.state` if available would be a sensible default.  `History.navigate` should take a `stateObject` as an additional parameter.

**Comment by akwuh** [comment]
@rafayepes I'm fully agree with your argument. I love Backbone and its simplicity, but this API change introduces a bunch of problems and workarounds in the code, when the app should store 1-to-1 relationship between url and state. Native way of interacting with History API would be much much easier.
