### ISSUE TITLE
Unable to call super.initialize()

### ISSUE THREAD

**Issue by framerate** [jashkenas/backbone#785]
I'm new to backbone, so I could be missing something. But I have something like:

var ChildClass = BaseClass.extend(
{
    initialize: function()
    {
        Backbone.Model.prototype.initialize.call(this);
        alert("child init (should see parent init before this but you don't)!");
    }

}

Maybe I'm going about this wrong? I've been coding all day so forgive me if so :). But why can't I call super.initialize this way?

**Comment by sorin-postelnicu** [comment]
I have an even more weird case, in which I want to override the constructor! And I want to perform some code in my constructor, then call the __super__ constructor, and then do some other stuff in my constructor.

The solution is like this:
http://jsfiddle.net/vpya2swk/1/

    var BaseClass = Backbone.Model.extend({
        constructor: function () {
            console.log('Greetings from BaseClass constructor');
        }
    });
    var ChildClass = BaseClass.extend({
        constructor: function () {
            console.log('Greetings from ChildClass constructor');
            this.constructor.__super__.constructor.apply(this);
            console.log('...and ChildClass constructor finished!');
        }
    });
    
    var test = new ChildClass();
    
    // alerts:
    // => Greetings from ChildClass constructor
    // => Greetings from BaseClass constructor
    // => ...and ChildClass constructor finished!
