### ISSUE TITLE
model.destroy() not passing id params

### ISSUE THREAD

**Issue by sgentile** [jashkenas/backbone#789]
with emulateJSON and emulateHTTP off - I had to apply this fix:

// Ensure that we have the appropriate request data.
    if (!params.data && model && (method == 'create' || method == 'update' || method == 'delete')) {
      params.contentType = 'application/json';
      params.data = JSON.stringify(model.toJSON());
    }

(added method == 'delete')

otherwise, no params are sent with the DELETE call.  

(It could be streamlined to only include the id)

**Comment by luisaugustos** [comment]
or custom the url inside your destroy method

```
this.model.destroy({
                url: URL + "problem/" + this.model.get('id'),
                success: function (model, response) {
                    console.log(response);
                    console.log('success');
                },
                error: function (model, response) {
                    console.log(response);
                    console.log('error');
                }
            });
```

URL = a constant with my base url

**Comment by solivavinicius** [comment]
@boo1ean Thanks!
