### ISSUE TITLE
Routing should be agnostic to leading and trailing slashes

### ISSUE THREAD

**Issue by jashenson** [jashkenas/backbone#848]
Currently, defining routes as `"/search"` is not equal to `"search"`, which is also not equal to `"search/"` or `"/search/"`. Backbone should consider all of these routes as equal, so that all routing is agnostic to the leading and trailing slashes.

**Comment by raymondji** [comment]
(Apologies for the revival)

https://github.com/jashkenas/backbone/issues/1885 says the update included:
- Normalizing trailing and leading slash behavior in routes

But on Backbone 1.3.3 I'm continuing to see the issue of '.../foo' and '.../foo/' treated differently.
Am I misinterpreting the intended behaviour?

Thanks.

**Comment by emileber** [comment]
@raymondji use `.../foo(/)` in your router's routes to treat both as the same routes. Backbone gives you the tools to choose how to interpret the routes.

From the[ doc on `routes`](http://backbonejs.org/#Router-routes):

> Trailing slashes are treated as part of the URL, and (correctly) treated as a unique route when accessed. `docs` and `docs/` will fire different callbacks. If you can't avoid generating both types of URLs, you can define a `"docs(/)"` matcher to capture both cases.
